### PR TITLE
Added basic support for TypeScript 

### PR DESCRIPTION
**Pull request by oliverguenther**
This supersedes https://github.com/opf/openproject/pull/3735 with fixed `npm-shrinkwrap.json`.

/cc @furinvader, @romanroe: You should clarifiy the role of `typings/tsd.d.ts`, since its specified in the config, but excluded from Git.

Also, please add some kind of documentation before merging this.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-feature-typescript.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://oliverguenther-feature-typescript.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
https://community.openproject.org/work_packages/21913/activity

**Comment by ulferts** [comment]
Copying my comment from #3735:

> However, instead of "npm install" I had to do
> npm install --save typescript
> npm install --save ts-loader

Would that also be necessary for users wanting to install OpenProject after this is merged? We would then have to update our testing and delivery pipeline.

**Comment by oliverguenther** [comment]
No, `--save` is only required to introduce the dependency into package.json. `npm i(nstall)` is sufficient on the user side of things.

**Comment by romanroe** [comment]
The file `typings/tsd.d.ts` gets generated with `tsd install` and is required for the build. The content is based on `tsd.json`. 

I am a bit lost between https://community.openproject.org/work_packages/21913/activity and this pull request. What can I do to help with the TypeScript integration?

**Pull request merged**
