### PR TITLE
add sqlite to .travis.yml

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by ulferts** [comment]
sqlite is not officially supported by OP. It might work, but we do not strive for it to work.

**Comment by marutosi** [comment]
Why?
Redmine and ChiliProject support SQLite3.
Do you refuse migration from Redmine and ChiliProject?

**Comment by ulferts** [comment]
It's just a question of time and prioritisation. If we had a whole bunch of time at our hands we would do it. Maybe once we remove more of the hand written sql and replace it with AR/Arel supporting sqlite will be easier.

For the time being, postgresql and mysql are used in production and sqlite to my knowledge less so. Maybe that is just my limited view, so please correct me if I am wrong. 

So to clarify, I would like to support sqlite but I like supporting postgres and mysql even more.

**Comment by marutosi** [comment]
> postgresql and mysql are used in production

It is true.
But, PostgreSQL and MySQL are too expensive for users to try to use for evaluation in first time.
For developers, SQLite is easy to use for multi branches.

**Comment by ulferts** [comment]
We can not maintain sqlite currently, and the travis run already fails on the migration.

**Pull request closed without merging**
