### PR TITLE
Fix/icon font and alignments

### PR DESCRIPTION
**Pull request by wielinde**
This PR tries to improve one core problems of vertical icon positioning. It centers the glyphs of the openproject icon font lower, so that they look good next to text of the same font size.

Another issue is that our Lato font apparently renders one pixel higher Win Chrome than other fonts.

The other commits adopt toolbar and main-menu.

As a final statement: Not all our vertical positioning problems are solved. Windows seems to tend to draw everything a bit further up than Mac. The lowest rendering does Mac Chrome. This is somewhat beyond our influence so I stop my efforts here.

### CODE REVIEW

**Comment by oliverguenther** [comment]
You've added a `openproject-icon-font-2.svg`, is that by design?

**Comment by wielinde** [comment]
@oliverguenther Thanks, I added them by mistake. Now they are removed.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/15a2c840e90a77a0a67c58aa8e1c78170522cf2d) (deployed commit: 1569ebe8ef4083521250b4ee38dccd9d79f9dbee).

**Comment by oliverguenther** [comment]
LGTM 👍

**Pull request merged**
