### PR TITLE
[Foundation] Even moar quick wins

### PR DESCRIPTION
**Pull request by floriank**
This will change the _transitional_ work package form slightly to be more in line with the requirements of https://community.openproject.org/work_packages/19198.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-fix-19198-quick-wins-part-deux.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-fix-19198-quick-wins-part-deux.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Just a sanity check: Do we really want to remove the border on the embedded update form of the work package. It is looking like this and I don't find that particularly salient:

image

Probably totally out of scope of the PR but I really dislike the approach of styling this one particular view to achieve a look that existed before. In essence, we are working around the styleguide. The better approach would be to define a consistent behaviour (e.g. max-width) for form--select-container, form--text-area, ...

**Comment by floriank** [comment]
The suggestion was made by @lindenthal. I think, we should not spent more time than we really have to on this form.

**Comment by myabc** [comment]
> Probably totally out of scope of the PR but I really dislike the approach of styling this one particular view to achieve a look that existed before. In essence, we are working around the styleguide. The better approach would be to define a consistent behaviour (e.g. max-width) for form--select-container, form--text-area, ...

I'm afraid I agree.

**Comment by floriank** [comment]
> I'm afraid I agree.

This is probably not really feasible to implement in due time, is it?

**Pull request merged**
