### PR TITLE
[WIP] rails update to 3.2.19

### PR DESCRIPTION
**Pull request by GarstgerUnhold**
https://www.openproject.org/work_packages/13446.

### CODE REVIEW

**Comment by ulferts** [comment]
Some gems are updated that are not a necessity:
i18n
multi_json
thor

But I have to admit, that the specs are still failing. But I would still separate updating the other gems from upgrading rails.

**Comment by ulferts** [comment]
Specs break because of the other security fix included in 3.2.19 which is was [not part of the security warning](https://groups.google.com/forum/#!msg/rubyonrails-security/wDxePLJGZdI/WP7EasCJTA4J). With rails/rails@297bff7f8f01fbda2a6bacaed4afb3d060292b9f the line

<pre>
config.active_support.escape_html_entities_in_json = true
</pre>

in our application.rb now becomes active. 

According to the [tests of the prototype-rails](https://github.com/rails/prototype-rails/blob/master/test/template/prototype_helper_test.rb#L156) gem, this setting is adhered to when using rjs.

The escaped html including the select tag does not work for updating the versions select (after fixing the path used). This should be fixable by only updating the options within the select (works even in IE now).

But a bad feeling remains. On the one hand we should now assess how grave the lack of having escape_html_entities_in_json active the whole time is. On the other hand we have to assess what breaks now that the setting is active.

**Comment by GarstgerUnhold** [comment]
@ulferts can you describe the circumstances where the version update did not work for you? After rebasing this onto the current `release/3.0` branch with the version route updates (d13ccc5 and 5024f4c), this seems to work perfectly for me (tried Chrome and FF). Is it an IE only bug?
Maybe the tests are still failing at this point (dunno, travis is still going), but I'd think this is probably because they test stuff that's pretty much irrelevant to the functionality itself.

**Comment by ulferts** [comment]
@GarstgerUnhold, I haven't come as far as to really check on the application. So the only indication I have are the specs. And there where two that failed. If they are fixed and we test everything thoroughly I am satisfied. I just think that we have to make sure everything works by clicking through the application even if all tests pass.

**Comment by cratz** [comment]
https://travis-ci.org/opf/openproject/jobs/29974237

**Comment by GarstgerUnhold** [comment]
@cratz yeah, but what I'm saying is, those tests seem to be checking on implementation details. The non-XSS test should (ideally) not be bothered by escaping issues.

**Comment by ulferts** [comment]
@GarstgerUnhold, whether you fix the test or go that extra mile of improving them is up to you.

**Comment by ulferts** [comment]
@GarstgerUnhold have you had a chance yet to take a look at the application in work. I had forgotten but reading through my old comments, I now remember that adding a version in the work package view [actually breaks when the rails version is updated](https://github.com/opf/openproject/pull/1577#issuecomment-48545174)

**Comment by cratz** [comment]
If the escaping related stuff is fixed version create should work since I already backported the fix for the other problem:
https://github.com/opf/openproject/pull/1584

**Comment by ulferts** [comment]
My experience from testing with it says otherwise @cratz. I had to change the code from replacing the whole select to just replace the available options. But please test @GarstgerUnhold and we will know.

**Comment by GarstgerUnhold** [comment]
@ulferts @cratz I actually never saw the version creation from the work package view break because of escaping (after rebasing this onto the current release/3.0, which includes the mentioned backports). That's why I posted https://github.com/opf/openproject/pull/1577#issuecomment-49025571. For me, it just looks like broken tests.

**Comment by ulferts** [comment]
@GarsterUnhold, have you tested this with the IE. I seem to remember that this broke when creating the version.

**Comment by ulferts** [comment]
@GarstgerUnhold, @cratz, tested everything and looks good.

**Pull request merged**
