### PR TITLE
Change search keyboard shortcut to s, project shortcut to p

### PR DESCRIPTION
**Pull request by mfrister**
No ticket for this.

### CODE REVIEW

**Comment by GarstgerUnhold** [comment]
"/" on os x 10.9. + firefox.v25 opens quick search and consequently Github uses "s" for its global search shortcut. Might be a good idea to build something adaptive, too.

**Comment by mfrister** [comment]
Actually, Github just don't show their '/' shortcut on Firefox, which by default searches the current project while 's' searches globally on GitHub.

Gmail like this PR just captures '/', so Firefox doesn't show the search field when pressing it.

Given that 's' is already taken for selecting a project (s p) and Gmail uses '/', I think it's ok although semantics are different on GitHub.

**Comment by mfrister** [comment]
Ok, so after discussing this with @tessi, I'll change the project menu shortcut to `p` and the global search shortcut to `s`. Once we have a project-only search, we can think about a good shortcut for that.

**Comment by mfrister** [comment]
@tessi Changed the shortcuts to `s` and `p`.

**Comment by tessi** [comment]
@GarstgerUnhold are you ok with the new key-assignments? I'd merge this soon, unless you have any more concerns.

**Comment by GarstgerUnhold** [comment]
@tessi Sure, go ahead. I'm not totally invested in that, anyway. The Quicksearch-thingy was just something I immediately thought of when reading this. "S and P are fine with me".

**Comment by tessi** [comment]
:thumbsup:

**Pull request merged**
