### PR TITLE
add news subject to url (reborn)

### PR DESCRIPTION
**Pull request by linki**
Second attempt on displaying the news title in its url (original https://github.com/opf/openproject/pull/426).

This PR changes the `news_controller` to not use the generic `model_object` functionality to find news items. By doing that we can cleanup the parameters before querying the database (converting the url parameter to an ID).

Original text:

I noticed that OpenProject has poor urls for its news. This PR appends the subject to the news link to make them more memorizable and to know what to expect before clicking.

It turns

https://www.openproject.org/news/20

into

https://www.openproject.org/news/20-openproject-now-has-a-twitter-account

Note: both urls work today already. The PR only changes the links rails generates when using its helper methods.

### CODE REVIEW

**Comment by hschink** [comment]
@linki would you mind moving your test unit tests to specs? Just give me a note if you don't have any time for it, so I can finish this PR.

**Comment by linki** [comment]
fine, I'll do that.

**Comment by linki** [comment]
done, what a tedious task :-( @hschink

**Comment by hschink** [comment]
Thanks for the rebase @linki! :+1: It seems that only your specs are failing now. :wink:

**Comment by ulferts** [comment]
Hey @linki,

Can you please fix the failing tests. I would like to have that in OpenProject 3.0 and to have less open PRs.

**Comment by linki** [comment]
what two lines of code can mean for the whole test suite... :-/

**Pull request merged**
