### PR TITLE
Minor Sass cleanup

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work packages

This PR belongs to general house keeping tasks: https://community.openproject.org/work_packages/18714

After addressing the font-color problem this PR should now also solve https://community.openproject.org/work_packages/20270
## Description

After a hint by @myabc I did some further consolidation of the `_misc_legacy.sass` file.

I tried to get rid of some rules where I have a high certainty, that they are outdated.

I'll be happy to delete more rules (at least those with a low risk of breaking stuff for now). If someone can tell me that one of my deletions will break stuff this would be great.

I'd propose to merge this PR **after** releasing 4.1.2.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-cleanup-sass.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-cleanup-sass.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
LGTM :+1:

**Comment by NobodysNightmare** [comment]
I will have to check whether the atwho rule is really expendable, according to @floriank it might not be.

**Comment by NobodysNightmare** [comment]
RFC (CC @myabc @floriank):

I introduced new color variables I felt neccessary. Colors like our primary color (and others) are currently defined in a very themable way, this is great. However, we often use them as background color, without ensuring that the text color is readable (i.e. accessible) for the given background color. I will often find "white" hardcoded as text-color, which is fine for the themes we built, but would not work as soon as I chose `#FFFFBB` as primary color (or any other light color).

I therefore introduced variables that explicitly cover text that is displayed **on** the given color (e.g. primary).

If you think this is a good idea, I should probably go ahead and at least use those colors in some popular places (e.g. buttons).

**Comment by NobodysNightmare** [comment]
This PR has become a solution for: https://community.openproject.org/work_packages/20270

**Comment by floriank** [comment]
so far, LGTM.

I concur that we should wait until `4.1.2` has been released.

**Comment by ulferts** [comment]
@floriank OPS is working with a fixed hash. As QA is done, I think release/4.1 is still good to merge.

**Comment by floriank** [comment]
Ah great. I'll do a quick click through after lunch and merge it afterwards

**Comment by myabc** [comment]
http://sassnotsass.com/

**Comment by NobodysNightmare** [comment]
@floriank commented 11 days ago:

> Ah great. I'll do a quick click through after lunch and merge it afterwards

Hey Florian, how is lunch going? Do I have to worry?

;-)

**Comment by floriank** [comment]
> Hey Florian, how is lunch going? 

Still eating.

**Pull request merged**
