### PR TITLE
[18404] Styling inline edit: Change cursor and line height

### PR DESCRIPTION
**Pull request by HDinger**
- Changes the used cursor in inline edit fields.
- Reduce line height of the wp table.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-feature-inline-edit-cursor-line-hight.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://hdinger-feature-inline-edit-cursor-line-hight.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Don't we want to keep the not-allowed cursor for non-editable fields? :sob: 

Rest LGTM.

**Comment by HDinger** [comment]
The idea was that since the ID is now clickable but not editable the cursor would irate. But you are right, for other fields it would still make sense. I will change it.

**Comment by HDinger** [comment]
@oliverguenther The id field is now the only not-editable field which has the normal cursor.

**Pull request merged**
