### PR TITLE
Make Ruby style consistent in test-unit tests

### PR DESCRIPTION
**Pull request by myabc**
Because #2115 was in a more mergeable condition at the time, I skipped converting test-unit test syntax in original PR #2136. 
#2115 has since diverged and it would be probably be easier to repeat the migration steps based on a fresh branch.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://feature-consistent-ruby-style-test-unit.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://feature-consistent-ruby-style-test-unit.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
@myabc If you would fix the remaining hound issues I would happily merge all 3,5k lines of your PR ;-)

**Comment by myabc** [comment]
@NobodysNightmare Fixing line lengths to conform will require a fair amount of manual work. It's probably better if we do this as we do along instead.

**Comment by NobodysNightmare** [comment]
Merging... the failures should be known _Umfaller_ tests...

**Pull request merged**
