### PR TITLE
[25544][25596] Render contents of additional relation rows

### PR DESCRIPTION
**Pull request by oliverguenther**
Implements [#25544](https://community.openproject.com/projects/openproject/work_packages/24454) for additional relation rows.

This required a refactoring of the way work packages are refreshed in the table, since now multiple passes can add full work package members to the table, not just the primary render pass.

Also fixes https://community.openproject.com/work_packages/25596

**Open issues**

- [x] Table inline edit is unique for each work package ID. If a work package occurs twice due to a relation column folded out, it is not uniquely identifiable.
- [x] ~~Timeline appears to render relations not only to FS relations~~ Not originating from this PR.

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/363191ba7cbb3017a0021d6a43674bf9381847f5) (deployed commit: f14a74a365e12045399ce00dd0de8c95e71e0403).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/154659361b5939b3f34f3421e8fe49a8513e652b) (deployed commit: 2fb002e176429e20d10fdda9a20b060c7feda9b1).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/56d9410d8c1c0d38a44507b75f141075b8d23359) (deployed commit: f2dfdb1de72f110582ec6f014ea63bfeea4d959c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7846c10923625ac48835832f1cfc39477738b5ca) (deployed commit: 98fb45d496a68feb88004570e7c8db52dd1ce8f7).

**Comment by oliverguenther** [comment]
Only failing spec is the flickering custom_field_spec

**Comment by ulferts** [comment]
For some reason, I cannot open some of the relation columns:

screen shot 2017-06-22 at 15 28 53

I can open them when I have loaded the same work package in the details pane (relations tab) and also sometimes after opening other relation columns before

screen shot 2017-06-22 at 15 30 36

**Comment by ulferts** [comment]
Having relations columns adds about a second (on my machine/medium sized project) to the time the user has to wait for the initial loading of the table. As such, it is good that you implemented the change intelligently enough as to not do all the extra work when no such columns exist.

I didn't check on a multi threaded server, and the results might be quite different there, but it seems that one could save quite some time when first querying for the additional work packages instead of for the query form:

screen shot 2017-06-22 at 15 32 55

Doing that, the table could be rendered faster as it all necessary information would be fetched first. The filters would be available later than but that section is less important.

**Comment by ulferts** [comment]
image

Expanded relation columns are not hidden when collapsing a group

**Comment by ulferts** [comment]
I sometimes<sup>TM</sup> cannot close a relation column
image

**Comment by ulferts** [comment]
Probably not unique to this feature as I can construct other scenarios where the same does apply:
If I have a work package A and add a relation to a work package B from a different project and B lacks a required custom field and the custom field is not active in the project of work package A, I in effect cannot edit the work package B displayed as a result of expanding the relation column of work package B (when displayed in the project of work package A) as the column does not exist there:
image

As said in the beginning, this is not unique to the feature but it will probably happen more often now. We should open the split view in such a scenario then.

**Comment by oliverguenther** [comment]
I can't seem to reproduce ~~the first~~ and fourth comment. The others (well, except the last one) should be fixed.

**First**

~~The relation builders assume that all required work packages in target relations are fully loaded by the wpTableRelationColumns service. The error stems from a work package not being loaded - Can you reproduce this reliably with certain steps?~~

**You're likely loading more than 20 elements, which is the pageSize of the WP filter. I guess we'll need an override to the pageSize to output all elements.**

**Fourth**

The log output appears fine. The row click handler registers a click on the row, but is skipped because the event target is a child of a table cell. The relation click handler logs when a click is registered. I did find some inconsistencies in the return value of the row click handler so that might have been it, but since I could not reproduce it, I'm not sure.

**Last**

I agree, however I think we should deactivate the column splicing then. I find that very irritating since it changes my query without asking, and does not revert to my configuration after the WP saved correctly.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/68ac4f67104dae9ee69196d5d6da63aeec75367e) (deployed commit: 5bf976691976c7948d870b1596b5e455ae8ac0ae).

**Comment by ulferts** [comment]
> I agree, however I think we should deactivate the column splicing then. I find that very irritating since it changes my query without asking, and does not revert to my configuration after the WP saved correctly.

YES, pretty please

**Comment by ulferts** [comment]
The height calculation for the rows (table vs. timelines) seems to be slightly off: 
image

This will not prevent merging the PR.

**Pull request merged**
