### PR TITLE
Nowrap in column header css.

### PR DESCRIPTION
**Pull request by manwithtwowatches**
https://www.openproject.org/work_packages/11893

This seems too easy. Perhaps my lack of css knowledge is showing.

### CODE REVIEW

**Comment by ulferts** [comment]
:+1:

**Comment by myabc** [comment]
Looks right. How do we handle long column headers (e.g. custom field headers) though?

**Comment by manwithtwowatches** [comment]
They have max 30 characters.

**Comment by myabc** [comment]
@manwithtwowatches where are they truncated? (sorry if I'm missing something)

**Comment by ulferts** [comment]
In either case, they are a question for a separate PR. The table column is always just one line so I believe that this looks good for now.

**Comment by manwithtwowatches** [comment]
@myabc i thought it was Rails model validation but having a quick look i can't actually see it anywhere... try making a custom field though it validates the name to max 30 chars.

**Pull request merged**
