### PR TITLE
Indent lists in wp panel; increase height of project list

### PR DESCRIPTION
**Pull request by mk84**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mk84-wp-fullscreen-list-styles.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mk84-wp-fullscreen-list-styles.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by mk84** [comment]
@basiszwo please review and merge

**Comment by basiszwo** [comment]
After creating 10 projects the list still has this size

bildschirmfoto 2015-09-29 um 22 00 05

**Comment by mk84** [comment]
@basiszwo the height depends now on viewport height.

**Pull request merged**
