### PR TITLE
remove rack definition from Gemfile

### PR DESCRIPTION
**Pull request by marutosi**
Original PR is #3147.

It is managed by Gefile.lock.
It should be updated by "bundle update rack".
For example #2953.

@myabc is wrong.
https://github.com/opf/openproject/pull/3147#issuecomment-112861712

https://github.com/rails/rails/blob/v3.2.22/actionpack/actionpack.gemspec#L26

> s.add_dependency('rack', '~> 1.4.5')

So, you can update by "bundle update rack".
https://bitbucket.org/marutosi/openproject-pr3147-rack/commits/a978bf65b6ceb2c0f5fb8f86e92275b6b8cf6cd5

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-0-rack.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-0-rack.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Dear @marutosi,

this will not get merged even if you open up the same PR all over again. We already closed:
- #3152 
- #3151 

Please accept our decisions. 

By reopening a PR you are in no way helping the discussion. Worse, you are blocking OpenProject development by using up the limited travis workers we have. I sincerely hope that this is not your intend. 

I welcome your contributions to OpenProject and thus must ask you to be more cooperative so we can work with them and see to making OpenProject better.

As your PRs have the tendency to fail their travis run and you typically open up a lot of PRs, please let travis run on your fork before opening a PR here.

Kind regards,

@ulferts

**Comment by marutosi** [comment]
> Please accept our decisions.

I cannot accept because you are wrong.

> By reopening a PR you are in no way helping the discussion.

Again, contributor cannot reopen PR closed by "ものわかりの極めて悪い" repository owner.

> limited travis workers we have

This is travis defect.
I will create travis issue.

> please let travis run on your fork before opening a PR here.

I always run travis.
https://travis-ci.org/marutosi/openproject/builds

**Comment by marutosi** [comment]
> This is travis defect.

https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-76325277

**Comment by marutosi** [comment]
> I will create travis issue.

I have created https://github.com/travis-ci/travis-ci/issues/4114 .

**Pull request closed without merging**
