### PR TITLE
[34712] Menu too small/completely hidden on Roadmap

### PR DESCRIPTION
**Pull request by bsatarnejad**
Make the menu visible and the whole menu sidebar scrollable.

https://community.openproject.com/projects/openproject/work_packages/34712/activity

### CODE REVIEW

**Review by ulferts — APPROVED** [review]
Change looks good @bsatarnejad.

Admittedly, I do not have the setup at hand to see if the behaviour is also working in case the "Buy now" teaser is there. Did you check for that?

Something that would also be good if you could check it: Do we actually need the `main-menu-wrapper` in the DOM? It does not appear to have styles and when I remove it just to try it out, I did not spot any problems. Could you please double check?

**Comment by bsatarnejad** [comment]
Hi @ulferts yes we need this wrapper for wiki and WPs pages while the buy-now-teaser component is added to the dom. If it wasn't, there would be two scrolls in sidebar menu.

Screenshot from 2020-10-01 12-45-09

 
I recheck the changes in wiki, workpackages and roadmap pages.

**Comment by wielinde** [comment]
@bsatarnejad @ulferts Unfortunately this brakes the BCF module in the BIM edition. As we have a BIM deployment tomorrow morning and I didn't find a solution for the Roadmap quickly enough, I decided to revert this PR here and gain some time to fix it while allowing BIM users still use their software.

**Comment by wielinde** [comment]
@bsatarnejad There is another issue coming up with your solution. It is a feature that the left arrow `.main-menu--arrow-left-to-project` and the module name button `main-menu--parent-node` stays always visible while the content below is scrollable. The idea is that should always be able to go one navigation level up quickly.

**Comment by ulferts** [comment]
@wielinde can you and @bsatarnejad then please try to figure out a solution together?

**Pull request merged**
