### PR TITLE
Rails4.0: update awesome_nested_set version to 3.0.2

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-rails4-ans-3-0-2.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by linki** [comment]
major version changes should be explained

**Comment by marutosi** [comment]
> major version changes should be explained

https://github.com/collectiveidea/awesome_nested_set/blob/v3.0.2/CHANGELOG#L13

**Comment by marutosi** [comment]
> linki added the invalid label 

Are you kidding?

**Comment by floriank** [comment]
> linki added the invalid label
> Are you kidding?

No, the label was added before your explanation.

**Comment by NobodysNightmare** [comment]
@marutosi  I am really looking forward to the day when you start to explain your changes:
1. without being asked explicitly
2. by writing things called "sentences"

Here is an example:

> This PR updates the version of awesome nested set to 3.0.2, which is required for Rails 4.1+
> see [the official changelog](https://github.com/collectiveidea/awesome_nested_set/blob/v3.0.2/CHANGELOG#L13)

**Pull request closed without merging**
