### PR TITLE
sqlite3: use '1=1' instead of Arel::Nodes::True.new

### PR DESCRIPTION
**Pull request by marutosi**
This is a part of #3040.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-sqlite3-project-sharing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-sqlite3-project-sharing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
If this is a part of #3040, why open another PR against the same branch?

**Comment by marutosi** [comment]
> why open another PR against the same branch?

Are you kidding?
Please teach me if it is possible.

**Comment by floriank** [comment]
PR <-> Branch is 1:1 at GitHub. Open a PR and work on that branch if you want to change anything on it. Multiple PRs with the same commits against the same branch basically do nothing of added value.

**Comment by marutosi** [comment]
I don't ask such thing.
I ask how to open "another PR against the same branch".

**Comment by floriank** [comment]
You just create a branch, push it to your repo, and create a PR against a branch in out repo.

**Comment by marutosi** [comment]
> You just create a branch.

Huh?

You said "why open another PR against the same branch?".

Again.
How can we open "another PR against the same branch"?

**Pull request closed without merging**
