### PR TITLE
Gemfile: use :mri for pry-byebug

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-3-0-pry-byebug.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-3-0-pry-byebug.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
Could you provide a short description on the reasoning behind this change @marutosi ?

**Comment by marutosi** [comment]
https://github.com/opf/openproject/commit/e0298f7196ac2d53e9692cecf5d457c314ec8066

**Comment by marutosi** [comment]
> Could you provide a short description

Why not reject #3182?

**Pull request closed without merging**
