### PR TITLE
update gon to 5.2.3

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-dev-gon-5-2-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-dev-gon-5-2-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
The general question of interdependent PRs aside. Just why:

commits
prs

**Comment by NobodysNightmare** [comment]
P.S.: You broke travis

> NameError: uninitialized constant Gon::GonHelpers

**Comment by NobodysNightmare** [comment]
@marutosi Please tell me if you intend to bring this PR into a form that passes the travis tests.
Otherwise I will close within the next few days, because it does not satisfy travis.

Also note the following things:
- please provide a description for your PRs
- when there are interdependencies between your PRs, tell us why they are neccessary. I personally do not see the link between updating `multi_json` (separate PR) and `gon`. So there is either a reason that you need to explain or it was a pure mistake.

**Comment by marutosi** [comment]
> please provide a description for your PRs

Why not reject #3182?

**Pull request closed without merging**
