### PR TITLE
[#40680] Documentation on how to use git inside of OP concerning the docs

### PR DESCRIPTION
**Pull request by as-op**
https://community.openproject.org/work_packages/40680

### CODE REVIEW

**Comment by as-op** [comment]
Recreated PR https://github.com/opf/openproject/pull/11024

**Comment by ghost** [comment]
@as-op this pull request is based on opf
the old pull request was based on adam-op repo. i am not allowed to work on the opf repo,
you mentioned that you will close the old one and i will have to re edit the things, now i am unsure if the edits are inside this pull request or not.
please advice. what i need to re-edit or not, thank you

**Comment by as-op** [comment]
https://github.com/opf/openproject/pull/11041#issuecomment-1197781703

**Review by machisuji — APPROVED** [review]
👍

**Pull request merged**
