### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### opf/openproject now has a Chat Room on Gitter

@myabc has just created a chat room. You can visit it here: [https://gitter.im/opf/openproject](https://gitter.im/opf/openproject?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/opf/openproject?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://gitter-badger-gitter-badge.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by linki** [comment]
:+1:

**Comment by linki** [comment]
thanks @gitter-badger

**Comment by gitter-badger** [comment]
no problem!

**Pull request merged**
