### PR TITLE
[26219] Manually change width of Gantt

### PR DESCRIPTION
**Pull request by HDinger**
Apply wp resizer to the timeline. 

* Since the component should be more generic the elements to resize and the according localStorageKey has to be given as parameter. 
* The `wp-resizer.service` is not needed any more.
* The resizer for timeline needs special styling rules to avoid that it is scrolled out of view.

https://community.openproject.com/projects/openproject/work_packages/26219/activity

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/169178b1fc7a1ab5f38c6a2800010e1b7b498e15) (deployed commit: 6a6adb45f2627f4ecad7c656cff93406afea8e68).

**Comment by lindenthal** [comment]
Hi @HDinger,

thanks for this feature. It is great!

One mini minor remark regarding the print view. Is it possible to hide the new drag handle in the print view?

image


Thanks
Niels

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/3a230e4bd3169089761a8f6f1bfee08cd966eb01) (deployed commit: 608791251046354be3118fc5d13a7b9bbbe07bed).

**Comment by HDinger** [comment]
Hi Niels,

thanks for your feedback. I included it in the latest commit.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/3575e6d33ba66eb435ef35c6d1b50c9cc938e694) (deployed commit: f8d5144096bdb9973ba2a6dd8a497e7d8b61c04f).

**Pull request merged**
