### PR TITLE
Use rails 4 secret_key_base

### PR DESCRIPTION
**Pull request by basiszwo**
This makes use of rails 4 secret_key_base functionality and removes the according deprecation warning `DEPRECATION WARNING: You didn't set`secret_key_base`.`

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://basiszwo-secret-key-base.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://basiszwo-secret-key-base.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by basiszwo** [comment]
@jonasheinrich can you please check implications of deployments? I guess we need to set `ENV["SECRET_KEY_BASE"]`

**Comment by jonasheinrich** [comment]
@basiszwo yes, in environments that get configured with environment variables that should be enough. 

But what do you think about an initializer that reads a yml-file (like the old `config/secret_token.yml`) and sets the environment variable? I would do it the following:
- if the env variable is already set -> do nothing
- if the env variable is not set and there is a correct `secret_token.yml` -> set the env variable
- if the env variable is not set and there is no correct `secret_token.yml` -> raise an error. 

This way we can also preserve `rake generate_secret_token`.

**Comment by basiszwo** [comment]
look, I removed this custom behaviour and replaced it with rails default behaviour. see `config/secrets.yml` for what you are referring to. 

Env variable is just for production environments.

**Comment by jonasheinrich** [comment]
I think this custom behaviour is a good thing to have. In some environments we don't use environment variables but the `config/secret_token.yml`. It would be easier and more flexible to keep that option. 
I thought the main advantage was to get rid of the deprecation warning. We would achieve that, too, with this option. 

Actually, I got that from the [upgrade guide to rails 4.1](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml):

> Use your existing secret_key_base from the secret_token.rb initializer to set the SECRET_KEY_BASE environment variable for whichever users running the Rails application in production mode. Alternatively, you can simply copy the existing secret_key_base from the secret_token.rb initializer to secrets.yml under the production section, replacing '<%= ENV["SECRET_KEY_BASE"] %>'.

**Comment by basiszwo** [comment]
So there are deployments to be adjusted to use `secrets.yml` file, right? @jonasheinrich can you do this? What is required for the packager installation?

**Comment by jonasheinrich** [comment]
yes, adjusting the secrets.yml looks good. 

For packager I think we just need to rename the env variable: https://github.com/pkgr/addon-openproject/blob/3b802946b3997af70e764ccd71756899f8296abf/bin/postinstall#L38

**Comment by basiszwo** [comment]
I created the pull request to the pkgr addon. @jonasheinrich please update the deployments accordingly. Please do not forget about SaaS.

**Comment by jonasheinrich** [comment]
I will adapt the deployments except for SaaS. I can have a look into SaaS but I think @crohr should also be notified about this.

**Pull request merged**
