### PR TITLE
[22126] Fix copy project

### PR DESCRIPTION
**Pull request by basiszwo**
https://community.openproject.org/work_packages/22126

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://22126-fix-copy-project.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://22126-fix-copy-project.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by jonasheinrich** [comment]
Afaik delayed job just logs into development/production log. Concerning log rotate it should be the same for all of our types of installations. On OpsWorks the [complete log folder should be logrotated](https://github.com/aws/opsworks-cookbooks/blob/b0b56ff404adea5ef6969a10d480b37b8fc4d7f5/deploy/definitions/opsworks_deploy.rb#L206). For customer installation this [should also hold true](https://github.com/finnlabs/chef-openproject/blob/c59fcfe5fce4339e415ac1695d02f2291653a3a1/templates/default/logrotate.erb#L2).
But I'm not sure about SaaS. And we should also inform the community about this change.

**Comment by basiszwo** [comment]
having everything in the production log is no problem but makes it hard to discover problems with background jobs. I would appreciate if we could separate this.

@crohr do we need to change sth. for SaaS deployment?

**Comment by crohr** [comment]
@basiszwo our SaaS platform is like heroku, in that logs must be sent to stdout. We're injecting `rails_stdout_logging` into OpenProject, which takes care of redirecting rails logs to `STDOUT`, but if you manually set delayed jobs worker to log into a file, those logs will be lost for SaaS (plus they won't be logrotated in the docker container). I don't understand why you need to separate them, isn't there some kind of prefix you could set on the logger to easily differentiate them in the same stream?

**Comment by crohr** [comment]
Or at least we need to be able to overwrite that as an option.

**Comment by oliverguenther** [comment]
Okay, then I suggest we move it out of this PR. @basiszwo: Can you revert the affected line https://github.com/opf/openproject/pull/3909/files#diff-d94ba68fd8ba35624af2db6416075d4dR36 so that we can move on with this PR?

**Comment by basiszwo** [comment]
Removed the separate log file.

**Comment by oliverguenther** [comment]
Thanks @basiszwo. :+1:  I've tested the copying process. Merge at will after travis.

**Pull request merged**
