### PR TITLE
[24025] Allow description and long text custom fields as columns on work package lists

### PR DESCRIPTION
**Pull request by bsatarnejad**
Enable WP grid to have description and long text custom field columns.

https://community.openproject.com/projects/openproject/work_packages/24025/activity

### CODE REVIEW

**Comment by oliverguenther** [comment]
@lindenthal I discussed with Behri and we will likely need your input on this. Simply adding the columns will too often break the flow of the table due to the height of the description (e.g, long headlines, images, etc.).

Quick ideas we came up with:

1. Only show a link "show description" that opens a toolbar / modal
2. Someone abbreviate the description so it fit into the table

Not very happy with either approach, but maybe you have additional ideas?

Best
Oliver

**Comment by lindenthal** [comment]
Hi @oliverguenther,
what is the use case for this feature? What is wrong with the split view?
Best
Niels

**Comment by oliverguenther** [comment]
Hi @lindenthal , the original ticket was primarily targeting that these columns are missing from a (structured) export and cannot be added by any other means. But we can remove that ticket from the backlog if you prefer.

I would suggest we pursue (1) to avoid any layout disruptions.

**Comment by lindenthal** [comment]
Hi @oliverguenther,
what do you mean with structured export? Is it the xls with descriptions?
Best
Niels

**Comment by oliverguenther** [comment]
Yes, for example a long test custom field cannot be exported into XLS, CSV, etc. We do have a specific case for XLS with descriptions, but that does not include custom fields

**Comment by lindenthal** [comment]
Got it: what about using the split view to show the content of those fields instead of a modal?

**Comment by oliverguenther** [comment]
That would work for the regular table yes. I wonder if it also makes sense to show these columns in an embedded table where we can't open a split view? 

Maybe we put this feature on hold and move it back to the wish list instead until we have a clearer image on what should happen

**Comment by lindenthal** [comment]
Hi @oliverguenther,
yes, I agree there are other parts of the application wither higher RICE values.

Best
Niels

**Comment by bluedeepimpact** [comment]
This topic has been reported again here: https://community.openproject.com/projects/openproject/work_packages/35588

**Pull request closed without merging**
