### PR TITLE
[20043] Upgrade to Rails 4.1.x

### PR DESCRIPTION
**Pull request by myabc**
:warning: **Please review, merge opf/openproject-translations#28 first**, adjusting branches in `Gemfile` as appropriate.

Replaces #3197

https://community.openproject.org/work_packages/20043

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-rails4-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-rails4-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
263 lines added, 259 lines removed

impressive! Seems like you have done a good job before this PR :+1: 

(as in: those are fewer lines than I would have expected)

**Comment by myabc** [comment]
> impressive! Seems like you have done a good job before this PR :+1:

Yep, that was the idea! :smile:

**Comment by oliverguenther** [comment]
@myabc Just to note: There are still some broken / yet-to-adapt cukes that I didn't catch due to lack of time in the spec PR.

**Comment by myabc** [comment]
@oliverguenther I'll take a quick look later today/tomorrow - @basiszwo needs a rough assessment of how long it'll take to get this + plugin PRs to a _mergeable-state_.

**Comment by oliverguenther** [comment]
@myabc I'll try to take care of the core cukes now, then you can focus on the plugin PR

**Comment by ulferts** [comment]
Looks all good so far @myabc. That list of plugin PRs over in #3197 is pretty long so are there actually any more plugins missing?

**Comment by oliverguenther** [comment]
@myabc I've addressed some issues over at https://github.com/myabc/openproject/pull/5.

I'm still getting the following errors:

```
(::) failed steps (::)

undefined method `encode' for RackSessionAccess:Module (NoMethodError)
./features/step_definitions/general_steps.rb:73:in `/^(?:|I )am already [aA]dmin$/'
features/activities/index.feature:48:in `And I am already admin'
```

It doesn't correctly load the parent `RackSessionAccess` module containing `#encode`. I can't seem to solve it by requiring it manually.

**Comment by myabc** [comment]
@oliverguenther 

> It doesn't correctly load the parent RackSessionAccess module containing #encode. I can't seem to solve it by requiring it manually.

Are you seeing this issue on Travis or locally?

Unfortunately, myabc#5 hasn't got the cukes green yet - it looks like there are still a few more issues to work though

**Comment by oliverguenther** [comment]
Locally. Looks like that issue shadows the actual travis issues you see on the CI.

**Comment by oliverguenther** [comment]
@myabc , I've created another PR with a fix for all cukes, but there's one feature whose issues are strange: `features/groups/group_memberships.feature`.

The problem in this feature is that the group table doesn't seem to contain the latest change, so the user that is to be deleted doesn't exist in the table: 

```
Unable to find css "#user-4" (Capybara::ElementNotFound)
./features/step_definitions/web_steps.rb:71:in `with_scope'
./features/step_definitions/web_steps.rb:78:in `/^(.*) within "(.*[^:"])"$/'
./features/step_definitions/group_steps.rb:79:in `/^I delete "([^"]*)" from the group$/'
features/groups/group_memberships.feature:143:in `And I delete "hannibal" from the group'
```

You can verify that this is indeed the case by forcing `GroupsController#edit` to reload `@groups`, which will contain the latest change, but I believe there must be some other issue that's causing this.

By using `eager_load` directly instead of `includes`, the association is correctly reloaded. This may be related to https://github.com/rails/rails/issues/16032

**Comment by myabc** [comment]
@oliverguenther thank you! I went ahead a merged myabc/openproject#6

**Comment by myabc** [comment]
the automatic openproject-translations job introduces a small merge conflict (in `Gemfile.lock`) once every 24 hours. It's probably easier to simply merge this branch manually in `dev` and fix the conflict then. / @ulferts @jonasheinrich

**Comment by myabc** [comment]
@ulferts @basiszwo @NobodysNightmare @oliverguenther This PR and the accompanying plugin PR's should now be ready for review. With the exception of two issues, they should be good to merge:
- two Cucumber failures in _openproject-impermanent_memberships_: I may need help here from @ulferts, as I'm not familiar with the plugin.
- cleanup of my _openproject-reporting_ [WIP commit](https://github.com/finnlabs/openproject-reporting/commit/c126b89f01633990fcf9c760e7168a8d9a119a8e): see comment https://github.com/finnlabs/openproject-reporting/pull/74/files#r38270495. Again, I think @ulferts is probably the best person to guide here.

The goal of this and related plugin PR's was to get Rails 4.1 running reliably. There are some _optional changes_ that could follow, but I feel this cleanup should happen in separate PR's:
- Replacement of `Project.allowed_to_condition` with `Project.allowed_to` (e.g. 29d98143)
- Replacement of `find_by_attr` with `find_by(:attr)`, purely for sake of consistency (e.g. #3400)
- Replacement of `order` SQL Strings with Hash (e.g. https://github.com/opf/openproject/blob/dev/app/models/work_package.rb#L74)

**Comment by ulferts** [comment]
@myabc, I will take a look at both issues you mentioned

**Comment by oliverguenther** [comment]
I've been manually testing and running the specs for org and my config, and they work fine except for one spec in the latter config that I could not yet figure out.

```
 1) API::V3::Queries::QueryRepresenter generation should indicate whether sums are shown
     Failure/Error: is_expected.to be_json_eql(query.display_sums.to_json).at_path('displaySums')
     JsonSpec::MissingPath:
       Missing JSON path "displaySums"
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/helpers.rb:51:in `missing_json_path!'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/helpers.rb:40:in `block (2 levels) in value_at_json_path'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/helpers.rb:40:in `fetch'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/helpers.rb:40:in `block in value_at_json_path'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/helpers.rb:37:in `each'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/helpers.rb:37:in `inject'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/helpers.rb:37:in `value_at_json_path'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/helpers.rb:9:in `parse_json'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/matchers/be_json_eql.rb:61:in `scrub'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/gems/json_spec-1.1.4/lib/json_spec/matchers/be_json_eql.rb:21:in `matches?'
     # ./spec/lib/api/v3/queries/query_representer_spec.rb:79:in `block (3 levels) in <top (required)>'
     # /Users/oliver/.rvm/gems/ruby-2.1.6/bundler/gems/rspec-example_disabler-deb9c38e3f4e/lib/rspec/example_disabler.rb:13:in `block (2 levels) in register_disabler'
```

Code-wise, the changes in this PR look good to me, except for one mistake I've introduced while fixing the specs. I've addressed this https://github.com/myabc/openproject/pull/7, even though it doesn't seem to be used and thus affect any example. I have not yet looked at the Plugin PRs except running specs on them.

**Comment by myabc** [comment]
@oliverguenther thanks for the review! - I'm not seeing the particular failure you mentioned locally (`bundle exec rspec ./spec/lib/api/v3/queries/query_representer_spec.rb`) or on the internal CI, so I'm not sure how much I can help. Since @NobodysNightmare's worked on the API extension points for plugins, he might have a better idea.

btw, I do see some some other flickering specs on Jenkins, but these AFAICT, also affect `dev`.

**Comment by oliverguenther** [comment]
I can only reproduce that particular spec on the `myproject` config, so this is probably not directly related to this PR, but rather some plugin side effect.

**Comment by myabc** [comment]
@oliverguenther curious. I was testing locally primarily with `myproject` config.

**Comment by oliverguenther** [comment]
Weird. I'll reassure I've completely cleaned up my installation and let them re-run to make sure.

**Comment by NobodysNightmare** [comment]
> JsonSpec::MissingPath: Missing JSON path "displaySums"

Basic questions:
- did you run all migrations? (if not `displaySums` could be `NULL` and would thus not be displayed)
  - if yes: did you `rake db:test:prepare`?
- nobody removed any lines reading `property :display_sums` from the `QueryRepresenter`, right? :wink:

Most probable cause is missing migrations in specs...

**Comment by oliverguenther** [comment]
Does not fail on a clean install. I did run both migrations and prepare last time, though. Oh well, better that way :)

**Comment by myabc** [comment]
Please remove wip tag.

**Comment by NobodysNightmare** [comment]
> Please remove wip tag.

Sir, yes sir!

**Comment by ulferts** [comment]
@myabc this is looking ripe to be merged. I made only some minor annotations regarding possible code improvements in the plugins. I'd like to wait for you feedback on my proposals and merge this then.

**Comment by NobodysNightmare** [comment]
:tada:

**Pull request merged**
