### PR TITLE
Fix LegacyIssuesToWorkPackages for AR API change

### PR DESCRIPTION
**Pull request by marutosi**
#select_all returns a ActiveRecord::Result.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-fix-legacyissuestoworkpackages.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@marutosi 

> #select_all returns a ActiveRecord::Result.

In Rails 4. In Rails 3.2 it [returns an Array](http://apidock.com/rails/v3.2.13/ActiveRecord/ConnectionAdapters/DatabaseStatements/select_all). Since `Array#size` aliases `length`, this PR isn't necessary IMO.

**Comment by marutosi** [comment]
http://www.ruby-doc.org/core-2.1.4/Array.html#method-i-length

**Comment by myabc** [comment]
http://www.ruby-doc.org/core-2.1.4/Array.html#method-i-length

> Also aliased as: `size`

**Comment by marutosi** [comment]
> Also aliased as: size

It is compatible with Rails3.

**Pull request closed without merging**
