### PR TITLE
Import _settings.scss before Foundation framework

### PR DESCRIPTION
**Pull request by myabc**
Order is important here: Foundation variables are generally declared with `!default` flag within the framework, meaning they will only be set if not already defined.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-fix-foundation-settings-import-order.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-fix-foundation-settings-import-order.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@floriank @NobodysNightmare be aware that buttons will now appear smaller: our custom `$button-padding` value was not respected.

Before:
another_repo_test_-_arbeitspakete_-_openproject-org
After:
seeded_project_-_work_packages_-_openproject

**Comment by floriank** [comment]
Alright, I think i have to rebase #2771 then.

**Comment by NobodysNightmare** [comment]
I actually like that more :)

**Pull request merged**
