### PR TITLE
[25073] Check whether a row has any following children in the table

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.com/projects/openproject/work_packages/25073/

### CODE REVIEW

**Comment by ulferts** [comment]
Seems to remove too much:

image

The faulty hierarchy indicator at "blubs" is removed, but so is the desired indicator at "Development".

As a comparison, a screenshot from the dev branch: 

image

**Comment by ulferts** [comment]
Please also double check the representation of such wps in the Timeline:

image

**Comment by oliverguenther** [comment]
> Seems to remove too much

What steps did you take to make it happen? I'm on a fresh instance and can't seem to reproduce it.

**Comment by ulferts** [comment]
Ah, figured out the difference. The problem only exists, when sorting by something different than "Parent" which will result in the row being removed from its normal position and displayed in grey. Looks good if not changing sort by:

image

**Comment by oliverguenther** [comment]
I've refactored the code to adhere to the structure of the other modes (a `rows` builder to instrument the whole process and moving to a `single-row` builder to handle, well, single rows of WPs).

Fixed the issue you remarked and added a spec for when the parent is moved outside the default flow due to the hierarchy mode - even when that's going away in a subsequent PR again.

**Comment by ulferts** [comment]
👍

**Pull request merged**
