### PR TITLE
Enable RSpec zero monkey patching mode

### PR DESCRIPTION
**Pull request by cbliard**
Avoid monkey patching global namespace by RSpec. 

See https://github.com/rspec/rspec-core/blob/main/features/configuration/zero_monkey_patching_mode.feature for details.

### CODE REVIEW

**Comment by klaustopher** [comment]
Nice one! Personally I am a fan to also remove the global `create`/`build`/... methods from `FactoryBot` and use `FactoryBot.create` instead.

**Comment by cbliard** [comment]
@klaustopher that's funny, because we did the opposite 1 year ago in https://github.com/opf/openproject/pull/10090

Personally, I prefer without the `FactoryBot.` prefix. This prefix feels just like noise when reading a test, and it makes the lines longer and harder to read.

**Comment by klaustopher** [comment]
Yeah, as I said, just a personal preference. I am fine with either way :)

**Comment by cbliard** [comment]
Unsurprinsigly, rubocop fails, and the github actions is reaching a limit here (`Only 65535 characters are allowed; 66075 were supplied`). 
If the tests are passing, I would suggest to just merge it.

**Review by klaustopher — APPROVED** [review]
"Problem" is that it's rescanning every file because you touched everything and there is just a lot of offenses in the test files. If the tests still pass, everything should be fine IMHO

**Review by aaron-contreras — APPROVED** [review]
Beautiful.

**Pull request merged**
