### PR TITLE
Fine tuning of DS basics

### PR DESCRIPTION
**Pull request by HDinger**
Since we merge the first DS PR in order to get relying features merged as well, there is some fine tuning to do:

- [x] Check subsequent changes by the product teams in the basics (colours, spacings, typography etc.)
- [x] Check  subsequent changes by the product teams in the components
- [ ] Todo:
  - [x] Button colours for outline and basic on hover and pressed
  - [x] Icons in buttons
  - [x] Spacing for buttons with icons
  - [x] Icons in chips
  - [x] Focus trap in drop-modal
  - [x] ~~Checkbox Items (Label and description for checkboxes)~~
  - [ ] Buttons in text fields
  - [x] Mobile version of drop modal: https://community.openproject.org/work_packages/41224/activity
  - [x] Correctly round buttons
  - [x] Limit drop modal height
  - [x] Checkbox background
  - [x] Text field color

Closes https://community.openproject.org/work_packages/41263/activity

### CODE REVIEW

**Comment by HDinger** [comment]
@b12f There are some issues with the project includes which prevent me from merging it:
1.  When the list of projects is longer than the available screen height, I cannot reach the modal buttons at the bottom and als the last project is half cut off
2. When I have to scroll, the checkboxes don't work correctly. The checkmark appears with an offset of the scrolled content:
Bildschirmfoto 2022-03-04 um 09 40 20

3. At some point when I clicked multiple projects, the whole page made a jump to the top resulting in white space below. The page was the stuck at this state and only solvable with a reload.
Bildschirmfoto 2022-03-04 um 09 44 07

**Comment by HDinger** [comment]
@b12f I think we should make the variables.sass file be loaded globally. Otherwise we need to import it every time we need to access a color variable (which will be basically every sass file). What do you think?

**Comment by b12f** [comment]
> @b12f I think we should make the variables.sass file be loaded globally. Otherwise we need to import it every time we need to access a color variable (which will be basically every sass file). What do you think?

Hi @HDinger, the variables are currently loaded globally in [openproject.sass](https://github.com/opf/openproject/pull/10200/files#diff-8c5820cce52ffa59e3f61d94fae925d7598362c0bcff6c951861d3a151511c6eR2), but in the per-component sass files, this does not happen. Unfortunately the angular cli & compiler seem to offer no option to import certain sass files for each file being compiled.

**Review by oliverguenther — APPROVED** [review]

**Comment by oliverguenther** [comment]
I altered the webfonts README as it was still referencing old paths as well as pinning the lockfile at v1 to keep its current form (we can re-evaluate if we can move to v2 and newer npm versions separately).

One downside with the approach of rendering the icon sass with mixins and definitions in one is that you can't import the mixins separately, say in the helpers, to use them in components. We could use two templates though (one for mixins, one for the icon classes) and run the generator twice. This downside however hasn't changed as you more or less moved / reused the functionality for the spot icons. So fine for me for now, but we should consider this if we need component icon mixins.

**Pull request merged**
