### PR TITLE
Restores transaction strategy

### PR DESCRIPTION
**Pull request by ulferts**
After some discussion about which one is faster and still produces
deterministic results, we decided to revisit the transaction strategy.

### CODE REVIEW

**Comment by mfrister** [comment]
As far as I can see, the timelines merge already included this:
https://github.com/opf/openproject/blame/c1bfd520/features/support/env.rb

But as @sschu said, setting this globally to truncation might make things significantly slower.
Does anyone have numbers about the speed decrease or reasons for setting this for all features?

**Comment by tessi** [comment]
I did some experiments a while ago. Haven't done any profiling, but it felt like a rough ~10% performance drop.
( _throwing numbers in the discussion, for which I have no proof_ )

**Comment by apfelfabrik** [comment]
I favor deterministic behaviour over performance. As long as we use the same isolation level in tests as in production, and we don't spend time investigating whether a failed test is just the result of some left-over/uncommited data, I'm good with either solution.

**Comment by apfelfabrik** [comment]
This is indeed cherry-picked from the private timelines branch, and is included in the squashed commit c1bfd5202a20a3f517595300cf0dba787c312fe8. I don't remember what specs exactly were affected by the change, so I hereby propose to:
1. Fix the build
2. Alter this PR to reintroduce the transaction model
3. See how the CI likes it

Opinions?

**Comment by tessi** [comment]
:+1:

**Comment by apfelfabrik** [comment]
I changed the strategy once more and changed the PR title and description accordingly.

**Comment by apfelfabrik** [comment]
Will Travis see this pull request despite its age?

**Comment by tessi** [comment]
I'll scheduled a rebuild on travis.

**Comment by nkenneweg** [comment]
How does this relate to #68

**Comment by mfrister** [comment]
I restarted the failed jobs again, since the last one failed.

**Comment by mfrister** [comment]
So, this doesn't seem to work well. Travis shows timeouts and even aborted a job due to no output for 10 minutes.
This doesn't happen with other jobs, so I assume this is related to this change.

**Comment by ulferts** [comment]
Nobody seems to care for this any more. I propose closing this. I will give this a grace period of a week. If nobody intervenes, I will close this.

**Comment by apfelfabrik** [comment]
L4st!

**Pull request closed without merging**
