### PR TITLE
[15285] Custom field button moved left (instead of being on the right) of the Custom fields page in Project settings

### PR DESCRIPTION
**Pull request by bsatarnejad**
https://community.openproject.org/projects/openproject/work_packages/50285/activity

### CODE REVIEW

**Review by HDinger — COMMENTED** [review]
Do you know by chance what originally lead to this bug? I am wondering if we break anything else with this change 🤷‍♀️  
Further, is there a reason you targeted this agains `release/13.0` and not `dev`?

**Comment by bsatarnejad** [comment]
> Do you know by chance what originally lead to this bug? I am wondering if we break anything else with this change 🤷‍♀️ Further, is there a reason you targeted this agains `release/13.0` and not `dev`?

Hi @HDinger I'll check it again if there is another reason raising this bug. :+1: 
For the second question: I checked the release 13.0 branch and found this bug there too, I thought it may be better to be fixed there. Should I change the base branch to dev?

**Comment by bsatarnejad** [comment]
Hi @HDinger 
I checked the changes again and figured out that this bug raised due to adding check all/uncheck all button to toolbar items [here](https://github.com/opf/openproject/commit/af292f6118be8fefdd6bed2cc67e3ef4f554e8d6#diff-cd8f3d3bd2248f948f63ba6b4d8e5f84b0797858a5f608042a7f6e4b930a2a8d) 
If we want to show the  check all/uncheck all button beside the toolbar title and other buttons on the right-side, we can use justify-content: space-between for the toolbar items which are 'check all/uncheck all button' and a group of buttons on the right side. I checked places which we have toolbar, it's not breaking other places.

**Comment by HDinger** [comment]
> Hi @HDinger I checked the changes again and figured out that this bug raised due to adding check all/uncheck all button to toolbar items [here](https://github.com/opf/openproject/commit/af292f6118be8fefdd6bed2cc67e3ef4f554e8d6#diff-cd8f3d3bd2248f948f63ba6b4d8e5f84b0797858a5f608042a7f6e4b930a2a8d) If we want to show the check all/uncheck all button beside the toolbar title and other buttons on the right-side, we can use justify-content: space-between for the toolbar items which are 'check all/uncheck all button' and a group of buttons on the right side. I checked places which we have toolbar, it's not breaking other places.

Ah, I understand. Thanks for looking that up! 👍

**Pull request merged**
