### PR TITLE
remove description warning from CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by marutosi**
Contributor cannot reopen PR closed by **stupid** repository owner.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-4-1-contributing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-4-1-contributing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
@marutosi your PRs are being closed because you constantly violate the contribution rules.

You re-open PRs that were closed without fixing any of the mentioned problems, you open PRs for the same problem twice. You are not someone I could communicate with. I don't know why to be honest. You linked a redmine ticket lately where you:
- wrote full sentences
- were polite
- explained stuff

Those are all things I'd like from you here on github as well, but you simply write nothing at all or simply copy your commit messages, you are at times insulting people (e.g. "stupid" from above).

I am honest: I sometimes get the feeling you are just trolling, this might not be your intention, but this is how your message arrives.

I am not closing this PR, because we explicitly **want** people to explain their stuff, the only community member not doing that is you.

**Comment by NobodysNightmare** [comment]
One last word of warning: If you keep on not playing by the rules we will see which further meaures we can take to stop you from distracting the work in this repository.

**Comment by marutosi** [comment]
You said "Please write description" many times. So I write a description on PRs.
Am I wrong?

**Pull request closed without merging**
