### PR TITLE
Fix migration for non-writable blank settings

### PR DESCRIPTION
**Pull request by cbliard**
https://community.openproject.org/wp/48125

### CODE REVIEW

**Comment by cbliard** [comment]
Once again I forgot to make the PR against 12.5. I'll rebase it.

**Comment by cbliard** [comment]
About the implementation, I hesitated to just delete the setting from the db so that the default value is picked (instead of trying to save the default value in the database, which is the current implementation).

**Comment by machisuji** [comment]
> About the implementation, I hesitated to just delete the setting from the db so that the default value is picked (instead of trying to save the default value in the database, which is the current implementation).

I would vote for deleting the setting. Since they are not writable they are not supposed to be in the DB to begin with. We could just check in the definition if it's writable, and if it isn't delete the setting rather than writing the default value.

**Comment by cbliard** [comment]
> > About the implementation, I hesitated to just delete the setting from the db so that the default value is picked (instead of trying to save the default value in the database, which is the current implementation).
> 
> I would vote for deleting the setting. Since they are not writable they are not supposed to be in the DB to begin with. We could just check in the definition if it's writable, and if it isn't delete the setting rather than writing the default value.

I'll do that then. Thanks @machisuji

**Review by machisuji — APPROVED** [review]
👍

**Comment by machisuji** [comment]
Thanks for the fix. Looks good to me!

**Pull request merged**
