### PR TITLE
Fix closing of datepicker on scroll.

### PR DESCRIPTION
**Pull request by knight-bubble**
[`* `#19612` Date picker is closed on scrolling`](http://community.openproject.org/work_packages/19612)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hirtie-maxim-fix-19612-date-picker-scroll-closing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hirtie-maxim-fix-19612-date-picker-scroll-closing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
@hirtie-maxim this should probably go against `release/4.1`

**Comment by NobodysNightmare** [comment]
Now the date picker is cut-off on the left side (at least if I am not at full width)

cut-off

**Comment by knight-bubble** [comment]
@NobodysNightmare, this is a known functionality, that an block with z-index and position absolute will be cut in block with overflow: hidden. If I will move it out of the block with overflow, then the datepicker won't be scrollable. We can do scrollable If we use some jQuery-magic :sparkles:, but it will some hard testebale calculations.

**Comment by NobodysNightmare** [comment]
@hirtie-maxim Then we will have to decide which way to go and which things are important here.

Probably try one (stay positioned, don't move) or try two (close on scroll) will be favorable.

Will have to see who can decide this ^^

**Pull request closed without merging**
