### PR TITLE
[19607] Use lodash cloneDeep instead of using angular.copy

### PR DESCRIPTION
**Pull request by floriank**
This should resolve a performance issue in the WP details view in the latest
Firefox. 

Should meet the requirements of https://community.openproject.org/work_packages/19607.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-fix-19607-fix-firefox-script-stop-issue.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-fix-19607-fix-firefox-script-stop-issue.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
:+1:

**Comment by NobodysNightmare** [comment]
I'll have another look and see if I can reproduce the performance issue and thus verify the fix...

**Comment by NobodysNightmare** [comment]
Problem is that I could not reproduce the performance issue locally, so we are basically left in the dark whether your fix will help.

:+1: if travis is green, but we will have to check the QA instance, whether it really helped at all...

**Pull request merged**
