### PR TITLE
Integrate openproject-release plugin functionality

### PR DESCRIPTION
**Pull request by oliverguenther**
This feature adds the option to print a release date and product version
to the admin/info view.

It tries to read the release/updated date from `config/RELEASE_DATE` or
the HEAD commit date, if available.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-feature-release-info.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://oliverguenther-feature-release-info.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
The release plugin also showed the version in the footer. We could make that an initializer and configurable, i.e., when users want to hide that two values. But I'm not entirely sure we need that for now.

**Comment by ulferts** [comment]
@oliverguenther I understand that we are writing the `config/RELEASE_DATE` file when packaging. When is `config/PRODUCT_VERSION` written?

**Comment by oliverguenther** [comment]
The RELEASE_VERSION should ideally be set when packaging product repositories. I haven't quite figured out a way to set this automatically, since we only derive other version numbers for MyProject. If it's not written, the product version is simply hidden.

**Pull request merged**
