### PR TITLE
cancels foundations overflow-y policy

### PR DESCRIPTION
**Pull request by ulferts**
This avoids unnecessary scrollbars in the forms.

https://community.openproject.org/work_packages/18518
https://community.openproject.org/work_packages/18923

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://fix-scrollbars-on-form-elements.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://fix-scrollbars-on-form-elements.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
I still have some scrollbars on some of the form elements in the view for 18923:

scrollbars

This is Chrome, Version 40.0.2214.115 (64-bit)

**Comment by floriank** [comment]
:+1: for 18518 though.

**Comment by floriank** [comment]
What a persistent problem:

scrollbars2

**Comment by myabc** [comment]
@floriank @ulferts we may want to look at either wrapping the relevant Foundation mixins – or trying to get Foundation to fix this upstream. Not sure why this this overflow setting is the default, when it's only really desirable for large content blocks.

**Pull request merged**
