### PR TITLE
[27992] Redesign OpenProject 8.0

### PR DESCRIPTION
**Pull request by HDinger**
This adds the new design to OP.

### ToDo

- [x] Change logo
- [x] Change default hex codes
- [x] Change favicon (currently I don't know where to get the file)
- [x] Clarify what the correct highlight color in the main menu shall be (see screenshot) --> a decision which is probably made by Christoph (?)
- [x] Check for further cases where the design is not correctly set 

https://community.openproject.com/projects/openproject/work_packages/27992/activity

### CODE REVIEW

**Comment by HDinger** [comment]
### Current state
bildschirmfoto 2018-08-17 um 16 17 44

**Comment by oliverguenther** [comment]
The active menu item looks too dark:

screenshot from 2018-08-17 13-58-32

**Comment by oliverguenther** [comment]
The query select menu still uses a dark color for non-highlighted entries

screenshot from 2018-08-17 13-59-30

**Comment by wielinde** [comment]
Hey @HDinger,

here some quick feedback on what I have found:

- [x] The OpenProject logo needs to sit 1px further down.
- [x] Search field within project selector shall have a little border radius, no background color.
- [x] The `active` color in main menu still has a bad contrast. Try the arrow left and arrow right buttons.

When design parameters are changed to white main menu background:

- [x] Placeholder text in query menu is not visible. I tried to use an alpha value on gray instead of white. Please feel free to try that out `color: rgba(190, 190, 190, 0.6)`
- [x] Outline of query search input hardly visible, as it is a very subtile shadow only. Maybe we can work with a gray+alpha background, again? So we would have a gray input field on a white menu background (not optimal, I know).

**Comment by HDinger** [comment]
@wielinde Thanks a lot! I included most of your remarks. Only the search field within project selector has still a background color, because I like it better ^^. Feel free, to submit a veto :-D

**Pull request merged**
