### PR TITLE
Virtual Scrolling Support for Work Package Table

### PR DESCRIPTION
**Pull request by romanroe**
**Comparing changes**

https://github.com/opf/openproject/compare/dev...romanroe:performance-improvements

**TODO**
- [x] Implement Virtual Scrolling
- [x] Disable watchers while not visible
- [x] Evaluate performance. Good/no good?
- [x] Test Accessibility

**Bugs**
- [x] Horizontal scrollbar
- [ ] Vertical scrollbar not visible once a horizontal scrollbar is necessary (bug not caused by virtual scrolling)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://romanroe-performance-improvements.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://romanroe-performance-improvements.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by romanroe** [comment]
@ulferts @oliverguenther The performance improved noticeable. Please check, feedback is appreciated. Good to merge once Travis is happy.

**Comment by oliverguenther** [comment]
It's noticeably faster, I still think we should display something to let the user know it's loading. But generally, good to go from my side.

**Comment by romanroe** [comment]
@oliverguenther I was hoping that you are completely happy and blown away ;-)

**Comment by oliverguenther** [comment]
@romanroe I assume we're not going to address the remaining issue you noted in the description in this PR? Should we merge this, then?

**Comment by romanroe** [comment]
@oliverguenther Correct. But have noticed this bug?

**Comment by oliverguenther** [comment]
Tried the PR on Teatro oncemore, the whole table pane appears to move and thus cause the vertical bar to move to the far right of the horizontal pane. It did disappear, but only from the viewport.

**Comment by romanroe** [comment]
Yes, thats what I meant.

**Pull request merged**
