### PR TITLE
Allow to configure asset_host, which can be used to host assets on a CDN

### PR DESCRIPTION
**Pull request by crohr**
Please let me know if there is some doc to update somewhere.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://crohr-feature-add-rails-asset-cdn-config.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://crohr-feature-add-rails-asset-cdn-config.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by machisuji** [comment]
@crohr Could please add some documentation to [CONFIGURATION.MD](https://github.com/opf/openproject/blob/dev/doc/CONFIGURATION.md)? Other than that this fine IMO.

**Comment by crohr** [comment]
@machisuji just added

**Comment by machisuji** [comment]
:+1:

**Pull request merged**
