### PR TITLE
19621 Fix autocomplete in sorting modal (all browsers), autocompleter visibility (IE)

### PR DESCRIPTION
**Pull request by myabc**
Supercedes #2863 

https://community.openproject.org/work_packages/19621

Also resolves:
- https://community.openproject.org/work_packages/19701

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-fix-19621-sorting-modal-in-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-fix-19621-sorting-modal-in-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
Autocompletion is not fixed yet, is it?

I'll probably come back when the work in progress label is gone ;-)

**Comment by myabc** [comment]
I didn't add the `max-height` override that @0xF013 had added in his PR, as I consider it out of scope: https://github.com/opf/openproject/pull/2863/files#diff-04e0f23e48434b17b59da0f3b34c4be2R99 – if we do implement it, I'd rather do so globally. @floriank @NobodysNightmare thoughts?

**Comment by NobodysNightmare** [comment]
I am not sure what that means TBH.

Is it about the dropdown not leaving the modal? This sounds out-of-scopish, because it is not mentioned in the ticket.

And in case it works that way now, I would rather leave it out too...

**Comment by floriank** [comment]
I concur, the `max-height` seems out of scope to me.

However, this should be reviewed by @NobodysNightmare for IE-related issues :wink:

**Comment by myabc** [comment]
> Is it about the dropdown not leaving the modal? This sounds out-of-scopish, because it is not mentioned in the ticket.

I think it was about the dropdown not leaving  _the viewport_ rather than the modal itself.

**Comment by NobodysNightmare** [comment]
LGTM, waiting for travis :+1:

**Comment by myabc** [comment]
https://community.openproject.org/work_packages/19701

**Pull request merged**
