### PR TITLE
Fix API to use JSON encoding for the body of non-GET requests

### PR DESCRIPTION
**Pull request by myabc**
See 6c36487 for why.

This Pull Request should make the API behaviour consistent with our own specification. For example: https://github.com/opf/op-api-v3-documentation/blob/master/apiary.apib#L234

Note: This does not currently test `RelationsAPI` (there was never any spec coverage for this resource)

### CODE REVIEW

**Comment by myabc** [comment]
#1715 was merged prematurely IMO (and this probably should have been spotted before merging in #1745).

**Comment by myabc** [comment]
@NobodysNightmare could you let me know if this is also the behaviour you expect?

**Comment by NobodysNightmare** [comment]
@myabc I am not entirely sure what I am seeing here.
Yes, I expect requests to be sent in JSON (as opposed to XML or YAML), but this is so obvious that I am not sure if this was the question ^^

**Comment by myabc** [comment]
@NobodysNightmare I just needed confirmation from your side :smile: 

>  but this is so obvious that I am not sure if this was the question

I'm pleased this is obvious to you, but without this fix, this isn't the case. We are currently expecting requests as `application/x-www-form-urlencoded`.

**Comment by NobodysNightmare** [comment]
This is why I included XML and YAML as counter-expectations ^^

I did not think about url-encoding, but I think for non-GET-requests (like the title says) this would be my expectation too.

However (not looking further at the code or the spec), I would also expect that request-parameters that work for url-encoded GET requests will also work for POST (and PATCH, and so on) as url-encoded.
But I don't know if we have any parameters that can be passed for both GET and non-GET requests.

**Pull request merged**
