### PR TITLE
[21473] Adjust My page to use homescreen widgets

### PR DESCRIPTION
**Pull request by oliverguenther**
Applies the homescreen widget styles to the my page layout.

There seems to be an issue with the reordering of blocks in edit mode due to the Sortable implementation that I did not yet figure out.

Relevant work package: https://community.openproject.org/work_packages/21473/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-feature-widget-styles.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://oliverguenther-feature-widget-styles.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
This is currently on hold from my side, please take over If you find the time.

**Comment by oliverguenther** [comment]
Functionaliity-wise, this looks good to me. I tried to quick-fix this while in Berlin while keeping the Sortable implementation, but this turned out to be the wrong path.

I have a minor issue though: There's a fine margin around some of the blocks, while on others (the two top-most in the screenshot do not.

This may be an issue from my commits, but it should be easy to fix. You can compare with the homescreen to see the desired border style around all blocks.

bildschirmfoto_2015-10-30_um_09_20_16

**Comment by why-el** [comment]
For the styling issues, @mk84 is best for it. I will create a new WP for that.

**Pull request merged**
