### PR TITLE
[#39772] update bcf to op view select

### PR DESCRIPTION
**Pull request by Kharonus**
- https://community.openproject.org/work_packages/39772
- fixed static view name resolving for bcf views
- added more-menu
- added bcf snapshot column to default views

### CODE REVIEW

**Comment by Kharonus** [comment]
This PR still targets the feature branch of the `op-view-select` rework.

it is meant to be on top of that feature. https://github.com/opf/openproject/pull/9957 is done, hence target branch is `dev` again.

**Review by b12f — APPROVED** [review]
LGTM

**Review by HDinger — COMMENTED** [review]
I am not quite sure whether that is intended or not: When I click on the ID link in a card, the split screen opens (same happens on the table). Normally when clicking the link we open the full view (compare for example with Boards or Work Packages module).

Other than that, it looks good 👍

**Comment by Kharonus** [comment]
It is currently intended, as we have no full view on any bcf route. The idea is, that the bcf module is consistent to itself and all of his viewer states. So, opening a workpackage in bcf (id click, double click or 'i' click), opens the details route (split). From there, if the user wants to work in full screen, he simply uses the extend to fullscreen icon, which leads him to the workpackages module into the full screen.

**Pull request merged**
