### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by Azure7111**
This is only house keeping: https://community.openproject.org/work_packages/18714

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://azure7111-fix-overdue-removal.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://azure7111-fix-overdue-removal.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
:+1: NICE!

**Comment by NobodysNightmare** [comment]
> This PR has no related ticket and should do nothing more than remove dead code.

The ticket is https://community.openproject.org/work_packages/18714 ;)

**Comment by NobodysNightmare** [comment]
good to merge if travis says yes :+1:

**Pull request merged**
