### PR TITLE
Feature/new default data

### PR DESCRIPTION
**Pull request by ulferts**
Consists of two parts:
1. Stripping the `DefaultData::Loader` of it's functionality and move everything into db/seed/...
   - The transparent creation of `PlanningElementTypeColors` has also been moved into the seeding
2. Adapting the seeded data according to the change requirements.
   - The type `none` is no longer seeded unless explicitly required. This should only be the case for installations that have had the timelines plugin installed. There shouldn't be to many of those. I still believe that the none type could serve it's purpose of implementing the null object pattern but this would only be necessary if it should actually be desired for work packages to be able to have no type.

Todo:
- [x] Remove loader altogether
- [x] Check with plugins
  - [x] Backlogs
  - [x] Multitenancy
  - ~~Meetings~~
- [x] Double check data
- [ ] Check to see whether the documentation needs to be adapted

https://community.openproject.org/work_packages/20853

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-feature-new-default-data.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ulferts-feature-new-default-data.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
Setting a WIP label, since there are open TODOs on your list.
Tell me if that labeling was applied at fault...

**Comment by ulferts** [comment]
How dare you @NobodysNightmare. :rage: 

Thanks, it's correct. They where missing.

**Comment by ulferts** [comment]
@kgalli, this removes `Redmine::DefaultData::Loader` in favor of completely seeding the database upon installation. It is still possible to specify the locale in which to seed the database by providing the locale via an ENV var, e.g.:

```
LOCALE=fr rake db:seed
```

We might want to adapt the packager based installation to accommodate to this.

**Comment by ulferts** [comment]
Wrong branch. Hm...

**Pull request closed without merging**
