### PR TITLE
Remove unsupported gems from Gemfile

### PR DESCRIPTION
**Pull request by mfrister**
This removes Gems for the unsupported JRuby and SQLite.

I think we should somehow specify the required ruby version, but I'm not sure on how to do this.
- Bundler (with `ruby` in the Gemfile) only allows to specify a x.x.x release (e.g. 2.1.1), but not a x.x release like 2.1. I don't think we want to do this.
- A `.ruby-version` file is used by rvm, rbenv and others to automatically select the right ruby version. For rvm, this automatically deselects a Gemfile one might use and I don't want to always create a `.ruby-gemset` file, so I don't like this solution either.

@ulferts @myabc Do you have any ideas on how to do this in a better way? Should we merge this anyway?

### CODE REVIEW

**Comment by mfrister** [comment]
@tessi just made me aware that we should check whether the repository tests still run without SQLite.

**Comment by tessi** [comment]
... that and that we have a bunch of files still referencing sqlite:

<pre>
./lib/chili_project/database.rb
./lib/tasks/ci.rake
./lib/plugins/acts_as_tree/test/acts_as_tree_test.rb
./lib/plugins/acts_as_journalized/test/schema.rb
./.travis.yml
./test/unit/lib/chili_project/database_test.rb
./config/database.yml.example
</pre>

**Comment by mfrister** [comment]
Added sqlite again as I don't want to look into all these tests and files now.

**Comment by myabc** [comment]
:+1: for 78c492b.

:-1: for 55a5eaa, but mostly because I'd (personally) like to see JRuby supported one day.

**Comment by myabc** [comment]
> Bundler (with ruby in the Gemfile) only allows to specify a x.x.x release (e.g. 2.1.1), but not a x.x release like 2.1. I don't think we want to do this.

Correct. There's no nice way to handle this, unless we want to roll our own version checking. I usually like to keep the amount of Ruby logic in a Gemfile to a minimum though.

RubyGems allows '~>' to be used with [required_ruby_version=](http://guides.rubygems.org/specification-reference/#required_ruby_version=). Unfortunately this doesn't help us much, as even if we were to add a `.gemspec` to the repo and call `gemspec` from our Gemfile, current versions of Bundler would simply ignore this attribute.

> A .ruby-version file is used by rvm, rbenv and others to automatically select the right ruby version. 

Including a `.ruby-version` file would cause pain for rbenv too, as (at least the last time I looked) rbenv won't do any fuzzy matching and instead requires an exact patch level to be specified.

**Comment by myabc** [comment]
> Bundler (with ruby in the Gemfile) only allows to specify a x.x.x release (e.g. 2.1.1), but not a x.x release like 2.1. I don't think we want to do this.

Given d9321bab, I might not be so adverse to specifying 2.1.1 in the Gemfile.

**Comment by mfrister** [comment]
> :-1: for 55a5eaa, but mostly because I'd (personally) like to see JRuby supported one day.

Just talked to @ulferts (answering part for him and part for me as he won't have time do it himself), he thinks using JRuby requires so much other work that it's not realistic that this will happen soon. As far as I know, JRuby doesn't support 2.1 (at least they don't advertise it on jruby.org), so I'd still remove it.

> Given d9321ba, I might not be so adverse to specifying 2.1.1 in the Gemfile.

How is this related? We still support 2.1.0, the problem with Travis was that their RVM dropped support for 2.1.0. Also, I think we'll support 2.1.2 once it's released.

@ulferts thinks we should add a check for the range of supported Ruby versions at some time, but doesn't think it's necessary to merge this PR. I also think this would be a good idea.

**Comment by linki** [comment]
@ulferts @myabc @meeee what are we doing with this? personally i like the cleaner Gemfile.

**Comment by mfrister** [comment]
Rebased this onto dev. Unless we support the platforms, I still like seeing the Gems removed.

**Comment by mfrister** [comment]
Anyone interested? Otherwise, I'll close this in a few days.

**Pull request closed without merging**
