### PR TITLE
[26006][25518] Replace details icon with context menu, open on first click

### PR DESCRIPTION
**Pull request by oliverguenther**
[26006] Replace details icon with context menu 
 [25518] Open details view on click in table 

https://community.openproject.com/wp/26006
https://community.openproject.com/wp/25518

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @wielinde , could you take a look at these changes?

**Comment by wielinde** [comment]
@oliverguenther Very nice! To me it feels so much more natural. I love it. 

Observations:
- I cannot close the menu with a click on exactly the same spot. I have to click elsewhere (and that might lead to some unwanted "action" such as opening another WP in split view.
- On mobile the context menu is working but you do not see the icon (you tap into a white area and a menu opens unexpectedly). I believe that on mobile the icon should simply be always visible.
- The triangle icon, especially at the beginning of a line, communicates to me a collapsing/opening of some area and not a menu. I bet that three dots might be less confusing. Probably the horizontal ones in order to not confuse them with drag'n drop handles (when vertical). I
- (Nice to have) The next natural thing for me would be to move the list up and down with the cursor keys and the right side of the split screen updating each time (as I am used to do it with my desktop mail app). Interestingly the cursor arrows sometimes move the selection in the list (at least those below the one I clicked with the mouse). However that does not update the right side of the split view yet.

I did not look into the code yet.

**Comment by oliverguenther** [comment]
> I cannot close the menu with a click on exactly the same spot. I have to click elsewhere (and that might lead to some unwanted "action" such as opening another WP in split view.

That's the same behavior across all dropdown/context menus. If we want to re-introduce subsequent clicks to close, we should do so for all elements.

> On mobile the context menu is working but you do not see the icon (you tap into a white area and a menu opens unexpectedly). I believe that on mobile the icon should simply be always visible.

I don't think that this looks good. Maybe we should use something like tap&hold on mobile instead? Still, I think we should make a separate ticket for mobile issues on the context

> The triangle icon, especially at the beginning of a line, communicates to me a collapsing/opening of some area and not a menu. I bet that three dots might be less confusing. Probably the horizontal ones in order to not confuse them with drag'n drop handles (when vertical).

That's the way Niels specified it. Not going to discuss this in the PR.

> (Nice to have) The next natural thing for me would be to move the list up and down with the cursor keys and the right side of the split screen updating each time (as I am used to do it with my desktop mail app). Interestingly the cursor arrows sometimes move the selection in the list (at least those below the one I clicked with the mouse). However that does not update the right side of the split view yet.

I agree. Currently, you can use j / k vim-style navigation to focus on the IDs, but it does nothing with the split view.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/854bb9153b2700c22a20b74f646638009acfccb0) (deployed commit: 2b8a8a0fa17f18f43843634bd368d644097be540).

**Comment by oliverguenther** [comment]
@wielinde On mobile, icons are now always shown. I believe we should discuss the rest separately from this feature.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4689e241d4ec89461dbf03f64f26838b7489119c) (deployed commit: 1e092b1fcead5f4ed3a8032a5b4799a8c2e23efb).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b446834d53d1cb9a09f307b8291eb906b01194f3) (deployed commit: 3e9cd60a6465494c3aa577419c56eeb854a26293).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/524abcb77f5f236f5e6a5248e5d964dcebc732ed) (deployed commit: 1d03dab4fc9ff227de9ceb59261932e729808f14).

**Pull request merged**
