### PR TITLE
add MySQL 5.6 environments to travis

### PR DESCRIPTION
**Pull request by marutosi**
OpenProject requires MySQL **5.6.13**.
https://www.openproject.org/systemrequirements/

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-0-mysql-travis.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-0-mysql-travis.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by marutosi** [comment]
http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/#Downgrading-MySQL-to-5.5.41

**Comment by floriank** [comment]
This should be rebased on `release/4.0`

**Comment by myabc** [comment]
Marking as invalid for same reason as here: https://github.com/opf/openproject/pull/2875#issuecomment-94399840. I don't think we can afford the extra load on Travis at this point in time.

**Pull request closed without merging**
