### PR TITLE
prepend relative url root to all v3 paths

### PR DESCRIPTION
**Pull request by ulferts**
Take heed of the relative url root in all api v3 paths we construct in the front end's path helper.

Fixes: https://community.openproject.org/work_packages/21824

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-fix-relative-url-root-in-api-v3-routes.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ulferts-fix-relative-url-root-in-api-v3-routes.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
https://community.openproject.org/work_packages/21824

**Comment by oliverguenther** [comment]
@ulferts This looks good to me and the linked WP bug seems fixed on a quick local test with a relative root. Do we wait for travis given the near demo?

**Comment by ulferts** [comment]
@oliverguenther nope, we don't. I ran the karam and protractor tests locally. That has to suffice. Thanks for the quick review.

**Comment by ulferts** [comment]
Self merging.

**Pull request merged**
