### PR TITLE
Publish guide on configuring OpenProject for scaled agile (SAFe)

### PR DESCRIPTION
**Pull request by psatyal**
First commit. Still making a few changes. Not ready for review yet.

### CODE REVIEW

**Comment by psatyal** [comment]
https://community.openproject.org/work_packages/51759/activity

**Comment by psatyal** [comment]
Hi @lindenthal. Here's the the current draft of the article on SAFe. 

Your review would of a lot of help. But perhaps wait until Monday for a review; my work setting up the demo environment might lead me to understand certain concepts better and make the text under the "In OpenProject" section of each point even more relevant. I'll tag you as a reviewer then.

**Comment by psatyal** [comment]
Hi @lindenthal,

Based on our discussion, I've replaced the previous article (still available as a separate archive.md file) with a new one that is a lot more straightforward, practical and actionable. 

I've added links to the demo environment and our documentation. 

Let's refine and finalise this tomorrow.

Cheers
Parimal

**Comment by as-op** [comment]
Closed in favor of PR https://github.com/opf/openproject/pull/14526

**Pull request closed without merging**
