### PR TITLE
introduce keyboard shortcuts

### PR DESCRIPTION
**Pull request by tessi**
Introduce keyboard shortcuts like <kbd>s</kbd> <kbd>p</kbd> for "search project".

Press <kbd>?</kbd> in a OpenProject page for a list of available shortcuts.

see: https://www.openproject.org/issues/2304

### CODE REVIEW

**Comment by apfelfabrik** [comment]
This should not be one PR.

**Comment by tessi** [comment]
@apfelfabrik remove the copyright stuff which is not related to keyboard shortcuts

**Comment by apfelfabrik** [comment]
Are you sure this is consistent w/ our accessibility requirements?

**Comment by tessi** [comment]
What exactly are your concerns here?

As far as I can see, it doesn't make things worse for screen readers. On the other hand it helps keyboard users.
The introduced shortcuts do not conflict with any browser shortcuts I know.

Github uses the same approach (press <kbd>?</kbd> to give it a try), if that helps :) (they have a way cooler help modal, though)

**Comment by tessi** [comment]
One could discuss if the "documentation" is enough (with documentation being a press on the <kbd>?</kbd>-key).

Plus, sometimes we use the `accesskeys` attribute ([which is inconsistently implemented, hard to remember, and not very flexible](http://webaim.org/techniques/keyboard/accesskey)). You can find "access key enabled" elements when executing the following in your javascript console on any page:

```
jQuery('[accesskey]')
```

**Comment by tessi** [comment]
(rebased on a current feature/rails3)

**Pull request merged**
