### PR TITLE
Fix alignment of datepicker in inplace editor.

### PR DESCRIPTION
**Pull request by knight-bubble**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hirtie-maxim-fix-datepicker-alignment-inplace-editor.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hirtie-maxim-fix-datepicker-alignment-inplace-editor.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
@hirtie-maxim Did you try it out yourself?

I don't see **any** date picker.

no-picker

**Comment by knight-bubble** [comment]
@NobodysNightmare, Did you try to rerun webpack? Or F5?

**Comment by NobodysNightmare** [comment]
I already did it twice to be sure... let me check again and write down what I do, tell me if something is wrong:

```
user@dev-vm $ npm i
bla bla bla

user@dev-vm $ RAILS_ENV=production bundle exec rake assets:precompile
bla bla bla
$(npm bin)/webpack --config webpack.config.js
bla bla bla
```

After that I start my rails server in the production enviroment, hit `F5` and `Ctrl+F5` several times in my browser. Now let me check...
I could verify the problem in three browsers on two OSes:
- chrome on windows
- firefox on windows
- firefox in my ubuntu VM

**Comment by NobodysNightmare** [comment]
It works on Teatro... Sorry @hirtie-maxim, I will have to burn my VM or something...

**Comment by NobodysNightmare** [comment]
What the....

On my local installation it works too, for WPs without a date and for WPs with a date... _except_ that one WP where it doesn't work...

**_investigating...**_

**Comment by NobodysNightmare** [comment]
Aha! It has to be a Milestone without a date: http://hirtie-maxim-fix-datepicker-alignment-inplace-editor.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/projects/seeded_project/work_packages/45/overview

**Comment by knight-bubble** [comment]
This issue isn't caused by styles, so I will create another PR to fix that.

**Pull request merged**
