### PR TITLE
[#58460] Rename Display comments preferences to "Newest on top" & "Newest at the bottom"

### PR DESCRIPTION
**Pull request by akabiru**
https://community.openproject.org/work_packages/58460

# What are you trying to accomplish?

In Account settings → Settings, rename the two options under Display comments to:
* Newest first = "Newest on top"
* Oldest first = "Newest at the bottom"

## Screenshots

Screenshot 2024-10-17 at 5 52 53 PM

Screenshot 2024-10-17 at 6 01 03 PM

# What approach did you choose and why?

Reused translations from activity tab as the two are linked

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

### CODE REVIEW

**Comment by akabiru** [comment]
Hi @MayaBerd , just a heads up that part of the translation is changing on user preferences 📖

**Review by Kharonus — APPROVED** [review]
LGTM.

Only one comment: I noticed in the docs the labels are written with a small first letter. while every real label out there in the app starts with a capital letter. Worth mentioning to Maya?

**Comment by akabiru** [comment]
> nly one comment: I noticed in the docs the labels are written with a small first letter. while every real label out there in the app starts with a capital letter. Worth mentioning to Maya?

Cheers, noticed the same- I presumed the reason was to maintain sentence case? I've tagged @MayaBerd just in case she has further thoughts 👍🏾

**Comment by MayaBerd** [comment]
@akabiru @Kharonus thanks for the heads up!

**Pull request merged**
