### PR TITLE
Issue and code review

### PR DESCRIPTION
**Pull request by nickmessing**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nickmessing-dev.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nickmessing-dev.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@nickmessing since this is two separate topics, can you split this into two PRs?

**Comment by nickmessing** [comment]
@myabc, 
https://github.com/opf/openproject/pull/2560
https://github.com/opf/openproject/pull/2561

**Comment by myabc** [comment]
Closing in favour of #2560, #2561

**Pull request closed without merging**
