### PR TITLE
allow to configure airbrake or errbit

### PR DESCRIPTION
**Pull request by linki**
helps us finding and fixing errors on running openproject instances as soon as they're happening.
- integration with kato, ios app, errbit as alternative oss backend, ...

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://linki-feature-airbrake.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://linki-feature-airbrake.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by kgalli** [comment]
@linki :+1:  Nice! Can you please add some documentation under `doc`. So we all know what it is good for and how the community can use it (documentation of the initialiser config part).

**Comment by linki** [comment]
It's Happening

**Comment by floriank** [comment]
I actually talked to some of the Airbrake guys at the WebSummit in Ireland. Pretty nice :)

:+1: for the change, although I concurr with @kgalli - please add some documentation.

**Comment by linki** [comment]
@kgalli @floriank
- configuration now possible via `configuration.yml` as well as corresponding `env` vars
- docs for `configuration.yml`

**Comment by floriank** [comment]
please the @houndci and I''l merge this :laughing:

**Comment by linki** [comment]
ideally, i would like to have this in an openproject plugin (that simply brings airbrake with it and extends the configuration options). this way we avoid cluttering the core code with stuff that people might not use (newrelic, google analystics, ...). what do you think?

**Comment by floriank** [comment]
Good Idea.

Would this be an option for all the _extra_ optional stuff which could be extracted over time?

Edit: sorry for closing - i am twitchy today :)

**Comment by kgalli** [comment]
:+1:

**Comment by linki** [comment]
@floriank yes, i think so

**Comment by linki** [comment]
@kgalli any chance to set this up for https://community.openproject.org/?

**Pull request merged**
