### PR TITLE
sqlite3: fix  db/migrate/migration_utils/customizable_utils.rb

### PR DESCRIPTION
**Pull request by marutosi**
This is a part of #3040.
This certificates no breaking MySQL and PostgreSQL.

https://mercurial.selenic.com/wiki/ContributingChanges#Organizing_patches

> - implement one clear step in your process
> - be sent as a separate email

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-sqlite3-customizable-utils.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-sqlite3-customizable-utils.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
We're doing gi, not mercurial.

We're having contribution guidelines.

We asked you multiple times to group the individual pieces of your change into a PR.

Stop reopening the partial PRs

**Comment by marutosi** [comment]
> We're having contribution guidelines.

Where?

**Comment by floriank** [comment]
Are you kidding?

Any time you create a PR there is an explicit warning on the top of the page with a link to them.

https://github.com/opf/openproject/blob/dev/CONTRIBUTING.md for the extremely unobservant.

**Pull request closed without merging**
