### PR TITLE
Feature/expand filters field set

### PR DESCRIPTION
**Pull request by tilt**
[`* `#8224` Filter menu displays "Options" area and (then) unnecessary expansion container for filters`](https://www.openproject.org/work_packages/8224)

### CODE REVIEW

**Comment by myabc** [comment]
@tilt I'll adjust styling slightly.

**Comment by tilt** [comment]
thanks a lot!

**Comment by myabc** [comment]
@tilt related: default behaviour should be that the filters are visible.

**Comment by myabc** [comment]
:+1:

**Comment by tilt** [comment]
tests will probably fail

**Comment by myabc** [comment]
@tilt Cukes will still fail: if you could take a look, that would be great.

**Comment by tilt** [comment]
I am but it's a lot of them

**Comment by tilt** [comment]
Damn the autocorrection, wip turns to sip and at least I could prevent it turning cukes to dukes

**Comment by myabc** [comment]
sip = shit in …?

**Comment by tilt** [comment]
what is ... unless it's what is standing for the letter p?

**Pull request merged**
