### PR TITLE
WIP Use active_record_store for sessions

### PR DESCRIPTION
**Pull request by mfrister**
https://www.openproject.org/issues/1718

Before merging this, we need to find a way to automatically clean the sessions table, otherwise it only grows.

### CODE REVIEW

**Comment by tessi** [comment]
(rebased @meeee s commit to be mergable again)

**Comment by tessi** [comment]
this is not of interest anymore, isn't it? We have memcached sessions now.

**Comment by mfrister** [comment]
Yep.

**Comment by mfrister** [comment]
Deleted the branch, please restore if you still need it.

**Pull request closed without merging**
