### PR TITLE
Get APIv3 Specification up-to-date with its implementation

### PR DESCRIPTION
**Pull request by NobodysNightmare**
This PR brings specification and actual implementation closer together.
The specification still goes further than the implementation in some places, but it should be quite managable and understandable now. (If I did not miss anything)

This PR also temporarily disables the PATCH-Endpoint for Work Packages, as it poses a security risk in its current implementation. This should make us safe for Release 4.0 and can be fixed in a later release.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-get-apiv3-spec-uptodate.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by NobodysNightmare** [comment]
If Travis agrees I'd consider this ready to merge...

Don't know about ruby-guidelines here, but I'd ignore the "missing space after #" comments of @houndci because they affect out-commented code and not "real" comments.

**Comment by ulferts** [comment]
:+1: for the tab replacement

**Comment by NobodysNightmare** [comment]
But :-1: for travis saying I killed the tests...

Probably the tests **did** cover this evil PATCH endpoint ^^

**Pull request merged**
