### PR TITLE
first comments on implications

### PR DESCRIPTION
**Pull request by henkela**
Feature to allow changing mail-templates (notifications) in the admin settings panel 
What would be further implications besides in app/mailers/? 

https://community.openproject.com/projects/openproject/work_packages/29570/activity

### CODE REVIEW

**Comment by lindenthal** [comment]
Hi @henkela,
Thanks for your PR. Actually I didn't really understand your goal. What exactly do you want to achieve? What is the problem you want to solve with this feature?
Best 
Niels

**Comment by henkela** [comment]
Hi Niels,
I just had a request the other day of somebody who was confused by the mail content triggered by a comment in a task. The mail’s content is @news and @comment. The news block confused my coworker so I was looking for how to change it and ended up finding that I would have to change the views, which would be overwritten with every update.

To put it brief: The question is how to customize the mail templates persistently still being able to use update by the package manager of the os?

Best,

Andreas

**Comment by oliverguenther** [comment]
Hi @henkela , I'm doubtful we're going to make mail templates configurable any time soon since it's quite a specific feature. I would suggest you:

1. keep your custom mail templates as patches and apply them after each update. It requires manual effort during updates but that could be automated (and the patch would auto-detect incompatibilities)
2. Keep your custom mail templates in an OpenProject plugin that overrides core views with the `CUSTOM_GEMFILE` environment set (cf., [this guide](https://www.openproject.org/plugins/install-plugins-packaged/)). This will survive updates but requires some development effort.

**Comment by oliverguenther** [comment]
I'm suggesting to close this PR in favor of discussion in https://community.openproject.com/wp/29570

**Pull request closed without merging**
