### PR TITLE
[APIv3] Improve performance for WP collections

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work packages

This first became a problem with https://community.openproject.org/work_packages/18491 and was discovered during the review of one of its PRs.
## Description

This PR improves the performance of WP collection responses by not embedding linked properties in work packages that are part of a collection.

This reduces:
- the amount of transfered JSON data
- the database load when querying the work packages
## TODO
- [x] include links for omited resources (they _should_ already exist anyway)
- [x] probably add corresponding endpoints for those links

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-fewer-embedding.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-fewer-embedding.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Let me know when this is ready for a preliminary review :+1:

**Comment by NobodysNightmare** [comment]
@oliverguenther I think this is good from my side.

Some day I want to have another look at the SQL output for a WP collection request via APIv3, but at least the massive activity requests are alread gone.

edit: I left out correct endpoints and links for `relations` since they do not play by the API rules in any way... so I keep ignoring them until some day they will really play by the rules...

**Comment by oliverguenther** [comment]
I've just tested the PR with all requests from the history I remembered to be somewhat slow, and both performance and query log are drastically improved.

**Comment by oliverguenther** [comment]
Code-wise, this is fortunately a rather small change. I don't particular like the `&& embed_links` copypasta, but you have a better judgement on whether that is the best way to switch all embedded links.

The rest LGTM :+1: , will merge after travis

**Comment by NobodysNightmare** [comment]
I don't like it either. Fortunately this is not needed for _all_ embedded resources, but only for those that are not embedded using the `linked_property` helper.

I hope in the future we will find a nice helper that fits for the other embedding purposes (i.e. embeding a collection, rather than a single property, this is the eky difference)

**Comment by oliverguenther** [comment]
There are some legitimate errors on travis, you probably forgot somewhere to include the embedded properties somewhere.

**Comment by NobodysNightmare** [comment]
@oliverguenther Looks like I forgot to update the mocks for the frontend tests...

Don't panic, it is only **_twelve thousand lines**_ of mocked JSON, I don't see how I could have messed up fixing those...

OMG.... I bet nobody even cares for those lines... let me see if the tests pass when I cut them down...

**Comment by NobodysNightmare** [comment]
Pushed the trimmed mocks...

Please (if possible) let both test runs complete. I am pretty sure that the second one will fail (at least I hope something will fail after deleting so many lines...)

**Comment by basiszwo** [comment]
@NobodysNightmare told me that this will break the current Angular UI. If this applies we cannot merge. Let's keep this open until #3366 is merged to dev.

**Comment by NobodysNightmare** [comment]
@oliverguenther I am totally lost on those protractor failures.

My one-line change in the code (not the test-related changes) seems to break in protractor while it is working fine on my dev server. (e.g. [this test case of yours](https://github.com/opf/openproject/blob/dev/frontend/tests/integration/specs/work-packages/details-pane/activity-with-revisions-spec.js))

I am talking about this line:

``` JS
var activities = workPackage.embedded.activities.embedded.elements;
```

Browser console shows fancy error message which I can't make any use of:

```
Error: Expected absolute or relative URL, but got: undefined
```

**Is there any chance you have an idea whats going wrong here?**

**Comment by oliverguenther** [comment]
Before your change, the mocked JSON would return an immediate array for the embedded property `workPackage.embedded.activites`. For example, activities:

``` JSON
"activities": [
   {
     "_type": "Activity",
     "_links": {
       "self": {
         "href": "/api/v3/activities/315",
         "title": "315"
       },
      (...)
    },
    {
        (Next activity ..)
    },
]
```

But now, you've effectively embedded a loaded collection in the test. That is what angular usually does when it initially loads a linked property. I guess it looks for the appropriate link, but doesn't find it to build / load the `LazyResource`

``` JSON
"activities": {
    "_type": "Collection",
    "_links": {
      "self": "/api/v3/work_packages/820/activities"
    },
    "total": 4,
    "count": 4,
    "_embedded": {
      "elements": [
      ... activities here ..
      ]
    }
}
```

I'm not sure how to resolve that with the mocks only.

**Comment by NobodysNightmare** [comment]
I am glad you did not see the problem either. I just found the source of my error:

``` JSON
"_links": {
  "self": "/api/v3/work_packages/820/activities"
}
```

Look hard... do you see it? It needs to read:

``` JSON
"_links": {
  "self": { "href": "/api/v3/work_packages/820/activities" }
}
```

I won't tell anyone how much time that cost me... just never forget to put the `href` hash around your links ^^

**Comment by oliverguenther** [comment]
We should get rid of these mocks ASAP. I'll write a helper to generate these from real requests.

**Comment by NobodysNightmare** [comment]
:+1:

**Comment by NobodysNightmare** [comment]
Rebased and pushed my changes. I hope travis agrees this time around.

@basiszwo I already adapted the frontend to obey the backend changes. Did you put this on hold to avoid merge conflicts or did you understand that I have not adapted the frontend accordingly?

The change in the actual code is a one-liner. However, I deleted around 12k lines from test-mocks to ease their maintenance (still @oliverguenther is right, they should be generated automatically).

**Comment by basiszwo** [comment]
I wasn't aware you already did the changes in the frontend and wanted to prevent problems.

If it's mergeable, go ahead :+1:

**Pull request merged**
