### PR TITLE
Refactor Bulk and Move controllers

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work packages
- Refactoring: https://community.openproject.org/work_packages/16342
- Also fixed a bug:
  - https://community.openproject.org/work_packages/5798 (public)
  - https://community.openproject.org/work_packages/20101 (private)
## Description

This PR rebases the work of https://github.com/opf/openproject/pull/1974 onto the current dev and applies further refactorings and fixes.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-refactor-bulk-move-controller.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-refactor-bulk-move-controller.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by Azure7111** [comment]
Is the target branch still appropiate? Because this PR contains a fix for a ticket which is scheduled for 4.3.

**Comment by floriank** [comment]
Probably not. At the moment,, the new `release/4.3` would be more appropriate. Although i am not sure if this fix is usable, as @NobodysNightmare played a "Dark Revival" card in response to the original "Curse of the Shinigami" to bring an older PR back from the Dead.

No where is my "Sky Burial" Trap card?

For non-nerds: We should probably talk about this solution.

**Comment by NobodysNightmare** [comment]
Decided with @ulferts to throw this away...

**Pull request closed without merging**
