### PR TITLE
allow planning elements without dates.

### PR DESCRIPTION
**Pull request by nkenneweg**

### CODE REVIEW

**Comment by mfrister** [comment]
What's pes?

**Comment by nkenneweg** [comment]
Changed it to planning elements.

**Comment by ulferts** [comment]
looks good to me, will wait for travis.

**Comment by ulferts** [comment]
OP issue: https://www.openproject.org/issues/1414

**Comment by mfrister** [comment]
@ulferts Any reason you didn't delete the branch?

**Pull request merged**
