### PR TITLE
Fix wrong redirect after forced pass change

### PR DESCRIPTION
**Pull request by tessi**
A new user (`first_login: true`) who is forced to change his password
(`forced_password_change: true`) was redirected to the change_password
page (instead of my_page) when he didn't get the login credentials right
on the first attempt.

The `back_url_hidden_field_tag` was added to the password form to
persist the original referer (in the case that the first password change
attempt does not succeed).
This makes the redirect work exactly as if the password change succeeded
on the first try.

https://www.openproject.org/work_packages/16674

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-16674-wrong-redirect-to-password-change-form.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by mfrister** [comment]
:+1:

Will merge once Travis says ok.

**Comment by tessi** [comment]
omniauth tests break - we will investigate!

**Comment by mfrister** [comment]
:+1:

**Pull request merged**
