### PR TITLE
[50489] Page cannot be scrolled after Meeting details are edited

### PR DESCRIPTION
**Pull request by HDinger**
When a Primer dialog is opened, it sets `overflow: hidden` on the body to avoid scrolling behind the dialog. When the modal is closed this should be reset. Therefore, all buttons that close the modal, need to have a certain `data` attribute.

https://community.openproject.org/projects/14/work_packages/50489/activity

### CODE REVIEW

**Review by dombesz — APPROVED** [review]
LGTM, thanks Henriette!👍
Edit: Looking into the failing specs.

**Review by dombesz — CHANGES_REQUESTED** [review]
Unfortunately the solution is not sufficient, as the form is being dismissed even when the submission failed with a validation. Hence the test failings.

**Comment by dombesz** [comment]
@HDinger I have addressed the issue, I came up with two approaches, please take a look:

1. [The first](https://github.com/opf/openproject/pull/14196/commits/a0d4d2a52c56a9b8930c333ed20d5f03ac971100) is a localised approach, each form needs to have the stimulus controller binding to close the parent dialog.
2. The second approach is the final version, it uses a global listener on successful form submissions to close the parent dialog.

IMO the second approach is comprehensive and it also solves the bug for any future form dialogs. The only case when it wouldn't work, is when we don't want to close the dialog upon a successful form submission. If that ever happens, we can introduce a data attribute on the form to prevent closing the dialog.

Both solutions require the use of appropriate http status codes for rendering form errors via turbo stream responses.

**Review by HDinger — COMMENTED** [review]
Thanks a lot for picking this up, @dombesz ! 🤗

**Pull request merged**
