### PR TITLE
[4164] Long wiki names are not abbreviated in side menu

### PR DESCRIPTION
**Pull request by HDinger**
used flexboxes to correctly size the menu items

https://community.openproject.org/work_packages/4164

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-4164-long-wiki-names.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-4164-long-wiki-names.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Is it still possible to pin wiki pages onto the menu? I can't seem to find where I can do that.

**Comment by HDinger** [comment]
Yes, it is. Go to the page you want to pin, choose 'more functions' and 'Configure menu item'. There you can pin the page onto the menu.

**Comment by oliverguenther** [comment]
Ah... The setting item isn't properly showing in my case. Removing `overflow:hidden` from `#content` lets it re-appear.

bildschirmfoto 2015-08-21 um 12 54 45

But that also happens on dev. I'll file a bug report.

**Comment by oliverguenther** [comment]
LGTM :+1:

**Pull request merged**
