### PR TITLE
update gon version to 4.0.3

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-gon-4-0-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-gon-4-0-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by marutosi** [comment]
What is status?

**Comment by floriank** [comment]
To give you an update: 

We are currently busy with the patch level releases for 4.1.x and the upcoming development for 4.2. I had a quick chat with @ulferts about dependency pinning in the Gemfile. 

Our goal will be to do this **before 4.2**, best case here would be to group the pinned dependencies and merge them before the 4.2 release.

Also please add a description to your PRs (either in the PR or the commit itself if you are worried about Github going down in the future) giving not only hints about what you are doing but also why you are doing it.

Sorry to keep you waiting.

**Comment by marutosi** [comment]
What is status?

**Comment by floriank** [comment]
this PR does more than it says - the fix sprockets commit is in there as well. Is this intended?

**Comment by marutosi** [comment]
> Is this intended?

Yes.

**Comment by marutosi** [comment]
Commit log says.
https://github.com/marutosi/openproject/commit/0cceab329ccf997800da970fc90fc4b0c8a45b7a

**Comment by marutosi** [comment]
What is status?

**Pull request closed without merging**
