### PR TITLE
Sorting dialog validation

### PR DESCRIPTION
**Pull request by myabc**
**Please merge opf/openproject#1445 first**

https://www.openproject.org/work_packages/9902

### CODE REVIEW

**Comment by myabc** [comment]
:warning: @manwithtwowatches ~~Please hold off on merging. While I'm at it, I want to fix the behaviour of the Cancel button (it does not reset the original query name in the selectable title).~~

**Comment by manwithtwowatches** [comment]
@myabc ok. also if you've probably noticed already but if you change the query name in page settings then it stays the same in the selectable title dropdown. didn't think that was in scope of this PR though.

**Comment by myabc** [comment]
@manwithtwowatches No, of course it's not in scope. You're quite right. I confused this PR with #1448.

Please go ahead and review/merge (I'll give Travis a kick).

**Comment by tilt** [comment]
@manwithtwowatches Have you already reviewed this PR?

**Comment by tilt** [comment]
Nice, I like the idea with the button-disableable mix in. The ticket also comprises restricting the sorting options to the selected columns though..

**Comment by myabc** [comment]
@tilt No. There's a separate bug for that: https://www.openproject.org/work_packages/8280

**Comment by tilt** [comment]
For me that looks like a different bug. In wp#9902 it's mentioned that sorting criteria should be selectable iff their columns are selected

**Pull request merged**
