### PR TITLE
Add lodash as a service

### PR DESCRIPTION
**Pull request by furinvader**
Lodash is now available as a service and should be used as such when needed.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://furinvader-refactoring-common-components.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://furinvader-refactoring-common-components.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
LGTM. Merge when ready.

BTW: Any chance we can make an effort to upgrade lodash? 4.0 just came out and we're still lurking at < 3.0 (possibly with lodash-migrate?)

**Comment by furinvader** [comment]
I have made an attempt to upgrade to 3.x already, but deemed it is unsafe until we're sure that everything is properly tested.
This is also one of the reasons why lodash is a service.

**Comment by furinvader** [comment]
Your suggestion about lodash-migrate might be gold.
I'll take a look ASAP.

**Pull request merged**
