### PR TITLE
Removed useless :lang option

### PR DESCRIPTION
**Pull request by marutosi**
See commit logs.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-tabular-form-builder.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by linki** [comment]
i don't see an explanation in the commit logs.

**Comment by linki** [comment]
@marutosi

**Comment by marutosi** [comment]
What?

**Comment by linki** [comment]
explanation missing

**Comment by marutosi** [comment]
What explanation?

**Comment by linki** [comment]
explanation why `:lang` is removed from `TabularFormBuilder`

**Comment by linki** [comment]
https://github.com/opf/openproject/pull/2108#issuecomment-63612617

**Comment by marutosi** [comment]
explanation why :lang needs in TabularFormBuilder

**Comment by linki** [comment]
explanation why `set_language_if_valid` is removed from `TabularFormBuilder`

**Comment by marutosi** [comment]
explanation why set_language_if_valid needs in TabularFormBuilder

**Comment by linki** [comment]
explanation why `set_language_if_valid` was in `TabularFormBuilder`

**Comment by marutosi** [comment]
explanation why set_language_if_valid needed in TabularFormBuilder

**Comment by ulferts** [comment]
Closing because of missing explanation.

**Comment by marutosi** [comment]
Are you kidding?
https://github.com/opf/openproject/commit/f5bb0067f0340b915dc6e75eabac29a587f26869

**Comment by marutosi** [comment]
#2492

**Pull request closed without merging**
