### PR TITLE
Feature/issue autocomplete

### PR DESCRIPTION
**Pull request by tessi**
Adds autocomplete for textareas - you get a github-like autocomplete for issue numbers, if you start typing "#...".

This works for work package numbers, as well as single words from the work packages subject:

selection_103

selection_104

You can choose autocomplete options with arrow keys and &lt;enter&gt;. If an item is selected, the items work package id is inserted.

### CODE REVIEW

**Comment by ulferts** [comment]
Looks like something I definitely want to have!

To be a brat:
- is is also liked to the other fields a user can insert wp numbers into (related wp, parent wp)?
- would it be possible to reuse select2 for that?

**Comment by tessi** [comment]
(Unfortunately) My approach introduces a new library for auto-completion. This is because select2 and the thing we use for related-wp are specialised to `<input>` fields. However, I want to add auto-completion for `<textarea>`s.

Within a `<textarea>` the positioning of the auto-complete dialog is very hard. Also, not the whole text needs to be completed (as when using `<input>`), but only a specific sub-match of the text (the first word after '#').

Furthermore, when writing in the `<textarea>`, the keyboard focus must remain in that `<textarea>` (and not go into a separate auto-completion dialog). This helps people with screenreaders to orientate and allows to ignore the auto-completion in case you write something it matches, but don't mean what it offers.

Thus, my solution is not linked to the other fields you've mentioned and it is not possible to used select2 for that.

But I can look into making it _look_ more like something we already use, so that the user is not distracted by three visually different auto-completion dialogs.

**Comment by tessi** [comment]
Now the autocompletion looks like this:
selection_110

as a reference, the wp-parent auto-completion looks like this:
selection_105

**Comment by hschink** [comment]
Hi @tessi,

this is a really cool feature! :+1: And trust me, I tried it at every spot you added it :coffee:. So, as you can imagine, I found some spots that don't work. Here is the list:
1. Work Package
2. [x] Edit
3. [x] Notes (also in the edit view)
4. Wiki
5. [x] Edit (solved in another [PR](https://github.com/finnlabs/openproject-video_upload/pull/6))

Finally, @ulferts said that the Ruby library does not exist for Rails 4.0. What do we do if we switch?

I merge your branch as soon as you fixed :wrench: those issues and answered the question. :smile: Just trigger me.

**Comment by tessi** [comment]
The gem is just a very tiny wrapper to serve [`at.js`](https://github.com/ichord/At.js) (and it's css and it's dependency [`caret.js`](https://github.com/ichord/Caret.js)). If the gem does not work for rails4 for whatever reasons, we can easily serve those files ourselves (or maintain our own gem that serves those files).

The places you mentioned do not work, because the `<textarea>` is dynamically added to the DOM. I just haven't thought of that. I'll look into this.

**Comment by tessi** [comment]
The Wiki#edit view does not work, because the openproject-video_upload plugin overwrites the Wiki#edit view (and it does not care about auto-completion). Using a plain (= no plugins) openproject works.

**Pull request merged**
