### PR TITLE
fix wp copy due to validations using dirty attrs

### PR DESCRIPTION
**Pull request by linki**
part of https://community.openproject.org/work_packages/19541

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://linki-fix-copy-project.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://linki-fix-copy-project.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
oh my

**Comment by myabc** [comment]
@linki could you check this is not the same issue that abf4a011f0e70f228869f4741feee9c3a3775196 deals with (Rails 4 branch)?

**Comment by linki** [comment]
@myabc looks like it's solving the same issue.

**Comment by NobodysNightmare** [comment]
@linki When the commit of @myabc is solving the same issue, can this PR be closed?

**Comment by basiszwo** [comment]
Closing this as it obviously wasn't important enough to be finished.

**Pull request closed without merging**
