### PR TITLE
Fix broken specs for CF controller

### PR DESCRIPTION
**Pull request by NobodysNightmare**
https://community.openproject.org/work_packages/18899

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://fix-broken-controller-specs.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://fix-broken-controller-specs.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
Ignoring @houndci for today, because I just want to fix the specs, not the style...

**Comment by NobodysNightmare** [comment]
Specs look not so broken to me.

**Comment by myabc** [comment]
:+1: @NobodysNightmare thanks for the useful explanation!

**Pull request merged**
