### PR TITLE
Feature/29218/search autocompleter

### PR DESCRIPTION
**Pull request by wielinde**
Autocompleter for global search field in top menu.

Finds work packages while you tip. Selecting a suggestion redirects the page to the selected work package.

Todo:
- [x] Completion on WP IDs
- [x] Width of results should not changes depending on search results

\
Out of scope:
- Autocompleting other entities such as Wiki pages
- Separate API endpoint for search

https://community.openproject.com/wp/29218

### CODE REVIEW

**Comment by oliverguenther** [comment]
Code-wise, LGTM :+1: I have a few remarks, but feel free to move them out of the PR if you note them somewhere as a ticket for 8.3.

- The autocomplete loading indicator is not wide enough to render properly (Fine for me to ignore for now)
- The autocomplete results look off since the toolbar sits between search and results. (Fine for me to ignore for now)
- The status colors are not loaded on pages other than work packages. 

screenshot from 2019-01-07 08-31-48

screenshot from 2019-01-07 08-31-57

You can fix this by calling `dynamicCssService.requireHighlighting();` anywhere when you render work packages. It will ensure it gets loaded once and only once.

**Review by oliverguenther — COMMENTED** [review]
Code-wise, LGTM :+1: I have a few remarks, but feel free to move them out of the PR if you note them somewhere as a ticket for 8.3.

- The autocomplete loading indicator is not wide enough to render properly (Fine for me to ignore for now)
- The autocomplete results look off since the toolbar sits between search and results. (Fine for me to ignore for now)
- The status colors are not loaded on pages other than work packages. 

screenshot from 2019-01-07 08-31-48

screenshot from 2019-01-07 08-31-57

You can fix this by calling `dynamicCssService.requireHighlighting();` anywhere when you render work packages. It will ensure it gets loaded once and only once.

**Comment by wielinde** [comment]
@oliverguenther I fixed point 1 and 3 and left point 2 (as discussed) as it is.

The loading indicator was always squashed unless used with modifier `-compact`, i.e. within the autocompleter for adding relations.

**Comment by oliverguenther** [comment]
:+1:

**Pull request merged**
