### PR TITLE
Fix timeline grouping labels (#2146)

### PR DESCRIPTION
**Pull request by tilt**
https://www.openproject.org/work_packages/2146

### CODE REVIEW

**Comment by ulferts** [comment]
Changelog, sorry.

**Comment by tilt** [comment]
@ulferts Ok

**Comment by hschink** [comment]
@tilt you fixed the labels **Erstes Gruppierungskriterium** and **Zweites Gruppierungskriterium**: I wonder whether **Ist ein Unterproject von** and **Hat eine Abhängigkeit zu Projekttyp** should be linked as well (see image)? 

Link checkbox to its label screenshot

If you vote for not fixing, then you just need to fix the tests.

**Comment by tilt** [comment]
@hschink If we add labels here I don't see a clever way to not break the entire style other than to modify our label css rule with a `:not(.leave-me-unstyled)` or to revert all label styles for these labels. I don't like either option but maybe there is some nicer css trick?

**Pull request merged**
