### PR TITLE
[19297] Revision view cleanup

### PR DESCRIPTION
**Pull request by floriank**
Reissued for release against 4.1. See #2771 for description. 

Meets the requirements of https://community.openproject.org/work_packages/19297.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-fix-19297-revision-view-cleanup.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-fix-19297-revision-view-cleanup.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
Just repeating things that were said in the original branch (and still seem to be open):

## @Azure7111

image

The Statistics button looks fine now, however please note the following points:
- The word "Revision" is now written in a very dark color and not in the same pale/gray as before
- The branch combobox is missing the dropdown arrow
- The branch in the branch combobox is offset (its a little above the baseline of Statistics and Revision)

Also, one more thing: Selecting the any branch other than the previously selected one makes it impossible to reopen the combobox. I could observe this behaviour in Chrome as well.

## @vcostin

screenshot from 2015-04-10 18 41 49
IE11 virtual box Win 8.1

## @vcostin

@Azure7111 this can be ctrl+F5 case, at least for the button

**Comment by NobodysNightmare** [comment]
If I see this correctly there is stuff left to be done by @vcostin (or @floriank but he already gave that PR to vadim...)

**Comment by floriank** [comment]
rebased against `release/4.1`

**Comment by floriank** [comment]
@vadim I rebased and fixed the tests - you should be able to have a look at the comments by @Azure7111 and @NobodysNightmare

**Comment by floriank** [comment]
This is in principal good to merge

**Comment by myabc** [comment]
@floriank @vcostin we can do a follow-up PR for the refinements.

**Pull request merged**
