### PR TITLE
Move Protractor tests under frontend/tests

### PR DESCRIPTION
**Pull request by myabc**
See 6ec5ca58, #2261.

Continuation of code reorganisation started in #2193.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-frontend-reorganisation-protractor.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
FYI @hschink @0xF013 @ulferts

**Comment by ulferts** [comment]
I like that it is moved. However I think we could use the chance to rename the folder to something that reveals the purpose of those tests, e.g. integration. Opinions?

**Comment by myabc** [comment]
@ulferts I'd be ok with that.

How about Karma tests? Should we move them under `tests/units`?

@0xF013 @hschink do you have  a preference?

**Comment by ulferts** [comment]
@myabc sounds reasonable to me.

**Comment by 0xF013** [comment]
@myabc @hschink I don't have any preferences

**Comment by hschink** [comment]
Me neither...

**Comment by myabc** [comment]
@ulferts PR is amended.

**Comment by ulferts** [comment]
@myabc looks good. Are you still working on this as the label suggests or is this free to merge?

**Comment by myabc** [comment]
@ulferts done now.

**Pull request merged**
