### PR TITLE
18530 Add, configure autoprefixer-rails

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/18530

:warning: **Before reviewing, clear your cache**, i.e.

```
    rake tmp:clear
```

Should also resolve issue:
- https://community.openproject.org/work_packages/18392

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://feature-18530-autoprefixer-rails.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://feature-18530-autoprefixer-rails.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@myabc for the mobile browsers, will we loose even more support for them by merging the branch or will we keep the status quo there?

**Comment by ulferts** [comment]
@myabc when testing, I see no regressions. I am not sure how to test this any further. Do you have a hint?

**Comment by myabc** [comment]
@ulferts if you don't mind booting up your VM, the best way to test this PR is to check and see if [18392](https://community.openproject.org/work_packages/18392) is still an issue.

**Comment by ulferts** [comment]
@myabc there seems to be problems with the `vertical` class in various places:

image

The rest of the flex related problems seem to be fixed.

**Comment by myabc** [comment]
@ulferts We'll need to finally figure out why IE doesn't deal with `vertical` flexboxes. This will also be an issue for #2492.

**Pull request merged**
