### PR TITLE
[27253] Custom actions: Design buttons in WP full and split view

### PR DESCRIPTION
**Pull request by HDinger**
This deal with Custom Action Buttons in the info row.

The behavior differs (because of the DOM structure) a bit from the one described in the ticket. Now it is a follows:

1. The info row moves at the top. This is based on an approximation. Since most of its content is fixed, I guess it is good enough.
2. The CustomAction buttons vary in their size. There is a maximum and minimum. However the buttons move to a new row before they shrink. I could not find any way around this because of the nested ActionButton structure. 

https://community.openproject.com/projects/openproject/work_packages/27253/activity

### CODE REVIEW

**Comment by HDinger** [comment]
This is how it looks like:

#### Large width
bildschirmfoto 2018-08-03 um 16 59 44

#### Middle 
bildschirmfoto 2018-08-03 um 17 00 00

#### Small 
bildschirmfoto 2018-08-03 um 17 00 14

**Comment by oliverguenther** [comment]
This results in wrapping the custom actions in two rows despite there being enough place (info row is not in `-wrapped` state)
screenshot from 2018-08-07 14-31-06

**Comment by HDinger** [comment]
I fixed the issue

**Comment by oliverguenther** [comment]
screenshot from 2018-08-17 09-55-14

Having multiple long Custom actions results in them being clipped (there are some hidden behind the overflow)

**Comment by HDinger** [comment]
Ok, I've given it another try

**Pull request merged**
