### PR TITLE
Added ngAnnotate

### PR DESCRIPTION
**Pull request by romanroe**
https://community.openproject.org/work_packages/21918/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://romanroe-ngannotate.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://romanroe-ngannotate.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by lindenthal** [comment]
Hi @furinvader 

can you please review @romanroe PR ?

Thanks
Niels

**Comment by furinvader** [comment]
Sure. I'll have a look tomorrow.

**Comment by furinvader** [comment]
Replaced by #3930

**Pull request closed without merging**
