### PR TITLE
Feature/with ng bind once

### PR DESCRIPTION
**Pull request by tilt**

### CODE REVIEW

**Comment by tessi** [comment]
We might not need this anymore. Angular 1.3 ships with bind-once functionality.
@myabc @ulferts @hschink any comments on this?

**Comment by hschink** [comment]
@tessi We may close this PR without deleting it because the places where ngBindOnce was introduced may still be valid for Angular's bind-once. What do you think?

**Comment by tessi** [comment]
I  just attempted to make the pull request queue a little shorter.  If you need this pr as a reminder,  I'm happy to let it stay open (I think it's actually better than having a branch without a pr,  as we tend to forget those branches)

**Comment by NobodysNightmare** [comment]
@myabc @opf/developers Is this a branch we still need?

We use Angular 1.3 and I am not optimistic that anyone will ever care for this branch again.

I would rather close it if nobody is ever going to use it anyway.
I don't even know what it does TBH, I can just imagine two things:
- new code will already use bind once, so this only applies to old code, which will hopefully fade away
- even more code is introduced not using it, making this PR only cover a small part

Either case would be bad for this PR.

I'd say keep it, if we can get a benefit out of it without sinking hours of work. And get that benefit soon. Otherwise the PR will rot and we don't need it...

**Pull request closed without merging**
