### PR TITLE
[chore] remove user no longer has errornous behaviour

### PR DESCRIPTION
**Pull request by Kharonus**
# What are you trying to accomplish?
- removing edge cases from code base

# What approach did you choose and why?
- updating NC 28 to NC 29 allows removal of user from its last group
- removed special handling from tests

### CODE REVIEW

**Review by brunopagno — COMMENTED** [review]
What happens if a customer wants to keep using nextcloud 28? Would they become blocked of upgrading openproject if that's the case?

**Comment by mereghost** [comment]
> What happens if a customer wants to keep using nextcloud 28? Would they become blocked of upgrading openproject if that's the case?

IIRC our integrity checks would report it as "non-compatible".

**Review by brunopagno — APPROVED** [review]

**Comment by Kharonus** [comment]
uhm, maybe we should bump the min NC version then? :D good idea, will ask @dominic-braeunlein 

so, dominic:
- ~shall we bump the supported min NC version to 29.0.9? In 15.1? This was the version I used for testing the group user removal.~
- we only have checks for versions of our integration app and group folder app
  - we could add a check for NC version, too
  - we could add the supported version of NC to our integration app (e.g. version 2.7.2 is supporting only 29 and up)

**Comment by Kharonus** [comment]
All in all, I'd take the version discussion out of this PR, which basically just amends the tests. no prod code changes. WDYT?

**Pull request merged**
