### PR TITLE
Invite User button in dynamic SelectInputComponent

### PR DESCRIPTION
**Pull request by aleixsuau**
https://community.openproject.org/projects/openproject/work_packages/35520

This pull request:

- [x] Adds the InviteUserButtonComponent to the SelectInputComponent when the schema.type === 'User'.
- [x] Refactors the InviteUserButtonComponent to:
> - [x] Allow using the InviteUserButtonComponent inside the Dynamic forms (InviteUserButtonModule to avoid cyclic dependencies).
> - [x] Avoid duplications; now the parent component is in charge to decide if it should place a InviteUserButtonComponent on it. The InviteUserButtonComponent is responsible to show himself if the user has permissions.
> - [x] Avoid useless injections; the InviteUserButtonComponent is only used in the MultiSelectEditFieldComponent, the CreateAutocompleterComponent and the  SelectInputComponent where it is shown or hidden depending on the showAddNewUserButton, because of that the MultiSelectEditFieldComponent and SelectEditFieldComponent seemed useless.

**Notes**
- Should we always add the button to the SelectInputComponent when schema.type === 'User'? Any exception?
- Is there any place where schema.type === 'User' but the MultiSelectEditFieldComponent or the SelectEditFieldComponent place the InviteUserButtonComponent (if the user has permissions)?

### CODE REVIEW

**Review by b12f — COMMENTED** [review]
Can we somehow pass this in as a slot/content projection from a parent? Making dynamic-forms depend on user-invite-modal is a bit weird, imo.

**Comment by aleixsuau** [comment]
Hi @b12f ,

Since the dynamic forms are rendered from a configuration object, I understand that there is no template where to place the content to project in this case. Furthermore, it seems to me that the 'InviteUserButtonComponent' is part of the input type 'User' (it has to be shown in all of them) so in this way, it would make sense that it is part of the dynamic form as all the other input types.

**Review by b12f — APPROVED** [review]

**Comment by oliverguenther** [comment]
@aleixsuau I was about to merge this, but it requires a merge conflict to be resolved after your improvement PR got merged

**Comment by aleixsuau** [comment]
I'm going to fix it 👍

**Pull request merged**
