### PR TITLE
use [:mri, :mingw] for syck

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-3-0-syck.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-3-0-syck.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
I am not sure, what exactly this helps with. @marutosi Any comments on why these changes are necessary?

windows support maybe?

**Comment by marutosi** [comment]
e0298f7196ac2d53e9692cecf5d457c314ec8066

**Comment by myabc** [comment]
Cherry-picked in dev 81aef06f. 3.0 will never support Ruby 2.2.

**Pull request closed without merging**
