### PR TITLE
Do not preserve keyword on search submit

### PR DESCRIPTION
**Pull request by why-el**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://why-el-21764-empty-search-field.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://why-el-21764-empty-search-field.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Again, please provide a description and link to the related work package https://community.openproject.org/work_packages/21764

**Comment by oliverguenther** [comment]
I'm not sure If its okay to remove the search tag in all situations, however I can't think of one where it would be a problem. Merging this now, it's easy to fix should we come up with something I missed.

**Comment by why-el** [comment]
Exactly. ;)

**Pull request merged**
