### PR TITLE
Feature/26625 null aware filters 2

### PR DESCRIPTION
**Pull request by akasparas**
This is pull request for filtering by fields which can have NULL values. First feature was requested in https://community.openproject.com/projects/openproject/work_packages/26625/activity . OpenProject progressed since then and I have no option to alter that text so details will be documented here.

First, added option to filter for null/not null date. There were no option so far: null, "", -1 were not accepted as a valid date for comparison.

Then, for numeric data types, == and != filters are adequate for fields with nulls, but <= and >= are not. So, new operator is introduced.

String "not contains" case was ok, but "contains" IMHO needlessly used COALESCE. Corrected.

Two issues remaining:
- what to do with null aware operators if the field is mandatory? should we hide these operators? what to do if the field was marked as not mandatory, then marked as mandatory and some values were set, and then again reverted to not mandatory?
- I feel that for date[time] fields at least before_or_null and after_or_null still are missing; maybe most of defined operators for date should have null aware version.

For these issues I need your direction how this should be implemented to be acceptable to OpenProject. For the first issue, I'm not good enough in Ruby to decide which class should do checking. For the second -- there are a lot of date comparison operators, if I'll multiply that number by two, users will get lost. So what would be acceptable compromise?

### CODE REVIEW

**Comment by akasparas** [comment]
Travis failures are not related to this pull request. I have no idea how to fix .loading-indicator presence.

**Comment by ulferts** [comment]
Hi @akasparas,

and thanks for the PR.

I have not finished thinking it through yet so the following is not set in stone.

I am not sure whether having the added functionality is worth the increase in complexity the user has to deal with. Maybe @RobinWagner or @lindenthal might want to chime in to shed some light on the requirements aspect of the PR. This will potentially add quite a few operators the user has to sift through.

But the complexity might be reduced by not restricting ourselves to the UI we currently have where one has

Name of the Filter           Operator         Values

To add the "less than"/"greater than" or none functionality we could also change this to be

Name of the Filter           Operator         Values    Checkmark for none value

We would then not need to display the additional operators. I am not sure if having the additional checkbox is better, though.

From a technical perspective the implementation follows along the lines of what we currently have and looks solid. Good work there.

The ideal solution would of course be to remove the inability to have "OR" concatenated filters. So the "I wish"-solution would be to be able to e.g. have one filter specifying the value to be lower than 5 OR the value to be not set. But with the filters being what they are I understand that you took the approach you went with. An alternative approach could be to have a dedicated value e.g. null which might be taken. But this might cause problems in the communication between the front and the backend with regards to the expected arity of the filter values. So having the added operators is probably the best we can do if we decide to go want the functionality.

@RobinWagner, @lindenthal, need your feedback here.

**Comment by akasparas** [comment]
Hi, Coleagues,
I understand that you're very busy with BIM branch of OpenProject at the moment and do not have time for redesign of filters. On the other hand changes that are proposed in current pull request are already useful in current form and are in daily use by my users. So, could you please consider merging this pull request at as is before next public OpenProject release and split redesign till less busy time?

**Comment by lindenthal** [comment]
Hi @akasparas,
Thanks a lot for your PR. We really appreciate that.

Can you please tell me more about the underlying problem you want to solve with this feature? What do you filter with this?

Best
Niels

**Comment by akasparas** [comment]
Hi, @lindenthal ,

Real world situations where we need to filter for null/non-null date:
- we have a custom field in all tasks InvoicedOn; at the start of the month we would like to filter all the tasks that are closed and have this field null and bill customers; when bills are sent we import dates for billed tasks
- when all the requirements from customer are collected and it is clear how to solve his problem, we change status into "Specified"; manager periodically filter all the tasks for this status and null start date to schedule these tasks

For "greater than or null" filter. In situation where is shortage of resources one may want to filter for task with end date later that some date in the future or not set to see what can be moved to the later date.

**Comment by lindenthal** [comment]
Hi @akasparas,

Thanks a lot for your patience. 

I had a look another look at your PR. I decided not to merge it mainly for two reasons:

- We have contact with very many OpenProject users. Noboday we talked to had a similar requirement.
- The user interface for the filters are already too complicated. I guess we need to separate something like "quick filter" and "advanced filter".

I am afraid that we can not take over the maintenance of your feature in the current state. It is really difficult for me to say this because we really appreciate your work.

Best
Niels

**Comment by akasparas** [comment]
Dear @lindenthal,

This PR in current form only adds 2 options for date field: filter all set and filter all unset. Such options are available for all other data types in OpenProject. How this could be too complicated?

On the other hand, when we're talking about all possible combinations of current filter and set/unset, then I agree, this will be complicated. And therefore come here to ask for a way to proceed (or stop at the current point).

Please reconsider. Thank you.

**Pull request closed without merging**
