### PR TITLE
Restore JRuby support

### PR DESCRIPTION
**Pull request by myabc**

### CODE REVIEW

**Comment by marutosi** [comment]
> > Stupid.
> > Should not be in description.
> > All deails should be in ticket and revisions.
> 
> even better! where are your tickets? i've never seen one, have a link?
> anyway, just pasting the summary of your pull request in the description field doesn't hurt, right?!

#1362
Where is ticket link?

**Comment by marutosi** [comment]
#1392

**Comment by linki** [comment]
@marutosi the difference to your pull requests is that @myabc wants to actually make it **work**!
there's more to it than just https://github.com/opf/openproject/pull/1354/files

**Comment by lindenthal** [comment]
Closing PR because it is outdated and not actively developed (not focus of OP 4.1.).

**Comment by myabc** [comment]
Re-opening. Further development was on hold pending the release of JRuby 9.0.0.0.pre1, which provides Ruby 2.x syntax features. Various commits could also be cherry-picked without any detriment to our MRI 2.1 support.

**Pull request closed without merging**
