### PR TITLE
moves select2 css customization to webpack

### PR DESCRIPTION
**Pull request by ulferts**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-project-dropdown-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-project-dropdown-styling.opf-openproject-5eefc6be83fa70526458.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
:+1:

**Comment by ulferts** [comment]
protractor flicker is killing me.

**Comment by myabc** [comment]
> protractor flicker is killing me.

@ulferts @0xF013 @hschink I think I now have a theory for why this is happening. As you're probably ware, Protractor automatically calls `waitForAngular` for us as it steps through the specs. `waitForAngular` will wait until all `$http` requests (and `$timeout`) are complete before proceeding. 

For the details pane we use Hyperagent, and as such `jquery.ajax`, not `$http`. Thus, Protractor has no way of knowing when this request is complete.

The most likely reason for this issue only just becoming apparent was the change in template loading in 21b28246. Previously `$http` requests would have been fired to load templates immediately after the resolution of the `jquery.ajax` request. Now that templates are pre-loaded into `$templateCache`, no `$http` requests are made.

To get around this issue, there are three possibilities:
- we tell Protractor to sleep before asserting the presence of the details pane. This would be the least amount of work upfront, but it is also a crude approach (and something the Protractor maintainers try to discourage).
- we try to find a way to tell Protractor to wait on `jquery.ajax` requests. I've looked through the source, and there is no public API for doing this.
- we modify Hyperagent to use `$http`.

**Comment by 0xF013** [comment]
@myabc @ulferts @hschink 
I think we can do something like

```
var oldAjax = jQuery.ajax
jQuery.ajax = function() {
  var args = arguments;
  $timeout(function() {
    oldAjax.call(args);
  });
}
```

I've seen angular libs that are wrapped for angular use a function like 'angularize' for async stuff that just wraps everything into $timeout, which is aware of the angular lifecycle

**Comment by myabc** [comment]
@0xF013 Actually, I'm not sure we even need to override `jQuery.ajax` globally. We should be able to wrap `jQuery.ajax` in the Hyperagent config itself:

```
  Hyperagent.configure('ajax', function ajax(settings) {
    // wrap in $timeout
    return  $timeout(jQuery.ajax(settings));
  });
```

**Comment by 0xF013** [comment]
@myabc or like that, but we need to make sure Hyperagent is not using the jQuery promises

**Comment by 0xF013** [comment]
we should make a blogpost about this

**Comment by myabc** [comment]
@0xF013 good idea :)

**Comment by hschink** [comment]
@0xF013 +1

**Pull request merged**
