### PR TITLE
Add block which can be used if 'relative_url_root' is configured

### PR DESCRIPTION
**Pull request by kgalli**
[Work Package #8421](https://www.openproject.org/work_packages/8421)

### CODE REVIEW

**Comment by myabc** [comment]
@kgalli Since this checks for `rails_relative_url_root.presence` anyway, could we not just use the commented version by default?

**Comment by kgalli** [comment]
@myabc Unfortunately not, because as far as I know passenger don't like this kind of configuration.

**Comment by machisuji** [comment]
We could check if the app runs in Passenger and skip the subdir business:

```
passenger = defined?(::PhusionPassenger)
# Don't map subdir when using Passenger as passenger takes care of that.
subdir = !passenger && OpenProject::Configuration.rails_relative_url_root.presence
map (subdir || '/') do
  use Rack::Protection::JsonCsrf
  use Rack::Protection::FrameOptions
  run OpenProject::Application
end
```

An alternative would be to just do it by default and simply not configure a subdirectory in passenger, would it not?

I.e. change

```
<Location /subapp>
    PassengerBaseURI /subapp
    PassengerAppRoot /websites/rack
</Location>
```

to

```
<Location /subapp>
    # PassengerBaseURI /subapp
    PassengerAppRoot /websites/rack
</Location>
```

**Comment by cratz** [comment]
I will test this on Friday with passenger and keep you up to date.

**Comment by marutosi** [comment]
> >    Stupid.
> >    Should not be in description.
> >    All deails should be in ticket and revisions.
> 
> even better! where are your tickets? i've never seen one, have a link?
> anyway, just pasting the summary of your pull request in the description field doesn't hurt, right?!

#1362
Where is ticket link?

**Comment by machisuji** [comment]
@marutosi You are right, there really should be a ticket for that. I have just created [one](https://www.openproject.org/work_packages/8421) and put a link to it in the description.

Thanks for pointing that out.

**Comment by machisuji** [comment]
Closing this in favour of #1398.

**Pull request closed without merging**
