### PR TITLE
Use a gem to correctly parse semantic versions

### PR DESCRIPTION
**Pull request by oliverguenther**
Found by @crohr

### CODE REVIEW

**Comment by crohr** [comment]
On debian-9 we also have the following error:

```
ArgumentError: Malformed version number string 10.1.26-MariaDB-0+deb9u1
```

@oliverguenther Maybe add it to the test case?

**Comment by oliverguenther** [comment]
> On debian-9 we also have the following error:
> 
> ```
> ArgumentError: Malformed version number string 10.1.26-MariaDB-0+deb9u1
> ```
> @oliverguenther Maybe add it to the test case?

Done! 👍

**Comment by crohr** [comment]
@oliverguenther great, thanks!

**Comment by crohr** [comment]
@oliverguenther hum... now it breaks for ubuntu:

```
       rake aborted!
       ArgumentError: 5.7.23-0ubuntu0.16.04.1 is not a valid SemVer Version (http://semver.org)
       /opt/openproject/vendor/bundle/ruby/2.5.0/gems/semantic-1.6.1/lib/semantic/version.rb:15:in `initialize'
       /opt/openproject/lib/open_project/database.rb:141:in `new'
       /opt/openproject/lib/open_project/database.rb:141:in `semantic_version'
```

**Comment by crohr** [comment]
@oliverguenther would it be possible to `sub(/-.*/,'')` the value?

**Comment by oliverguenther** [comment]
@crohr https://github.com/opf/openproject/commit/be6514208e should fix this. I decided only to cut the last build when it failed. But you are right that it does not really matter for our case.

**Pull request merged**
