### PR TITLE
Respect self-registration in saml

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.org/work_packages/59403
https://community.openproject.org/work_packages/59370

### CODE REVIEW

**Review by machisuji — APPROVED** [review]
👍 🙏

**Review by machisuji — CHANGES_REQUESTED** [review]
Looks good to me. There's just the `./modules/auth_saml/spec/seeders/env_data/saml/provider_seeder_spec.rb` that has to be fixed.

**Comment by oliverguenther** [comment]
@machisuji done

**Review by machisuji — APPROVED** [review]
Thanks!

**Pull request merged**
