### PR TITLE
[40038] Make team planner only accessible with EE token

### PR DESCRIPTION
**Pull request by bsatarnejad**
Check if the user has a correct EE token activated, otherwise redirect it to upsale template.

https://community.openproject.org/projects/openproject/work_packages/40038/activity

### CODE REVIEW

**Review by oliverguenther — CHANGES_REQUESTED** [review]
LGTM code wise :+1: The feature images are a bit blurry due to their size. Can we commit them in a larger resolution?

**Comment by bsatarnejad** [comment]
Hi @oliverguenther, I just exported the image from Figma and tried to improve its quality with photoshop, but it is not working nicely. Is there another way to have a more qualified image?

**Comment by HDinger** [comment]
>  I just exported the image from Figma and tried to improve its quality with photoshop, but it is not working nicely. Is there another way to have a more qualified image?

Hi @bsatarnejad just ask the product team (Marc) in the ticket for an image with a higher resolution.

**Comment by HDinger** [comment]
The product team does not have a final image yet, so I'll merge this for now. We will change the image later separately.

**Pull request merged**
