### PR TITLE
Work package edit sync

### PR DESCRIPTION
**Pull request by romanroe**
https://community.openproject.com/work_packages/21593/
- [x] Style inplace edit in split view @furinvader
  - [x] styling for subject field
- [x] Resolve API conflict WorkPackage vs WorkPackageResource
  - [x] work-package-resource.service.ts: ~~Remove wrapping function~~, export class @furinvader
- [x] Allow configuration of the displayed fields (currently inherited from global columns object)
- [x] Description field needs to regain `save|cancel` buttons
  - [x] comment field too
- [x] fix integrational tests
  - [X] Specs
  - [x] cukes
- [x] Not all fields with values are displayed even when they are configured to be displayed: https://github.com/opf/openproject/pull/4338/commits/bf8a4956692e234fc68620d68110f5f340760353
- [x] Full edit does not work. Clicking on "Edit" when in the split/full view should set all fields into edit mode. When in that mode, the blur event should not trigger a save. Related specs/cukes should be fixed once that is restored:
  - [x] /spec/features/work_packages/table/context_menu_spec.rb:25
  - [x] ./spec/features/work_packages/select_work_package_row_spec.rb:329
  - [x] ./spec/features/work_packages/edit_work_package_spec.rb:59
  - [x] features/work_packages/switch_type.feature:59 
  - [x] features/work_packages/switch_type.feature:71 _Replaced with spec in edit_work_package_spec_
  - [x] features/work_packages/update.feature:77 
  - [x] features/work_packages/update.feature:86 _Replaced with spec_
  - [x] features/work_packages/editable_fields.feature:46
  - [x] features/work_packages/editable_fields.feature:90
  - [x] features/work_packages/error_on_update.feature:54 _Replaced with spec in subject-editor_
- [x] Date (combination of due and start date) is not displayed/empty in the split/full view.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://romanroe-wp-edit-sync.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://romanroe-wp-edit-sync.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by furinvader** [comment]
Hey Roman, as the `WorkPackageResource` and `HalResource` implementation led to confusion of some extent (being classes defined within a function, thus not exportable),
I'll at first implement them in a way, so they are defined within the scope of the module (not of the function).

**Comment by furinvader** [comment]
I am going to replace the `wp-overview-panel` directive with something more fitting.
There already is one, which was just not in the right place.

**Comment by oliverguenther** [comment]
- [ ] ./spec/features/work_packages/details/inplace_editor/version_editor_spec.rb:46
- [ ] ./spec/features/work_packages/details/details_relations_spec.rb:17
- [ ] ./spec/features/work_packages/details/inplace_editor/custom_field_spec.rb:82
- [ ] ./spec/features/work_packages/details/inplace_editor/custom_field_spec.rb:59
- [ ] ./spec/features/work_packages/details/inplace_editor/custom_field_spec.rb:102
- [ ] ./spec/features/work_packages/details/inplace_editor/subject_editor_spec.rb[1:2:1:1:2]
- [ ] ./spec/features/work_packages/details/inplace_editor/subject_editor_spec.rb[1:2:1:1:3]
- [ ] ./spec/features/work_packages/details/inplace_editor/subject_editor_spec.rb[1:3:2:1:3]
- [ ] ./spec/features/work_packages/details/inplace_editor/subject_editor_spec.rb[1:3:1:1:3]
- [ ] ./spec/features/work_packages/details/inplace_editor/subject_editor_spec.rb:60
- [ ] ./spec/features/work_packages/details/inplace_editor/subject_editor_spec.rb:65
- [ ] ./spec/features/work_packages/details/inplace_editor/subject_editor_spec.rb:72
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:49
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:43
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:129
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:87
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:80
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:73
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:67
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:109
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb:118
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb[1:1:1:3:1]
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb[1:1:1:2:1]
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb[1:1:1:1:1:3]
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb[1:1:1:1:1:1]
- [ ] ./spec/features/work_packages/details/activity_comments_spec.rb[1:1:1:1:1:2]
- [ ] ./spec/features/work_packages/select_work_package_row_spec.rb:315
- [ ] ./spec/features/work_packages/select_work_package_row_spec.rb:328
- [ ] ./spec/features/work_packages/edit_work_package_spec.rb:59
- [ ] ./spec/features/work_packages/tabs/activity_tab_spec.rb[1:1:1:1:3]
- [ ] ./spec/features/work_packages/tabs/activity_tab_spec.rb[1:2:1:1:3]
- [ ] ./spec/features/work_packages/table/context_menu_spec.rb:25
- [ ] ./spec/features/work_packages/details/inplace_editor/description_editor_spec.rb[1:2:1:1:3]
- [ ] ./spec/features/work_packages/details/inplace_editor/description_editor_spec.rb[1:2:1:1:2]
- [ ] ./spec/features/work_packages/details/inplace_editor/description_editor_spec.rb[1:3:1:1:3]
- [ ] ./spec/features/work_packages/details/inplace_editor/description_editor_spec.rb[1:3:2:1:3]
- [ ] ./spec/features/work_packages/new_work_package_spec.rb[1:1:1:3:1]
- [ ] ./spec/features/work_packages/new_work_package_spec.rb[1:1:1:3:3:1]
- [ ] ./spec/features/work_packages/table/edit_work_packages_spec.rb:85

**Pull request merged**
