### PR TITLE
[25715] Even short subjects get truncated when many columns are displayed

### PR DESCRIPTION
**Pull request by HDinger**
Avoid a truncation of the subject table header. This occurred when there were only small subjects.

https://community.openproject.com/projects/openproject/work_packages/25715/activity

### CODE REVIEW

**Comment by HDinger** [comment]
@oliverguenther I did not find any issues. Could you check however whether this solution will break something else?

**Comment by oliverguenther** [comment]
bildschirmfoto 2017-07-17 um 08 33 24

This causes the subject column dropdown to be positioned not on the right side, but at the 30px padding distance, which looks different to other columns. Would be acceptable for me however if there is no other solution.

**Comment by HDinger** [comment]
@oliverguenther Yeah, I noticed that too. Unfortunately I did not found a good solution to avoid this.

**Comment by ulferts** [comment]
I've added a flex based solution to the PR which I believe is stable and way simpler than what we had before.

**Comment by oliverguenther** [comment]
👍 @ulferts. Merged this into dev, resolving a conflict from relation columns on the way

**Comment by ulferts** [comment]
Thanks @oliverguenther

**Pull request closed without merging**
