### PR TITLE
update fog version

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-dev-fog.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-dev-fog.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@marutosi @linki do we really want to pull in all of these dependencies? can we stick with `fog-core`?

**Comment by floriank** [comment]
Is this PR still relevant @linki @marutosi ?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Pull request closed without merging**
