### PR TITLE
[#42937] Improve Repositories Documentation

### PR DESCRIPTION
**Pull request by ghost**
[#42937] Improve Repositories Documentation

https://community.openproject.org/work_packages/42937

### CODE REVIEW

**Review by machisuji — APPROVED** [review]
👍

**Review by machisuji — CHANGES_REQUESTED** [review]
Please target release/12.1 instead of dev for documentation changes.

**Comment by birthe** [comment]
HI @adam-op I have moved the comment below the h1 headline in the system admin guide. Also, I have added a small note to the user guide. For me, ít's ready to be merged into 12.1. I will then take care to publish the changes on the website.

**Review by birthe — APPROVED** [review]

**Comment by ghost** [comment]
> Please target release/12.1 instead of dev for documentation changes.

@machisuji how could that happen again? Where shall I select release/12.1 ? which step?
how to change it now?

**Comment by ghost** [comment]
@machisuji i think that this can go to the merge now?

**Comment by oliverguenther** [comment]
You can edit the target branch at the top next to the title "edit". 
image

In case you accidentally based your changes also on dev, but want to base on 12.1, you have to force push. This is not the case here though

**Pull request merged**
