### PR TITLE
CircleCI

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-circle-yml.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-circle-yml.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
Please provide a description on why you think CircleCI should be used.

**Comment by marutosi** [comment]
> why you think CircleCI should be used.

https://github.com/travis-ci/travis-ci/issues/1147

**Comment by marutosi** [comment]
> Please provide a description

Why not reject #3182?

**Pull request closed without merging**
