### PR TITLE
[20043] Upgrade to Rails 4.1.x

### PR DESCRIPTION
**Pull request by myabc**
:warning: ~~**Includes commits from #3194. Please review, merge first.**~~

https://community.openproject.org/work_packages/20043

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-rails4-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-rails4-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Seeds are broken [due to the removal of the deprecated Railties `engines`](https://github.com/rails/rails/commit/4a2a504f40a8b6eec88e6aafefcf8e579a24e1c9#diff-7d0a784885a7ba0f99b77cb306dba31b). If you don't mind, I would contribute some changes concerning this + the broken specs.

**Comment by myabc** [comment]
@oliverguenther –

>  If you don't mind, I would contribute some changes concerning this + the broken specs.

Sure! that'd be great.

**Comment by oliverguenther** [comment]
I've started a PR against your branch over at https://github.com/myabc/openproject/pull/2.

**Comment by myabc** [comment]
Closed in favour of #3382 (against `dev`, not `feature/rails4`).

**Pull request closed without merging**
