### PR TITLE
18379 Filter styling

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/18379

Continuation of #2294.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://feature-foundation-apps-framework-filters.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://feature-foundation-apps-framework-filters.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@myabc I'd like to apply the styling to the timelines edit form to get this roughly consistent. What do you think?

**Comment by myabc** [comment]
@ulferts 

> I'd like to apply the styling to the timelines edit form to get this roughly consistent. 

I agree that the styling of the timelines edit form is currently broken… but do you mean you want to make the UI's appear similar? (e.g. the 'Filter work packages' section of the timelines edit form)

**Comment by ulferts** [comment]
> but do you mean you want to make the UI's appear similar? (e.g. the 'Filter work packages' section of the timelines edit form)

Yes, at least roughly because it is a filter after all (granted, the timeline edit form is so much more but it is also a filter). Of course, some elements of the filtering will not be present (e.g. remove filter, add filter) but at least the layouting might be similar. I don't intend to change the behaviour because it would be too much for now. I'd have to introduce some more css classes for the value types but I could reuse those on the reporting plugin.

I wouldn't want to invest too much work in the timelines form as it is going to be removed as soon as we can manage and applying the filter styling on it seems to be a fast way. I'd do it in a separate PR however.

**Comment by ulferts** [comment]
I thought about my proposal regarding timelines again. Now I don't believe that timelines should have the filter styling applied but rather that the filter styling should depend on a style that is also applied to timelines.

Therefore, I will finish this here by updating the styleguide.

**Comment by ulferts** [comment]
@myabc I think this is finished for now.

There are some deviations from the specifications:
- The logo for removing the filters differs. I used the icon used everywhere for removing. We might want to switch to a different logo but should then do so everywhere.
- The attributes of a filter (name, operator, value, multiselect toggler and remove icon) are not aligned to the top but in the middle. While I think having them aligned at the top would look nicer, it is harder to achieve, as we would have to set paddings/margins for every item. As long as the fonts are not finalised, I wouldn't want to do that. The ticket is called "quick wins" after all.
- I did not apply any styling to the form elements themselves as we agreed.

**Pull request merged**
