### PR TITLE
deps[Op#51376]: Bump `opf/primer_view_components` to v0.36.2

### PR DESCRIPTION
**Pull request by akabiru**
- https://github.com/opf/primer_view_components/releases/tag/v0.36.1
- https://github.com/opf/primer_view_components/releases/tag/v0.36.2

Screenshot 2024-07-09 at 4 05 46 PM

### CODE REVIEW

**Comment by akabiru** [comment]
There is a spacing issue - fixed in https://github.com/opf/primer_view_components/pull/143

**Review by HDinger — CHANGES_REQUESTED** [review]
Please also update the `override` dependency [here](https://github.com/opf/openproject/blob/dev/frontend/package.json#L178). Other than that, it is fine 👍

**Review by HDinger — APPROVED** [review]
This can be merged, but you can also directly update 0.36.2 if you want to

**Comment by akabiru** [comment]
> This can be merged, but you can also directly update 0.36.2 if you want to

Thanks, yes- upgrading now 👍🏾

**Pull request merged**
