### PR TITLE
extend attachments api to wiki_pages

### PR DESCRIPTION
**Pull request by ulferts**
Generalizes the work_package only implementation for reading, creating and deleting to all attachables:

* [x] wiki_page
* [x] messages
* [x] documents (https://github.com/opf/openproject-documents/pull/73)

The attachables do currently not exist as resources. The PR adds them as stubs only.

It also adds an endpoint for downloading attachments https://community.openproject.com/projects/openproject/work_packages/25103

### TODO:
* [x] Document added api resources
* [x] Endpoint to upload a generic (i.e. without a container) attachment
* [x] Claiming uploaded attachments on wp create
* [x] Background job to remove unclaimed (i.e. without container) attachments after a grace period.
* [x] Check code once again
 
https://community.openproject.com/projects/openproject/work_packages/27748/activity

### CODE REVIEW

**Comment by oliverguenther** [comment]
Any chance you can fix https://community.openproject.com/projects/openproject/work_packages/25103 while you're working on the attachment representer?

**Comment by ulferts** [comment]
@oliverguenther I'll look into it.

**Comment by oliverguenther** [comment]
There are also two additional issues (one related) that will need to be addressed:

1. When creating new wiki pages, we will probably need to upload the image right away - unless we can trick CKEditor to embed a data-url or similar before the resource exists. This problem is the same as the create-then-upload-attachments the work package page which should be resolved. It should be easy to upload attachments without a container reference and link them later on, the problematic part will be removing these when the creation was cancelled.


2. Uploading attachments is currently tied to the `add_work_packages` permission. We will want to introduce a separate permission to make it clearer

**Comment by oliverguenther** [comment]
:+1:

**Pull request merged**
