### PR TITLE
remove rack definition from Gemfile.

### PR DESCRIPTION
**Pull request by marutosi**
It is managed by Gefile.lock.
It should be updated by "bundle update rack".
For example #2953.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-0-rack.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-0-rack.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@marutosi no, with dependencies of dependencies that won't work. AFAIK you can only do `bundle update` if it is a _direct dependency_.

**Comment by marutosi** [comment]
Really?

https://github.com/rails/rails/blob/v3.2.22/actionpack/actionpack.gemspec#L26

**Comment by marutosi** [comment]
@myabc, you are wrong.

https://bitbucket.org/marutosi/openproject-pr3147-rack/commits/a978bf65b6ceb2c0f5fb8f86e92275b6b8cf6cd5

**Comment by myabc** [comment]
@marutosi oh. has the behaviour changed?

**Comment by marutosi** [comment]
I think you are confused with Rails 4.0.
https://github.com/rails/rails/blob/v4.0.13/actionpack/actionpack.gemspec#L24

> s.add_dependency 'rack', '~> 1.5.2'

**Comment by myabc** [comment]
@marutosi –

> I think you are confused with Rails 4.0.

might be. too much time spent on #2104 :smile:

**Pull request closed without merging**
