### PR TITLE
recovery test/fixtures/auth_sources.yml

### PR DESCRIPTION
**Pull request by marutosi**
This needs in LDAP test.
https://github.com/opf/openproject/blob/v4.0.9/test/unit/ldap_auth_source_test.rb#L49

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-ldap-fixture.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-ldap-fixture.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
Restarted the failing build as it seemed unrelated to the changes @marutosi made

**Comment by linki** [comment]
:-1:

https://github.com/marutosi/openproject/commit/e55c9765f0f009d66da14ff5060d25053bee6267#diff-289c53b4c0f454861db9a893a5ceb957R333 removes the fixture and changes the specs to use a `factory_girl` factory. i would prefer changing https://github.com/opf/openproject/blob/v4.0.9/test/unit/ldap_auth_source_test.rb#L49 to use the factory as well.

which is here now: https://github.com/opf/openproject/blob/2efd6f4e4535b14cd8577883e56770118215b46b/spec/legacy/unit/ldap_auth_source_spec.rb#L49

seeing that this is a hotfix it might be fine...

**Comment by floriank** [comment]
I'd prefer changing the test as well to get rid of the re-added fixture.

@marutosi To be specific: 
Change https://github.com/opf/openproject/blob/v4.0.9/test/unit/ldap_auth_source_test.rb#L49 to use a factory instead of the fixture.

**Pull request closed without merging**
