### PR TITLE
interactive selection mode

### PR DESCRIPTION
**Pull request by romanroe**

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/5c6171be791fb11edaff66b3ba7d61315c7495c3) (deployed commit: a0c6b2c8d78214beaaaa7a33cc480f52551ca605).

**Review by oliverguenther — APPROVED** [review]

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/0de0b6bf0e6613660f588fc1bf5351c2baf62733) (deployed commit: 38797317018dbbf577df3c150043096c435c173b).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/1165ad37f1dc1e154e753a59fa9aeae8ca185303) (deployed commit: 3a2f45e1000e88db07f3174634f797b9ec0d680f).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/e46d777357cb187fd25ed96476d2cdb66dcc361d) (deployed commit: 3a2f45e1000e88db07f3174634f797b9ec0d680f).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/817e461c9af4dd10d89239b7a658478ceb905a45) (deployed commit: 99c48c04a89840cc3d128f4699c64d008c1357c5).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c9462f01831a6e4fd0a942f3b1b6b303cde0ae1b) (deployed commit: 424b814af8505c03c35e49df92a38281a1892b8d).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c85ebb1f5903ae7e84e2325e9d2f3e81035555c6) (deployed commit: edd66511f23553428406e609591361877b362229).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/262a5ce203054fb55a1c98d6552eed5360c5475e) (deployed commit: dc9f410cd01516c14e3320be41faae71709e62c0).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/e4cf01068358c5e27fb62d96e2e4953e912257ab) (deployed commit: b783de8532fc38d0bd7ae907534e029a8ce26c49).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/f90388182d2d867658b4b48ea8792c40817c9049) (deployed commit: 7f829c375493bfc8e7a8b3409742000fa7b9cdf6).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/8aad720d96df6439e4bb56c32740e4ca90213ed2) (deployed commit: 2a98ddc0bd93a4fb28080ef64f8b8ccbafa3d40e).

**Pull request merged**
