### PR TITLE
Feature/improve apiv3 wp index

### PR DESCRIPTION
**Pull request by ulferts**
Improves the performance of APIv3 work_packages#index by:
- Eager loading objects associated with a work package to avoid n+1 queries.
  - Most of the eager loading is standard. The exception to this is the `:spent_time` association which this PR introduces. It does not rely on a DB table but on a SQL query instead. Please read the comments.
- Reusing representer classes that are prototypical for work packages of a certain project and type.
- Caching the root_path for all the urls that are used when rendering the representer. Following HAL, we have a lot of urls in each representer. So while each call to root_path is not taking overly long, the sum of the calls called for optimizing.

This PR focused on the representer. There will still be a lot of room for optimization e.g. in the query. However, there is one improvement on the query which already saves a lot of time by loading less sql columns.

:warning: Requires merging of finnlabs/openproject-costs#212 :warning: 

https://community.openproject.org/work_packages/22586/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-feature-improve-apiv3-wp-index.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://ulferts-feature-improve-apiv3-wp-index.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
I'll have to take another look at some of the tests.

**Comment by oliverguenther** [comment]
Did you add and remove `to_eager_load` in the course of this PR? The costs PR still seems to depend on it, but I have no knowledge of that method.

**Comment by oliverguenther** [comment]
:+1:  Nice work, global WP response times on Core and CE are roughly cut in half (this is without the Costs PR due to the issue mentioned above). (However with random seeded data, will run some tests on ite dump later)

**Core before**

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:   860 1000 359.9    891    2023
Waiting:      860 1000 359.9    890    2023
Total:        860 1000 359.9    891    2023
```

**Core after**

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:   330  456 341.1    340    1425
Waiting:      330  456 341.1    340    1424
Total:        330  456 341.1    340    1425
```

**CE before**

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:  1501 1649 177.9   1626    1973
Waiting:     1500 1649 177.9   1626    1973
Total:       1501 1650 177.9   1627    1973
```

**CE after**

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:   767  790  43.7    776     911
Waiting:      767  790  43.6    776     911
Total:        767  791  43.6    777     911
```

**Comment by ulferts** [comment]
Hm, I somehow messed up the branches across all the different repositories I have set up locally, @oliverguenther. Will fix that and report back.

**Comment by ulferts** [comment]
I think I fixed it now, @oliverguenther. Sorry for the confusion.

**Comment by oliverguenther** [comment]
Tested once more on local ite dump, works fine. Global unfiltered WP APIv3 response is still awfully slow, but both PRs cut the response time to roughly one third of before. :+1: 

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:  6430 6642 446.1   6535    7902
Waiting:     6430 6642 446.1   6535    7902
Total:       6430 6643 446.1   6535    7902
```

**Pull request merged**
