### PR TITLE
Extending the backend with new relation types / methods

### PR DESCRIPTION
**Pull request by manuschiller**
This extends the available relations configuration with following types:
- includes / part of
- requires / required by

Furthermore it adds a patch method for updating relations.

@machisuji @ulferts

### CODE REVIEW

**Comment by manuschiller** [comment]
@ulferts @machisuji 

In this context it would be nice if we could improve the autocomplete api for related workpackages.
For the current version of our `relations-tab` this is [done in the fronend ](https://github.com/manuschiller/openproject/blob/cc37db909675ada7c21723adc5a7682557595daa/frontend/app/components/wp-relations/wp-relations-create/wp-relations-autocomplete/wp-relations-autocomplete.directive.ts#L96), but it is not really efficient and has its limitations (e.g. only parents and children are getting rejected - but not grandparents / grandchildren)

**Comment by manuschiller** [comment]
@ulferts i believe this can be closed because of [pr 4892](https://github.com/opf/openproject/pull/4892)

**Comment by ulferts** [comment]
@manuschiller it is still valid. #4892 only contains the specification as of now. This might change and we might want to break up, cherry-pick or restructure the commits in this PR but they are still valuable.

**Comment by oliverguenther** [comment]
Closing as the first part is extracted in #4912. Please keep the second commit around for now since we can re-use it.

**Pull request closed without merging**
