### PR TITLE
[21588] Explicit project identifier editing

### PR DESCRIPTION
**Pull request by leewaa**
Replaces #3559
Workpackage: https://community.openproject.org/work_packages/21588/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://leewaa-21588-explicit-project-identifier-edit.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://leewaa-21588-explicit-project-identifier-edit.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by leewaa** [comment]
Work package: [21588](https://community.openproject.org/work_packages/21588/activity)

@mk84 styling:
- [x] Edit button on project settings page
- [x] Identifier form field on in the danger zone, fix the invalid styling for the field
- [x] Identifier form field hint

**Comment by lindenthal** [comment]
Hi Pete,

can you please rebase this PR so Teatro works again?

Thanks
Niels

**Comment by leewaa** [comment]
Sure

**Comment by leewaa** [comment]
Done

**Comment by lindenthal** [comment]
Hi guys,
whats the status here?
Regards
NIels

**Comment by leewaa** [comment]
Just waiting for travis to go green.

**Comment by leewaa** [comment]
In the meantime, someone want to review this? @oliverguenther, @marutosi, or @why-el ?

**Comment by leewaa** [comment]
@mk84 Have a please follow up on this? The changes you made to `tabular_form_builder` broke the build....

**Comment by leewaa** [comment]
Hey @mk84 can you please follow up on this? The changes you made to the `tabular_form_builder_spec` broke the build

**Comment by mk84** [comment]
@leewaa what do you mean? I haven't touched the `tabular_form_builder_spec`.

**Comment by leewaa** [comment]
Ah sorry not the spec I meant the tabular_form_builder itself.

**Pull request merged**
