### PR TITLE
[20676] add stackable nodifications in LSG

### PR DESCRIPTION
**Pull request by vcostin**
[`* `#20676` Feature [Styling][Design] Stackable notifications`](https://community.openproject.org/work_packages/20676)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://vcostin-feature-20676-stackable-notifications.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://vcostin-feature-20676-stackable-notifications.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
I have to admit: I have not yet an idea what the `-stack-top-center` modifier does:

stack

This screenshot is taken from the living styleguide, the only thing I changed is that I duplicated the `-success` notification. I did not add the stackable modifier to the success box or change other CSS rules.

Both versions (with and without `-stack-top-center`) seem to behave the same way.

**Comment by NobodysNightmare** [comment]
Also: I am not sure if your implementation is the thing that @floriank specified (or tried to specify). However: Note that my CSS knowledge is still a little rusty, so it might be my fault.

Your notification boxes seem to expose the following behaviour:
- they take the full width of the parent container
- they do not seem to float above the page, but I might be getting the requirement wrong here

I'd have expected them to have a limited width, but probably I am misunderstanding the "expected DOM" that is required to render them correctly.

**Comment by NobodysNightmare** [comment]
I checked the styleguide on http://clients.zzmedia.net/openproject/messages/styleguide/ again. There the following width-definitions are applied:

```
min-width: 250px;
max-width: 550px;
```

Without judging whether those width boundaries are good values, having them might fix the "full width" problem I mentioned above.

edit: Then again, if we allow our notifications to have a reduced width by default, we should also ensure that they are centered by default...

**Comment by floriank** [comment]
Note on Style: I think there should be a margin between multiple stacked notifications.

**Comment by floriank** [comment]
And @NobodysNightmare is correct:
- the should be a fixed width for the notifications, as @zzmedia suggested in the styleguide, it should be fixed width for now.
- the notifications should overlay on the content of the page. 

The original ticket specified a modifier class, which might have not been the best idea (my bad, sorry to have lead you down a wrong path here @vcostin :tired_face:)

A note on the **expected DOM**: I gave this a little bit of thought. What we could do is have a fixed container `div` for the page, like this:

``` html
<!-- I am BAD at naming things -->
<div class="message-container">
  <div class="notification-box"></div>
  <div class="notification-box"></div>
  <div class="notification-box"></div>
  <div class="notification-box"></div>
  .
  .
  .
  <div class="notification-box"></div>
</div>
```

with the styling along the lines of:

``` css
.message-container {
  position: fixed;
  top: 20px; /* or some higher value, I dunno, we have to play with it */
  /* etc.*/
}
```

This would give us better handling in AngularJS as we could just wrap this into a directive controlling a stack of notifications. The `message-container` should overlay the rest of the page. A problem here might be that it would scroll along with the page. I am not sure if this might be a good thing.

The style requirement stays the same, the `.notification-box` should be centered on the whole page overlay with (for now) fixed widths.

**Comment by Azure7111** [comment]
If I may chime in on your concern about having multiple stacked notifications scroll along with the page: Imagine having so many stacked notifications so that your screen height is completely used up by it. Now think about how scrolling would feel with these...

**Comment by vcostin** [comment]
Any design suggestions :) ?

**Comment by floriank** [comment]
Not really, but we could get around this by placing the container at the end/start of the body:

``` html
<body data-ng-app="openproject">
<!-- Magical Unicorns and Dragons -->
<div class="message-container"></div>
</body>
```

and using 

``` css
.message-container {
  position: absolute;
}
```

instead of `fixed`. I am by no means a CSS expert, so this might or might not work.

**Comment by vcostin** [comment]
can't make animation in a `CSS position:absolute;` container so I wrapped in another `div`

**Comment by floriank** [comment]
@vcostin: What is the status on this? Still WIP?

(I just noticed you cannot remove labels yourself :worried:)

**Comment by floriank** [comment]
@vcostin You could also elevate the power of [Zurb foundation notifications](http://foundation.zurb.com/apps/docs/#!/notification)

**Comment by vcostin** [comment]
I'll take a look

**Comment by vcostin** [comment]
@floriank have a look

**Comment by floriank** [comment]
i removed the label, will take a look after i finished the first attachments in create iteration

**Comment by floriank** [comment]
I am not good at naming myself, but `op-container-holder` is strange.

Maybe `notification-box--wrapper` or something along the lines.

**Comment by floriank** [comment]
While this does work for the LSG, trying it out for a normal template does not:
The Messages are not yet centered.
screenshot from 2015-07-13 16 47 51

In the example I tried using a single message with a container on the bottom of the document, right before the `</body>`.

**Comment by vcostin** [comment]
Now it should be centred as well in the OP layout. Tomorrow I'll test in other browsers, currently tested on latest FF.

**Comment by floriank** [comment]
Great, I'll have a look - I currently work out the details for the notification service, which should make decision making here easier.

**Comment by vcostin** [comment]
display flex in `.notification-box--wrapper` were overlaid over left side menu so it weren't accessible till notification message were closed. I tested in FF, IE10-11, Chrome. This should work.

**Comment by floriank** [comment]
Okay, I did qa quick rundown of the supported browsers. We might have to think about the responsive solution to these notifications, but that's a story for another time.

**Pull request merged**
