### PR TITLE
BIM User Guide - BCF Management & IFC Viewer

### PR DESCRIPTION
**Pull request by ValentinEge**
[#40273] Create BIM documentation

https://community.openproject.org/work_packages/40273

### CODE REVIEW

**Comment by lindenthal** [comment]
Hi @ValentinEge,
thanks for working on this. What is the current status here?
Best
Niels

**Comment by ValentinEge** [comment]
Hi @lindenthal ,
the description of all functions within OpenProject BIM is done. The only thing what's missing is the Revit Addin.
I'll have a meeting with some Revit experts within the next days to finalize the documentation for Revit OpenProject Addin as well.
Best, Valentin

**Comment by ValentinEge** [comment]
> Hi @lindenthal , the description of all functions within OpenProject BIM is done. The only thing what's missing is the Revit Addin. I'll have a meeting with some Revit experts within the next days to finalize the documentation for Revit OpenProject Addin as well. Best, Valentin

After finalizing the documentation we might have to replace the screenshots / GIFs. I used the current state of the IFC model which has some already knowkn issues with displaying the model (e.g. the color of the roof). I also made the screenshots with a test version (you can see the demo label within the videos).

**Comment by lindenthal** [comment]
Hi @ValentinEge,
OK, thanks. 
I suggest to do add the Revit docs in a separate PR. 
Who will review the docs?
Can you please also add the work package to the description of this PR?


Best
Niels

**Comment by ValentinEge** [comment]
Hello @lindenthal ,
Ok, I'll add the Revit docs in a separate PR.
At the moment there is no one checking the docs. But I think it makes sense if someone out of the core team who knows the current documentation (and in the best case never tried the BIM Edition) checks it.

"Can you please also add the work package to the description of this PR?"
Yes for sure. But I don't know how .. :)

Best, Valentin

**Comment by lindenthal** [comment]
Hi @bpetraus,
Can you please do the review for the docs?
Thanks
Niels

**Pull request merged**
