### PR TITLE
Fix opening of links in new tab using ctrl.

### PR DESCRIPTION
**Pull request by knight-bubble**
[`* `#19639` Work package page reloaded when clicking on link on work package list`](http://community.openproject.org/work_packages/19639)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hirtie-maxim-fix-19639-page-reloading.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hirtie-maxim-fix-19639-page-reloading.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@hirtie-maxim specs fail

**Comment by myabc** [comment]
I messed up and merged into `dev`.. subsequently applied the patch to `release/4.1` – unfortunately this commit will appear now appear twice.

**Comment by myabc** [comment]
@hirtie-maxim Can you check this functionality?  spec temporarily skipped: https://github.com/opf/openproject/commit/ef8491e11b37f1e682c71906557c20c43cab867d

**Pull request merged**
