### PR TITLE
Adapt relations frontend to new API

### PR DESCRIPTION
**Pull request by oliverguenther**
Uses the new relation API to clean up the relation frontend:
- Adds a RelationResource to handle most of the information and link passage
- Suggests to replace the broken ui-select (#24135) with typeahead from bootstrap.

https://community.openproject.com/work_packages/24135
https://community.openproject.com/work_packages/24078

### CODE REVIEW

**Comment by crohr** [comment]
FYI, this PR was impossible to build on pullpreview due to the following error (see https://pullpreview.com/opf/openproject/sessions/f1cd212674fc2b2f64f0271ea1057f0ab07bc584/logs):

```
1477911422016: npm ERR! notsup Unsupported
1477911422153: npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.14
1477911422287: npm ERR! notsup Valid OS:    darwin
1477911422421: npm ERR! notsup Valid Arch:  any
1477911422557: npm ERR! notsup Actual OS:   linux
1477911422691: npm ERR! notsup Actual Arch: x64
```

Is there any cache or configuration file that might explain this? /cc @oliverguenther @machisuji

**Comment by openprojectci** [comment]
Hey Cyril,

the fix is to update to npm 4.0.
I did this for saas-openproject already in the docker file (https://github.com/finnlabs/saas-openproject/commit/b33dd50d7da48645b29bdcb8823c3c9028526a19 https://github.com/finnlabs/saas-openproject/commit/b33dd50d7da48645b29bdcb8823c3c9028526a19) and also bumped the node version to 6.9.1.

I don’t quite know how this works for pull preview. Do we have to update the Dockerfile in the core or is that a separate issue?

~ Markus

**Comment by crohr** [comment]
@machisuji OK I see, yes it would be best to also modify the core `Dockerfile` (https://github.com/opf/openproject/blob/dev/Dockerfile), so that the docker image can be built there as well. Can you take care of it?

**Comment by machisuji** [comment]
@crohr Alright sure, I'll take care of it.

**Comment by machisuji** [comment]
Updated the [Dockerfile](https://github.com/opf/openproject/commit/230b0d0fb5af343c28c1bb3451e69b4461e721eb).

**Pull request merged**
