### PR TITLE
update Gemfile to include Rubocop

### PR DESCRIPTION
**Pull request by NobodysNightmare**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://feature-include-rubocop.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://feature-include-rubocop.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@NobodysNightmare would have liked not to have had this as a dependency, but if this is the only way to make things work well with tooling…  @ulferts thoughts?

**Comment by NobodysNightmare** [comment]
At least our tooling requires it to be in the Gemfile...

What would _suffice_ is to solely `bundle update ruby-progressbar`. In this case we could use the latest rubocop in our own `Gemfile.local`.

**Comment by myabc** [comment]
@NobodysNightmare 

> What would suffice is to solely bundle update ruby-progressbar. In this case we could use the latest rubocop in our own Gemfile.local.

That would be better IMO. I have to work out in what part of the codebase we're actually using `ruby-progressbar` first… :frowning:

**Comment by ulferts** [comment]
@myabc AFAIK we are only using it in the migrations from OP 2.4 to 3.0 (e.g. journals) where we have some very lengthy calculations to do which take some hours.

Why wouldn't you want to have rubocop as part of the Gemfile? Doesn't the styling we force the code to have (hound on Github) require you to have it?

**Comment by NobodysNightmare** [comment]
Any decision here?

Since `ruby-progressbar` was updated I can use rubocop in my Gemfile.local without conflicts... however, this still causes updates to my Gemfile.lock.

I'd like a decision here: Include rubocop? Exclude it? Is it fine to do the other changes to the Gemfile.lock?

**Comment by myabc** [comment]
@NobodysNightmare merged. While I'm still not a fan of having this in our `Gemfile`, there are other greater annoyances (like `Gemfile.plugins` resulting in a dirty `Gemfile.lock`)

**Pull request merged**
