### PR TITLE
[22624] Add link to success message on work package update/create

### PR DESCRIPTION
**Pull request by manuschiller**
related to [https://community.openproject.org/work_packages/22624/activity](url)

The flash message which appears after a successful creation / update of a workpackage now contains a link for switching to the full screen view.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://manuschiller-22624.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://manuschiller-22624.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Hey @manuschiller. Seems to work fine.

Can you add the string to `en-js.yml` instead of hard coding it in english? Also, please use the string `Click here to open this work package in fullscreen view`.

Also, you can remove the `$apply` (see the codeclimate issue https://codeclimate.com/github/opf/openproject/pull/4251)

**Comment by manuschiller** [comment]
thanks for the I18 hint!
Actually codeclimate is wrong in this case. Without `apply` the view won't change because of the loadingIndicator component. Maybe it's based on a jquery plugin handling its events or callbacks outside the angular digest cycle?

**Comment by oliverguenther** [comment]
Ah well, yes it does that sometimes. No worries then. Thanks for the i18n update! Merging after travis.

**Pull request merged**
