### PR TITLE
Clean unnecessary properties in npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by myabc**
Apparently npm shrinkwrap is not idempotent. This allows for clean
diffs.

See https://github.com/npm/npm/issues/3581

See #2342 for original PR introducing npm shrinkwrap.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-clean-npm-shrinkwrap.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@ulferts @0xF013 Workflow after adding a npm dependency to `package.json`:

``` bash
npm i && npm shrinkwrap && ./scripts/clean-shrinkwrap.js
```

(not sure where to document this)

**Comment by ulferts** [comment]
@myabc the only thing that comes to mind is extending the doc directory with a doc/developer folder. The RUNNING_TESTS.md could also be moved in there, then.

**Comment by 0xF013** [comment]
@myabc @ulferts what about postinstall?

**Comment by myabc** [comment]
@0xF013 I'm not sure I want it to be that automatic (?)

**Comment by myabc** [comment]
Merging myself as this is relatively straightforward.

**Comment by 0xF013** [comment]
Blasphemy

**Pull request merged**
