### PR TITLE
Use ruby 2.2.3 on travis

### PR DESCRIPTION
**Pull request by basiszwo**
https://community.openproject.org/work_packages/20046/activity#

### CODE REVIEW

**Comment by basiszwo** [comment]
@lindenthal @oliverguenther @why-el ruby 2.2.3 looks good in core. Will check against community edition locally.

**Comment by why-el** [comment]
:+1:

**Comment by why-el** [comment]
@jonasheinrich in case you are busy I can take over this just let me know. Would love to see this ruby version in core.

**Comment by jonasheinrich** [comment]
@why-el I'm not completely sure what needs to be done here. But I will update rvm on our internal ci. I think that is a necessary step, should be done first and can only be done by me (I guess).

**Comment by why-el** [comment]
Ok, then do that and if all good we merge here. :+1:

**Pull request merged**
