### PR TITLE
Fix/try a stable merge

### PR DESCRIPTION
**Pull request by tessi**
this PR is there to show what a stable-to-dev merge brings.

Let's see what travis thinks of it.

### CODE REVIEW

**Comment by tessi** [comment]
actually the release branch (and not the stable branch) should be merged (according to git-flow). However, the release and stable branch are identical at the moment.

**Comment by myabc** [comment]
@tessi was there a reason for creating a PR from a branch off stable (`fix/try_a_stable_merge`) rather than stable itself?

**Comment by tessi** [comment]
I tried that merge on my machine and some tests didn't pass. I expected that I need to add some fixes and, thus, precautionary created a branch. Later it turned out to be some random failing tests because I configured thing wrong locally.

Long story short: there is no special reason that this is a branch, it just happened.

**Comment by tessi** [comment]
I merged the release branch into dev manually. so this PR is obsolete

**Pull request closed without merging**
