### PR TITLE
Bug #19028: [Regression][Accessibility] No auto-focus set when opening modal windows in work package list

### PR DESCRIPTION
**Pull request by nickmessing**
https://community.openproject.org/work_packages/19028

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nickmessing-bugfix-19028-auto-focus-modal.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nickmessing-bugfix-19028-auto-focus-modal.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@nickmessing at least on my dev environment (macos/chrome) no focus is set for e.g. the columns modal:

image

Additionally, I'd like to make the angular-context-menu repo an opf repo to avoid having it coupled to any individual developer. Would that be OK?

**Comment by nickmessing** [comment]
Don't merge yet, need to focus tests...

**Comment by floriank** [comment]
cannot merge anyway - need to rebase.

**Comment by nickmessing** [comment]
@ulferts, yes, ofc, I forked it from @0xF013 anyway.

**Comment by 0xF013** [comment]
@floriank as soon as it is mergeable, we can make the whole 'merge-merge-bower' stuff

**Pull request closed without merging**
