### PR TITLE
Add acceskey that toggles details view.

### PR DESCRIPTION
**Pull request by knight-bubble**
[`* `#17808`  Define access key to switch between WP list and split screen`](http://community.openproject.org/work_packages/17808)
see also #2918

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hirtie-maxim-fix-17808-access-key-switch.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hirtie-maxim-fix-17808-access-key-switch.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by machisuji** [comment]
Works like a charm! :+1:

**Comment by machisuji** [comment]
Then again, one thing: it always opens the the detail pane for the first work package in the list. Though I would've thought that [this line](https://github.com/opf/openproject/pull/2922/files#diff-68a0f92ab05a59c574f4d604e6848310R277) would make it so the pane is opened for the currently selected (via double click) work package.

Mind, it's not specified for which work package the pane is supposed to be opened.

**Comment by machisuji** [comment]
Though which work package's overview pane is opened is dependent on `$scope.preselectedWorkPackageId` just like when pressing the details pane button which triggers `#openLatestTab`. Said function also seems to always open the first work package.

So if it is indeed not the right work package it's out of scope of this PR and a general problem with `$scope.preselectedWorkPackageId`.

**Pull request merged**
