### PR TITLE
[42939] Project autocompleter is too wide in work package table

### PR DESCRIPTION
**Pull request by bsatarnejad**
Set min width for the table column including ng-select or an auto completer component, which is a project auto completer in this case.

https://community.openproject.org/projects/openproject/work_packages/42939/activity

### CODE REVIEW

**Review by HDinger — CHANGES_REQUESTED** [review]
The changes have not fixed the issue:
Bildschirmfoto 2022-07-11 um 13 47 11

I assume that this is due to the long placeholder text. Since this only happens in the project field and nowhere else, I suspect that there is something special about the field. Spontaneously I noticed that all other fields show directly the current value instead of a placeholder. I think it's worth trying to do that for the project field as well, instead of setting a minimum width that is too big or too small depending on the language anyway.

**Comment by bsatarnejad** [comment]
> The changes have not fixed the issue: Bildschirmfoto 2022-07-11 um 13 47 11
> 
> I assume that this is due to the long placeholder text. Since this only happens in the project field and nowhere else, I suspect that there is something special about the field. Spontaneously I noticed that all other fields show directly the current value instead of a placeholder. I think it's worth trying to do that for the project field as well, instead of setting a minimum width that is too big or too small depending on the language anyway.

Hi @HDinger  thanks a lot! The difference here is that other fields are using create-autocompleter while we have a seperate component for project field named project-autocompleter and it is using op-autocompleter that has a placeholder. For auto completers we had the same problem before: https://community.openproject.org/projects/openproject/work_packages/39833/activity

**Comment by HDinger** [comment]
> Hi @HDinger thanks a lot! The difference here is that other fields are using create-autocompleter while we have a seperate component for project field named project-autocompleter and it is using op-autocompleter that has a placeholder. For auto completers we had the same problem before: https://community.openproject.org/projects/openproject/work_packages/39833/activity

I don't know if that is really the same issue, as the mentioned ticket refers to the split screen and not the table. I am aware that there are different components being used, but nevertheless it would make sense in my eyes to show the currently selected project in the search field instead of a placeholder like we do it in the other table fields. If that fixes the issue -  great, if not - we will have to dig deeper for the reason. 
Please keep in mind, that these changes only apply for the `project-autocompleter` in the `project-edit`-fields and not for all autocompleters in general.

**Comment by HDinger** [comment]
Closing in favour of https://github.com/opf/openproject/pull/11030

**Pull request closed without merging**
