### PR TITLE
Add quiet_assets to mute assets pipeline logging

### PR DESCRIPTION
**Pull request by myabc**
Enabled in development environment only.

### CODE REVIEW

**Comment by mfrister** [comment]
:+1:

**Comment by myabc** [comment]
Even doing front-end development, I seldom find asset request logging in development useful. Worse, it obscures important requests.

**Comment by linki** [comment]
:heart: :heart: :heart:

**Comment by linki** [comment]
@myabc would you care to also add `config.quiet_assets = true` to the config files so it's easier to re-enable asset logging in case someone needs it?

or a commented out `# config.quiet_assets = false`

see https://github.com/evrone/quiet_assets#usage

**Comment by mfrister** [comment]
@linki Doesn't commenting out the Gem in the Gemfile have the same effect and needs the same effort?

**Comment by myabc** [comment]
:+1: for @linki's suggestion. 

@meeee is a less-obvious and clumsier solution IMO. A dirty `Gemfile.lock` in a repo is always an annoyance, and inevitably there is always a developer that inadvertently commits it.

**Comment by mfrister** [comment]
@myabc Good point, didn't think about Gemfile.lock. Then I also like @linki's suggestion :+1:

**Comment by tessi** [comment]
:green_heart: :heart: :green_heart:

**Comment by linki** [comment]
:heart_eyes:

**Comment by ulferts** [comment]
:+1:

**Pull request merged**
