### PR TITLE
actually allow disabling ssl in production

### PR DESCRIPTION
**Pull request by linki**
`false` in an env var evaluates to true

we should rather create a production-like environment (e.g. called `staging`) that's mostly `production` but differs slightly. i.e. enable cache classes, compile assets but disable ssl, serve assets by rails, debug log level etc.

### CODE REVIEW

**Comment by ulferts** [comment]
@linki there will probably be a problem when taking the information directly out of the configuration.yml. Because then the value will probably be a boolean and `true == 'true'` is `false`

**Comment by linki** [comment]
right, damn it

**Comment by linki** [comment]
staging env like https://github.com/finnlabs/concierge/pull/92 (internal)

**Comment by linki** [comment]
i don't want to add more piece of crap code to openproject, so let's close and revert this whole force ssl thing. let me think about other solutions to this problem. currently, we only need it for some internal setup and i guess the community isn't disabling ssl in production either.

**Comment by NobodysNightmare** [comment]
> i don't want to add more piece of crap code to openproject, so let's close and revert this whole force ssl thing.

@linki So how do we proceed with this PR?

**Comment by NobodysNightmare** [comment]
closing this PR.

Please re-open it if you think this was at fault.

**Pull request closed without merging**
