### PR TITLE
17350 not possible to display more than one timeline via wiki macro

### PR DESCRIPTION
**Pull request by hschink**
[`* `#17350` Not possible to display more than one timeline via wiki macro`](https://community.openproject.org/work_packages/17350)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://hotfix-17350-not-possible-to-display-more-than-one-timeline-via.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@hschink Strangely, I wasn't able to produce the console errors mentioned in the WP on `dev`, but one error does appear on this branch.

seeded_project_-_seed_-_openproject

**Comment by hschink** [comment]
@myabc can you give me a hint how to reproduce that? Thanks a lot!

**Comment by ulferts** [comment]
@myabc, any update on this for @hschink?

**Comment by ulferts** [comment]
My local test indicate that it is running now. At least it is running better than before where it was not running at all. Given the shear amount of possible paths however, I can not vouch for it to run completely. But as it is better than before, I am willing to live with that.

**Pull request merged**
