### PR TITLE
[20447] Add required to timelog fields

### PR DESCRIPTION
**Pull request by oliverguenther**
Timelog was missing some required option for fields.

https://community.openproject.org/work_packages/20447/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-fix-20447-timelog-required-fields.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://oliverguenther-fix-20447-timelog-required-fields.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Those seem all legit, @oliverguenther but I am wondering as to why the WorkPackage's ID is not a mandatory field.

Really not part of the original WP but I believe the ID field should be required, too.

**Comment by oliverguenther** [comment]
You can actually log time without an association to the work package through the toolbar item `Log time` on the time sheet of a project, e.g., `/projects/demo-project/time_entries`.

In there, the work package is optional. As they both share the same view, we could pass a flag when the context is a work package to make the field mandatory in that case.
Should that happen in this PR?

**Comment by ulferts** [comment]
> You can actually log time without an association to the work package through the toolbar item

Didn't know that @oliverguenther. In that case, I think it should be in a separate WP and PR.

**Pull request merged**
