### PR TITLE
[37404] Remove fixed height of ng-select container

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.org/wp/37404

### CODE REVIEW

**Comment by oliverguenther** [comment]
Also fixes height part of https://community.openproject.org/wp/37261

**Review by b12f — COMMENTED** [review]
Can you make this `min-height` instead maybe? I added this so all kinds of input fields have the same height.

**Comment by oliverguenther** [comment]
> Can you make this `min-height` instead maybe? I added this so all kinds of input fields have the same height.

Done. I also had to set a line-height to the placeholder, which is only shown when the select is empty (so at min-height) and this appears to fix both issues. Let me know what you think

**Review by b12f — APPROVED** [review]
LGTM

**Pull request merged**
