### PR TITLE
Only sortable columns will now have option to sort in UI.

### PR DESCRIPTION
**Pull request by manwithtwowatches**
https://www.openproject.org/work_packages/9836

### CODE REVIEW

**Comment by ulferts** [comment]
fails

just a pointer for notification

**Comment by tilt** [comment]
@manwithtwowatches CI's red here unfortunately

**Comment by manwithtwowatches** [comment]
i know. i'm trying to understand why that test is failing.

**Comment by tilt** [comment]
why did you close it? I can fix the tests, I mean I could do so now

**Comment by manwithtwowatches** [comment]
i got confused and forgot that there was other stuff in this PR. hold on i'll rebase on dev and make another PR.

**Pull request closed without merging**
