### PR TITLE
15160 fixed work packages table header

### PR DESCRIPTION
**Pull request by myabc**
https://www.openproject.org/work_packages/15160

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-15160-fixed-work-packages-table-header.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
Removing WIP – not because this PR isn't without some issues – but because it's ready for some thorough review.

**Comment by ulferts** [comment]
@myabc, having taken a look at it I am impressed at how far this has progressed.

I have noticed the following issues up until now:
- Sometimes<sup>TM</sup> (haven't been able to nail it down) the column header dropdown arrows are not positioned correctly on loading the page. 
- Sometimes<sup>TM</sup> the rightmost column header dropdown arrows are positioned too much to the right. This will cause an unnecessary horizontal scrollbar.
- Some actions where content is added/removed to/from the page are not handled yet. The arrows are not repositioned.
  - Opening/removing the details pane
  - Opening/collapsing the project menu
  - Adding/removing columns
- Some columns are wider than they need to be.
- Some columns are smaller than it is looking good. This applies to columns lacking values.
- The gray bar for the overall sum is not wide enough when the details pane is opened.
- The vertical scrollbar is hidden behind the details pane if the pane is open. Not sure if it is a good idea to move the scrollbar to the left.

**Comment by myabc** [comment]
@ulferts 

> The vertical scrollbar is hidden behind the details pane if the pane is open. Not sure if it is a good idea to move the scrollbar to the left.

If we want columns to be horizontally scrollable, then this isn't possible.

**Comment by lindenthal** [comment]
https://www.openproject.org/work_packages/15160

**Comment by myabc** [comment]
@ulferts 

> Opening/collapsing the project menu

what do you mean by project menu?

I believe I've now either dealt with, or commented on, all of the issues you raised. If you could take another look, that would be great.

**Comment by ulferts** [comment]
>  Opening/collapsing the project menu
> what do you mean by project menu?

image
This seems to be not handled as of now.

On columns with small width, sorting by them breaks the layout:
image

Granted, this might not be the most important case here: When having the details pane open and a lot of columns active and then remove the columns, the remaining columns are distributed again to take up the remaining space. In its extreme, this leads to a very very wide column:
image
Can we recalculate the table width upon column deletion/adding?

**Comment by myabc** [comment]
@ulferts 

> This seems to be not handled as of now.

No, it's not. It's not entirely straightforward, as non-Angular code will need to broadcast an event. Best/cleanest solution would be to rework navigation as an Angular directive.

> Can we recalculate the table width upon column deletion/adding?

we should be doing that already.

**Comment by ulferts** [comment]
> No, it's not. It's not entirely straightforward, as non-Angular code will need to broadcast an event. Best/cleanest solution would be to rework navigation as an Angular directive.

Can't we for the time being simply call the broadcasting within non angular code?

image

From what I see, column width is calculated after a column is removed but not table width. In the screenshot, the table would fit inside the visible area with ease but does not because the table width is not reduced. 

I don't want to be nagging, it's not a big issue, so if it would be to hard to do, let's talk.

**Pull request merged**
