### PR TITLE
[21327] long words destroy headline in timelines package overview

### PR DESCRIPTION
**Pull request by HDinger**
set the overflow values so that the headline will be punctuated

https://community.openproject.org/work_packages/21327

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21327-long-words-destroy-headline-timelines-package.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21327-long-words-destroy-headline-timelines-package.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by basiszwo** [comment]
Did you test this in IE, Safari, Chrome and Firefox?

**Comment by HDinger** [comment]
I tested Safari, Chrome, Opera and Firefox and it worked fine there.

**Comment by basiszwo** [comment]
Should be checked in IE as well. Probably more important than Opera :smile:

**Comment by NobodysNightmare** [comment]
I'll have a look at IE 11...

**Comment by NobodysNightmare** [comment]
Correct display in Chrome:

image

Not so correct display in IE11:

image

Still I agree that this is the mother of all edge cases:
- you do not simply need a long subject, multiple words will wrap just fine...
- you need a subject with a single word so long, that you can't even imagine how long it needs to be...

I agree that technically this does not work in Internet Explorer... Still I am not sure how much pain (including a solution that is generally worse, but works in IE) we want to take for this edge-case.

Talking of edge-cases, I did not test it in [edge](https://de.wikipedia.org/wiki/Microsoft_Edge)!

**Comment by basiszwo** [comment]
I think this should work in IE 10+ too.

**Comment by NobodysNightmare** [comment]
@ulferts Came with a great argument: This is the work package legacy view! The one we want to delete for OpenProject 5.0...

@basiszwo Does that change anything? Still don't know why this WP is still aiming for a post 5.0 release...

**Comment by HDinger** [comment]
Since the plan is to remove the rails-based view as part of 5.0, this bug won't be followed any longer. Thus this PR can be closed.

**Pull request closed without merging**
