### PR TITLE
remove description warning from CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by marutosi**
**GitHub is proprietary**. If GitHub stops service, we will lost
descriptions and discussions on GitHub.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-4-1-contributing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-4-1-contributing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
You do realize you are effectively DOSing our Travis infrastructure with you multitude of PRs?

**Comment by marutosi** [comment]
It is non sense.

My PR rate is ordinary for active **opensource** project.

If you feel travis is slow,
why do not you use and publish your **internal CI infrastructure** ?
https://github.com/opf/openproject/commit/239a68cb9c1e1fa5d04b5f0275eed3049f578337

You should run ruby 1.9, 2.0, 2.1 and 2.2.
Why do you run only 2.1?

**Comment by floriank** [comment]
> My PR rate is ordinary for active **opensource** project.

Your PR rate _today_ was quite extraordinary. Reopening the same PRs again and again against the recommendations of the team was quite a feat (triggering TravisCI Pr runs for each one). Some would consider this trolling. Others would consider it childish.

> You should run ruby 1.9, 2.0, 2.1 and 2.2.

I concur.

> Why do you run only 2.1?

Because right now we do not have the resources to check, review and maintain openproject with our limited resources. There is, after all a team behind openproject working here @finnlabs.

> why do not you use and publish your **internal CI infrastructure** ?

Because our internal CI is used to run different plugin configurations for openproject for different customers Customers usually use one version of ruby and particular database setups. The current solution is not ideal and we do know that, however, we are still bound to a business reality we can't just throw out the window. 

---

I highly recommend that if you have problems with us or the prcesses here opf/openproject, you'd consider talking to us directly. We have a [Gitter channel](https://gitter.im/opf) and at least some of us are reachable on Twitter, e.g. [myself](http://twitter.com/carhillion) or [@myabc](https://twitter.com/myabc)

**Comment by marutosi** [comment]
> Reopening the same PRs again

Because contributor cannot reopen PR closed by **stupid** repository owner.

**Comment by floriank** [comment]
Your original PR (#3040) containing all the commits you want to add is still open. You know that, do you?

**Comment by marutosi** [comment]
You said GitHub UI is unusual and terrible, so I open separate PRs.

**Comment by marutosi** [comment]
You said "Please write description" many times. So I write a description on PRs.
Am I wrong?

**Comment by floriank** [comment]
> You said GitHub UI is unusual and terrible,

Did I? Refresh my memory here, I did a quick search and found nothing of the sort. I personally like the Github UI. Others may think different, but that does not change the fact that we conduct our Reviews through this interface. 

>  so I open separate PRs.

We asked you to group your commits into a PR when they logically belong to the same topic (e.g. `sqlite` support). We also told you in the past that force-pushing and opening a multitude of small PRs effectively kills our TravisCI runs, as we do not have unlimited resources there.

> Please write description

Yep, we told you that, it's also in the contribution guidelines. You can use other PRs by other contributors as examples for good descriptions, **most**\* of them are very good, weighing advantages and disadvantages of the changes they propose. I'd expect the same from you.

*Before you go and find evidence, I know that there are very small PRs that do not have a description.

**Comment by marutosi** [comment]
> We asked you to group your commits into a PR

Huh?

I wrote "descriptions" at each revisions commit logs.
So, I said "See commit logs".

What is "description" of group commits?

**Comment by floriank** [comment]
> So, I said "See commit logs".

There is a difference between the description of each commit and the PR description. The PR description should contain a general overview of _what_ your trying to do (e.g. "support SQLite") and why you are doing it (e.g. "SQLite would make it easier to run tests"). It is different from the description from the description of each commit.

We will discuss the points in the PR to weigh benefits and disadvantages.

> What is "description" of group commits?

I think you mean the description of the PR - which is just a fancy name for a branch we can discuss.

---

I also wonder why your English is so much better in the Redmine community.

**Comment by marutosi** [comment]
> The PR description should contain a general overview of what your trying to do

It should be on workpakage.
https://community.openproject.org/work_packages/13974

So, description is simple  link.
Am I wrong?

**Comment by floriank** [comment]
Could be. You can use the PR and the ticket in OP. whatever works better for you.

**Comment by marutosi** [comment]
Do you agree PR description can be empty if workpackage does not exist?

**Comment by floriank** [comment]
If a work package does not exist for a problem (which can happen), the PR should have a description of what it does and why, even if the individual commits contain messages explaining what they do.

**Comment by marutosi** [comment]
> Did I? Refresh my memory here, I did a quick search and found nothing of the sort. I personally like the Github UI.

https://github.com/opf/openproject/pull/3109#issuecomment-110648935

**Comment by marutosi** [comment]
> Reopening the same PRs again and again against the recommendations of the team was quite a feat (triggering TravisCI Pr runs for each one)

As I described at https://github.com/opf/openproject/pull/3154#issuecomment-113480502 ,
this is travis defect.

**Comment by marutosi** [comment]
> this is travis defect.

I have created https://github.com/travis-ci/travis-ci/issues/4114 .

**Pull request closed without merging**
