### PR TITLE
update codeclimate-test-reporter version

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-0-codeclimate-test-reporter-update.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-0-codeclimate-test-reporter-update.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
@myabc didn't we remove the codeclimate test reporter yesterday?

**Comment by myabc** [comment]
@floriank no, not yet. CodeClimate coverage reporting been inactive for quite some time though (since 57ec29eaa3f67f271561e0d2d980610c942691f0) because of this issue: https://github.com/codeclimate/ruby-test-reporter/issues/49

**Comment by myabc** [comment]
@floriank we could merge #2573, once @marutosi fixes tests. It'd be nice to find a replacement service though - perhaps worth taking another look at https://coveralls.io/ / @linki

**Pull request closed without merging**
