### PR TITLE
Fix mobile scrollable tabs

### PR DESCRIPTION
**Pull request by b12f**
Scrollable tabs were not scrolling anymore, causing overflow issues across the page.

Closes https://community.openproject.org/projects/openproject/work_packages/39123/activity?query_id=2881

### CODE REVIEW

**Review by HDinger — CHANGES_REQUESTED** [review]
With this implementation you show a scrollbar within the tabs. This might not be super critical on Mac OS where the scrollbar vanishes when not needed, but it is on windows as the permanently visible scrollbar looks really ugly when compared to how it was before.
Bildschirmfoto 2021-10-25 um 13 27 21

For comparison, this is how it looked before (and how it still should look like in the end imho):
scolling
**Note** no scrollbar and arrows at the end.

**Comment by b12f** [comment]
@HDinger this is a test mention

**Review by oliverguenther — APPROVED** [review]
~~Looks good to me, thanks for the efforts. I would have expected the spec renames to be of the sort `expect_notification` => `expect_toast`, but it is `expect_toaster`? What is the difference in `toast` vs `toaster`?~~

Sorry, wrong PR

**Comment by b12f** [comment]
ah that's an old rename, I can change that

**Comment by b12f** [comment]
Last comments refer to https://github.com/opf/openproject/pull/9765

**Review by oliverguenther — CHANGES_REQUESTED** [review]
As mentioned, the scrolling does no longer work as referenced in the video of Henriette.

**Review by HDinger — CHANGES_REQUESTED** [review]
I am really sorry, but in my eyes this is step back with regards of UI. There are multiple things that bother me:
* The scrollbar looks super heavy as it has nearly the same height as the text. Especially in the Wp view, this looks rather ugly.
* The fading effect in the end is only useful, if there is text faded out. Depending on the screen size, users will miss it. For example, here there are 4 more entries, which I don't see at all:
Bildschirmfoto 2021-11-09 um 09 07 49
* When it comes to accessibility, users who rely on the keyboard, also have a hard time as they can tab to the elements but don't see what they are selecting.

**Review by HDinger — CHANGES_REQUESTED** [review]
Thanks for your patience @b12f ! I think we are almost there, I just found issue: On the split screen, the icon to go to full view or close the split screen are missing. Could you please check that?
Bildschirmfoto 2021-11-10 um 14 23 35

**Pull request closed without merging**
