### PR TITLE
[25070] Quick wins design timelines view and split view

### PR DESCRIPTION
**Pull request by HDinger**
This makes design changes on the WP page. For details have a look at the according WP.

https://community.openproject.com/projects/gmbh/work_packages/25070/activity

### CODE REVIEW

**Comment by HDinger** [comment]
### Before
bildschirmfoto 2017-04-28 um 15 56 34

### AFTER
bildschirmfoto 2017-04-28 um 15 52 24

### BEFORE
bildschirmfoto 2017-04-28 um 15 56 28

### AFTER
bildschirmfoto 2017-04-28 um 15 52 43

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c4f4d56affeabb5f06546afc4cd64196ed5f44b8) (deployed commit: d2a57a36505372721e3eacaa83570877c89d73d4).

**Comment by oliverguenther** [comment]
LGTM code-wise. @lindenthal Does this match your specs?

**Comment by lindenthal** [comment]
Let's create a separate PR for the remaining topics.

**Pull request merged**
