### PR TITLE
Fix replacing references of presenter_id

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.org/work_packages/57986

### CODE REVIEW

**Comment by oliverguenther** [comment]
The failing spec is unrelated

**Review by cbliard — APPROVED** [review]
Nice. I tested it and it works.

Then I added a few commits instead of adding review comments to
- fix rubocop warning
- remove leftover shared example in the original file
- make test (hopefully) easier to read by removing the need to specify `created_at` and `updated_at` attributes, and removing `author_id: principal.id` attribute as it would have been overwritten anyway.
- add a test for Journal::MeetingAgendaItemJournal#author_id

If these changes are ok for you, feel free to merge it.

**Comment by cbliard** [comment]
And we could also rewrite the shared example to replace this output:
```
    with WorkPackage
      behaves like rewritten record
        for work_package
          when author_id is set to the replaced user
            replaces its value
          when author_id is set to a different user
            keeps its value
      behaves like rewritten record
        for work_package
          when assigned_to_id is set to the replaced user
            replaces its value
          when assigned_to_id is set to a different user
            keeps its value
      behaves like rewritten record
        for work_package
          when responsible_id is set to the replaced user
            replaces its value
          when responsible_id is set to a different user
            keeps its value
    with CostQuery
      behaves like rewritten record
        for cost_query
          when user_id is set to the replaced user
            replaces its value
          when user_id is set to a different user
            keeps its value
    with Notification actor
      behaves like rewritten record
        for notification
          when actor_id is set to the replaced user
            replaces its value
          when actor_id is set to a different user
            keeps its value
```

with this output
```
    with WorkPackage
      replaces user references found in #author_id
      replaces user references found in #assigned_to_id
      replaces user references found in #responsible_id
    with CostQuery
      replaces user references found in #user_id
    with Notification
      replaces user references found in #actor_id
```

But I refrained from doing it because it may push things a little too far.

**Comment by oliverguenther** [comment]
Thanks @cbliard , I like the change. If you have it prepared already, could you submit this to `dev`? I'll go ahead and merge this so we can get 14.5.1 out

**Comment by cbliard** [comment]
Sure, will do 👍

**Comment by cbliard** [comment]
I give up on it. The code needed to get it looking like what I posted is a bit too convoluted. I'll keep it in a local branch in case I have an idea about how to make it work.

**Pull request merged**
