### PR TITLE
Fix hidden display of participants dialog

### PR DESCRIPTION
**Pull request by oliverguenther**
The participants dialog is called from multiple places, but it was rendered inside a DOM element that is hidden for desktop. A test was also missing for desktop, preventing the error from being found in the first place

https://community.openproject.org/work_packages/54148

### CODE REVIEW

**Review by HDinger — CHANGES_REQUESTED** [review]
The modal is opened correctly. 👍 

On mobile, there is currently also the "Add participants" button shown:
Bildschirmfoto 2024-04-15 um 13 08 11

Before, there was a link "Show all"


Bildschirmfoto 2024-04-15 um 13 08 47

**Comment by HDinger** [comment]
Can we then also get rid of this file https://github.com/opf/openproject/blob/dev/modules/meeting/app/components/meetings/sidebar/details_component.sass ?

**Review by HDinger — COMMENTED** [review]
The mobile link still looks different than before (bold and black instead of normal and blue). I don't know if that is desired by the product team, but I am fine with merging this and tackling that separately.

**Comment by oliverguenther** [comment]
> The mobile link still looks different than before (bold and black instead of normal and blue). I don't know if that is desired by the product team, but I am fine with merging this and tackling that separately.

I simply missed that. Fixed it and double-checked it looks as before now

**Pull request merged**
