### PR TITLE
Revert/breaking changes

### PR DESCRIPTION
**Pull request by ulferts**
Reverts two merges which lead to to a lot of test failures. 

We should fix the failures before starting a new attempt to get it into dev.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-revert-breaking-changes.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ulferts-revert-breaking-changes.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Not sure if I that fixes all the failures now. I'll let travis take a look at it.

**Comment by ulferts** [comment]
FYI @furinvader

**Comment by oliverguenther** [comment]
You seem to have caught them all. Had to restart one job, but that was only running indefinitely after the job reported successful completion of the tests.

**Pull request merged**
