### PR TITLE
Expose aggregate module in components

### PR DESCRIPTION
**Pull request by oliverguenther**
For use in plugins. If you want to import it, write, e.g.:

`import {WorkPackageResource} from 'core-components';`

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-housekeeping-ts-module-exports.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://oliverguenther-housekeeping-ts-module-exports.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@oliverguenther not sure if I want to merge this based on my experiences. I don't think that what is done here is wrong but something seems to be missing which does not allow to specify more than one export in the `index.ts`

**Comment by oliverguenther** [comment]
We can exclude the index.ts for now since I have no clue where that issue exactly originates from, but should at least merge the webpack config changes, since that resolves the wall of TypeScript warnings when using plugins.

**Comment by oliverguenther** [comment]
I've rebased this to change only the webpack config. It avoids huge typescript warnings such as in https://s3.amazonaws.com/archive.travis-ci.org/jobs/134033763/log.txt

**Pull request merged**
