### PR TITLE
Getting ready for Teatro

### PR DESCRIPTION
**Pull request by semenyukdmitry**
Hey!

I am developer at Teatro.io and I want to offer you our service — it automatically creates a staging server for each opened pull request.

Teatro.io is free for open source projects — some large projects like GitLab (https://github.com/gitlabhq/gitlabhq/pull/7140 ), ErrBit (works out-of-the-box, @ndbroadbent approved Teatro), Rails Admin (https://github.com/sferik/rails_admin/pull/2029) and others are already using Teatro as free stage servers.

Here's URL of Teatro stage server for my fork of OpenProject: http://teatro.semenyukdmitriy-openproject-c0cbbd9c72a820fede1e.ttrcloud.com/. Awesome, isn't it?

When you connect project to Teatro, we'll automatically post a comment (via @TeatroIO) with like to unique stage server that was made for this specific branch (see https://github.com/semenyukdmitriy/openproject/pull/1 for example).

To use Teatro you need:
— sign in using Github account on http://Teatro.io
— add your project

**Benefits**:
— demo for new users (always up to date!)
— the way to test changes: each Pull Request gets separate stage server
— FREE for open source!

Have any questions? — Post a comment.

### CODE REVIEW

**Comment by myabc** [comment]
I'm not the (only) decision maker here, but definitely a cool idea.

**Comment by tessi** [comment]
Looks great!



I'd give it a try. Are there any objections?

**Comment by tessi** [comment]
@semenyukdmitriy at https://teatro.io/pricing I read that the number of stages (PullRequests for which you have a running staging server) is limited. Is that right? What would be the limit for OpenSource projects?

**Comment by semenyukdmitry** [comment]
@tessi No limits for open source.

**Comment by tessi** [comment]
Thanks @semenyukdmitriy

**Comment by mfrister** [comment]
Deactivating until someone fixes the secret token problem:

```
Application.initialize!... Error: secret_token empty!
Please set it with ENV variable 'SECRET_TOKEN' or 
run 'rake generate_secret_token'
Exiting
```

**Comment by semenyukdmitry** [comment]
@meeee seems like it's because of non-standard name of main branch (`dev` instead of `master`); we hardcoded `master`.

**Comment by mfrister** [comment]
@tessi kindly provided a fix and reenabled Teatro: #1690 

Teatro should work for PRs now. An option to change the default branch would be great nevertheless :)

**Pull request merged**
