### PR TITLE
[23289] [Accessibility] Focusverlust nach dem Speichern eines Eintrags

### PR DESCRIPTION
**Pull request by HDinger**
This sets the focus if a field in the wp table is submitted.

https://community.openproject.com/work_packages/23289/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-23289-focusverlust-nach-dem-speichern-eines-eintrag.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-23289-focusverlust-nach-dem-speichern-eines-eintrag.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
@HDinger Can you rebase this on the current dev? It should resolve the travis failures.

**Comment by HDinger** [comment]
Done. However there are still some issues with the internet explorer left before this can be merged. @romanroe Did you make any progress here? Is it because of the IE or my virtual machine?

**Comment by romanroe** [comment]
@oliverguenther I get a 403 when I try to open https://community.openproject.com/work_packages/23289/activity Any idea?

**Comment by oliverguenther** [comment]
@romanroe Any news on your end regarding the IE issue?

**Comment by oliverguenther** [comment]
In my VM. IE11 seems to sometimes lose focus to outside the windows (and focuses the toolbar instead). I'm not sure whether we can fix this, as your approach is definitely correct.

**Comment by romanroe** [comment]
@oliverguenther So it might be IE randomly (???) focus UI elements, right? At least that's the way it looked to me :-/

**Pull request merged**
