### PR TITLE
Remove HALAPIResource-based Work Package usages

### PR DESCRIPTION
**Pull request by oliverguenther**
Since we now have good integration of the WorkPackageResource in all parts of the details and full view, we can remove the legacy HALAPIResource implementation.

This is working towards removing the last copypasta in details and show controller. However, it is not contained in this PR, but is made much simpler since we no longer use two types of resources.

**TODOS**
- [x] Remove the workPackage HALAPIResource usages
- [x] Fix npm test usages of the HALAPIresources
- [x] Add separate resource for User type
- [x] Re-Use wp-edit-wiki-textarea module for the comment field.
- [x] Remove  `workPackageRefreshRequired` events which now are only a thin wrapper around the cache subscription. Most controllers subscribe themselves already.
- [x] Comments are not yet loaded automatically
- [x] Rename `workPackageResource` that was used for identifying the new resource when the cache service was introduced to show/details a few weeks back
- [x] Dropping an attachment on the description uploads and inlines it, but doesn't reload the attachment list https://github.com/opf/openproject/pull/4605/commits/4a58534c63fbef89992acfcb927014b04c4d226c

**Review comments**
- [x] No link in author. Caused by missing association of `user` link to UserResource (I thought this would have been possible through a `type`d link?) https://github.com/opf/openproject/pull/4605/commits/d3d205e297b40a17d040dedc3808d0d09fba0384
- [x] Reload activities after saving the WP. https://github.com/opf/openproject/pull/4605/commits/d3d205e297b40a17d040dedc3808d0d09fba0384
- [x] Removing attachments updates the attachment list https://github.com/opf/openproject/pull/4605/commits/f982288511781e9628bf739bcbdb70293b570842
- [X] Comment field styling https://github.com/opf/openproject/pull/4605/commits/dec29734a48fd55edba8d9770dd1c8dae82d4882
- [x] Comment field accessibility https://github.com/opf/openproject/pull/4605/commits/080a4b6ae5b020e5cb8ed24a3e3963fa6c7bdf43
  - [x] Title has been replaced with aria-label to avoid duplicate reading
  - [x] Save button is correctly enabled/disabled
- [X] Copy menu item visibility https://github.com/opf/openproject/pull/4605/commits/3e829bcb94ce3310b24967bd06f8129c9d3a9c3d
- [x] Activity numbering https://github.com/opf/openproject/pull/4605/commits/f0467138ecc82ae65e7b75f042250452ec2b3364
- [x] Adding an attachment does not update the activity list https://github.com/opf/openproject/pull/4605/commits/bc200d3f63aa7a89638b7d841aed818354f046a2
- [x] Removing an attachment does not update the activity list https://github.com/opf/openproject/pull/4605/commits/640ccbc6eb5f9a7bc6f6d81de82de2d0875686a5

**Out of scope**
- Remove unused styles. We have a large overlap between new and old inline/inplace styles so it's error prone to remove that on my own.
- Attachment in wp-new is broken. It's also broken on dev. Ticket: https://community.openproject.com/projects/openproject/work_packages/details/23592
- The "watch"/"unwatch" icon is not updated when the current user is removed/added to the list of watchers (Could be separated from this PR as it is tracked in https://community.openproject.com/work_packages/23585/activity)
- Global wp create still throws error (https://community.openproject.com/work_packages/23595/activity)
- Braces still shown in preview when description is empty https://community.openproject.com/work_packages/23584/activity

Fixes:
https://community.openproject.com/work_packages/23156
https://community.openproject.com/work_packages/23157
https://community.openproject.com/work_packages/23604

Lays foundation for:
https://community.openproject.com/work_packages/20417

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-housekeeping-remove-old-code.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://oliverguenther-housekeeping-remove-old-code.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
There is no link on a comment's author as there is in dev:
image

**Comment by ulferts** [comment]
Showing attachments without having to press "show all" seems to be fixed :+1:

image

**Comment by ulferts** [comment]
The bug that when I press "+ New work package" while being on a work package having attachments leading to the attachments being displayed as if they where uploaded for the new work package still exists. But this does not have to be fixed in the current PR.

**Comment by ulferts** [comment]
The activities are not reloaded after an edit is done. By that, the activities do not reflect the changes made to the work package until the work package is reloaded.

**Comment by ulferts** [comment]
Removing attachments does not update the list of attachments on the work package. When pressing on the trash bin, the confirm dialog is displayed, when confirming deletion, the backend request is processed, but the attachment does not get removed from the list.

**Comment by ulferts** [comment]
image

The design is slightly of:
- The bottom padding/margin is missing
- The placeholder text is not italic

**Comment by ulferts** [comment]
The comment field has the following accessibility flaws:
- When tabbing into the field for adding a comment, the screen reader reads "Click to add a comment click to add a comment link"
- When tabbing to focus the "Save" checkmark below the add comment field, the screenreader reads "Comment save link disabled" even when I have written something into the field and the link is no longer displayed as disabled.

**Comment by ulferts** [comment]
The attachment d'n'd feature does no longer set the correct text in the description field.

**Comment by ulferts** [comment]
The "Copy" menu item is not displayed when triggering the details pane from the wp-list and even after moving on from there to the full view. It is displayed when opening those two views with deep links.

**Comment by ulferts** [comment]
image

The activities are not numbered.

**Comment by oliverguenther** [comment]
@ulferts Thanks for the thorough click-through. I believe I have addressed all your issues (I've linked all respective fix-commits in the TODOs above).

> The bug that when I press "+ New work package" while being on a work package having attachments leading to the attachments being displayed

might be fixed due to my refactoring but I have not explicitly worked towards that. If it is not, I'd like to move it out of this PR.

**Comment by oliverguenther** [comment]
@ulferts I've noticed that attachments in create-mode aren't working. However, that appears to be true also on dev / edge. 

I've created a ticket at https://community.openproject.com/projects/openproject/work_packages/details/23592 and suggest we move it out of this PR.

**Comment by oliverguenther** [comment]
Since I really didn't want to reload the entire resource, I tried to be clever about reloading activities in the attachment directive. I believe we should provide some kind of frontend knowledge what links affect others as part of the Hal Cache. There, we can effectively purge the cache without explicitly reloading stuff.

@ulferts  That being said, it fixes the reloading of activities.

https://github.com/opf/openproject/pull/4605/commits/bc200d3f63aa7a89638b7d841aed818354f046a2

**Comment by ulferts** [comment]
I'll wait for Travis and merge it in then.

**Pull request merged**
