### PR TITLE
Create es.yml

### PR DESCRIPTION
**Pull request by sebadamus**
This is a spanish-latinamerican neutral translation (its not finished yet, I have taken en.yml as base file)

### CODE REVIEW

**Comment by sschu** [comment]
:thumbsup:

**Comment by sebadamus** [comment]
Mmm ok, how do I edit the file? cant get it with this github I never used :-(
Does it have to be aproved or something?

**Comment by relaxdiego** [comment]
Just curious if you guys considered [Transifex](https://www.transifex.com/plans/) for managing the localization files? They have an unlimited free plan for open source projects.

**Comment by tessi** [comment]
Thanks @sebadamus for your translations. you can edit the es.yml file in the github ui (within the branch of your pull request) or in your local checkout.

@relaxdiego, good point! I'm all in for using a translation tool/service. I started a [thread in the forum](https://www.openproject.org/boards/6/topics/108) (so we can merge this PR without ending the discussion).

**Comment by mfrister** [comment]
@sebadamus: I'm sorry for the late reply. When going to the [`es.yml` file in the `patch-1` branch](https://github.com/sebadamus/openproject/blob/patch-1/config/locales/es.yml) on your openproject fork and you're logged in, you should see an `Edit` button right above the contents of the file :)

**Comment by mfrister** [comment]
We now have OpenProject on the translation platform crowdin, feel free to contribue here:
https://crowdin.net/project/openproject

You could even upload your existing .yml file there and automatically get your previous translations.

**Pull request closed without merging**
