### PR TITLE
if we are logged out and do ajax, we can redirect to login page.

### PR DESCRIPTION
**Pull request by crijke**
This is a port of a recent change in the rails2-openproject-branch.

### CODE REVIEW

**Comment by tessi** [comment]
Is there a test for this feature?

**Comment by tessi** [comment]
BTW: I like the idea :thumbsup:

**Comment by nkenneweg** [comment]
I am not really sure how to test this.
You could of course test the correct API-Response-Status but testing the confirm window and the redirect to the login page seems difficult to me.

**Comment by tessi** [comment]
I think a cucumber test is the way to go here.

Is the confirm window a native browser window, or something in the DOM? When it's the later, cucumber should just work fine. For the former, it is probably possible too -- I just don't know how it is done.

**Comment by nkenneweg** [comment]
It is a native browser window and I also do not know how you can test those.

**Comment by tessi** [comment]
And again StackOverflow provides us the answer to our problem :)

http://stackoverflow.com/questions/2458632/how-to-test-a-confirm-dialog-with-cucumber/5002648#answer-5002648

Add <code>@javascript</code> to the cuke and use <code>page.driver.browser.switch_to.alert.[button_text]</code> in the step definition.

**Comment by nkenneweg** [comment]
@cnrk @tessi I added tests. This should be ready to merge.

**Comment by mfrister** [comment]
Travis thinks otherwise, apparently some API tests expect a 401, but they now get a 403.
Btw, "401 Unauthorized" seems more appropriate than "403 Forbidden" for not logged in users. In case we don't want to reveal whether a resource exists, we should use 404, like GitHub does for private repos when you're not logged in.

**Comment by nkenneweg** [comment]
Changed it back to a 401. some tests will still fail as they want to have basic auth.
I am still wondering because basic auth should not work anyhow, but it looks like it does for those tests. still investigating.

**Comment by nkenneweg** [comment]
@tessi @meeee This should be ready to merge. Failing tests are translation problems and not my fault.

**Comment by mfrister** [comment]
I think this wasn't ready for merge, but I should probably have commented here in addition to talking to @nkenneweg. The WWW-Authenticate header must be sent with 401 responses. See [HTTP RFC2626, 14.47 WWW-Authenticate](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.47).

@nkenneweg Could you make another pull request, which again adds the WWW-Authenticate header and the test for it?

**Comment by crijke** [comment]
also see https://www.openproject.org/issues/1141

**Comment by Nilos** [comment]
@meeee This feature is difficult. On the one hand we do not want to have a senseless login window but on the other hand we want to send a 401 which requires a WWW-Authenticate.
I would like to discuss two possibilities:
1. Add a WWW-Authenticate header but for a browser request set the method to something unknown (e.g. FORM)
2. Add a WWW-Authenticate header but for a browser request return a 200 OK and let the browser handle stuff.

I would prefer solution 1 but I am not sure browser will react to an unknown auth method with a login window anyhow. What is your opinion?

**Comment by mfrister** [comment]
As discussed, I would add something like a X-AuthenticationScheme: session header to browser requests. When the server encounters such a request and the session is timed out, it should respond with a 401 with a WWW-Authenticate set to session (I'm not sure whether realm or other parameters are mandatory).

**Pull request merged**
