### PR TITLE
Installing mysql2 gem errors on MacOS Mojave.

### PR DESCRIPTION
**Pull request by alireza-salehi**
https://gist.github.com/fernandoaleman/ee3ac6957c2ba4f7d7d33a251d58b191

### CODE REVIEW

**Comment by ulferts** [comment]
Hi @alireza-salehi,

thanks for the PR.

We discontinue supporting MySql in the next OpenProject release (10.0). It is already deprecated in 9.0. On that basis, I reject the PR. Sorry.

**Comment by alireza-salehi** [comment]
> Hi @alireza-salehi,
> 
> thanks for the PR.
> 
> We discontinue supporting MySql in the next OpenProject release (10.0). It is already deprecated in 9.0. On that basis, I reject the PR. Sorry.

if it is deprecated why there is a gem that we need to install before running project? please remove dependency in gem file if it is deprecated, because it prevents installing and debugging the project

**Comment by ulferts** [comment]
The current dev does not contain a mysql gem in its gemfile. Are you referring to a different location?

The 9.0 branch contains a mysql gem so people can still use it as it is only deprecated. Maybe you meant to issue your PR against that branch?

**Comment by alireza-salehi** [comment]
> The current dev does not contain a mysql gem in its gemfile. Are you referring to a different location?
> 
> The 9.0 branch contains a mysql gem so people can still use it as it is only deprecated. Maybe you meant to issue your PR against that branch?
my bad, i created PR on dev branch!
i'm working on 8.x and 9.x branch now, I will create another PR for 9.x branch then, thanks,

**Pull request closed without merging**
