### PR TITLE
Added Info for Enterprise Cloud to SAML Docs

### PR DESCRIPTION
**Pull request by ghost**
Added Info for Enterprise Cloud to SAML Docs

### CODE REVIEW

**Review by oliverguenther — APPROVED** [review]
LGTM, could you rebase this to release/12.1 @adam-op ? Thanks!

**Comment by ghost** [comment]
@oliverguenther the workflow with github desktop still allows this user error, which I am not able to solve without deleting the branch and recreating all my changes
please could you rebase it somehow? I am not aware how that works in github desktop
we must find out a method that the release/12.1 branch is selected by default in the 2nd screenshot of step 13:
https://www.openproject.org/docs/development/contribution-documentation/documentation-process/#step-13-create-a-pull-request

**Comment by ghost** [comment]
or just merge it to dev, and so what? :)

**Comment by oliverguenther** [comment]
Cherry-picked into release/12.1 in https://github.com/opf/openproject/commit/987f5e3437ced564ec6d18a262e66570e02e630d

**Pull request closed without merging**
