### PR TITLE
Corrections for:

### PR DESCRIPTION
**Pull request by nsalguero**
- https://community.openproject.com/projects/openproject/work_packages/26599/activity
  - https://community.openproject.com/projects/openproject/work_packages/26614/activity
  - https://community.openproject.com/projects/openproject/work_packages/27283/activity

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @nsalguero , thanks for your fixes! They are very appreciated.

I'm a bit very about this section here: https://github.com/opf/openproject/pull/6992/files#diff-2592f82506218b74a9c44fdfccf52a9fR33 Could you not use `CGI.escapeHTML(str)` instead to escape the entire string?

**Comment by nsalguero** [comment]
Hi,

In my tests, also escaping >, ' and ", like `CGI.escapeHTML(str)` does, and not only < and &, causes other problems during diff that I was not able to solve.  That is why I wrote `escape_some_html_entities` which only escape < and &.

Moreover, since each < is replaced by &amp;lt;, > in not interpreted as the end of an HTML tag.

**Comment by oliverguenther** [comment]
Tests are running locally fine with using `escapeHTML` instead. Could you check with your example whether https://github.com/opf/openproject/pull/6994 also works? If not , could you provide an example file or spec example to me where it breaks?

Thanks for your efforts!
Best,
Oliver

**Comment by nsalguero** [comment]
When using `escapeHTML`, if a diff contains a line where a < is replaced by a > for instance, the generated code will be `...<span>&l</span>t;...` for the old line and `...<span>&g</span>t;...` for the new line because the difference between &amp;lt; and &amp;gt; is only l replaced by g.

When using my `escape_some_html_entities`, in the same example, the generated code will be `...<span>&lt;</span>...` for the old line and `...<span>></span>...` for the new line.

Here is an example:
[changeset_r196_r195.diff.txt](https://github.com/opf/openproject/files/2764737/changeset_r196_r195.diff.txt)

**Comment by oliverguenther** [comment]
Thanks, that's just what I missed. It only affects the highlighted section. I fixed this over at #6994 and your diff now looks fine.

screenshot from 2019-01-17 08-31-22

Could you one more time confirm that PR works in your case as well?

Best,
Oliver

**Comment by nsalguero** [comment]
Hi,

With your latest modifications, I see double HTML encoding for the lines that do not have highlighting.  See:
before

The problem is solved with this patch (which also removes two methods I introduced and that are no more needed with your version):
[correct_double_html_encoding_for_lines_without_highlighting.patch.txt](https://github.com/opf/openproject/files/2767731/correct_double_html_encoding_for_lines_without_highlighting.patch.txt)
See:
after

Best regards,

Nicolas

**Comment by oliverguenther** [comment]
True, good point. I added the patch.

**Comment by oliverguenther** [comment]
Merged the other PR for now. Thanks for your efforts! :tada:

**Pull request closed without merging**
