### PR TITLE
[26420] Show additional attributes of work package attachments

### PR DESCRIPTION
**Pull request by HDinger**
Show attachments author and date.

https://community.openproject.com/projects/openproject/work_packages/26420/activity

### CODE REVIEW

**Comment by HDinger** [comment]
bildschirmfoto 2017-12-08 um 13 38 13

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/ae26ab3ecde3374a04163dd59e41ee947dd1d3e5) (deployed commit: b280dd026d20291521693be46931fa99c208902c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/207cd494ae9495485b869b79eef336f60e92bb74) (deployed commit: c072a6c500d659144f3180eede25fe4c196a8e2e).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/0c08ab6b89fd24ef6735b351ce3168d3107935be) (deployed commit: c072a6c500d659144f3180eede25fe4c196a8e2e).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4fb09a4a8d58930145315bd05ccdad70c0cfc345) (deployed commit: c072a6c500d659144f3180eede25fe4c196a8e2e).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/26e30719c27609057419807c40715fac2be923cb) (deployed commit: c072a6c500d659144f3180eede25fe4c196a8e2e).

**Pull request merged**
