### PR TITLE
[#43681] Include date alerts in notification settings

### PR DESCRIPTION
**Pull request by DmitryBash**
Include date alerts in notification settings
https://community.openproject.org/projects/openproject/work_packages/43681
https://community.openproject.org/projects/openproject/work_packages/44413

### CODE REVIEW

**Review by b12f — APPROVED** [review]
LGTM, tho it might be good if @bsatarnejad takes another look, as I've coded large parts of this myself

**Comment by bsatarnejad** [comment]
> LGTM, tho it might be good if @bsatarnejad takes another look, as I've coded large parts of this myself

Hi @b12f Everything looks fine! I have just a question, is it possible here to use spot-selector-field instead of using a checkbox and a label on notification settings page?

While the checkbox is unchecked, there should be a value selected in the select box?
Screenshot from 2022-10-26 13-47-54

And a minor issue is to replace 'Same day' with 'same day' based on its design.

**Comment by bsatarnejad** [comment]
Screenshot from 2022-10-26 14-02-38
As you see in the above picture from figma, there is a space around the options and the selected one on the select box.

But the space designed on the figma is not implemented, as you see below:
Screenshot from 2022-10-26 14-02-10

**Comment by bsatarnejad** [comment]
Hi @DmitryBash Thanks a lot! It looks really good!
I have some minor issues to fix based on the parent WP specifications:

> There is a check box labeled "Start date" (checked by default), with a drop down next to it with "1 day before" selected by default.
> There is a check box labeled "Finish date" (checked by default), with a drop down next to it with "1 day before" selected by default.
> There is a check box labeled "When overdue" (not checked by default), once checked, a drop down next the selection "everyday" selected appears.

So at the beginning, the Start Date and Finish Date check boxes should be enabled and their dropdowns should be visible and active.
The When Overdue check box should be unchecked and its dropdown should not be visible.

> Unchecking the checkboxes hides the drop-down.

While unchecking the checkboxes, the drop down is still visible, only disabled,but  it should be hidden.

Screenshot from 2022-11-03 12-46-24

**Review by dombesz — COMMENTED** [review]
@DmitryBash in order to verify the settings are saved correctly, some integration tests are required in the `spec/features/notifications/settings/date_alert_settings_spec.rb` file. (There are also some failing tests on the CI)

**Review by dombesz — APPROVED** [review]
LGTM 👍

**Pull request merged**
