### PR TITLE
Fix/non matching pagination

### PR DESCRIPTION
**Pull request by ulferts**
Fixes the problem of having too few work packages displayed on the work package list for the pagination size displayed. E.g. when [searching for the word 'schon' as an admin on community only 37 work packages are displayed but pagination shows it to be 50](https://community.openproject.org/projects/openproject/search?q=schon&work_packages=1) (as an administrator).

The reason for this is the usage of a query that works like this:

```
WorkPackage.where(id: query.results.select(:id)
```

where `query.results` leads to an sql statement that has `LEFT JOIN` on comments and attachments (two times).

If the string is found in multiple left joined records, the associated work package record is returned multiple times. 

Other options for fixing this would be to add a `distinct` on the selection or a `group(:id)` but both have their caveats:
* distinct: Postgresql requires to have every column in an ORDER BY present in the select if distinct is applied. This approach has been hackliy tried in  #9011 but found to risky. Doing it properly would require a lot of rework with uncertain results.
* group: While I currently do not know a scenario in which we use `GROUP BY` it might still be used later on and would then conflict with using it as a replacement for `distinct`.

This approach taken here means that further development needs to be on the look out for JOINs whenever multiple hits are possible.

### TODO 

* [x] Go through other filters using joins to double check them

https://community.openproject.org/projects/openproject/work_packages/35045

### CODE REVIEW

**Comment by wielinde** [comment]
Hey @ulferts, let me quickly sketch your solution here as a sketch was missing in the description above:

For filters that need to check data in related tables, such as comments and attachments, you don't join them anymore with the WP table. Instead you do sub-queries that check if there are hits in those related tables. That is elegant as you don't need to carry those related tables with you after that check. And it works as we don't need to provide information of the related tables with the query result. We only return WPs. 

I like that approach as it is pretty lean.

Questions that come up:

- If we ever want to return data from the related table it'll get trickier. But that is not the case, right?
- What other filters will need a rewrite? WP relationship filters (follows, precedes, includes, ...)?
- What about the "Includes" counter column?
- has BCF issue

**Comment by ulferts** [comment]
@wielinde I went through the other filters and they are looking fine. Most use the same pattern (well an `id IN` instead of `EXISTS`) we now use for the search filter. The bcf_issue filter is an exception but since a work package can only have one bcf_issue this should be safe.

**Comment by oliverguenther** [comment]
[Quoting my reply from the older PR](https://github.com/opf/openproject/pull/9011#issuecomment-786176778)

> I still owe you that comment. As already discussed, a `LATERAL` join would be the preferred option as far as I could investigate. It allows you to limit the joined rows. This is very similar to a subselect, however with LATERAL, you can access columns to the outer select which would not be possible with a regular subselect ([cf. this SO question](https://stackoverflow.com/questions/28550679/what-is-the-difference-between-lateral-and-a-subquery-in-postgresql))
> 
> On the exemplary community query that Wieland mentioned in the ticket, the double join statement on attachments is causing double rows:
> 
> Here's the pastebin with a minmal example. As long as you have two attachments with one filename "schon.txt" and one with content "schon", the bug gets triggered, because then both conditions in the joins match but are different. Also it doesn't matter that the SQL contains two separate joins.
> 
> https://pastebin.com/jD27SX0x
> 
> We could either group by or use distinct (which we do here and I believe also in the past queries implementation).
> 
> However, postgres also allows us to restrict the number of rows returned from the right table in the left join with LATERAL. It has multiple requirements however:
> 
> 1. The JOIN needs to be rewritten as a subselect with `LEFT OUTER JOIN LATERAL ( SELECT ...)`
> 2. The subselect needs a `LIMIT 1`
> 3. The join condition then can be `ON TRUE` since the join condition `container_id / container_type` is moved into the subselect
> 
> Here's the example rewritten with LATERAL that works for my test data.
> 
> ```sql
> SELECT
>     "work_packages"."id", attachment_file_name_attachments_f3c7a271.* 
> FROM
>     "work_packages"
>     LEFT OUTER JOIN "statuses" ON "statuses"."id" = "work_packages"."status_id"
>     LEFT OUTER JOIN "projects" ON "projects"."id" = "work_packages"."project_id"
>     LEFT OUTER JOIN journals comment_journals ON comment_journals.journable_id = work_packages.id
>     AND comment_journals.journable_type = 'WorkPackage'
>     AND comment_journals.notes ILIKE '%schon%'
>     LEFT OUTER JOIN LATERAL (
>         SELECT * FROM attachments
>         WHERE container_id = work_packages.id
>         AND container_type = 'WorkPackage'
>         AND (file_tsv @@ to_tsquery('english', 'schon') OR fulltext_tsv @@ to_tsquery('english', 'schon'))
>         LIMIT 1
>     ) AS attachment_file_name_attachments_f3c7a271
>     ON TRUE
> WHERE
>     "work_packages"."project_id" IN (
>         SELECT
>             DISTINCT "projects"."id"
>         FROM
>             "projects"
>             INNER JOIN "enabled_modules" ON "projects"."id" = "enabled_modules"."project_id"
>             AND "enabled_modules"."name" IN ('work_package_tracking')
>             AND "projects"."active" = TRUE
>         WHERE
>             "projects"."active" = TRUE
>     )
>     AND (
>         (
>             work_packages.subject ILIKE '%schon%'
>             OR work_packages.description ILIKE '%schon%'
>             OR comment_journals.id IS NOT NULL
>             OR attachment_file_name_attachments_f3c7a271.id IS NOT NULL
>         )
>     )
> ORDER BY
>     work_packages.updated_at DESC,
>     work_packages.id DESC
> LIMIT
>     50 OFFSET 0
> ```
> 
> I'm fine with merging this PR as a fix for the pressing issue, but would expect that we likely missed some orders somewhere that will cause an error now so would like prioritize rewriting the joins soonish.

I still believe this will work if we can ensure that every lateral join retrieves only one row. That being said, I like this approach and would only be interested in a performance comparsion between the lateral and subquery. I believe you're effectively writing the same subquery just without access to the left joined row. This is fine unless we need more complex join expressions. In that case, we should still be able to mix lateral and regular subqueries.

**Comment by ulferts** [comment]
@oliverguenther I have compared two boiled down versions on my dev machine with PostgreSQL 13.2:

### Lateral join

```sql
WITH id_query AS (
    SELECT "work_packages"."id"
    FROM "work_packages"
    LEFT OUTER JOIN LATERAL (
		SELECT * from attachments attachment_content_attachments_2cb46386
                    WHERE attachment_content_attachments_2cb46386.container_id = work_packages.id
                        AND attachment_content_attachments_2cb46386.container_type = 'WorkPackage'
                        AND "attachment_content_attachments_2cb46386"."fulltext_tsv" @@ to_tsquery('english', 'abc')
	  LIMIT 1
	) attachment_content_attachments_2cb46386
	ON TRUE
    LEFT OUTER JOIN LATERAL (
		SELECT * FROM attachments attachment_file_name_attachments_2a1f6f48
                    WHERE attachment_file_name_attachments_2a1f6f48.container_id = work_packages.id
                        AND attachment_file_name_attachments_2a1f6f48.container_type = 'WorkPackage'
                        AND "attachment_file_name_attachments_2a1f6f48"."file_tsv" @@ to_tsquery('english', 'abc')
		LIMIT 1
		) attachment_file_name_attachments_2a1f6f48
	ON TRUE
    WHERE
       attachment_content_attachments_2cb46386.id IS NOT NULL
        OR attachment_file_name_attachments_2a1f6f48.id IS NOT NULL
    ORDER BY work_packages.id
    LIMIT 10
    OFFSET 1
)

SELECT * FROM work_packages where id IN (SELECT id from id_query)
```

### EXISTS
```sql
WITH id_query AS (
    SELECT "work_packages"."id"
    FROM "work_packages"
    WHERE
       EXISTS (SELECT 1 from attachments attachment_content_attachments_2cb46386
                    WHERE attachment_content_attachments_2cb46386.container_id = work_packages.id
                        AND attachment_content_attachments_2cb46386.container_type = 'WorkPackage'
                        AND "attachment_content_attachments_2cb46386"."fulltext_tsv" @@ to_tsquery('english', 'abc'))
	
        OR EXISTS (
			  SELECT 1 FROM attachments attachment_file_name_attachments_2a1f6f48
                    WHERE attachment_file_name_attachments_2a1f6f48.container_id = work_packages.id
                        AND attachment_file_name_attachments_2a1f6f48.container_type = 'WorkPackage'
                        AND "attachment_file_name_attachments_2a1f6f48"."file_tsv" @@ to_tsquery('english', 'abc')	
			)
    ORDER BY work_packages.id
    LIMIT 10
    OFFSET 1
)

SELECT * FROM work_packages where id IN (SELECT id from id_query)
```

### Results

Using `/timing` in `psql` I repeatedly fetched the two queries. Admittedly, this is not overly scientific but the results are roughly:
* LATERAL: 40-50 ms
* EXISTS: 7-10 ms


If I interpreted the query execution plan correctly, the lateral will first join all attachments and only then filter on the desired values whereas the EXISTS will first filter the attachments and then apply the EXISTS condition.

Because of that, I'd go with the EXISTS solution.

**Review by oliverguenther — APPROVED** [review]
Thanks for testing. You could move the two conditions within the LATERAL join, but not sure if that would make a difference.

**Pull request merged**
