### PR TITLE
[#36518] respect hide mail preference in member list

### PR DESCRIPTION
**Pull request by schuemann**
The member table should hide the email address if the user has the "Hide my email address" box checked in their profile.

### CODE REVIEW

**Comment by b12f** [comment]
Hi @schuemann and thanks for your contribution! Afaics, a feature spec is now failing, so this might have been intended behaviour. We'll get back to you asap.

**Review by oliverguenther — CHANGES_REQUESTED** [review]
`./spec/features/members/membership_filter_spec.rb` is now failing because it expects the email to be showing, which now is no longer the case. Could you extend the test by adding to the user factories:

```
  let!(:peter) do
    FactoryBot.create :user,
                      firstname: 'Peter',
                      lastname: 'Pan',
                      mail: 'foo@example.org',
                      member_in_project: project,
                      member_through_role: role,
                      preference: FactoryBot.build(:user_preference, hide_mail: false)
  end

  let!(:hannibal) do
    FactoryBot.create :user,
                      firstname: 'Pan',
                      lastname: 'Hannibal',
                      mail: 'foo@example.com',
                      member_in_project: project,
                      member_through_role: role,
                      preference: FactoryBot.build(:user_preference, hide_mail: true)
  end
```

which would then result in hannibal not showing the email. The example test needs to remove the checks for `find_mail` for hannibal and instead always expect that its mail is not showing.

There is also the problem that accessing `pref` will result in an N+1 query without preloading it. I'll look into this separately

**Comment by schuemann** [comment]
@oliverguenther I run into a NotNullViolation using the  FactoryBot. Do you have an idea what goes wrong?

**Comment by oliverguenther** [comment]
Hi @schuemann , I pushed some changes that allows the test object to create a preference. There was a bug in how preferences are created from factories that did not take in your changes.

As a last remark: We might want to render some "hidden" info instead of an empty cell, what do you think?

Otherwise, LGTM 👍  Thanks for your contribution!

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
