### PR TITLE
Fix/wysiwyg changes

### PR DESCRIPTION
**Pull request by b12f**
~~This all depends on https://github.com/opf/commonmark-ckeditor-build/pull/59~~ No longer applies (@ulferts)

Closes https://community.openproject.com/projects/openproject/work_packages/35607/activity
Closes https://community.openproject.com/projects/openproject/work_packages/35629/activity
Closes https://community.openproject.com/projects/openproject/work_packages/35593/activity
Closes https://community.openproject.com/projects/openproject/work_packages/35644/activity
Closes https://community.openproject.com/projects/openproject/work_packages/35603/activity

### CODE REVIEW

**Comment by aleixsuau** [comment]
Hi @b12f ,

- Issue [35629](https://community.openproject.com/projects/openproject/work_packages/35629) expects the images to be aligned to the left. They seem to be aligned to the center, while it is the figure that is aligned to the left. Not sure if it is the expected behavior.
- I also see that, when resizing the image (50%, 75%, or original size), it is the figure which is resized while the image seems to have always the original size. Not sure if it is the expected behavior.
- ./spec/features/wysiwyg/custom_css_classes_spec.rb:113 is failing. It seems that the changes in the ckEditor 'op-macro-wp-button' (allowWhere: ['$block'], allowWhere: [ '$text']) creates an extra paragraph.

Best

**Comment by b12f** [comment]
Hi @aleixsuau 

regarding the images, I'm not sure I understand. The images are left-aligned for me, inside of a non-aligned figure. So you could have a 100% figure with a 50% image inside. The reason I'm doing it this way is so that the figure itself still behaves the same way between images and tables. [This change](https://github.com/opf/openproject/pull/8884/files#diff-dea7da0eec7d2ef1a1974e1de4546b52e3db7d6ae4af8067e972d0458bc653c7R35) is responsible for that.

I've fixed the test. Thanks!

**Comment by aleixsuau** [comment]
Hi @b12f ,

I mean that, in the editing mode, I see the images always center-aligned and in the original size:

image
image
image


In the view mode, I see the images left aligned but they seem to be in the original size too even when they have been resized. For example, this image was resized to 50% but seems to be still 100%.

image

Don't you see them like that?

**Comment by b12f** [comment]
I was using larger images to test. Since resizing images by doing a width: 50% makes no sense (it's always based on the parent width, so there's no control), I've made sure the figcaption also goes to x% width when resizing. That way the behaviour is more transparnet to the user (the parent is resized, not the image)

**Comment by lindenthal** [comment]
hi @ulferts,
I can confirm the change with the headings.

I suggest one last change:

Currently the space between two paragraphs is too large. I just tried 0.8rem which looks much better. Is it possible to make this last change? It makes a huge difference.
Thanks
Niels

image

**Pull request merged**
