### PR TITLE
Fix Missing subfolder in url for some modules

### PR DESCRIPTION
**Pull request by 0xF013**
[`* `#10712` User is shown as deleted incorrectly`](http://www.openproject.org/work_packages/10712)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://0xf013-feature-10712-missing-subfolder-in-url.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by hschink** [comment]
@0xF013 In the overview tab versions are not linked correctly. Additionally, what do you think about tests?

**Comment by hschink** [comment]
@0xF013 Also the query selection does not work when `rails_relative_url_root` is set.

**Comment by hschink** [comment]
Closed in favor for #2002

**Pull request closed without merging**
