### PR TITLE
19490 Upgrade select2 to 3.5.x

### PR DESCRIPTION
**Pull request by myabc**
:warning: **Includes commits from #2796, Please review, merge first.**

https://community.openproject.org/work_packages/19490

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-19490-select2-3-5-upgrade.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-19490-select2-3-5-upgrade.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@vcostin can also check this is compatible with your changes in #2791?

**Comment by vcostin** [comment]
select2#~3.4 which resolved to 3.4.8 and is required by angular-ui-select2#0.0.5, angular-ui-select2-sortable#0.0.1
 for now it's a perfect fit version 3.4.8

**Comment by vcostin** [comment]
Styles are compatible for select2 3.5.2

**Comment by myabc** [comment]
@vcostin thanks for verifying!

**Comment by myabc** [comment]
Reissued as #2835 against `release/4.1`

**Pull request closed without merging**
