### PR TITLE
update simplecov to 0.10.0

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-1-simplecov.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-1-simplecov.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by floriank** [comment]
This PR does more than the description says - afaik the sprockets update will be done along the lines of @myabc's PR for rails 4 - see #2104 .

**Comment by marutosi** [comment]
> afaik the sprockets ...

Are you kidding?

**Comment by floriank** [comment]
> Are you kidding?

No.

**Comment by marutosi** [comment]
Have you run "bundle update _gem_"?
It is easy to reproduce #3041 description.

You are kidding.

**Comment by marutosi** [comment]
What is status?

**Pull request closed without merging**
