### PR TITLE
[FIX] Number of reported work packages in personal activity differs from number in My page

### PR DESCRIPTION
**Pull request by jonasheinrich**
Old Pull request: https://github.com/opf/openproject/pull/981

Fixes https://www.openproject.org/work_packages/5002

### CODE REVIEW

**Comment by machisuji** [comment]
@meeee @myabc Everyone happy?

**Comment by myabc** [comment]
@machisuji I'm never happy, but this PR makes me happier :dancers:

**Comment by mfrister** [comment]
@jonasheinrich I expected something like the following, that not only tests that a specific scope chain is called, but also that the right thing is done with its return value.
Otherwise the same scope chain might be called for another reason that doesn't have to do with the number of reported work packages and this test wouldn't notice it.

``` ruby
  describe 'index' do
    before do
      WorkPackage.stub_chain(:on_active_project, :with_author, :visible, :count).and_return(3)
      get :index
    end

    it 'correctly assigns the number of reported work packages' do
      expect(assigns(:reported_count)).to eql(3)
    end
  end
```

This is optional, but could make things even better:
If you have a scope chain this long that you use at several places, it might be useful to create a method for it. You could e.g. create a method called `reported_work_package_count` on User.

Feel free to come over to talk some more about this if you want :)

**Comment by mfrister** [comment]
@machisuji Thanks for the improvements!

You check for a specific string in the controller spec ('Reported work packages'). After having lots of problems with checking for a specific string instead of a translation with the multi provider login changes, I'd rather not use a specific string in a spec.

You could either change that to check for the translated string or just check that the controller assigns the correct value to the instance variable.

**Comment by machisuji** [comment]
@meeee et voilà

**Comment by mfrister** [comment]
@machisuji Merci beaucoup!

**Pull request merged**
