### PR TITLE
remove obnoxious warning about old bundler version

### PR DESCRIPTION
**Pull request by linki**
bundler 1.5 is almost a year old now.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-bundler-warning.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
:+1:

**Comment by marutosi** [comment]
http://www.redmine.org/issues/19172

**Comment by marutosi** [comment]
https://packages.debian.org/wheezy/bundler

> 1.1.4-6

**Comment by marutosi** [comment]
http://packages.ubuntu.com/trusty/ruby-bundler

> 1.3.5-2ubuntu1

**Pull request merged**
