### PR TITLE
 [MIGRATION] Prepare schema migration table

### PR DESCRIPTION
**Pull request by hschink**
Implements [ticket 1992](https://www.openproject.org/issues/1992)

### CODE REVIEW

**Comment by apfelfabrik** [comment]
The confirmation dialog is a good idea, but only if the shell is interactive. Rake tasks tend to be executed in deployment scripts, especially those that are built around migrations. So I would suggest one of the following:
- remove the confirmations or
- check whether the shell is interactive [1].

I believe @cratz is with me on this one :-)

[1] http://stackoverflow.com/questions/3384982/how-can-i-determine-if-my-process-is-being-run-interactively

**Comment by apfelfabrik** [comment]
There are other issues here. Some of the rake tasks seem to have dependencies to migrations that couldn't be run before others of the rake tasks were executed. I am commenting [ticket 1992](https://www.openproject.org/issues/1992).

**Comment by apfelfabrik** [comment]
One more thing: `migrations:documents:delete` and `migrations:attachments:delete_from_projects_and_versions` both state they'd be deleting all documents. Only one of those statements can be true, I suppose.

**Comment by hschink** [comment]
@apfelfabrik: Documents and attachments are two different things, thus, only one rake task is actually stating it is deleting documents. The other one deletes attachments (from versions and projects).

**Comment by apfelfabrik** [comment]
I have restarted the failed travis build.

**Pull request merged**
