### PR TITLE
Remove pandoc and option to migrate from textile

### PR DESCRIPTION
**Pull request by oliverguenther**
Pandoc was used when migrating from Textile to Markdown/CommonMark in OpenProject 8.0.0. Since then, this has only been left in in case user migrated from older versions. As this has impacts on the slim docker container, now is a good time to finally remove it.

### CODE REVIEW

**Review by crohr — APPROVED** [review]
Looks fine to me, although some changes are not in my core competence.

**Review by ulferts — CHANGES_REQUESTED** [review]
Change itself is fine, @oliverguenther . 

The only request I have is an [update to the documentation](https://github.com/opf/openproject/blob/dev/docs/installation-and-operations/misc/textile-migration/README.md?plain=1#L5-L11) basically stating the limitation now in place same as it is stated in the migration.

**Comment by oliverguenther** [comment]
The doc change is already added here: https://github.com/opf/openproject/pull/13305/files#diff-8ef4b3ddb5ba760aa4a52760fccb4f5bdff06151a739c21154200b1685ffa8cd

**Comment by oliverguenther** [comment]
https://community.openproject.org/work_packages/49457

**Pull request merged**
