### PR TITLE
Feature/rubocop

### PR DESCRIPTION
**Pull request by javierojeda94**
Running rubocop on a fresh fork reported 6916 offenses, this pull request fixes some of the easy ones of those offenses. After this PR, the total offenses are 5198 offenses.

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi Javier,

🙇  for the effort you put into this. This will help us use rubocop autofix more in the future to detect  issues.

There appears to be a frozen array that's modified in an initializer. Please see the travis output for more information:

I've assigned it for the next release, since the upcoming 7.2. draws to a close.

```
RuntimeError: can't modify frozen Array
  /home/travis/build/opf/openproject/lib/redcloth3.rb:380:in `map!'
  /home/travis/build/opf/openproject/lib/redcloth3.rb:380:in `<class:RedCloth3>'
  /home/travis/build/opf/openproject/lib/redcloth3.rb:169:in `<top (required)>'
  /home/travis/build/opf/openproject/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
  /home/travis/build/opf/openproject/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
  /home/travis/build/opf/openproject/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
  /home/travis/build/opf/openproject/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
  /home/travis/build/opf/openproject/config/initializers/redcloth_numbered_headings.rb:31:in `<top (required)>'
```

**Comment by ulferts** [comment]
Thanks again @javierojeda94.

Just out of curiosity, what will you be working on? Cyberstalking you on community.openproject.org didn't reveal anything 😈 . Let us know if there is anything you need help with.

**Comment by javierojeda94** [comment]
Thanks @oliverguenther and @ulferts! I really appreciate your recognition for our effort. 

We (@casp and I) are very excited to contribute with opensource community. 

@oliverguenther sure! We're going to check what was the error and fix it as soon as possible. We want to keep this project free of offenses so the code improves it's quality! 

@ulferts we are not really behind any reported bug, by now we only want to understand the codebase and fixing this offenses are a great way to do it! 

I have a question, is there any way for me to check for travis-pipeline on my development environment? I think it is better to solve all those issues in our development environment than to let travis notify about them.

Thanks both of you!

**Comment by javierojeda94** [comment]
Update! 

rubocop output:
`2367 files inspected, 4636 offenses detected`

@casp fixed the issue with the frozen array.

Also, codeclimate is not complaining. We will try to keep it like that

**Comment by casp** [comment]
Update!

rubocop output:
2367 files inspected, 2838 offenses detected

**Comment by oliverguenther** [comment]
> I have a question, is there any way for me to check for travis-pipeline on my development environment? I think it is better to solve all those issues in our development environment than to let travis notify about them.

You can run all tests manually on your local machine. Please see [the testing documentation](https://github.com/opf/openproject/blob/dev/docs/development/running-tests.md) for more information.

**Comment by oliverguenther** [comment]
We have recently added the functionality to upload screenshots from feature tests to a S3 bucket of our own, which is configured through ENV variables. It seems that travis hides some of the ENV vars (marked secret) to forks, which is why tests are not starting for your PR.

Please include this fix, either by merging `origin/dev` or by  applying it manually to your PR. The tests should then start correctly.
https://github.com/opf/openproject/commit/d1d5d566203677775bee4def49b55174bf9b6409

**Comment by ulferts** [comment]
Closing this with sadness. But no one will be able to apply this any more.

**Pull request closed without merging**
