### PR TITLE
Fix/global version filter

### PR DESCRIPTION
**Pull request by ulferts**
https://www.openproject.org/work_packages/9045

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-global-version-filter.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@ulferts looks fine, except for a few style issues in the routing spec.

**Comment by ulferts** [comment]
@myabc, you are right, that was sloppy. Fixed all the criticised stylings.

**Comment by myabc** [comment]
:+1:

**Pull request merged**
