### PR TITLE
[43892] When adding users to a group, existing users are shown in the autocompleter

### PR DESCRIPTION
**Pull request by bsatarnejad**
Pass the correct values for inputs of angular user autocompleter component and render the component in ruby by using angular_component_tag.

https://community.openproject.org/work_packages/43892/activity

### CODE REVIEW

**Review by b12f — APPROVED** [review]
LGTM, the filters were just broken because they were handed over wrong?

**Comment by bsatarnejad** [comment]
> LGTM, the filters were just broken because they were handed over wrong?

Yes Exactly, the filters were not passed correctly. 

The failing tests are not related to these changes here, though I think it is also mergable.

**Comment by oliverguenther** [comment]
@bsatarnejad The spec fail locally for me as well. It looks like they originate from this PR. I think it might have something to do with the body appendTo ?

**Comment by bsatarnejad** [comment]
> @bsatarnejad The spec fail locally for me as well. It looks like they originate from this PR. I think it might have something to do with the body appendTo ?

No, I don't think so. I checked the failing tests on release 12.2 branch, there were these errors too. When opening the ng-select, it calls _updatePosition() and this function needs the parent of the select. when there is no value for appendTo, the parent is null and raise an error there.

**Comment by oliverguenther** [comment]
In any case, the broken spec might shadow other failures here, so I think it makes sense to fix them as part of this PR

**Pull request merged**
