### PR TITLE
Git adapter encoding handling

### PR DESCRIPTION
**Pull request by oliverguenther**
The git adapter currently has a bug that denies to annotate regular
text files when the author name has an umlaut.

This commit changes the binary file detection by simply counting null
bytes. This may not detect all binary files correctly, but that isn't a
requirement.

The original check was arguably used to avoid rendering large binary
files in the browser.

This also re-introduces the path encoding from 4.2, which was seemingly lost in the new form.

Relevant bug report: https://community.openproject.org/work_packages/20883

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-fix-git-annotate-utf8.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://oliverguenther-fix-git-annotate-utf8.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
> This commit changes the binary file detection by simply counting null bytes.

I think this is not a good idea, thinking of UTF-16 encoded text files...

edit: Or I am still not quite getting what you are doing here...

**Comment by NobodysNightmare** [comment]
I verified my assumption. Using a UCS-2 encoded textfile this check now shows the file as being binary.

What also disturbs me: In any case a binary file will cause an HTTP 500 (that is rendered well, but a 500 nonetheless)

**Comment by oliverguenther** [comment]
@NobodysNightmare UTF-16 still returns 500, as before, but I've made this explicit through an added test file in the repository and specs. We will have a better solution for these cases once we refactor the git adapter (wish list).

**Comment by NobodysNightmare** [comment]
As discussed in person:

The selection of the path encoding for git does not seem to select UTF-8 as default (as advertised).

**Comment by NobodysNightmare** [comment]
LGTM :+1: 

Waiting for travis to agree!

**Pull request merged**
