### PR TITLE
Feature #25066 Add link to work package list

### PR DESCRIPTION
**Pull request by wielinde**
I added a „Custom fields“ link to the menu settings as described here:

https://community.openproject.com/projects/openproject/work_packages/25066

Unfortunately I did not find the place where to add some specs for it. Am I right that there is not a place yet? Where should I put it?

### CODE REVIEW

**Comment by oliverguenther** [comment]
I would move the links into the `work_package_collection_representer`. There are associated representers specs in `spec/lib/api/v3/work_packages`.

**Comment by wielinde** [comment]
@oliverguenther Thank you for the hint. I updated the code accordingly.

**Comment by oliverguenther** [comment]
@wielinde Tests are still failing :/

**Comment by wielinde** [comment]
@oliverguenther Thank you. And I am very happy that the tests failed as my code was wrong. Hurray!!! I fixed the code.

**Comment by oliverguenther** [comment]
LGTM 👍

**Pull request merged**
