### PR TITLE
Highlight correct error field in EE trial form

### PR DESCRIPTION
**Pull request by HDinger**
Depending on the error (invalid email, taken email or taken domain) the according field in the form should be highlighted with a red border and the according message should be shown.

### CODE REVIEW

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/930f7b5e8c53f7b83e68f6b4b41a8c4499e33e49/frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts#L37">frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts#L37</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/930f7b5e8c53f7b83e68f6b4b41a8c4499e33e49/frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.ts#L40">frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.ts#L40</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by oliverguenther — CHANGES_REQUESTED** [review]
When initially entering a domain that was used, this works fine. If I hit "try with another mail address" and enter another mail that was used already, the request goes through, but when opening it again, the field is marked red.

Steps to reproduce:

1. Enter trial form with valid content
2. Click "try with different mail"
3. Enter mail that was used already



Screenshot from 2020-04-21 15-33-20

**Comment by HDinger** [comment]
Good catch 👍 I hope i found all issues now.

**Review by oliverguenther — APPROVED** [review]
I fixed the tests after changing the error classes. LGTM

**Pull request merged**
