### PR TITLE
run ldap tests on travis

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-ldap.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-ldap.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
You are missing a description.

In the description you could for example explain why you removed the `sudo: false` tag and why this is a good idea in your opinion.

One consequence I know about: http://docs.travis-ci.com/user/workers/container-based-infrastructure/

But there are probably more consequences...

**Comment by myabc** [comment]
I'd be loath to move off the Travis container infrastructure.

**Comment by NobodysNightmare** [comment]
If only your PR descriptions were as expressive as your tweets... https://twitter.com/marutosijp/status/590166516395413505

**Comment by marutosi** [comment]
> why you removed the sudo: false tag

https://github.com/ruby-ldap/ruby-net-ldap/pull/196#issuecomment-94634417

**Comment by NobodysNightmare** [comment]
And still you fail to see which other consequences this has (e.g. it is no longer possible to run on travis containerized infrastructure).

And you point me to a comment that points someone else to a commit message that points to the log output of travis.

You see the layers of indirection here? I can already see you pointing someone else to your comment here, just to add another layer of indirection.

**Comment by floriank** [comment]
This contains #2882 entirely, please see the discussion there for my suggestion on fixing the test instead of reintroducing the fixture.

**Pull request closed without merging**
