### PR TITLE
Explicitly add testing email settings

### PR DESCRIPTION
**Pull request by b12f**
If you have a `.env` file in the repository that specifies mal settings, these can overwrite the default mailing settings for the testing setup. This commit explicitly sets the appropriate env variable correctly.

### CODE REVIEW

**Comment by apfohl** [comment]
> If you have a `.env` file in the repository that specifies mal settings, these can overwrite the default mailing settings for the testing setup. This commit explicitly sets the appropriate env variable correctly.

So we have to set it explicitly to the thing back, where mails get opened in the browser?

**Comment by b12f** [comment]
For testing you mean?

**Comment by apfohl** [comment]
> For testing you mean?

Maybe I don't get what this switch is actually doing. For now I assume it sets email delivery in general to a mechanism called 'test'. Please correct me :).

**Comment by b12f** [comment]
This sets the email delivery to `test` only for the `backend-test` container, so it won't affect the normal `backend` container

**Review by apfohl — APPROVED** [review]

**Pull request merged**
