### PR TITLE
Meets #7507: Open in new Tab from Backlog has become harder

### PR DESCRIPTION
**Pull request by netfighter**
[`* `#7507` Open in new Tab from Backlog has become harder`](https://www.openproject.org/work_packages/7507)

### CODE REVIEW

**Comment by hschink** [comment]
@myabc, @tilt this PR affects the modal directive. So, can you please have a look on this? Thanks a lot!

**Comment by hschink** [comment]
@netfighter That fix works in the backlogs view but not in the timelines view.

**Comment by netfighter** [comment]
@hschink Added the Ctrl+Click event on timeline planning elements. That will open the work package page in a new browser tab. Unfortunately, the SVG 'rect' elements do not react on mouse middle-click, so the full anchor-like behavior cannot be implemented.

**Comment by hschink** [comment]
@netfighter Thanks, now it works for the rendered planning elements. :+1: But, still, the links in the timelines table (left of the Gantt chart) cannot be opened in a separate windows by using `Ctrl + left click`. Can you have a look on this too? Thanks a lot!

**Pull request merged**
