### PR TITLE
[Slow Win] Move the comment field in activities to the top

### PR DESCRIPTION
**Pull request by floriank**
Meets https://community.openproject.org/work_packages/19341.

Requires _Premium PR review_<sup>TM</sup>

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-fix-19341-move-comment-field-to-top.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-fix-19341-move-comment-field-to-top.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
The new comment input is only moved to the top on the activity tab of the details pane. Is that intended? There is a comment field on the overview tab as well and that one remained at the bottom which strikes me as inconsistent. This also does not take into account the setting that exists where the user can choose whether he want't to have the activity in chronological or reverse chronological order. This setting is only active on the activity tab whereas the overview tab statically shows the last three activities in reverse chronological order.

The solution should IMO:
- Place the input on the overview tab at the top of the activity tab
- Place the input on the activity tab on the top of the activity tab if the user has chosen to display the activity in reverse chronological order and at the bottom if the user has chosen to display the activity in chronological order.

Additionally, the styling breaks:
image

**Comment by floriank** [comment]
Strange - the styling error does not occur for me. mh, I only got the request to move the input to the top, with no further instructions.

This should be postponed, as it would probably way longer than expected.

**Comment by NobodysNightmare** [comment]
As discussed I am closing this PR, as it would cause other trouble and you will probably not reuse anything here when you do the proper solution.

I'll update the corresponding ticket too.

**Pull request closed without merging**
