### PR TITLE
[rebase #769] remove branches from .travis.yml

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by marutosi** [comment]
This is rebasing #769.

**Comment by mfrister** [comment]
Thanks for your pull request! I'm sorry, but testing all feature branches we're working on needs to much resources on Travis, so we'd regularly need to wait pretty long for the tests (we had this before and it didn't work out). Pull requests are being tested nevertheless.

If you want to test your changes before creating a pull request, please run the tests locally or modify the .travis.yml in your fork and remove that commit before creating a pull request.

I'd love there being a better way, but this seems to be a limitation of Travis for now.

**Comment by marutosi** [comment]
> but testing all feature branches we're working on needs to much resources on Travis

Yes. But it is because your work flow is wrong.
Why do you push feature and bug fix branches to central repository?
Do you understand DVCS work flow?
Why do not you use forked repository to review pull request?
Why do you use force push?
Why do you have garbage branches and tags in central repository?

> Pull requests are being tested nevertheless.

No.
Have you sent pull request to other repositories?

> If you want to test your changes before creating a pull request, please run the tests locally or modify the .travis.yml in your fork and remove that commit before creating a pull request.

Why?
Do you all do this?

Is your project OpenSource?

**Comment by mfrister** [comment]
> Why do you push feature and bug fix branches to central repository?

For at least some of the branches, multiple people are working on them. Even for a DVCS, a central repository is the simplest way to share them.

> Do you understand DVCS work flow?

There's no such thing as _the_ single right workflow. What do you think we should improve?

>  Why do not you use forked repository to review pull request?

Why should we do that?

>  Why do you use force push?

We don't use force push on main branches. What's wrong with using them on feature branches?

>  Why do you have garbage branches and tags in central repository?

We try to delete feature and bugfix branches once they're merged, but probably don't catch them all. Which branches do you think are garbage?

> > Pull requests are being tested nevertheless.
> 
> No.

Yes, they are. Just look at the green check mark next to your commit in this pull request.

>  Do you all do this?

Yes, we run tests locally we think are relevant, all others run once there is a pull request.

> Is your project OpenSource?

Yes.

**Comment by marutosi** [comment]
> What do you think we should improve?

https://github.com/progit/progit/blame/33aded7a2e2abfe81f85/en/05-distributed-git/01-chapter5.markdown#L796
http://marutosi.bitbucket.org/redmine-shinagawa-20121110/one-html/html/index.html#id79

> We don't use force push on main branches. 

What is main branches?

> Which branches do you think are garbage?

https://github.com/opf/openproject/branches?merged=1

**Comment by mfrister** [comment]
This is the workflow we aim for: https://www.openproject.org/projects/openproject/wiki/Git_Branching_Model
What exactly should we improve about it?

> What is main branches?

dev, stable (once 3.0 is released) and release branches

You're right about the merged branches, we should clean them up more often.

**Comment by marutosi** [comment]
> This is the workflow we aim for: https://www.openproject.org/projects/openproject/wiki/Git_Branching_Model
> What exactly should we improve about it?

Git-flow is **branch** management strategy, not **repository**.
And it is _for smaller projects_.
https://bitbucket.org/bos/hgbook/src/0f70d9b750669c755a2013815140da299ec54475/en/ch06-collab.xml?at=default#cl-156
https://github.com/progit/progit/blame/33aded7a2e2abfe81f85/en/05-distributed-git/01-chapter5.markdown#L11
https://github.com/progit/progit/blame/33aded7a2e2abfe81f85/en/05-distributed-git/01-chapter5.markdown#L384

Why do not use **Public Large Project** model?
https://github.com/progit/progit/blame/33aded7a2e2abfe81f85/en/05-distributed-git/01-chapter5.markdown#L472
https://bitbucket.org/bos/hgbook/src/0f70d9b750669c755a2013815140da299ec54475/en/ch06-collab.xml?at=default#cl-343
http://mercurial.selenic.com/wiki/KernelPractice

**Comment by marutosi** [comment]
**Pull Request** is for **Integration-Manager Workflow** and **Dictator and Lieutenants Workflow**.
https://github.com/progit/progit/blame/33aded7a2e2abfe81f85/en/05-distributed-git/01-chapter5.markdown#L23
https://github.com/progit/progit/blame/33aded7a2e2abfe81f85/en/05-distributed-git/01-chapter5.markdown#L39

Do you understand what Pull Request is?

**Comment by mfrister** [comment]
I understand there are other models, but why do you think Git Flow is not appropriate? Why would we need multiple repositories?

**Comment by marutosi** [comment]
As you agreed, this repository has many garbage branches.
Deleting branches and force pushing is very dangerous operation.

**Comment by mfrister** [comment]
Neither did we have significant problems with force pushes yet, nor do I see problems with some merged branches lying around (Git warns you anyway when deleting an unmerged branch).

**Comment by marutosi** [comment]
OK. You admit that your project is small and for few developers and not for worldwide.
I don't know why did you remove languages except English and German.

Good luck, and good night.

**Comment by mfrister** [comment]
> You admit that your project is small and for few developers and not for worldwide.

We're not yet at a scale where our current development workflow doesn't work. Once it shows its limitations we will adapt it.

We removed other languages because we didn't have the resources to adapt all languages. We set up a project on Crowdin, where we welcome all contributions: https://crowdin.net/project/openproject/

Thanks for your feedback!

**Pull request closed without merging**
