### PR TITLE
Gemfile: awesome_nested_set: use github 2-1-stable branch

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by ulferts** [comment]
Hey @marutosi,

thanks for the PR. Can you please elaborate on the improvements of this PR. I can see that you removed a patch but I am not sure if changing from a release to a stable branch is worth it.

Best

Jens

**Comment by marutosi** [comment]
For Rails 4 porting.

**Comment by ulferts** [comment]
This fails miserably. Care to fix?

**Comment by marutosi** [comment]
<pre>
gem "awesome_nested_set",
    :git => "git://github.com/marutosi/awesome_nested_set.git",
    # PR 230, 231 and 232
    :ref => "4c4fdfe80f7451b"
    # PR 234
    #:ref => "5531b9b431209b0"
    # PR 235
    #:ref => "d34770bbe2f1f83"
    # PR 234 and 235
    #:ref => "8cdba83ba174b"
    # :git => "git://github.com/collectiveidea/awesome_nested_set.git",
    # :git => "https://bitbucket.org/marutosi/awesome_nested_set-git.git",
    # :branch => "2-1-stable"
    # :tag => "2.1.5"
    # :tag => "v2.1.6"
    # :ref => "3d5ac746542"
</pre>

**Comment by marutosi** [comment]
Because you refuse SQLite pull request, I cannot fix.

**Comment by ulferts** [comment]
I am sorry to hear that. 

The reason I refused SQLite was because I did not see a chance for anybody to fix it in a reasonable amount of time. It failed on one of the first migrations. We currently have the problem of too many open PRs. A couple of those stayed open because we like the idea (e.g. the default route removal :+1: ) of the PR but can not currently get them to pass a CI run. Those PRs tend to age, they become unmergeable and the effort or rebasing them time after time is just to much. We would like to try to focus on about one PR per person.

How about we do it like this:
1) Working SQLite PR
2) This PR

How does it sound?

**Comment by ulferts** [comment]
As this seems to require a working SQLite, we are closing this for now. Once OP is working with SQLite, feel free to open up a new branch.

**Pull request closed without merging**
