### PR TITLE
update activerecord-tableless version

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-0-activerecord-tableless.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-0-activerecord-tableless.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@marutosi For test dependencies I prefer to be less specific about the version required. In other words:

``` ruby
gem 'faker', '~> 1.4'
```

**Comment by floriank** [comment]
this is not required to be merged into `release/4.0` but `dev`, if at all.

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by floriank** [comment]
DRY.

**Comment by marutosi** [comment]
What does "DRY" mean?

**Comment by floriank** [comment]
http://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Comment by marutosi** [comment]
Please describe more details.

**Pull request closed without merging**
