### PR TITLE
[Gantt-Chart] Scroll to Today's Position #40167

### PR DESCRIPTION
**Pull request by srkunze**
https://community.openproject.org/projects/openproject/work_packages/40167/activity

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @srkunze , changes LGTM, but they are breaking the following feature spec: ./spec/features/work_packages/timeline/timeline_dates_spec.rb

**Comment by srkunze** [comment]
@oliverguenther I ran the spec on dev and the branch. There eems to be some issues with the dev branch as well. I'll look into the branch-specific issues.

DEV:
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb:112 # Work package timeline date formatting with default settings with german locale user shows german ISO dates
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb[1:3:1:6:1:1] # Work package timeline date formatting setting dates with an existing duration only sets the start, due dates and duration on a drag and drop create over the weekend behaves like sets dates, duration and displays bar sets dates, duration and duration bar

BRANCH:
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb:284 # Work package timeline date formatting setting dates with an existing duration only cancels when the drag starts or finishes on a weekend
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb:200 # Work package timeline date formatting setting dates with an existing duration only displays the hover bar correctly
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb[1:3:1:8:1:1:1] # Work package timeline date formatting setting dates with an existing duration only when ignore_non_working_days is true sets the start, due dates and duration on a drag and drop create over the weekend behaves like sets dates, duration and displays bar sets dates, duration and duration bar
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb[1:3:1:4:1:1] # Work package timeline date formatting setting dates with an existing duration only sets the start, due dates while preserving duration on a drag and drop create behaves like sets dates, duration and displays bar sets dates, duration and duration bar
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb[1:3:1:3:1:1] # Work package timeline date formatting setting dates with an existing duration only set the start, due date while preserving duration over the weekend behaves like sets dates, duration and displays bar sets dates, duration and duration bar
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb[1:3:1:5:1:1] # Work package timeline date formatting setting dates with an existing duration only sets the start, due dates while preserving duration on a drag and drop create over the weekend behaves like sets dates, duration and displays bar sets dates, duration and duration bar
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb[1:3:1:6:1:1] # Work package timeline date formatting setting dates with an existing duration only sets the start, due dates and duration on a drag and drop create over the weekend behaves like sets dates, duration and displays bar sets dates, duration and duration bar
rspec ./spec/features/work_packages/timeline/timeline_dates_spec.rb[1:3:1:2:1:1] # Work package timeline date formatting setting dates with an existing duration only set the start, due date while preserving duration behaves like sets dates, duration and displays bar sets dates, duration and duration bar

**Comment by srkunze** [comment]
@oliverguenther Can you have a look at it? :)

**Review by oliverguenther — APPROVED** [review]
Appears to be working fine. Thanks @srkunze

**Pull request merged**
