### PR TITLE
Fix/merge release 4 0 into dev

### PR DESCRIPTION
**Pull request by ulferts**
Because of the conflicts I had to resolve, I want to run this through travis before merging.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-merge-release-4-0-into-dev.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by hschink** [comment]
@ulferts Do you like to use this PR to merge https://github.com/opf/openproject/pull/2276 back to `dev`?

**Comment by hschink** [comment]
@ulferts Sorry that I didn't recognize the missing camel casing. :disappointed:

**Comment by ulferts** [comment]
@hschink as discussed, I added a jshint configuration header. Fixed some styling issues while doing this.

**Pull request merged**
