### PR TITLE
[19894] Upgrade livingstyleguide to 2.0.0

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/19894

Upstream issues (~~blocking~~ worked around in 792a98f):
- https://github.com/livingstyleguide/livingstyleguide/issues/133

Upstream issues (minor):
- https://github.com/livingstyleguide/livingstyleguide/issues/134

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-livingstyleguide-upgrade.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-livingstyleguide-upgrade.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
This is good to merge. However, I would add some documentation for the new `Gemfile` and `Gemfile.lock` in `frontend/`.

Anyways, :+1: - we should merge this **after** `release/4.1` is stable.

**Comment by ulferts** [comment]
@floriank unsure now because of the changes in the branching, but shouldn't release/4.2 now be the correct merge target

**Comment by floriank** [comment]
It's a sole development topic, so it could go against `dev` - the main reason @myabc did this upgrade (iirc) was that the LSG get to bloated at times and version 2 supports pages (instead of having everything on one single page) - in any case, this has to be rebased against something first.

**Comment by NobodysNightmare** [comment]
Is anyone going to rebase this?
I'd like this to happen...

**Comment by floriank** [comment]
me too, but i do not have awesome collab powers on @myabc's fork.

**Comment by floriank** [comment]
Also, as @ulferts pointed out, this could go into `dev` for the moment. As this would be useful for 4.3 development,I'd say merge it against `dev` before `release/4.3` is created.

**Comment by myabc** [comment]
@floriank you do now.

**Comment by floriank** [comment]
rebased.

**Comment by NobodysNightmare** [comment]
I merged this PR into the `dev` branch in this commit: https://github.com/opf/openproject/commit/25b7211b557a8de6efbfff3a6f87622e14db20fb

We will not take it in earlier versions to make sure there are no shenanigans regarding dev ops topics (even though I doubt those are affected, but better be safe than sorry)

**Pull request closed without merging**
