### PR TITLE
Downgrade npm to 6.x and revert lockfile to v1 due to npm bug

### PR DESCRIPTION
**Pull request by oliverguenther**
https://github.com/npm/cli/issues/2610#issuecomment-851347583

### CODE REVIEW

**Comment by oliverguenther** [comment]
Awaiting packager build  https://packager.io/gh/opf/openproject/refs/fix/npm-ssh-error

**Comment by b12f** [comment]
npm install is failing in the specs. It might be easier to pin npm on a lower version?

**Comment by oliverguenther** [comment]
> npm install is failing in the specs. It might be easier to pin npm on a lower version?

yes that's probably the way to go. This means reverting to a v1 lockfile though, but is fine with me for now until they get it fixed.

**Comment by oliverguenther** [comment]
Still waiting for packages now after the devDependencies changes

**Review by b12f — APPROVED** [review]
Unfortunate about the devDeps, but LGTM

**Pull request merged**
