### PR TITLE
fixed query column name mapping

### PR DESCRIPTION
**Pull request by machisuji**
WP [#23231](https://community.openproject.com/work_packages/23231)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://fix-query-column-names.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://fix-query-column-names.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@machisuji Travis doesn't like it... at all :(

**Comment by machisuji** [comment]
@ulferts all green now

**Comment by oliverguenther** [comment]
👍

**Pull request merged**
