### PR TITLE
Feature/rails3 group assigned issues

### PR DESCRIPTION
**Pull request by GarstgerUnhold**
This is basically the same as https://github.com/opf/openproject/pull/40 but with (presumably) working tests and 2 fixed model validations.

### CODE REVIEW

**Comment by apfelfabrik** [comment]
Please consider we're on GPL3 now. This might lead to problems when merging in patches from Redmine. Both https://github.com/opf/openproject/commit/2cfdbda8bf6ede297aa0910261f315677c03ae23 and https://github.com/opf/openproject/commit/435d4a7be65045ff1e11334faa57ce81e3bc6219 are problematic.

**Comment by lindenthal** [comment]
Both Redmine and ChiliProject are distributed under GPL v2 and younger. So this shouldn't be a problem.

**Comment by mfrister** [comment]
@GarstgerUnhold Any updates on this? A rebase on the current feature/rails3 would be great.

**Comment by apfelfabrik** [comment]
https://github.com/opf/openproject/commit/f65540ce7a29033fd6177ee48b10743bb2b0813d used to be https://github.com/opf/openproject/commit/2cfdbda8bf6ede297aa0910261f315677c03ae23, as well as https://github.com/opf/openproject/commit/9441f2eae0959e4189df5e142fd665df14fa0caa used to be https://github.com/opf/openproject/commit/435d4a7be65045ff1e11334faa57ce81e3bc6219. You shouldn't remove original authorship! It appears you squashed the original changes into merge commits, which lost their parents in the process. Get this straightened out and I can merge the PR.

**Comment by ulferts** [comment]
OpenProject ticket: https://www.openproject.org/issues/1715

**Comment by hschink** [comment]
This PR does not handle journals :newspaper: correctly: If one deletes the group a work package is assigned to, the deleted group does not show up in the journal entries.

**Comment by ulferts** [comment]
Rebased it in order for it to be mergeable

**Comment by ulferts** [comment]
Fixed the reassignment upon deletion @hschink mentioned. Upon deletion, every work package is reassigned to the DeletedUser, the journals are updated accordingly.

**Pull request merged**
