### PR TITLE
adds missing priority_id to planning_element/show in API v2

### PR DESCRIPTION
**Pull request by machisuji**

### CODE REVIEW

**Comment by machisuji** [comment]
@NobodysNightmare did you create a work package for this?

**Comment by NobodysNightmare** [comment]
nope, I hoped it would fit into the "no Ticket for very small PRs"-policy...

**Comment by nkenneweg** [comment]
I am a little confused because in my memory the priority id was already in the api...

**Comment by NobodysNightmare** [comment]
@nkenneweg It was only present in the index-action, but **not** in the show-action.

**Comment by machisuji** [comment]
Would someone just merge this? ^^ It is unlikely to break anything and creating a ticket as well as following the usual process might indeed be a wee bit too much trouble for a 13-character change.

**Pull request merged**
