### PR TITLE
Add /api/v3/meetings index action

### PR DESCRIPTION
**Pull request by oliverguenther**
Precursor for https://community.openproject.org/work_packages/4742

---

- [x] Make the project filter section a bit more generic
- [x] Add autocompleter option
  - [x] Fix that currently selected filter value is not shown in autocompleter
- [x] Make filter component output JSON data as well as new format
- [x] Add all filters that the meeting supports and add components for the values if needed
  - [x] Add UI for `Queries::Meetings::Filters::ProjectFilter`
  - [x] Add UI for `Queries::Meetings::Filters::TimeFilter`
  - [x] Add UI for `Queries::Meetings::Filters::AttendedUserFilter`
  - [x] Add UI for `Queries::Meetings::Filters::InvitedUserFilter`
  - [x] Add UI for `Queries::Meetings::Filters::AuthorFilter`
  - [x] Add UI for `Queries::Meetings::Filters::DatesIntervalFilter`
- [ ] Find a possibilty to not allow multi select in some cases

### CODE REVIEW

**Comment by oliverguenther** [comment]
- [ ] On the default meetings page, I see a time filter selected for "past", but the filter is actually filtering for future values.

Bildschirmfoto 2024-04-10 um 10 09 34

- [ ] I believe we should hide the project filter in the project context

**Comment by oliverguenther** [comment]
Code-wise, LGTM. I removed the needs review label, we can merge this once the past thing is ready. I assume that product will still want the project filter to be hidden

**Comment by klaustopher** [comment]
Will look into this later today 👍 

Assumption: snake_case to camelCase conversion, but will check further

**Comment by klaustopher** [comment]
It was not what I assumed, but the new TimeFilter did only set a value for the filters and thus it had an empty value in the select. It works now and also uses the proper translation for the displayed values.

The issue that the number was to high is that we are adding the project filter twice:

```ruby
    query = ParamsToQueryService.new(Meeting, current_user).call(params)
    # ↳ When there is a project_id filter in the URL this is added as a filter to the query

    query = apply_default_filter_if_none_given(query)

    if @project
      query.where("project_id", '=', @project.id)
      # ↳ This adds the filter regardless and we end up with the ProjectFilter twice in the list
    end
```

I have added a workaround in [222fef2](https://github.com/opf/openproject/pull/15162/commits/222fef23c9388b489187b261d89ebc593d31dac7) but I'm not sure if we should rather fix the underlying problem.

**Comment by oliverguenther** [comment]
I've extracted that into a separate PR: https://github.com/opf/openproject/pull/15281

**Pull request merged**
