### PR TITLE
Significant performance improvment !!

### PR DESCRIPTION
**Pull request by vikaskedia**

### CODE REVIEW

**Comment by b12f** [comment]
Hi @vikaskedia and thanks for your PR! Unfortunately, this only changes the docker development environment, and misses all other instances (ci, pullpreview, documentation, etc.). I'm also unsure whether this would constitute a breaking change regarding compatibility, requiring us to publish as v12 instead of v11.3.0 next.

What do you think @ulferts ?

**Comment by ulferts** [comment]
@crohr is currently attempting to move everything to PG 12. Don't know why he is not using 13 (**/cc** @crohr), though. What we definitely need is an update path for users having used docker before as PG needs to have scripts run when upgrading between major versions so that the existing data is kept.

Other than that, I would be fine with having a DB update only for docker. OP is running fine on PG 13 so why not use it. And I also wouldn't say we have to wait for OP 12.0 in order to do that as the docker image is self contained and AFAIK does not allow (without modifications) to have an external DB e.g. a cluster.

**Comment by crohr** [comment]
> @crohr is currently attempting to move everything to PG 12. Don't know why he is not using 13 (**/cc** @crohr), though. 

Probably because https://www.postgresql.org/download/linux/debian/ lists postgres-12 in their example script, which I supposed references the recommended version they want us to use. But I'm happy to make it postgres 13.

> What we definitely need is an update path for users having used docker before as PG needs to have scripts run when upgrading between major versions so that the existing data is kept.

Yes indeed

> Other than that, I would be fine with having a DB update only for docker.

Not sure I understand. What about the package installations?

**Comment by ulferts** [comment]
> Not sure I understand. What about the package installations?

I mean that as far as I am concerned, we don't necessarily have to keep the PG version used by the packaged installation in lockstep with the docker installation. As our requirements at the moment are PG >= 9.5 (soon to change), I think it ok if one where higher than the other. But of course, the package installation needs to be updated as well. Ideally, we should update them constantly (at least every major version)

**Comment by ulferts** [comment]
@vikaskedia thanks again for the proposal. As outlined, we are going to support PG 12/13 as soon as we get around to doing it but cannot simply merge this PR due to a lack of a migration path for existing installations.

**Pull request closed without merging**
