### PR TITLE
[26647] Quick wins work packages fullscreen view on mobile

### PR DESCRIPTION
**Pull request by HDinger**
Change mobile full view. 

https://community.openproject.com/projects/openproject/work_packages/26647/activity

### CODE REVIEW

**Comment by HDinger** [comment]
bildschirmfoto 2017-12-01 um 09 49 41

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/311af161feb0d1bc2b25ec3db5a72610ed9a4f07) (deployed commit: 56c82f1848a5bc16f65d2af44e5c83ef9fb6376f).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/ab53fa1ec99c34e714d4be1d349bdeb21698ff1b) (deployed commit: 56c82f1848a5bc16f65d2af44e5c83ef9fb6376f).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/2a6dc7087aff33a5c2f116b70bdce59a7a504547) (deployed commit: eb24a9f84df596c69cb3349f68a99cd76f61d6c2).

**Review by oliverguenther — APPROVED** [review]
Changes LGTM. The ticket specifies the comment button which is missing, has that been included?

Depending on feed back from @lindenthal , good to merge from my side.

**Comment by HDinger** [comment]
The comment button has been taken out of scope. There is a little remark at the end of the description in the WP.

**Pull request merged**
