### PR TITLE
fix save button state

### PR DESCRIPTION
**Pull request by 0xF013**
[`* `#17263` Save button displayed for existing queries even when no changes have been performed`](http://community.openproject.org/work_packages/17263)
- [x] check columns

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://0xf013-fix-17263-query-save-button-state.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://0xf013-fix-17263-query-save-button-state.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@0xF013 this breaks various specs/cukes.

**Comment by ulferts** [comment]
@0xF013 didn't see the label, sorry.

**Comment by 0xF013** [comment]
@ulferts I still can't understand what is breaking them

**Comment by 0xF013** [comment]
@ulferts @myabc could you run this on your CI or try `bundle exec rspec spec/features/menu_items/query_menu_item_spec.rb` locally? I can't reproduce the spec fail

**Comment by ulferts** [comment]
@0xF013 will do

**Comment by ulferts** [comment]
@0xF013 I do have the same problems but I believe it has to do with [Problems with selenium and the FF35](https://code.google.com/p/selenium/issues/detail?id=8387). Which version of FF do you have?

**Comment by 0xF013** [comment]
@ulferts was 34.0.5. Updated to 35, fails like as expected. Can we tell the CI which version of FF to use?

**Comment by ulferts** [comment]
@0xF013 can you please rebase this? Rebasing should also fix the FF35 problem.

**Comment by 0xF013** [comment]
@ulferts thank, rebased. waiting for Travis

**Comment by 0xF013** [comment]
@ulferts @myabc that was a legitimate regression. pushed, waiting

**Comment by myabc** [comment]
@0xF013 thanks for double-checking!

**Comment by myabc** [comment]
@0xF013 this works much better. Unfortunately, changing column configuration (i.e. through the Columns/Sort by/Group by dialogs) does not mark the query as dirty.

**Comment by 0xF013** [comment]
@myabc noted

**Comment by 0xF013** [comment]
@myabc added flag modification where I know. Hope I didn't miss other places

**Comment by myabc** [comment]
@0xF013 looks good :+1:

**Pull request merged**
