### PR TITLE
[22858] Add updated_on to project admin table

### PR DESCRIPTION
**Pull request by oliverguenther**
This adds an 'updated on' column to the admin project table,
and extends assocations to `Project` to cause the project's updated_on
to be updated.

https://community.openproject.com/work_packages/22858/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-feature-project-activity.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://oliverguenther-feature-project-activity.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by machisuji** [comment]
Good to merge once travis agrees. :+1:

**Comment by ulferts** [comment]
Closed in favor of: opf/openproject#4390

**Pull request closed without merging**
