### PR TITLE
Move jshintrc to frontend folder

### PR DESCRIPTION
**Pull request by floriank**
This has been bugging me for quite some time now.

Simply executing

```
gulp lint
```

in `./frontend` does nothing, as the `.jshintrc` is located in the root
folder of the application. This commit will move the `.jshintrc` to
the `frontend` folder.

Ticket: https://community.openproject.org/work_packages/18869

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-fix-move-jshintrc.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-fix-move-jshintrc.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
:+1:

**Comment by floriank** [comment]
I am not really sure why the protractor test fails. any ideas @0xF013 ?

**Comment by 0xF013** [comment]
@floriank one of those tests is flickering for reasons unknown.

**Pull request merged**
