### PR TITLE
Scrolling into view the activity component

### PR DESCRIPTION
**Pull request by aleixsuau**
https://community.openproject.com/projects/openproject/work_packages/34341

This pull request:

- [x] ScrollsintoView the activity component with the activityNo === to URL anchor

### CODE REVIEW

**Review by ulferts — CHANGES_REQUESTED** [review]
The activity is scrolled into view again, but, at least when sorting the activity with the newest on top, only the header of the referenced activity is visible (activity `#5` is referenced):

image

The actual activity can still not be read by the user without scrolling.

If I where to apply the hack of adding a `setTimeout` to the `scrollIntoView` the result would look like expected

image

The user can now read the activity right away without scrolling.

But who would use a hack like this? Any idea how a proper solution might look like?

**Comment by aleixsuau** [comment]
Hi @ulferts ,
I created [this 'Idea' work package](https://community.openproject.com/projects/openproject/work_packages/34426) to improve this behavior later and get the fix working asap. I did so because I found some unexpected behaviors:

- The activities are not available in the DOM on the parent WorkPackageActivityTabComponent.ngAfterViewInit which means that we don't have control over the rendering. This is probably why we are scrollinIntoView from the element itself (UserActivityComponent). Probably we are injecting dynamically some components here without communicating it to Angular. I would need to debug it.

- The scrolling container seems to be wrong or not fully rendered when we scrollIntoView the element (the element is scrolled to the bottom of the page) but it's ok after the SetTimeOut. This is something to debug also.

In these cases the setTimeout is usually a sign of control loss and, in practical terms, it triggers a Change Detection Cycle for the entire app. Wrapping it with this.ngZone.runOutsideAngular avoids the Change Detection Cycle (and its performance costs), remaining only the ugly hacky forms. This is what I did in the last pull request. This way we could have the fix working soon and do all the debugging and improvements later, on another task. What do you think?

**Review by ulferts — CHANGES_REQUESTED** [review]
Fixing this bug now and taking a look at the 'why' later works for me in this case @aleixsuau. The hack is not that huge and with the added ngZone (which I did not know, thank you for that) it seems bearable.

That being said and probably unrelated to your fix so far I have noticed that when clicking on an activity, the anchor is not appended correctly, e.g.
`http://localhost:4200/projects/aaaaa/work_packages/100/activity#activity-30?#activity-30`

Apart from looking wird, following that url will not result in having the activity scrolled into view.

Could you please look into this?

**Comment by oliverguenther** [comment]
After some debugging, I found out that the double hash issue is cause by a bug in uirouter and opened a pull request with them https://github.com/ui-router/angular/pull/847

**Comment by ulferts** [comment]
Merging now as the anchor bug is unrelated

**Pull request merged**
