### PR TITLE
Hint that a WP has relations

### PR DESCRIPTION
**Pull request by wielinde**
https://community.openproject.com/projects/openproject/work_packages/25814/activity

### CODE REVIEW

**Comment by oliverguenther** [comment]
I like the idea, my two remarks:

1. Why not `10+` when more than 10 relations exist? I find the dots confusing
2. You need to add that to the details tab row as well (ideally, extract into a small directive).

**Comment by wielinde** [comment]
@oliverguenther 

1. I remembered the two dots from some twitter client and remembered that I liked it. But I am not too much attached to it.
2. Yes. Tried that and stopped as the data is not available. Please see ticket.

**Comment by oliverguenther** [comment]
Relations _may_ be embedded into the work package payload - currently if you request a single work package through `/api/v3/work_packages/:id`. The work packages in the table do not have their relations or activities embedded and thus need to be loaded explicitly.

Since this information is used only for seeding the frontend relations data, it will never get updated later on (e.g., after adding or removing a relation).

To show the indicator at all times with the last known value, please do the following:

1. Separate this badge as a small 1.5 `.component` [see here](https://docs.angularjs.org/guide/component) and add a binding for the work package id.

2. Inject the `wpRelations` service and call `wpRelations.require(<work package id>)` to ensure the relations are being loaded. This call will return a cached value if it already exists.

3. Subscribe to changes to the relations state with

```
wpRelations.state(<work package id>) // Get the single state object
.values$() // Return the RX observable for the value stream (states have values and non-value streams)
.subscribe((relationsForWpId) => ....)
```

**Review by oliverguenther — CHANGES_REQUESTED** [review]
Relations _may_ be embedded into the work package payload - currently if you request a single work package through `/api/v3/work_packages/:id`. The work packages in the table do not have their relations or activities embedded and thus need to be loaded explicitly.

Since this information is used only for seeding the frontend relations data, it will never get updated later on (e.g., after adding or removing a relation).

To show the indicator at all times with the last known value, please do the following:

1. Separate this badge as a small 1.5 `.component` [see here](https://docs.angularjs.org/guide/component) and add a binding for the work package id.

2. Inject the `wpRelations` service and call `wpRelations.require(<work package id>)` to ensure the relations are being loaded. This call will return a cached value if it already exists.

3. Subscribe to changes to the relations state with

```
wpRelations.state(<work package id>) // Get the single state object
.values$() // Return the RX observable for the value stream (states have values and non-value streams)
.takeUntil(scopeDestroyed$(this.$scope)) // Unsubscribe the observer when this scope is destroyed
.subscribe((relationsForWpId) => this.updateCountScope)
```

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/8624a464328ba5dd5b5a7fd75061523f4c2a6769) (deployed commit: 1c497c12669972cc9a063d0bf5a9699c16b6efc2).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/edb9d0ee6e1bd9d68510275b33e5af9054137a8f) (deployed commit: 1c497c12669972cc9a063d0bf5a9699c16b6efc2).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/af07536977104adcd876dc37f3cf358c565c94a6) (deployed commit: 98dc0a8cc3022cd916030440c31b4e40b041cab5).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/2fe7338d646323e495efa0323dac3f1043e107be) (deployed commit: 98dc0a8cc3022cd916030440c31b4e40b041cab5).

**Comment by wielinde** [comment]
@oliverguenther Thanks for all the input. I think it is ready. Could you please give it another look?

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/e52873d340508934b73830f21db877ae3effac38) (deployed commit: 070f1e660105ee47face3ade7535854bb7a380df).

**Comment by lindenthal** [comment]
@wielinde I just had a look at it on Win 10 with Chrome. The badge is not aligned correctly.

image

**Review by oliverguenther — APPROVED** [review]

**Comment by oliverguenther** [comment]
I like the badge position, it's common to place them shifted upwards a bit. Merging this for now.

**Comment by wielinde** [comment]
@lindenthal Could you please be more specific. What is not aligned? The number inside the circle or the circle in regards to the word "Relations"? Or both?

**Pull request merged**
