### PR TITLE
19479 Set up Sauce Labs for Karma tests

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/19479

Relates to #2245

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-19479-karma-sauce-labs.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-19479-karma-sauce-labs.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
I have no idea what this is:
- What is sauce labs?
- Why do we need it?
- Why is the WP description empty?
- Is this PR WIP?

**Comment by myabc** [comment]
@NobodysNightmare answered in #2245.

**Comment by NobodysNightmare** [comment]
Haha, answering with a link ^^

Still, this PR should be WIP, shouldn't it?

If I understand you correctly, we would disable the travis jobs for frontend and move that part to the sausage labs, right?

edit: also https://saucelabs.com/ does not respond for me ^^

**Comment by myabc** [comment]
@NobodysNightmare 

> Still, this PR should be WIP, shouldn't it?

Yep. Oversight on my part. This should target 4.2 (although I'd have loved to have had this in for 4.1). Hopefully @floriank and I can work on this during our _Übergabe phase_.

**Comment by myabc** [comment]
> sausage labs, right?

How :de: of you.

**Comment by floriank** [comment]
> sausage labs, right?

Omnomnomnomnomnom :hamburger: 

> our Übergabe phase.

If there is the time for that.

**Comment by myabc** [comment]
> If there is the time for that.

It's more like a coronation. :crown:

**Comment by floriank** [comment]
Sounds like the crown from that one NiN song - "Hurt" it was, methinks

**Pull request closed without merging**
