### PR TITLE
Mouse cursor file upload dropbox

### PR DESCRIPTION
**Pull request by kgish**
Trivial change but this was bugging me so I thought what the heck.

### CODE REVIEW

**Comment by oliverguenther** [comment]
You've committed changes to the Gemfile.lock due to you adding a plugin. This will cause all tests to fail, please revert that change.

**Comment by kgish** [comment]
Sorry, that was careless of me. What's the best way to remove Gemlock.lock from my PR?

**Comment by oliverguenther** [comment]
> Sorry, that was careless of me. What's the best way to remove Gemlock.lock from my PR?

Don't remove it, just remove that change, e.g., `git checkout dev -- Gemfile.lock`.

**Comment by oliverguenther** [comment]
Please re-open PR when conflict is resolved.

**Comment by kgish** [comment]
For sake of clarity, I just created a new PR: https://github.com/opf/openproject/pull/5185

**Pull request closed without merging**
