### PR TITLE
Feature/enterprise-css-variables

### PR DESCRIPTION
**Pull request by wielinde**

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/8165c20c47ce698c31cd3501c307f8b6b23fded5) (deployed commit: 8c71c468850c9133577f58016ea23d65fc5b16c4).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/2451d2de2532609cf84b0ce678c4fe5d3e400f1f) (deployed commit: e844b32b6b514289793e2013b6a09e010ce53e17).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/405599bd70059f6085a7d4cc7458ed61901433ad) (deployed commit: c742e7f853c7fd6d613c353b90cb672599b94a4d).

**Comment by machisuji** [comment]
@wielinde pull preview failed mit

```
1486464908915: ERROR:  relation "design_colors" does not exist
1486464908915: STATEMENT:  CREATE UNIQUE INDEX  "index_design_colors_on_variable" ON "design_colors"  ("variable")
```

Fehlt da vielleicht eine Migration? Ah nein es gibt eine. Aber vielleicht muss man [das hier](https://github.com/opf/openproject/pull/5178/files#diff-dea80d6b8558bdcb78e7727d299003e6R9) ausserhalb des `create_table` blocks ausführen.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/85c920c5f54b398c7be1fd5cbbcffbd1c36cd73b) (deployed commit: 96252ae18ccc2c10bcf7e1c316287320befb6d26).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/3b04af8b29d4ac137f27d499f2b959467f07ac91) (deployed commit: 96252ae18ccc2c10bcf7e1c316287320befb6d26).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/6c8a8de4f04ec48cd1b1d4ea235ef69f5b1874d0) (deployed commit: b84dc0be5be5d30082f7d2b7e705430664228881).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/a9e1b7aaaf3c542d79799b9e248349de975af6b9) (deployed commit: 2cec1b246e5489bd152707523242c118c1744d81).

**Comment by oliverguenther** [comment]
@wielinde Lots of remarks from code climate regarding the code. Could you have a look at them? https://codeclimate.com/github/opf/openproject/pull/5178

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b3b974ddef55485ded4ff90cec0e0a511db7df90) (deployed commit: 3c7bf225c61e36c413c03cf89502b728aec45d11).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/5273d51e19417fcac299cb5f072356cd8ebbe06c) (deployed commit: 9d06e6fac70ab706aedbb3c2c622d487036bbb84).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4d82e79db93672e6e8fda5143d8160f361a97e19) (deployed commit: 6463657a9edfd5ae5690461c700f84e956afe4d4).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c97768d08859022bc047885596211ac726717fbd) (deployed commit: d46a177e4cf8edfe0261b825592ff7409a5b515e).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/db3c4ade424413e04e56acbc3e76cdbe511a29ba) (deployed commit: a3eedb0024cf726a7a66610072b61a656fb9a671).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/46ed0f4b43520ca87e3c40b9d27ac220ff4e12ba) (deployed commit: f0cffac931d6f30e185d1bf0ea1c0189d1c19f89).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/11fb26fa9433b1d943e5e0c051fe32eb0614eef2) (deployed commit: c9a8ecfe81e1948d8e8d15193fc79cc5a6d039ac).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/8128578011b16c7d2a61ea0e15db33b4e817f09c) (deployed commit: a19b258a92f2ea49cb114c74d4d6df53c3ea46fc).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/efa59fe517dba76aa34efcb6924001287c39d0a3) (deployed commit: 657d3335e896256924b7f77455b20c6563ad3e97).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/f1c4fa2abb8870885ab92edb0974f99c5fe1141f) (deployed commit: 814c2db1ff6039f22e210245f2fe228713e6b230).

**Comment by lindenthal** [comment]
hi @wielinde, you have the WIP and the needs review tag assigned. Actually we use them mutually exclusively here. Is it ready for review or are you working on it?
Best
NIels

**Comment by oliverguenther** [comment]
It is in review and being worked on. I think both tags together are fine in this situation.

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
