### PR TITLE
[19428] Remove label truncation [fixup]

### PR DESCRIPTION
**Pull request by myabc**
Continuation of #2873 

https://community.openproject.org/work_packages/19428

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-fix-19428-label-truncation.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-fix-19428-label-truncation.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@NobodysNightmare RE: your comment in the original PR https://github.com/opf/openproject/pull/2873#issuecomment-94795485

> I find it also disturbing that some field labels (e.g. responsible) already get overlapped by their input fields at a window width of ~1500px. 

Agree with you here. I think think we ought to give the labels a larger default, but I'm unsure as to whether this is in the scope of this WP/PR. My memory is a little fuzzy these days, but I seem to remember this working better previously (thanks to various _quick wins_ along the way though, there has been a good deal of _churn_ in this part of the view code)

**Comment by NobodysNightmare** [comment]
I am not sure if that was better anytime. The truncation issue and especially the low width for labels was apparent quite "from the start" (from my point of view).
So I think the width was always that way. Not truncating stuff made it a whole lot better anyway ^^

**Comment by NobodysNightmare** [comment]
For my taste most of the time the values get too much space, while the labels get to few. However, this is all subjective stuff, isn't it?

edit: That means: until now, I did not yet look at your PR

**Comment by floriank** [comment]
@myabc: ping. could you check what is left to do here. Thanks!

**Comment by floriank** [comment]
@myabc Second ping - is there still anything you have here? Otherwise i would take a final look tomorrow to get it into the release.

**Comment by myabc** [comment]
@floriank ready for review. In retrospect, I'd probably chose to simplify things and make `TabularFormBuilder` apply the `-required` modifier to the `form--field` container.

**Comment by floriank** [comment]
I'd say this is good enough for now. There is still an issue if the label content gets too long, e.g. for "Responsible" will lap under the select. A fix in the future could include using wider labels, but this would be out of scope in my opinion.

**Comment by floriank** [comment]
@NobodysNightmare can you have another look?

**Comment by NobodysNightmare** [comment]
I had another look with @floriank.

When opened in a modal (e.g. backlogs) it still looked ugly. The best quick win we could find was to allow wrapping for the two column layout of the edit form.

This means on small screens (and modals) the layout will only have one column, but will not be ugly. Opinions may vary...

**Comment by myabc** [comment]
@NobodysNightmare 

> This means on small screens (and modals) the layout will only have one column, but will not be ugly. Opinions may vary...

That makes sense.

**Pull request merged**
