### PR TITLE
18372 migrate to ui select in modals

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/18372
- [x] sorting
- [x] group by
- [x] columns
- [x] assimilate #2457

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://feature-18372-migrate-to-ui-select-in-modals.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://feature-18372-migrate-to-ui-select-in-modals.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
WIP, because this doesn't actually work yet.

@ulferts this _might_ help if you decide to use ui-select on the timelines edit page. / @0xF013

**Comment by myabc** [comment]
https://community.openproject.org/work_packages/18372

**Comment by myabc** [comment]
@0xF013 can you incorporate the changes from #2457 into this PR?

**Comment by 0xF013** [comment]
@myabc yes

**Comment by myabc** [comment]
@0xF013 rebased. will give it another check

**Pull request merged**
