### PR TITLE
[25356] Icons in toolbar not aligned correctly

### PR DESCRIPTION
**Pull request by HDinger**
This takes care of the icon alignment within the toolbar. 
I am aware that this solution is a bit ugly. Since unfortunately flex boxes within buttons are not supported by Firefox, it was the only way I found which works for all browsers and operating systems. 

https://community.openproject.com/work_packages/25356/activity

### CODE REVIEW

**Comment by HDinger** [comment]
bildschirmfoto 2017-05-26 um 11 05 58

**Comment by HDinger** [comment]
@oliverguenther What do you think? Is this pixel profiteering acceptable?

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/dd6015ac1af1d01b8646a1d4c9127eb7b0cf7648) (deployed commit: af5b22523a35fbcbf4e6e5aca47699d407100460).

**Comment by lindenthal** [comment]
@wielinde und @HDinger the alignment is still not correct on Windows/Chrome. Please have a look at the red part.
toolbar3

The icons are also still too small.

**Comment by wielinde** [comment]
@HDinger I can confirm that Windows Chrome shows that layout.

**Comment by wielinde** [comment]
@HDinger I allowed myself to work a little bit on this topic. I have not solved the core problem. However, I added a class "toolbar-icon" to all icon buttons in the toolbar so that we finally can make them squared at least.

The original problem is somewhat nasty. I believe, but I have no prove, that the problem comes somehow from the webfont. I believe the Glyphs are not centered, or bigger. I believe that as the printend glyphs are bigger than the 14px line-height/font-size. If I add a color to the icon's background, you can see, that the glyphs quite often stand out at the ceiling.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/6653744a26fe298c1e0ed2efe553bf21e402df5f) (deployed commit: 5c383eb9f3c95884fe6448df7b2ab1b051789cae).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/91922becaac5ac888a930e4a3e2844fa90d36382) (deployed commit: 4bf644552641dd3e1f38bebe1d95631f859f6ef0).

**Comment by HDinger** [comment]
@wielinde Thanks a lot, for taking care! I had a similar assumption that the reason is somewhere hidden in font, but I have no proof for that either.

**Comment by wielinde** [comment]
@oliverguenther This branch does not completely solve the original problem yet but it still would improve the dev branch as it renders toolbar buttons that only have an icon as squares. So I recommend merging it into dev. Then, in a more fundamental approach, in a second PR, I will improve the icon font itself and get to the core of many alignment issues. Agreed?

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/3b5635a36e87986906c3eebbacd37323ddc506e1) (deployed commit: ddc3d01f299a487a044aae289d182276746e0f0c).

**Pull request merged**
