### PR TITLE
Feature/rails3 sortable timelines columns

### PR DESCRIPTION
**Pull request by nkenneweg**
Make rows sortable. Issue: https://www.openproject.org/issues/1913

### CODE REVIEW

**Comment by hschink** [comment]
Even after a merge I cannot see the changed hover mouse cursor of #409... :alien:

**Comment by nkenneweg** [comment]
@hschink you are correct. Forgot to set the css class on the columns field.

**Comment by nkenneweg** [comment]
Now there should always be a different cursor.

**Comment by hschink** [comment]
Looks good! Thanks :cherry_blossom:

**Pull request merged**
