### PR TITLE
[29288] Wait for postgres to start up in public image

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.com/wp/29288

### CODE REVIEW

**Comment by l0rn** [comment]
As some one who has been affected by this bug i can say that 5x2 seconds might not be enough, if postgres exited dirty previously it could take some minutes even, depending on database size.

To think out of the box: i think the docker setup for openproject is wrong in the first place since dockers main purpose is to isolate _one_ process. So my long term advise would be to exclude redis, postgres and all the other services and provide a sane docker compose. readyness checks can be made in docker-compose very nicely.

**Comment by oliverguenther** [comment]
Thanks Jonatan for chiming in

I believe we had a docker-compose configuration for the CE image and I'm not sure why that was discarded. Maybe @crohr  and @machisuji  can chime in here, this isn't really my area of expertise.

**Comment by crohr** [comment]
@oliverguenther maybe we can make the number of retries an env parameter with the default being 5?

@l0rn at the time this was written docker-compose was not in the same state as it is today, and having a single docker command to launch everything was pretty nice, especially since there are a few moving parts involved. Granted if this was to be done today we might go a different route.

**Comment by oliverguenther** [comment]
Waiting for up to 30s now with a configurable retry count of 10

**Review by crohr — APPROVED** [review]

**Pull request merged**
