### PR TITLE
Apple Silicon Support (arm64)

### PR DESCRIPTION
**Pull request by ricardobalk**
I added support for successfully building the Dockerfile on Apple Silicon (M1 / M2 CPUs) and running OpenProject on `http://localhost:8080`.

```sh
ln -s docker/prod/Dockerfile ./Dockerfile
docker build --no-cache -t openproject/community:dev .
docker run -it -p 8080:80 \
  -e OPENPROJECT_SECRET_KEY_BASE=secret \
  -e OPENPROJECT_HOST__NAME=localhost:8080 \
  -e OPENPROJECT_HTTPS=false \
  openproject/community:dev 
```

> Note: I used the .NET installation script from `https://dot.net/v1/dotnet-install.sh`, because Microsoft does not include the `dotnet-runtime-6.0` package, not even when [following the instructions on their website](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian). You can try this yourself: `docker run --rm -it debian:11-slim`.

### CODE REVIEW

**Comment by ulferts** [comment]
Hey @ricardobalk , first of all, thank you for the contribution and welcome to the group of OP contributors!

We are currently in the last stretch of a feature development cycle so it might take us a bit to take a look at this. 

First impressions:
* updates the Debian used
* changes the way the dotnet runtime is integrated which might conflict with he BIM edition building (/cc @wielinde)
* Do we have anybody with a Silicon chip to verify the changes? Maybe @crohr

**Comment by ricardobalk** [comment]
No need for an actual device with Apple Silicon, it could as well be tested on a Raspberry Pi 4, which also has an arm64 processor. Haven't tried that out with OpenProject yet. However, in general, I have been to build Docker images locally on my Apple with M1, pushing it to Docker Hub, pulling it on my Raspberry Pi 4 and running them there.

What exactly is that BIM edition about?

**Comment by ulferts** [comment]
@ricardobalk the BIM edition is a [variant of OpenProject tailored to the building industry](https://www.openproject.org/blog/bim-project-management-software-on-premises/). 

Especially the dotnet runtime changes will need to be looked at by @wielinde as that runtime is only necessary for BIM. Otherwise, it will not be used at all. 

Turns out we do have a couple of devs with M1 chips so that should not be a problem.

**Comment by ricardobalk** [comment]
Updates on this? Does the `dev` branch run on arm64<small>\*</small> at the moment? And can this PR be closed?

**Pull request closed without merging**
