### PR TITLE
Hide Mail address by default

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work package

https://community.openproject.org/work_packages/20574
## Description

For the largest part this PR only adds GPL headers (and changes the default of a DB column).

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-private-mail-by-default.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-private-mail-by-default.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Good to merge once travis agrees.

**Comment by ulferts** [comment]
One spec fails:

`/spec/lib/api/v3/users/user_representer_spec.rb`

**Comment by NobodysNightmare** [comment]
Failing spec?

**_deleted!**_

**Pull request merged**
