### PR TITLE
Fix/angular timelines show warning 6364

### PR DESCRIPTION
**Pull request by manwithtwowatches**
Maybe someone could explain to me why the explicit scope.$apply() is necessary.

### CODE REVIEW

**Comment by myabc** [comment]
@manwithtwowatches `scope.$apply()` is needed because the function in question is called as a `setTimeout` callback.

**Comment by myabc** [comment]
Unlikely the Travis CI spec failure is related to this change (probably flickering spec). Will merge. / @meeee

**Comment by mfrister** [comment]
Yep, looks like flickering spec. Something setting the locale to german and not setting it back.

Did you keep the branch intentionally?

**Comment by myabc** [comment]
@meeee 

>  Did you keep the branch intentionally?

Gone. I sometimes clean-up branches in batches (with git-sweep) instead.

**Comment by mfrister** [comment]
git-sweep sounds like a tool I want. I'll try it :+1:

**Pull request merged**
