### PR TITLE
[WIP] Rewrite query tests

### PR DESCRIPTION
**Pull request by tilt**
:exclamation: Depends on https://github.com/opf/openproject/pull/693

### CODE REVIEW

**Comment by ulferts** [comment]
Hey Till,

can you please rebase/merge as appropriate.

Some of the PR should already be part of dev now, so rebasing would ease the review.

Best

Jens

**Comment by tilt** [comment]
Hey, sure - I think I've only transferred like 20% of the tests yet

**Comment by tilt** [comment]
Ok @ulferts - rebased it is!

**Comment by tilt** [comment]
Postponed

**Pull request closed without merging**
