### PR TITLE
Remove summary attribute from Projects

### PR DESCRIPTION
**Pull request by leewaa**
Work package: https://community.openproject.org/work_packages/20771
- [x] Remove all traces of the summary attribute from Project modal and views.
- [x] Adjust specs
- [x] Display Project description in one line, trunctated

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://leewaa-20771-remove-summary-field.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://leewaa-20771-remove-summary-field.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by leewaa** [comment]
Opps, had issues with hub

**Comment by leewaa** [comment]
@oliverguenther This is ready to merge, review at will

**Comment by oliverguenther** [comment]
:+1:

**Pull request merged**
