### PR TITLE
Replace hand-rolled Project.find with FriendlyId

### PR DESCRIPTION
**Pull request by myabc**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-friendly-id.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-friendly-id.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
Nice to see that "there is a gem for that" :+1:

**Comment by myabc** [comment]
@NobodysNightmare the gem can do a lot, lot more – but this is the minimally invasive approach. Its patching of Rails 4 finder methods is much better tested than our own.

**Comment by ulferts** [comment]
:+1:

**Pull request merged**
