### PR TITLE
[28818] Bottom entry in work package context menu not visible in Gantt chart on smaller screens

### PR DESCRIPTION
**Pull request by HDinger**
Let the context menus always fit into the page.

https://community.openproject.com/projects/openproject/work_packages/28818/activity

### CODE REVIEW

**Comment by HDinger** [comment]
### Before
bildschirmfoto 2018-10-26 um 09 12 04

### After
bildschirmfoto 2018-10-26 um 09 11 20

**Comment by oliverguenther** [comment]
It's a bit repetitive and we'll run into the same issue once we create another dropdown menu class. I suggest you extract some default params such as `colission: flipfit` and `of: this.$element` into the `OpContextMenuTrigger` base class and use `_.assign` in the subclass to override it.

**Comment by HDinger** [comment]
👍 Done

**Comment by oliverguenther** [comment]
Thanks :+1:

**Pull request merged**
