### PR TITLE
Switch to single select when creating membership

### PR DESCRIPTION
**Pull request by basiszwo**
https://community.openproject.org/work_packages/21998/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://21998-single-select-on-members.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://21998-single-select-on-members.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
https://community.openproject.org/work_packages/21998/activity

**Comment by ulferts** [comment]
I am no judge when it comes to the design. To me it looks like the requirements have been fulfilled.

There is an inconsistency between the accessibility screen and the non accessibility screen. While it is only possible to select one role in the non accessibility screen due to the dropdown, the accessibility screen has check boxes which allow for selecting multiple roles.

**Comment by oliverguenther** [comment]
I've discussed this inconsistency with Stefan, and there's another inconsistency with the inline editing, which also shows multiple checkboxes. While I initially agreed with @ulferts that I preferred selects in both regular and accessible create, I don't think it matters much.

I'm merging this, and we can replace it on a very short notice If we agree to a common style.

**Pull request merged**
