### PR TITLE
when type is changed the status is updated also Meets #14592 and #7515

### PR DESCRIPTION
**Pull request by slawa85**
[`* `#7515` Copy/Move does not update available statuses`](https://www.openproject.org/work_packages/7515)
[`* `#14592` Status displayed in bulk edit do not respect workflow`](https://www.openproject.org/work_packages/14592)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://netfighter-feature-update-status-when-type-is-changed-7515-1459.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by mfrister** [comment]
@slawa85 Could you please address the issues houndci found? I'm not sure all make sense, but I saw at least a few cases where the comments are valid.

**Comment by slawa85** [comment]
This PR should be merged after this one https://github.com/opf/openproject/pull/1974

**Comment by myabc** [comment]
@ulferts @slawa85 is this PR still relevant?

**Comment by NobodysNightmare** [comment]
The problem behind this PR is still real, the user is proposed options that can't be reached.

However, it is discussable whether:
- full strictness of workflows should be enforced (e.g. prohibit to "skip" a status)
- it would suffice to employ more meaningful error messages as an alternative

As this PR is not mergable in its current state, we decided to close it for the time being and provide an apropriate fix later.

**Pull request closed without merging**
