### PR TITLE
Update the link to the upgrade information doc

### PR DESCRIPTION
**Pull request by lindenthal**

### CODE REVIEW

**Comment by lindenthal** [comment]
Link to the issue on openproject:
https://www.openproject.org/issues/1038

**Comment by tessi** [comment]
The wiki page you are linking to (https://www.openproject.org/projects/support/wiki/Upgrade) is currently empty.

**Comment by lindenthal** [comment]
I guess it is a trade off. In my opion it is more useful to have a link to an empty wiki page than a link to a different application. 
I also created another ticket to prepare that wiki page.
https://www.openproject.org/issues/1039

**Comment by tessi** [comment]
I'll merge this PR, as Niels is right. The old link points to information, which is not applicable anymore (as it is about a rails 2.3 chiliproject, and not rails 3.2 openproject).

Progress on the upgrade doc can be inspected here: https://www.openproject.org/issues/1039

**Pull request merged**
