### PR TITLE
update gon version to 4.0.3

### PR DESCRIPTION
**Pull request by marutosi**
Ref: #2592

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-gon-4-0-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-gon-4-0-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
Thnks for the PR - however, this seems to contain other stuff besides the update to gon. Is this intended?

**Comment by marutosi** [comment]
Yes. Gemfile is broken.

**Comment by marutosi** [comment]
https://github.com/opf/openproject/pull/3015

**Comment by NobodysNightmare** [comment]
closing because it is apparently superseded by https://github.com/opf/openproject/pull/3019

**Pull request closed without merging**
