### PR TITLE
[25659] Buttons with inverted color scheme

### PR DESCRIPTION
**Pull request by HDinger**
Invert the colors of highlighted buttons.

https://community.openproject.com/projects/gmbh/work_packages/25659/activity

### CODE REVIEW

**Comment by HDinger** [comment]
bildschirmfoto 2017-12-15 um 17 15 39

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b7099690c40c815f7651bae65754ae148982a6bb) (deployed commit: f7c3e0a02a76a57d2c60b0e7f369d431913a1539).

**Comment by lindenthal** [comment]
Hi @HDinger and @wielinde 

I just had a look at this at PP. I think this looks much better now.

I would like to extend this PR a little.

On the homescreen we currently have three green buttons.

grafik

Let's have only the button for the enterprise edition green. The other two buttons should be blue with white font.

What do you think?

Best
Niels

**Comment by wielinde** [comment]
@lindenthal, @HDinger,

I agree that we should try to use the green "alt-highlight" only once per screen. Then we can indicate the user what we believe that she should do next and lead her through the onboarding.

I doubt that the Enterprise Edition is the most important button on that screen, when a user is onboarding. Only a satisfied user will reach out for the Enterprise Edition as she wants more of the awesomeness. Product satisfaction is the most valuable thing on the long run, I believe.

**Comment by lindenthal** [comment]
Hi @wielinde 

I agree. Let's have a look at this in a different PR.

Best
Niels

**Comment by wielinde** [comment]
LGTM 👍

**Pull request merged**
