### PR TITLE
[20248] display errors in the WP details pane via NotificationsService

### PR DESCRIPTION
**Pull request by floriank**
This will change the current errors (which are attached to the the individual field at the moment) into a notification provided by the previously introduced `NotificationsService`.

This Pr will thereby meet the requirements for https://community.openproject.org/work_packages/20248.
## Things left to do/discuss
- [ ] Accessibility - I think the plan from the specification might or might not work (currently, the focus stays with the erroneous field
- [ ] "continue editing" - see above
## Out of scope
- "Create another WP like this" functionality in successful updates and/or after successful creation

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-feature-20248-error-collection.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-feature-20248-error-collection.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Assuming to be WIP as there are ToDos left unchecked.

**Comment by ulferts** [comment]
There is a glitch in behaviour.

When I initially clear the work package subject an error message is displayed (to be expected):

image

Now when I fix the problem and enter a subject, and save, the work package is saved ok but another error notification pops up with the same error message than before:

image

**Comment by ulferts** [comment]
In order to get this PR merged I propose:
- fixing the glitch
- adding tests 
- Postpone accessibility and "continue editing" so a later PR.

**Comment by floriank** [comment]
> Postpone accessibility and "continue editing" so a later PR.

That's alright with me, I will address the glitch later today. There are general tests for the functionality already though, but not for the error cases.

@basiszwo these tests can be time consuming to write, what do you think?

**Comment by basiszwo** [comment]
skip them.

**Comment by floriank** [comment]
alright.

**Pull request closed without merging**
