### PR TITLE
WP list edit feature

### PR DESCRIPTION
**Pull request by furinvader**
**General**
This PR introduces inplace editing for work packages in the list view.
It's still WIP and will be either split into multiple PRs or squashed.

After trying `angular-xeditable` and fiddling around with the current inplace edit implementation, I've found that implementing a slim new module was the quickest solution.

**TODO**
The list is not complete yet.
These are the most obvious things for now.
- [x] Enable subject field editing
- [x] Enable drop down field editing (Type, Priority, ...)
- [x] Save the work package
- [ ] WP status field schema does not provide allowed values (API)
- [ ] Enable date field editing
- [ ] Update work package table after submit using the new values
- [ ] Enable two-way binding between list and details view
- [ ] Make query filters actually work
- [ ] Handle custom fields
- [ ] ~~Make WP schema accessible (especially `allowedValues`) via the linked resource 'schema'. 
  Currently, we have to request the WP edit form first, which is quite unnecessary.~~
- [ ] Use schema properties in edit form templates (linke `maxlength`, `minlength` and so on)
- [ ] Missing tests
  - [ ] `HalTransformedElement` service

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://furinvader-experimental-new-wp-table-1-wip.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://furinvader-experimental-new-wp-table-1-wip.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
I believe this should be targeting the `dev` branch

**Comment by furinvader** [comment]
Sure, I'll close this PR and split the last commit in sensible chunks.

**Comment by furinvader** [comment]
Closed in favour of #4159

**Pull request closed without merging**
