### PR TITLE
[#41947] Fresh instances should have feature_storages_module_active false

### PR DESCRIPTION
**Pull request by cbliard**
https://community.openproject.org/work_packages/41947

### CODE REVIEW

**Comment by cbliard** [comment]
It happens in https://github.com/opf/openproject/blob/f5887d6d14e609b9f6cf1edb2decd08be7ef81a0/app/seeders/basic_data/setting_seeder.rb#L50-L52

If the value is `nil`, then it defaults to empty string. And if the value is `false`, it also defaults to empty string, which is truthy.

The issue already existed before `OpenProject::Configuration` and `Settings` were merged in PR #10296 
a33524ef6d is the commit before the PR got merged:
https://github.com/opf/openproject/blob/a33524ef6d5269022a4b47912211f62aba19bbf6/app/seeders/basic_data/setting_seeder.rb#L50-L52

It was mitigated by the fact that the `Setting.some_property?` method was always using `        ActiveRecord::Type::Boolean.new.cast(value)` to cast the value to a bool, and casting `''` returns `nil` which is falsy. The actual value was still an empty string.
https://github.com/opf/openproject/blob/a33524ef6d5269022a4b47912211f62aba19bbf6/app/models/setting.rb#L108-L113

For instance, `oauth_allow_remapping_of_existing_users` has a default value of false. After seeding:
```
Setting.oauth_allow_remapping_of_existing_users
=> ""
Setting.oauth_allow_remapping_of_existing_users?
=> nil
```

To fix the issue, we should ensure that boolean value stored in database as empty string is cast as false, and stop setting value to empty string during seeding. Each definition should have a valid default value.

**Review by ulferts — CHANGES_REQUESTED** [review]
Don't think that it will cause an immediate problem but since the purpose of this PR is to clean up I am going to be a bit pedantic.

If the seeding ran before the fix, the database will still contain the empty strings for e.g. 
`Setting.oauth_allow_remapping_of_existing_users`

It will now result in `nil` rather than `''` but that is different from the expected behaviour.

**Comment by cbliard** [comment]
Thanks for reviewing @ulferts 

I can probably write something to remove data that should not have been seeded (and I'd be curious to know why this seeding of default values is actually done)

So how do we handle it when we have database data to fix? Do we create a rake task or do we run it in a migration?

**Comment by ulferts** [comment]
> I'd be curious to know why this seeding of default values is actually done.

Being the one having written the code I cannot say anymore and am actually wondering just like you.

> So how do we handle it when we have database data to fix?

Writing a migration is what we do typically.

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
