### PR TITLE
[24405] Show user registration as modal dialog

### PR DESCRIPTION
**Pull request by HDinger**
This shows the user registration form as modal.
**Note** This PR can only be merged once the previous PR has been merged (https://github.com/opf/openproject/pull/5095).

**TODO**
_Behavior/Styling_
- [x] When clicking on 'Create new account' a modal opens.
- [x] The styling of the modal is similar to the onboarding style.
- [x] The other possible login methods look like in the specification.
- [x] When clicking on create, the user is created.
- [x] When entering wrong/missing content an error message is shown.

_Implementation_
- [x] The modal implementation is the same as the onboarding modal.
- [x] Adapt the tests to the new structure.

https://community.openproject.com/projects/openproject/work_packages/24405/activity

### CODE REVIEW

**Comment by HDinger** [comment]
### Current status
bildschirmfoto 2016-12-16 um 15 57 09

**Comment by HDinger** [comment]
The custom styles for the other login methods were made in the according plugins:
* https://github.com/opf/openproject-auth_plugins/pull/16
* https://github.com/finnlabs/openproject-openid_connect/pull/32

**Comment by HDinger** [comment]
@machisuji The tests are finally green 🎉 Can you have a look the PR?

**Comment by machisuji** [comment]
Great work!

**Pull request merged**
