### PR TITLE
Docs for 13.0: Added details on delay/lag and renamed operators

### PR DESCRIPTION
**Pull request by psatyal**
https://community.openproject.org/wp/49092

### CODE REVIEW

**Comment by psatyal** [comment]
Hi @MayaBerd, I'll do a separate PR for Baseline (to keep things separate, since we have two WPs). This one is ready for review :)

**Review by MayaBerd — APPROVED** [review]

**Comment by MayaBerd** [comment]
@psatyal makes sense. Thanks for updating this PR. I've only fixed one small typo directly.

**Comment by psatyal** [comment]
Thanks, @MayaBerd. Can this PR be merged?

**Comment by MayaBerd** [comment]
@psatyal from my side - yes, we can merge it.

**Pull request merged**
