### PR TITLE
Enable YJIT in docker images

### PR DESCRIPTION
**Pull request by klaustopher**
In our Saas environment we already have YJIT enabled, after upgrading to Ruby 3.3.1 in #15379 we can also enable it in all of our docker images

### CODE REVIEW

**Comment by oliverguenther** [comment]
We would need to do the same for packages, or I'd rather prefer an initializer that allows an opt-out through env instead of opt-in.

**Comment by klaustopher** [comment]
Yeah, also a valid option

**Comment by klaustopher** [comment]
Rails 7.1 even adds this as a default. Will add the initializer here as well

**Review by oliverguenther — APPROVED** [review]
Thanks! 👍

**Pull request merged**
