### PR TITLE
fix factoryGirl screws up rake db:migrate process

### PR DESCRIPTION
**Pull request by marutosi**
$ rake db:migrate RAILS_ENV=test

rake aborted!
ActiveRecord::StatementInvalid: Could not find table 'work_package_journals'

http://stackoverflow.com/questions/12423273/factorygirl-screws-up-rake-dbmigrate-process

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-factorygirl.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-factorygirl.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@marutosi you need to add require statements to `test_helper.rb` and `spec_helper.rb`.

**Comment by floriank** [comment]
:point_up: what @myabc said. Otherwise the test suite(s) won't run properly.

**Comment by NobodysNightmare** [comment]
Sadly after merging this PR specs for plugins are broken... See discussion here: https://github.com/opf/openproject/commit/30dcd66cf839c21996f0090d70828c782f11ae20

**Comment by NobodysNightmare** [comment]
I will for now revert this PR, because running specs is kind of important to me.

If anybody has feedback on:
- how to fix this properly
- why this causes trouble (because I really can't imagine why)

they should call me.

Best regards

**Comment by myabc** [comment]
reverting this PR is not really an option as this breaks migrations locally (I believe @machisuji also hit this issue a couple times)

**Comment by NobodysNightmare** [comment]
@myabc I think your sentence was not complete.

The problem here is that we are in a workable state without this PR and in a completely not workable state _with_ this PR. My third question could be _when do I ever need to run `rake db:migrate RAILS_ENV=test`?_ Because I never did that before...

**Comment by machisuji** [comment]
I can confirm that I do run into this problem locally every time I try to set up a config. Migrations fail. Specs don't run.

Doing the 'require: false' trick does help. Dunno why it breaks the specs on the CI. I think this is a good opportunity to take a thorough look at the problem and fix it once and for all. Any volunteers?

**Comment by NobodysNightmare** [comment]
> Dunno why it breaks the specs on the C

Just for the record: It does not break the specs **on the CI**. It breaks the specs for plugins! Locally as well as on the CI.

@machisuji Does `bundle exec rake spec` work for you? This is how I performed the setup step... not quite by the books, but it works.

I am fine with someone solving the issue once and for all, but it needs to work ^^

**Comment by myabc** [comment]
>  My third question could be when do I ever need to run rake db:migrate RAILS_ENV=test?

I find myself needing this surprisingly often. For instance, when if I modify the database schema and want to run a single spec.

**Comment by NobodysNightmare** [comment]
I guess I did not run into that issue because of my `rake spec` workaround. Which is not a pretty one for sure.

**Comment by myabc** [comment]
@NobodysNightmare can you try moving the `factory_girl_rails` require further up, just before Rails is required.

``` ruby
require 'factory_girl_rails'
require File.expand_path('../../config/environment', __FILE__)
```

Then `bundle exec rake spec:plugins`.

This works for me, but not yet 100% sure why.

**Comment by myabc** [comment]
FactoryGirl does some magic to find definitions (see [`FactoryGirl::Railtie`](https://github.com/thoughtbot/factory_girl_rails/blob/master/lib/factory_girl_rails/railtie.rb#L21)). I guess the Railtie needs to be required before the other parts of Rails. Admittedly, my knowledge of Rails initializers / Engine load order is pretty weak.

**Comment by myabc** [comment]
I ought to have read [the part of the docs on using Factory Girl without Bundler](http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Using_Without_Bundler).

**Pull request merged**
