### PR TITLE
[21734] Apply notification styles on flash messages and error explanations

### PR DESCRIPTION
**Pull request by mk84**
https://community.openproject.org/work_packages/21734/activity

With this pull-request all flash messages and notifications have the same styles.

What needs to be done:
- [x] All flash messages should have a close-handler.
- [x] Adjust position of notifications when there's already a flash message

Think the following task is out of scope:
A notification should remove a flash message if there is one. For example: when you log your time on a wp and save, you will see a flash message. After that when you edit the wp you will get a notification.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mk84-21734-flash-messages-redesign.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mk84-21734-flash-messages-redesign.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by leewaa** [comment]
For `/time_entries` when deleting a time entry the flash message is hidden under the main header. Also its green?
image

This also applies for `projects/seeded_project/time_entries` after deleting an entry

**Comment by mk84** [comment]
@leewaa thanks! This should be fixed now. And the message is green because it's a successful deletion.

**Comment by leewaa** [comment]
Ok great! 

Are there any plugins that need changing also?

**Comment by mk84** [comment]
@leewaa I haven't found any plugin that would need an update for this.
And I added a possibility to close alerts via keyboard.

**Pull request merged**
