### PR TITLE
15246 date picker start of week always sunday in english

### PR DESCRIPTION
**Pull request by hschink**
[`* `#15246` Date picker start of week always Sunday in English`](https://www.openproject.org/work_packages/15246)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-15246-date-picker-start-of-week-always-sunday-in-englis.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
`feature`?

**Comment by machisuji** [comment]
A test would be great indeed!

**Comment by hschink** [comment]
@myabc Regardless of whether its a feature or bug we always use the `feature` prefix.

**Comment by hschink** [comment]
@machisuji As you request...

**Comment by machisuji** [comment]
<3

**Comment by myabc** [comment]
@hschink 

> Regardless of whether its a feature or bug we always use the feature prefix.

I'm not sure that's correct.

In any case, I don't consider it very important. 

While evaluating this WP the other day, I realised that we're precompiling _localisations for all  supported jQuery UI locales_ and not just English, German. Related PR #1850 fixes this.

**Comment by myabc** [comment]
:+1:

**Pull request merged**
