### PR TITLE
Feature/removing children on relations tab

### PR DESCRIPTION
**Pull request by mtakac2**
https://www.openproject.org/work_packages/14573

### CODE REVIEW

**Comment by ulferts** [comment]
@mtakac the karma tests are failing.

**Comment by mtakac2** [comment]
@ulferts fixed. Should be fine now.

**Comment by manwithtwowatches** [comment]
I think this is fine to merge. Anyone have a problem?

**Comment by myabc** [comment]
Looks ok.

Styles weren't changed in this PR, but perhaps icon alignment should be addressed.

seeded_project_-_openproject

**Comment by ulferts** [comment]
styled it:

image

Though I am not sure why not to apply the 1em style to all icons. But it seemed to be quite some change in my opinion.

Anybody wants to merge? @mtakac, @myabc, @manwithtwowatches

**Pull request merged**
