### PR TITLE
Fix XSS in select2 formatter

### PR DESCRIPTION
**Pull request by mfrister**
Tested in IE8.

OpenProject Issue: https://www.openproject.org/issues/1011 (login-only)

### CODE REVIEW

**Comment by tessi** [comment]
looks good. i'll do some manual tests (we dont have travis for the old version) and merge, if everythings works.

**Comment by tessi** [comment]
I am not able to execute the tests. :( Thus, I cannot merge your pull request.

**Comment by mfrister** [comment]
testunit tests are not working anyway, but they are also not affected by JavaScript changes.

Cukes run again after reverting a commit in 607c6a680d5208623dfdba014de4e70863cfad64, the same three fail with and without this change.

**Comment by tessi** [comment]
haven't seen the tests running. _merge and run_

**Pull request merged**
