### PR TITLE
[#44265] "Group by" options in Cost report are broken

### PR DESCRIPTION
**Pull request by dombesz**
See [OP#44265](https://community.openproject.org/work_packages/44265)
Also making the "Add Group-by Attribute" disabled, so it cannot be selected as a group by value.
image

### CODE REVIEW

**Review by ulferts — APPROVED** [review]
The change is fine.

But when now using that to select the very long custom field, the problem continues:

image

Limiting the width of the selected elements as well seems like a good idea. We can do that as a separate PR though.

**Comment by dombesz** [comment]
@ulferts I'll do it in this PR.

**Review by ulferts — CHANGES_REQUESTED** [review]
👍 on adding the title when truncating.

I would have preferred a solution based on css (`text-overflow: ellipsis`) as we have in most of the places. But I don't insist on it. What I don't understand though is why having `max-width` on the one hand and then js based truncated on the other. 

Additionally, the solution can lead to the '...'  being right next to the close 'x' which makes those two hard to discern:  

image

A bit of padding would help, IMO.

**Comment by oliverguenther** [comment]
:warning: please rebase onto `release/12.3` and change the target branch

**Comment by dombesz** [comment]
@ulferts I changed it to using ellipsis, initially the `overflow: hidden` was causing some misalignment issues, hence I tried with the truncate, but now it works as expected.
image

**Review by ulferts — APPROVED** [review]
Thanks for all the extra miles, @dombesz.

**Pull request merged**
