### PR TITLE
14727 Remove icon cannot be reached by keyboard

### PR DESCRIPTION
**Pull request by hschink**
[`* `#14727` Remove icon cannot be reached by keyboard`](https://www.openproject.org/work_packages/14727)

### CODE REVIEW

**Comment by manwithtwowatches** [comment]
@hschink Might be out of scope but should it be the case that after deleting the relation the focus should then be some near, like the next relation, instead of not being focussed on anything?

oh in fact that's what's being addressed here right? https://github.com/opf/openproject/pull/1808

**Comment by hschink** [comment]
@manwithtwowatches That's actually a good idea! In #1812 I refactored the focus functionality. As soon as #1812 becomes part of the core I extend this branch accordingly.

**Comment by hschink** [comment]
@manwithtwowatches As promised in https://github.com/opf/openproject/pull/1799#issuecomment-53437122 I added the feature you requested in https://github.com/opf/openproject/pull/1799#issuecomment-53414901.

**Comment by manwithtwowatches** [comment]
@hschink nice one. so is this still work in progress or is it ready to review?

**Pull request merged**
