### PR TITLE
[20449] [Accessibility] Some error messages cannot be perceived with the screen reader

### PR DESCRIPTION
**Pull request by HDinger**
This adds a hint label for date picker. 
This PR is needed for: https://github.com/finnlabs/openproject-meeting/pull/122

https://community.openproject.com/work_packages/20449/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-20449-some-error-messages-cannot-be-perceived-with-.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-20449-some-error-messages-cannot-be-perceived-with-.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Both PRs look good to except: Is there a reason why you didn't add the label to the locales of the plugin itself? 
https://github.com/finnlabs/openproject-meeting/blob/dev/config/locales/en.yml

**Comment by HDinger** [comment]
@oliverguenther I expect other date pickers to have the same problem. So they will need the label too. That is why I decided to put it in the core.

**Comment by oliverguenther** [comment]
Ah, fine with me!

**Pull request merged**
