### PR TITLE
18328 Configure gulp-autoprefixer to add vendor prefixes

### PR DESCRIPTION
**Pull request by myabc**
:warning: **Includes commits from #2695. Please review, merge first.**

Relates to #2524

https://community.openproject.org/work_packages/18328

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-18328-gulp-autoprefixer.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-18328-gulp-autoprefixer.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@myabc, @floriank Looks fine to me. I checked: 
- running in dev mode and making changes
  - styleguide is updated
  - app is updated
- compiling and running in production mode
  No problems I could spot.

**Comment by ulferts** [comment]
@myabc now travis is complaining.

**Comment by myabc** [comment]
@ulferts `query_menu_items.feature`.  not sure if this is a valid failure or not.

**Pull request merged**
