### PR TITLE
[24332] Avoid macro expansion inside pre/code tags

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.com/work_packages/24332

### CODE REVIEW

**Comment by silkentrance** [comment]
Hi @oliverguenther how about making pre a macro by itself instead of a part of the wiki markup language. In fact, it does actually break with the textile markup language and having something like

```
{{pre
<pre>-formatted blob of text
}}
```

looks a lot more natural.

In addition, the macro would just html escape the pre-formatted blob of text and render a document fragment that is a pre element, e.g.

```
<pre>
&lt;pre&gt;-formatted blob of text
</pre>
```

While existing wiki content must be migrated, the overall complexity of the code would be reduced a lot.

This would require #5040 :grinning:, though.

**Comment by oliverguenther** [comment]
This wouldn't work with the current structure since macros are expanded after redcloth, so the inner `<pre>` would already be cleaned during the textile process. I've refactored the PR to have all custom rules applied inside the `parse_non_pre_blocks` callback. That makes it somewhat clearer.

**Comment by silkentrance** [comment]
@oliverguenther I don't know if this might the cause of the/other problem(s), but see for example ``parse_non_pre_blocks`` and where it reads

```
        if tags.empty?
          yield text
        end
```

This is executed prior to that any tags will be pushed to the initialized (empty) tags local var.

Should this not be moved down to at the end of the routine in order to for it being filled up with non closing tags? Or is the local var tags yet some other by-convention magic that I do not yet understand?

I for my part would debunk ``parse_non_pre_blocks`` altogether and make it an utility for macros that allow html input in the form of ``parse_html``...

**Comment by silkentrance** [comment]
@oliverguenther I have here a branch that gets rid of ``parse_non_pre_blocks`` altogether, based on current release/6.1 including this. It also includes the PR for #5040. In fact, I merged the release/6.1 into that PR.

However, and since the aforementioned routine ``parse_non_pre_blocks`` is faulty, it also exposes the same problems, namely failure to complete any unmatched opening a/o closing tags. So we would need to make this two PRs instead.

When will this be merged into dev so that we can work on this for the next release?

**Comment by oliverguenther** [comment]
release/6.1 is periodically merged into dev (Jens did that just an hour ago in https://github.com/opf/openproject/commit/69431d13e709f34e687e84644b6b9f223f851cd4) so those changes should now be ready on dev.

I'm not sure I get your point regarding `tags.empty?`. When tags are empty, you are matching a line such as `fooobar<pre>`. Here, `text=fooobar, tag = `pre`. It's okay to yield the text since we're before the tag.

**Pull request merged**
