### PR TITLE
refactor inplace editor switch

### PR DESCRIPTION
**Pull request by 0xF013**
[`* `#17769 ` refactor inplace editor switch`](http://community.openproject.org/work_packages/17769)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://0xf013-feature-refactor-inplace-editor-view.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@0xF013 like this approach better – still think it would be better to split into multiple directives though.

**Comment by 0xF013** [comment]
@myabc I agree about splitting into multiple directives but I would first map the use cases e.g. we might only need a ton of simple input editors and a couple of special ones, then I would just create a couple of directives that in their turn call this existing general directive.

**Comment by 0xF013** [comment]
@ulferts rebased

**Comment by ulferts** [comment]
@0xF013 thanks, the protractor tests failed (probably flicker). Leaving it for now so you have the chance to take a look at it.

**Pull request merged**
