### PR TITLE
updates api gems + dependent ones

### PR DESCRIPTION
**Pull request by ulferts**
Updates grape and reform to their current head version.

As a result other gems are updated as well. As I could see no harm in updating them, I didn't check whether every update was strictly necessary.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-update-grape-and-reform.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
Cherry-picking 17ea449d (from #2104) should help with one of the spec failures.

**Comment by ulferts** [comment]
@myabc thanks for the hint but for now I simply removed the update of i18n.

**Comment by myabc** [comment]
@ulferts ok, makes sense.

**Pull request merged**
