### PR TITLE
[#55100] Meeting sections do not show "Move up" and "Move to top" action

### PR DESCRIPTION
**Pull request by dombesz**
https://community.openproject.org/work_packages/55100

### CODE REVIEW

**Review by HDinger — CHANGES_REQUESTED** [review]
It works correctly for the section that was just moved. However, the section that is now newly at the top (respectivly bottom) does not show the correct items.

agenda_items_menu_after_drag

**Comment by jjabari-op** [comment]
@HDinger thanks for double checking! it should be fixed now :)

**Review by HDinger — COMMENTED** [review]
Yes, the described issue works correctly. 👍  While testing, I just found one other thing: When creating a new section, the previuosly last section is not correctly updated. It still shows only the arrows up, but should have all options:

Bildschirmfoto 2024-05-16 um 11 59 33

I don't know if that is an easy fix. If not, feel free to extract that into a separate ticket.

**Comment by jjabari-op** [comment]
@HDinger Good eye! That's an easy fix actually, give me a sec ;)

**Comment by jjabari-op** [comment]
@HDinger Could you have another look? Thank you!

**Review by HDinger — APPROVED** [review]
Looks good, thanks 👍  Good to merge, once the tests are green

**Pull request merged**
