### PR TITLE
16486 workpackage list throws 500 with target version filter

### PR DESCRIPTION
**Pull request by hschink**
[`* `#16486` WorkPackage List throws 500 with TargetVersion Filter`](https://www.openproject.org/work_packages/16486)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-16486-workpackage-list-throws-500-with-target-version-filte.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by tessi** [comment]
Apart from my question above this PR seems to fix the issue (tested on Teatro). I'd merge this when the question is resolved.

**Comment by myabc** [comment]
@tessi `xit` indicates the spec is pending.

**Comment by ulferts** [comment]
`xit` basically disables the test. (@myabc again beat me to it)

From what I see, this however was not touched by @hschink. So I propose briefly checking whether it can be deactivated. If it can be, do so and merge. If not, merge.

**Comment by tessi** [comment]
Alright! It just looked like a typical vim-related typo (And I'm not yet familar with all the things).

**Comment by tessi** [comment]
An while we're at it: I hope the CI will not break, because

**Pull request merged**
