### PR TITLE
time_event: Initial APIv3 support

### PR DESCRIPTION
**Pull request by DipSwitch**
This is a work in progress PR, but if someone wants to take a look and tell me if i'm on the right track please do so.

Questions areas for me are:
- `lib/api/v3/time_entries/time_entry_collection_representer.rb` : since it's quite heavy on the database, a join would be nice here =)
  
  ```
  Started GET "/api/v3/work_packages/3/time_entries" for 192.168.0.6 at 2016-07-02 22:55:44 +0200
     (1.3ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
    User Load (1.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser', 'DeletedUser') AND `users`.`id` = 1 LIMIT 1
    WorkPackage Load (1.9ms)  SELECT  `work_packages`.* FROM `work_packages` WHERE `work_packages`.`id` = 3 LIMIT 1
    Project Load (0.9ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
     (1.1ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 1
    Project Load (1.7ms)  SELECT `projects`.* FROM `projects` WHERE (projects.status=1 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='work_package_tracking'))
    TimeEntry Load (1.0ms)  SELECT  `time_entries`.* FROM `time_entries` WHERE `time_entries`.`work_package_id` = 3 LIMIT 30 OFFSET 0
     (1.1ms)  SELECT COUNT(*) FROM `time_entries` WHERE `time_entries`.`work_package_id` = 3
    TimeEntry Load (1.2ms)  SELECT `time_entries`.* FROM `time_entries` WHERE `time_entries`.`project_id` = 1 AND `time_entries`.`work_package_id` = 3
  ```

And the add support of the `time_entry` since this is is not done (like with the `work_packages`) with a `app/services/add_time_event_service.rb`

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://dipswitch-pr-add-time-event-api-support.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://dipswitch-pr-add-time-event-api-support.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Hi DipSwitch,

thanks for starting work in an area which has been heavily requested for quite some time now. You will make a lot of users very happy (and myself being one of them) when that feature is done. 

Before getting to your specific questions I'd like to propose a method of work we have employed before when working on the api. I found it helped us structure the work at hand and enabled us to understand what we where doing. 

I read your code and I think I got what you what to achieve (something with time entries, right?) but what I have problems with is understanding the limits of what you want to implement.

To that goal, I propose extending the [api documentation](https://github.com/opf/openproject/blob/dev/doc/apiv3-documentation.apib) first, listing the resources you want to add with their attributes and permissions and also specifying the endpoints at which they can be manipulated. The existing documentation should give you enough of an example to be extended easily but feel free to ask if you have any questions.

With the documentation showing where your PR is heading, I should be able to help you better than I could without knowing your intentions. 

From my point of view, we would need the following endpoints to fully support time entries:
- GET `api/v3/time_entries/:id`: Read a single time entry
- PATCH `api/v3/time_entries/:id`: Update a single time entry
- DELETE `api/v3/time_entries/:id`: Delete a single time entry
- POST `api/v3/time_entries` Create a single time entry
- POST `api/v3/time_entries/form` Utility end point aiding in the creation of time entries analogue to how it is done for work packages
- POST `api/v3/time_entries/:id/form` Utility end point aiding in updating a time entry analogue to how it is done for work packages
- GET `api/v3/time_entries/schema` Read definition of what attributes a time entry has analogue to how it is done for work packages
- GET `api/v3/work_packages/:id/time_entries` List of time entries associated with the work package
- GET `api/v3/projects/:id/time_entries` List of time entries associated with the project

A TimeEntry resource will have the following attributes:
- `id`: Integer attribute
- `comments`: String attribute
- `spentOn`: Date attribute
- `createdAt`: DateTime attribute
- `updatedAt`: DateTime attribute 
- `project`: Project link
- `user`: User link
- `work_package`: WorkPackage link
- `activity`: Activity link

Because of the `activity` attribute, which is a required field for time entries, we would need to have two additional end points:
- GET `api/v3/activities/:id` or GET `api/v3/time_entries/activities/:id` Read a single time tracking activity.
- GET `api/v3/activities` or GET `api/v3/time_entries/activities` Read all available time tracking activities.

We wouldn't need additional end points for activities just yet and we might not need them for quite some time but without a valid href the api would sport non existing links and there would be no means to get all the activities a client can select from when wanting to create/update a time entry. Although, when thinking about it, the `form` could also provide the list of available activities so that we might get away with having only the first end point of the two.

The end points for the `project`, `user` and `work_package` link exist already.

One might wish for a GET `time_entries` end point offering filtering like we have for work packages but that is not elementary and thus I wouldn't do it right now.

This is my idea of what one needs to do so that time entries are complete. Again, if you where to update the api documentation within the PR, I would be able to grasp your idea.

From what I have seen, you are already working on:
- GET `api/v3/work_packages/:id/time_entries` 
- GET `api/v3/projects/:id/time_entries` 
- GET `api/v3/time_entries/:id/`
- POST `api/v3/time_entries` or some end point like that. I recommend using the end point I mentioned instead of nesting it at e.g. `api/v3/work_packages/:id/time_entries` as we have learned to use as little nesting as possible. The payload object can also be reused for the form endpoints so that can also be considered work in progress. 

That is quite some achievement already so keep going.

Regarding your concern of the impact on the database when using the `time_entry_collection_representer` I can easy your mind. The work package collection representer has way more to do and it is still fast enough. Just make sure to eager load `user`, `project` and `activity` once you render links to them in the collection to avoid having n+1 queries.

Using a service to encapsulate the code for adding a time entry sounds like a good idea. Alas, I fear that I did not get your question there.

:+1: for already having tests for parts of your code.

Feel free to ask again once a question pops up. I will try to look into the PR regularly and might give you hints. Let me know if you want feedback on the code.

**Comment by DipSwitch** [comment]
Thanks for the feedback, I'll see when I've got time to work on some more =) Buzy times

**Comment by lindenthal** [comment]
@DipSwitch: How is it going with this PR?

**Comment by kgish** [comment]
Shall I have a look at this?

Where's the best place to look in order to get up and running quickly with api/v3?

**Comment by kgish** [comment]
Can someone please respond?

**Comment by oliverguenther** [comment]
@kgish You would get a deep insight in how the application works by having a go.

To get started with API development, please see the following resources:

- [APIv3 blueprint documentation](http://opf.github.io/apiv3-doc)

- [Grape](https://github.com/ruby-grape/grape) as the API routing/request framework

- [roar](https://github.com/trailblazer/roar) representers converting collections and records to/from JSON

- [reform](https://github.com/trailblazer/reform) Contracts and validations for actions happening outside the rails model validations

The implementation of the API is very concise, so you should be able to get going by looking at other end points, such as the [/users API](https://github.com/opf/openproject/tree/dev/lib/api/v3/users). The whole tree of APIv3 is in [lib/api/v3](https://github.com/opf/openproject/tree/dev/lib/api/v3).

**Comment by kgish** [comment]
Thanks, I'll definitely checks these out.

**Comment by DipSwitch** [comment]
Sorry this kinda got derailed, since we are using another application. Also spare time is scarce at the moment, sorry...

**Comment by ulferts** [comment]
As I had some time at hand while riding train, I implemented the read part of the API in #5776. Then end points:

* GET `/api/v3/time_entries` with filter capabilities
* GET `/api/v3/time_entries/:id`

as well as the auxiliary end point

* GET `/api/v3/time_entries/activities/:id` 

are introduced there.

**Comment by ulferts** [comment]
Closing this as #5776 together with #5816 provide the same functionality and are close to being finished.

**Pull request closed without merging**
