### PR TITLE
[21705] Attachment section styling

### PR DESCRIPTION
**Pull request by mk84**
https://community.openproject.org/work_packages/21705/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mk84-21705-attachment-section-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mk84-21705-attachment-section-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by mk84** [comment]
#### Before

## before

#### After

after

**Comment by lindenthal** [comment]
Hi Magda,
I think the visuals were misleading. The delete Icon and the frame should only be visible on hover.
Thanks
Niels

**Comment by mk84** [comment]
@lindenthal I updated the styles as discussed with you yesterday.

**Pull request merged**
