### PR TITLE
[release/3.0] Getting ready for Teatro

### PR DESCRIPTION
**Pull request by marutosi**
[release/3.0] Getting ready for Teatro

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-release-3-0-teatro.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by linki** [comment]
no useful description, duplicates https://github.com/opf/openproject/pull/1693

**Comment by marutosi** [comment]
> no useful description

Description in commit logs.

**Comment by linki** [comment]
here is what you should write

> enabling `teatro` for `release/3.0` branch

then follows why you want to do that plus some context (a ticket on openproject.org containing a discussion about it would be a good fit.)

**Pull request closed without merging**
