### PR TITLE
[21638] No keyboard focus when opening columns modal from column context menu

### PR DESCRIPTION
**Pull request by furinvader**
The `ui-select` field is now focused correctly.

https://community.openproject.org/work_packages/21638/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://furinvader-bug-21638-insert-columns-focus.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://furinvader-bug-21638-insert-columns-focus.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Functionality-wise, this looks good and works fine. Are there any possible implications of using angular-ui-select here that we should test?

**Comment by furinvader** [comment]
There shouldn't be. Before, we've been using an older fork, which just hat fewer features and rather minor bugs.
The reason for the update though, was to use the `focus-on="eventName"` feature to set the focus after an event was called.

**Comment by oliverguenther** [comment]
Thanks for the clarification. :+1:

**Pull request merged**
