### PR TITLE
Corrected highlighting and styling for detailed wp macro

### PR DESCRIPTION
**Pull request by Rincewind34**
Implements [OP#45455](https://community.openproject.org/wp/45455)

### CODE REVIEW

**Comment by ulferts** [comment]
The `dev` branch had failing specs from whence you branched off which is probably why the specs are failing in this PR. Please rebase/merge to fix this.

**Review by cbliard — CHANGES_REQUESTED** [review]
Thanks. I really like the extra space between status and type, and the removal of the visual clutter `(-)`.

Regarding the functionality, it should be able to display dates when start date is not set. Here is an example:

image

When there is no start date, it should display like when there is no start date, something like (no start date - 2022-12-29).

Note that the original implementation got it wrong too, and displays "(-)" when only the finish date is set. Still I think it would be a missed opportunity to not fix it.

**Comment by Rincewind34** [comment]
@cbliard  Copy that, it's of course an easy fix. Two questions:

1. Where are the tests for this component supposed to go - do we want tests? If yes, any existing examples would be appreciated. 
2. Do we have a utility function for checking if dates are set sitting around somewhere? It's not in hal/workpackage-resource.ts

**Comment by cbliard** [comment]
@Rincewind34 Yes, it should be an easy fix.

1. Macros specs are located in `spec/features/wysiwyg/macros` directory. `quicklink_macros_spec.rb` is the right one. I would not test for appearance, but rather for content: not test that the spacing is 6px, but test that the displayed text is `"New milestone #42: some title (2022-12-30 - 2023-01-02)"`, or even just test the dates part, as the content is already tested by the existing test.
2. I was thinking the same. Ideally, I'd like to have two functions: one to indicate there are dates like `workPackage.hasDates`, one to indicate if it is a milestone like `workPackage.isMilestone`. But I did not find them and I'm not that experienced in frontend. just adding another `|| !!workPackage.dueDate` will do.

**Comment by Rincewind34** [comment]
@cbliard Ok, I'll get started on the testes on my next "OpenProject work day" :)

On a general note: I'm more than happy to do a few code cleanups along the way. I understand that the code base is at parts very old? I feel like not implementing these new util methods now is not doing us any favour in the future. I'm also happy to search the existing code base and replace the occurrences appropriately.
The two methods you mentioned would unarguably increase the readability of the code. As someone who spent the last few weeks scooping through the code, this is much needed at some points.

If that is something I can participate in, I'm happy to do it! I'll also happily engage in a small meeting if there are any concerns about this causing more trouble than it's worth with me doing refactoring.

**Comment by cbliard** [comment]
Thanks @Rincewind34, that's very much appreciated. Then please go ahead and implement the methods I mentioned in `frontend/src/app/features/hal/resources/work-package-resource.ts`.

You can add unit tests for the added methods in `frontend/src/app/features/hal/resources/work-package-resource.spec.ts`. Then run them with `ng test --include=src/app/features/hal/resources/work-package-resource.spec.ts` from the `frontend` directory.

You can also run all tests with `npm run test`, and there are other options in the `frontend/package.json` but I'm not very familiar with it.

**Comment by cbliard** [comment]
@Rincewind34 I have implemented the missing case for when a work package has a due date but no start date, and added tests for it.

If you're ok with the implementation and the tests are green, I'll merge it.

**Pull request merged**
