### PR TITLE
Add git support in our apache authentication scripts

### PR DESCRIPTION
**Pull request by tessi**
I'd like to see git supported in our authentication scripts (just like we support svn).

This PR aims to do that.

see: https://www.openproject.org/work_packages/14384

### CODE REVIEW

**Comment by myabc** [comment]
@tessi is this still relevant?

**Comment by tessi** [comment]
@myabc not sure if you (meaning the opf) still wanna have this feature. The only thing missing was that someone wanted to test it (probably @kgalli as he knows about the apache/svn setup already).

In case you don't care about this feature anymore, just drop it.

**Comment by NobodysNightmare** [comment]
@kgalli Can you please evaluate if this PR is still worth something? I'd really like to avoid rotting PRs, seems like oyu could be able to decide here...

**Comment by floriank** [comment]
@kgalli - I know you're busy, but could you give us a quick evaluation if we can salvage anything?

**Comment by kgalli** [comment]
@oliverguenther AFAIK you are working on this. Any thoughts. I do not like the whole Perl dependency including delegating repository management to the web server.

**Comment by oliverguenther** [comment]
While I'm working on repository management, the changes currently do not encompass authentication for repositories. However it will allow third party adapters to replace the Apache wrapper with some other dedicated authentication scheme (e.g., Gitolite). 

[The corresponding WP is currently on hold](https://community.openproject.org/work_packages/14383) and I think the whole Perl wrapper should be deprecated, but depending on if and when that comes, this PR is a clean solution for Git in the meantime.

**Comment by oliverguenther** [comment]
Superseded by https://github.com/opf/openproject/pull/3289

**Pull request closed without merging**
