### PR TITLE
Meets #2393: No warning when leaving site without saving

### PR DESCRIPTION
**Pull request by slawa85**
```
* `#2393` Fix: No warning when leaving site without saving
```

### CODE REVIEW

**Comment by slawa85** [comment]
Ticket: https://www.openproject.org/work_packages/2393

**Comment by hschink** [comment]
@slawa85 I cannot merge this PR.

**Comment by hschink** [comment]
@slawa85 I guess you need to rebase this branch. There are a lot of commits that do not belong to you I guess.

**Comment by hschink** [comment]
Merged cleaned up branch with the following two commits:
1. [1e94c80](https://github.com/opf/openproject/commit/1e94c804c8582c0c15b850317973fd15364890c7)
2. [886050c](https://github.com/opf/openproject/commit/886050c72c491aa268dc0b05bae23c6f62d0d0cc)

**Pull request closed without merging**
