### PR TITLE
Multiselect custom field lists

### PR DESCRIPTION
**Pull request by machisuji**
WP [#3580](https://community.openproject.com/projects/openproject/work_packages/3580/activity)

**Open Questions**

* Do we want to keep the translation feature for list custom values?
*  wp index: display multiple values what way?

TODO

* [x] add custom options to CustomField to allow updating list options without breaking things
* [x] remove translations for custom field default value and possible values (=> custom options)
* [x] APIv3 render value as arrays (all selected values)
* [x] settings: add toggle/checkbox to allow multi-select
* [x] WP fullscreen view: display multiple values
* [x] WP fullscreen view: update with multi select
* [x] WP index view: display multiple values
* [x] WP index view: update with multi select
* [x] Filter with multi select
* [x] Group with multi select
* [x] semantic multi select option settings view

### CODE REVIEW

**Comment by silkentrance** [comment]
@machisuji keeping the translation feature would be nice

**Comment by ulferts** [comment]
@machisuji you will also have to:

#### adapt the api v3 schema in order for the backend to signal if a custom field supports multiple values.
We could either:
* Add a `"multiple"` attribute to the schema, e.g.
```
      "customField1": {
        "type": "StringObject",
        "name": "Module",
        "required": false,
        "hasDefault": false,
        "writable": true,
        "visibility": "default",
        "multiple": true,
        "_embedded": {
          "allowedValues": [
            {
              "_type": "StringObject",
              "value": "Activity",
              "_links": {
                "self": {
                  "href": "/api/v3/string_objects?value=Activity"
                }
              }
            },
            <snip>
            {
              "_type": "StringObject",
              "value": "Others",
              "_links": {
                "self": {
                  "href": "/api/v3/string_objects?value=Others"
                }
              }
            }
          ]
        }
```
*Or* alter the `"type"` to communicate the ability to handle multiple values, e.g.:
```
      "customField1": {
        "type": "[]StringObject",
        "name": "Module",
        "required": false,
        "hasDefault": false,
        "writable": true,
        "visibility": "default",
        "_embedded": {
          "allowedValues": [
            {
              "_type": "StringObject",
              "value": "Activity",
              "_links": {
                "self": {
                  "href": "/api/v3/string_objects?value=Activity"
                }
              }
            },
            <snip>
            {
              "_type": "StringObject",
              "value": "Others",
              "_links": {
                "self": {
                  "href": "/api/v3/string_objects?value=Others"
                }
              }
            }
          ]
        }
```

The `"multiple"` attribute does have the advantage of being simpler but it is also limited in that we will only be able to support Arrays that way.

I stumbled upon this while thinking about the API query implementation as the same will be needed for the columns, sorting criteria and the like. As you probably haven't yet reached the point where you alter the API I can come up with a proposal and you can tell me if you like it.

#### Migrate the existing custom field values

We talked about this, already so this is merely a reminder

**Comment by machisuji** [comment]
@ulferts I think I like the second version better. Yes, I haven't touched the API yet. Open to proposals. Thanks!

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/11387291530cf433fb71b6eea70bd5200ff6066c) (deployed commit: a50d3fde10c1c9a7fd02bb9debaab52de43fb5d0).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/bcf1209c16b9444efd03df043f47e577b441fd23) (deployed commit: 460ddfce7891ef32b15e466b783cc8fb607fc280).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/25ba52417ae5783ba7bf8343800e9b6a4abae41c) (deployed commit: 91199190c45f99593504cda0de59a7a7de44029b).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c5781ca88eee8ac96190b1124cc2bf681da856ba) (deployed commit: df7daa358d98c109a5a4f9828f2791169247cbde).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/bfbeff94daa42a40c4e74c90eea30d7c9aecba38) (deployed commit: c9b05fd33bdb5f68a771c6439cd88ffef90131a6).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/fcad49b5e80ed25548180e72f9bcdab98ca2dfe0) (deployed commit: c9b05fd33bdb5f68a771c6439cd88ffef90131a6).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/a8e80a8f28affec66d372159779473008f41784a) (deployed commit: c9b05fd33bdb5f68a771c6439cd88ffef90131a6).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/0db941da0513526440123c5918d05a6c6e9d4835) (deployed commit: a75893dc24eaf4473906ae212023cf6c22712fe0).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/8f6925da10b9b3aa0a89a88c33717a86a545b67b) (deployed commit: a75893dc24eaf4473906ae212023cf6c22712fe0).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/6040ad2d46630a23919b7c35821d5c65eb570c0d) (deployed commit: eaf8de87806028b5552305830b556d397239ea68).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/14f871290e8143e0216f045800eb508d21b1f29a) (deployed commit: 9a22e95a4f71350bd35aba8ce15da418ea8df12e).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7c381b4c628dcb51016ab355be9c697f4bbf52d4) (deployed commit: 26015bfe0b954b0d7dd65ea7ab8931db9a34f204).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/ec2474a98f4877fc4fd44d7d7340af8aab768d77) (deployed commit: 77055a26efedf39f56478d609da1b46be8959cbb).

**Comment by oliverguenther** [comment]
LGTM code and feature wise. Good to merge after travis.

**Review by oliverguenther — APPROVED** [review]

**Review by oliverguenther — APPROVED** [review]

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/813fd8b1ee9de820a6cd9bf80acbb0a4be1a915b) (deployed commit: d89a42b75ba73e11fbe84ef36398e1f86778869a).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/db280b9e615443e568103d370079f9bd336cea49) (deployed commit: edccc087514c2dcc1817225cb4ae29633687c203).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/1f4db41eabea1ef42a5bf2060330a4352f8e7161) (deployed commit: 771266af6ff629645733d074d2a7c15d56d7059f).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7c18feed90b36bba62a0ed967bc313f1effb047e) (deployed commit: d6292a0e3767184ab262f20d39995c1e6bb1601b).

**Pull request merged**
