### PR TITLE
[21279] Fix seed data for development environment

### PR DESCRIPTION
**Pull request by basiszwo**
https://community.openproject.org/work_packages/21279

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://basiszwo-21279-fix-seed-data.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://basiszwo-21279-fix-seed-data.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by basiszwo** [comment]
@ulferts can we merge this?

**Comment by NobodysNightmare** [comment]
LGTM :+1: 

Thanks for splitting it up into two commits, this eased review a lot!

**Comment by basiszwo** [comment]
yeah, should have done that before :unamused:

**Pull request merged**
