### PR TITLE
preparation of sqlite3 support

### PR DESCRIPTION
**Pull request by marutosi**
https://www.openproject.org/work_packages/13974
https://community.openproject.org/work_packages/13974

This is a part of #3040.
This certificates no breaking MySQL and PostgreSQL.

https://github.com/git/git/blob/v2.4.3/Documentation/SubmittingPatches#L37

> (1) Make separate commits for logically separate changes.

https://mercurial.selenic.com/wiki/ContributingChanges#Organizing_patches

> implement one clear step in your process be sent as a separate email

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-sqlite3-prepare.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-sqlite3-prepare.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
Is this a duplicate of #3040?

As @ulferts already said in https://community.openproject.org/work_packages/13974: There is currently no plan to support SQLite.

@NobodysNightmare should we close this as well?

**Comment by marutosi** [comment]
> Is this a duplicate of #3040?

No.

**Comment by floriank** [comment]
> No.

It contains 4 of the 5 commits, so it's at least a partial duplicate.

**Comment by marutosi** [comment]
> It contains 4 of the 5 commits, so it's at least a partial duplicate.

It means "you said GitHub UI is unusual and terrible".

**Comment by marutosi** [comment]
> It means "you said GitHub UI is unusual and terrible".

https://github.com/opf/openproject/pull/3098#issuecomment-110626010

**Comment by floriank** [comment]
> It means "you said GitHub UI is unusual and terrible".

I do not get it - what do you mean? You have 4 commits in here (https://github.com/marutosi/openproject/commit/6ebaaf2f722ae7a06212ea3ecab3c445cec09157, https://github.com/marutosi/openproject/commit/c2790d0779b1da80d96d2fd326cf9bf350ce5120, 
https://github.com/marutosi/openproject/commit/18fe646b2ba8fe2c32c0d547cfdf55c754051f74,
https://github.com/marutosi/openproject/commit/4daef431c186cdc4d48bddc2eaac06c72f76034e) which are found in #3040.

> #3098 (comment)

Circular reasoning?

**Comment by marutosi** [comment]
GitHub does not have feature of PR for PR.

**Comment by marutosi** [comment]
> GitHub does not have feature of PR for PR.

So, I sent separating PRs.
Do you understand?

**Comment by floriank** [comment]
No, as you present the same, unaltered commits in two different PRs. 

Your first PR (#3040) contains this PR completely, in addition to 1 extra commit (https://github.com/marutosi/openproject/commit/dd2ae6ff91504c5829cc4cb9714152ba55829a8a). If you want to change something in your original PR, you can just add more commits to the branch you used to create the PR in the first place.

**Comment by marutosi** [comment]
#3040 **had** one revision originally.

https://github.com/opf/openproject/pull/3040#issuecomment-107979878

> Please adhere to the hound warnings

So I created new separating PRs.
Am I wrong?

**Comment by marutosi** [comment]
> you can just add more commits

GitHub UI says.
It means "you said GitHub UI is unusual and terrible".

**Comment by floriank** [comment]
> Please adhere to the hound warnings

@NobodysNightmare told you to fix them - you could have just added another commit fixing the style instead of opening a new PR. If you are not satified with having an extra commit, you could even squash it into fewer commits and force push **at the end**.

> It means "you said GitHub UI is unusual and terrible".

If you think so. If the Github workflow we impose for this project is not to your liking, I couldn't care less, as it works for all of us so far.

**Comment by marutosi** [comment]
>  it works for all of us so far

"us" are OpenProject members, not OpenSource contributors.

**Comment by floriank** [comment]
> "us" are OpenProject member, not OpenSource contributors.

I disagree. Quite a few OpenSource contributors use the Github UI.

**Comment by NobodysNightmare** [comment]
I tend to like this PR more than the initial one, because it does not add SQLite to the travis.yml.

I think we should verify that the changes here do not break other databases functionality wise and then this could be good to merge.

The reason I don't want to include SQLite in travis is rather pragmatic: The builds would take even longer and they already take too much time, I hope this is understandable.

At the topic of GitHub UI: GitHub assumes a 1:1 relationship between a PR and a branch. So changing stuff on your branch will change the PR, regardless whether it is a force push/rebase or simply adding more commits.

**Comment by marutosi** [comment]
> I disagree. Quite a few OpenSource contributors use the Github UI.

Pardon me? I don't know what you mean.

**Comment by marutosi** [comment]
> Quite a few OpenSource contributors use the Github UI.

Yes. Linux and Git never use GitHub UI.

**Comment by floriank** [comment]
Rails does, Angular does. 

And most importantly, OpenProject does.

**Comment by marutosi** [comment]
Why do you  use GitHub which is **proprietary**?
There are many **opensource** DVCS management tools.
One is **Kallithea**.
https://kallithea-scm.org/

**Comment by NobodysNightmare** [comment]
May we stop the discussion at this point? Call me ignorant, but I will **not** discuss moving away from GitHub. Period.

**Comment by floriank** [comment]
I think it's beyond the scope of this discussion to question the use of GitHub.

**Comment by linki** [comment]
+1 for bringing back the sqlite3 gem. we currently solve the problem of a non-existing database connection at precompilation time by [targeting a temporary sqlite3 database](https://github.com/opf/openproject/pull/2591/files#diff-3254677a7917c6c01f55212f86c57fbfR169). for that to work we [need to inject the sqlite3 gem](https://github.com/opf/openproject/pull/2591/files#diff-3254677a7917c6c01f55212f86c57fbfR143), though. this complicates all the things, like [bundle caching](https://github.com/opf/openproject/pull/2591#issuecomment-112003260) and mounting local code in after the fact for development purposes.

**Pull request closed without merging**
