### PR TITLE
Feature/detail pane another set of translations

### PR DESCRIPTION
**Pull request by mtakac2**
https://www.openproject.org/work_packages/15136

### CODE REVIEW

**Comment by mtakac2** [comment]
@myabc I removed the uppercasing in js. Could you please add `text-transform` in to the css?

**Comment by myabc** [comment]
@hschink :+1: thanks

**Comment by hschink** [comment]
Rebased

**Comment by manwithtwowatches** [comment]
@mtakac @hschink I should probably apologise for this as it looks like it was me that forgot to do all of these in the first place:D

**Pull request merged**
