### PR TITLE
Set assignee and dates in wp-single-card (full rendering) to float bottom

### PR DESCRIPTION
**Pull request by Rincewind34**
Fixes [OP#45454](https://community.openproject.org/wp/45454)

**Please notice**, that I changed the place-self attribute from dates. That was already set to center for some reason that isn't apparent to me. I scooped through the application a bit and I couldn't figure out, where that matters.

The styling of the inline card was slightly off before, I didn't break it:
Screenshot 2022-12-15 at 11 00 14

The boards don't benefit from this feature, as they don't align cards by columns.

### CODE REVIEW

**Comment by ulferts** [comment]
The `dev` branch had failing specs from whence you branched off which is probably why the specs are failing in this PR. Please rebase/merge to fix this.

**Comment by Rincewind34** [comment]
@ulferts done (on all three pull requests). Test is still failing, but I don't see anything related to my changes.

**Comment by b12f** [comment]
Below are the two states. In the old iteration, the dates are centered against the avatar. With the changes in this PR, they're both aligned to the bottom of the card.

Without this PR:


With this PR:


I would personally vouch against this. The card currently does not show a principal name next to the avatar, but if it would it would show that name vertically centered with the avatar. With this change, the two pieces of text would be misaligned:

With this PR and with principal names:
20221219_12h48m38s_grim

I understand we do not show the principal name currently, but I do think it shows that we should center-align text that is "on the same line" as an avatar, since that's what we globally default to.

Pinging @psatyal @marcalcobe

**Comment by Rincewind34** [comment]
@b12f I agree and changed the code according to your feedback. Now the subject row is prioritised when growing and the assignee/dates row occupies always the amount of space it needs.

**Comment by psatyal** [comment]
Hi @b12f and @Rincewind34,

Based on the original WP (https://community.openproject.org/projects/openproject/work_packages/45454/activity), I agree that when board items are quite long, the assignee/date row can align to the bottom of the card.

However, as @b12f mentioned, this line must align with the assignee row in general (so in boards view, the Assignee name and dates must align).

So having the whole horizontal block be bottom-aligned + center-aligning text within it should do the trick 👍.

**Review by b12f — APPROVED** [review]
LGTM. Thanks a ton for the work you put in @Rincewind34

**Pull request merged**
