### PR TITLE
Show children duration clamp on gantt charts

### PR DESCRIPTION
**Pull request by aleixsuau**
https://community.openproject.com/projects/openproject/work_packages/32881

This pull request adds the following features:

- [x] If a work package has derived dates from children there are clamps below the bar. Also if the children are not on the same page or filtered out. Or the user does not have the permission to see the children.
- [x] The clamp turns red if the derived dates are before/after the manually scheduled dates (shown case). The clamps are black in case the derived dates are "inside" the dates.
- [x] In the automatic scheduling mode there are black clamps below the bar indicating that there are children.
- [x] Hovering a work package's row with visible children shows a grey box wrapping all its descendants (children, grandchildren...)
- [x] Highlight a row (blue) also when it has children.
- [x] Allow edit parent work packages dates dragging on the Gantt chart.

@ulferts I had to remove the row's z-index in order to have the parent's wrapper box below its children wp bars. As far as I could see, it doesn't affect any functionality but please double-check that it doesn't have side effects.

### CODE REVIEW

**Review by ulferts — CHANGES_REQUESTED** [review]
Hi @aleixsuau ,

there seems to be a couple of bugs related to the highlighting of the hierarchy. In case a work package is reported to have derived dates, the row below it will always be highlighted (on hover) regardless of whether the work package below is the actual child:
image

This is also present in the last row where the highlighting is simply displayed over empty space:
image

As a personal preference, I would have preferred the hierarchy highlighting to be displayed when hovering somewhere in the row. Currently, it is only displayed when hovering over the bar or the clamp which sometimes makes it hard to aim.

image

Also probably a personal preference, I would have preferred the hierarchy highlighting to span the whole of the descendants. To me, when having a deeper hierarchy, the highlighting now leads to grandchildren being visually excluded which makes it harder for me to parse:

image

When a work package has a child work package that has no finish date, it is displayed to end today (fading out). This looks weird when combined with the clamps as it is hard to reason why the clamps only span such a short duration when the child is displayed with a long bar. I believe this is not introduced in the PR and that the parent displays the derived dates correctly, but the combination looks off.

image

**Review by ulferts — CHANGES_REQUESTED** [review]
I think this is almost finished and looking good while at it.

There is one minor bug in case the parent work package does not belong to the original filtered set and is loaded afterwards to keep the hierarchy intact (indicated by the row being grayed out), e.g:
image
Here 2796 is grayed out since it is loaded afterwards. 
In such a case, the background normally applied to the children is never shown

**Comment by ulferts** [comment]
@aleixsuau, I just noticed, that the hover highlighting of the row does also not work for those added work packages:
image
If you stumble over the code responsible for this, it would be great if you could fix this as well.

**Comment by aleixsuau** [comment]
> @aleixsuau, I just noticed, that the hover highlighting of the row does also not work for those added work packages:
> image
> If you stumble over the code responsible for this, it would be great if you could fix this as well.

Hi @ulferts ,
I just pushed the fixes for those cases.

Did you take a look at this: "I had to remove the row's z-index in order to have the parent's wrapper box below its children's wp bars. As far as I could see, it doesn't affect any functionality but please double-check that it doesn't have side effects"?

Thanks

**Review by ulferts — APPROVED** [review]
Looking mighty fine, @aleixsuau :+1:

**Comment by ulferts** [comment]
@ingamai I noticed that the `z-index` in question has been added by you. Do you have any insights as to why it was added. I did not see any change in behaviour.

**Comment by ulferts** [comment]
Merging now. We might have to take another look at the z-index but as neither @aleixsuau nor I could spot anything, it shouldn't be to bad.

**Pull request merged**
