### PR TITLE
[18800] Restyle and restructure projects table in admin overview

### PR DESCRIPTION
**Pull request by HDinger**
used new tabe component design for projects table

https://community.openproject.org/work_packages/18800

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-feature-18800-restyle-projects-table.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-feature-18800-restyle-projects-table.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Thanks @HDinger , looks good so far!

I think the action buttons should be moved to the far right of the table (not sure if you plan on doing that, anyway), like in the first line of the following example which simply uses `text-align: right` for the buttons class

What do you think?

bildschirmfoto 2015-08-11 um 15 08 22

**Comment by HDinger** [comment]
Yeah, it looks better for me too. I'm going to do that.

**Comment by oliverguenther** [comment]
I've talked with Niels and he discovered the following issues wrt the table style:
1. The separating line between header row and content is not shown (compare with the work packages table):
   bildschirmfoto 2015-08-11 um 15 39 19
2. The highlight of a column does not apply to the whole column header, but only to the text 
3. There's a small margin between the column header text and the cell text (see vertical line below). They should be aligned

bildschirmfoto_2015-08-11_um_15_40_09

**Comment by ulferts** [comment]
> The highlight of a column does not apply to the whole column header, but only to the text

This behaviour of the work packages table is done via JS. (see https://github.com/opf/openproject/blob/dev/frontend/app/work_packages/directives/work-packages-table-directive.js#L112). We'd need to extract this behaviour from the work packages table and create a generic directive for that.

I could do that but it is definitely outside the scope of this PR.

**Comment by oliverguenther** [comment]
Thanks for the update, then let's move it out of this PR. I [have opened a separate work package](https://community.openproject.org/work_packages/21235) for that.

**Comment by NobodysNightmare** [comment]
> We'd need to extract this behaviour from the work packages table and create a generic directive for that.

Is that the behaviour I merged yesterday? Just asking to make sure the state of this PR, we could either:
- integrate the real highlighting now (if that is what I merged yesterday)
- leave it as is (with the broken highlight of the header) and wait for [WP 21235](https://community.openproject.org/work_packages/21235)
- remove the column highlight until it looks good (in [WP 21235](https://community.openproject.org/work_packages/21235))
- stall this PR until [WP 21235](https://community.openproject.org/work_packages/21235) is finished

**Comment by oliverguenther** [comment]
I believe the highlight is not that broken that it would impede merging this. It simply requires programatically expanding the width of the sort header field to span over the whole column width. @ulferts mentioned that this also happens in the work package directive and would need to be moved / recreated in the separate directive.

**Comment by NobodysNightmare** [comment]
I initially reported this in a [different PR](https://github.com/opf/openproject/pull/3344), but probably this one is the better place:

The headlines of table columns seem to overlap quite easily:

table-size

Should we allow word wrapping in the headers?

**Comment by ulferts** [comment]
Merging #3346 and then using it within this PR should remove the problems with the width and highlight the headers correctly.

At least as good as the work packages table did it.

**Comment by oliverguenther** [comment]
There's still one cuke broken in here, whose trivial fix I've already provided elsewhere (i think in my own PR): 
https://github.com/HDinger/openproject/pull/3

**Pull request merged**
