### PR TITLE
Gemfile: add :x64_mingw platform (aka RubyInstaller x64)

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-release-3-0-x64-mingw.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@marutosi 
This comment applies to all of these PRs: #2250, #2252, #2253, #2254

While these may be valid patches, we're only issuing _critical bug_ and _security_ fixes for Release 3.0. 
If you want to re-create PRs against Release 4.0 or dev, then they will be considered.

**Comment by myabc** [comment]
@marutosi ALSO PLEASE DESIST FROM FORCE-PUSHING TO TRAVIS. THAT REALLY PISSES ME OFF.

**Comment by marutosi** [comment]
Because you all use rebase.
https://github.com/opf/openproject/pull/2219#discussion-diff-20442793

**Pull request closed without merging**
