### PR TITLE
Run rubocop with lefthook only on modified lines

### PR DESCRIPTION
**Pull request by cbliard**
Inspired and adapted from
  https://gist.github.com/skanev/9d4bec97d5a6825eaaf6
  https://gist.github.com/MaxLap/ea4b6d1df81de3024562798b5501b9c8

### CODE REVIEW

**Comment by oliverguenther** [comment]
Tested locally, appears to work nicely. Thanks for looking into it :+1:

**Comment by cbliard** [comment]
Great! Thanks for testing it @oliverguenther

**Comment by oliverguenther** [comment]
@cbliard This is still marked as draft, but for me would be good to merge otherwise. WDYT?

**Comment by cbliard** [comment]
@oliverguenther yep, I wanted to give anyone a chance to test it. As you tested it, it's ready for review.

**Pull request merged**
