### PR TITLE
Improved the new project page template selection UI

### PR DESCRIPTION
**Pull request by b12f**

### CODE REVIEW

**Review by oliverguenther — APPROVED** [review]
Works well for me visually. I'd give @wielinde another say in this before merging

**Comment by b12f** [comment]
Before we merge, I'd like to rename the  `op-select-box` to `op-highlight` or something similar. If you have any other ideas hmu @oliverguenther

**Comment by oliverguenther** [comment]
If we determine that the component is always use to highlight a choice (select box or other input), I'd like the name `op-highlighted-choice|input`.

**Comment by oliverguenther** [comment]
I'm going to go ahead and merge this for now as I depend on these changes for a bug fix. If we have another round of visual changes, I'd suggest we do them in a separate PR then.

**Pull request merged**
