### PR TITLE
[#41934] restrict members filter scope to visible principals

### PR DESCRIPTION
**Pull request by Kharonus**
- https://community.openproject.org/work_packages/41934

### CODE REVIEW

**Comment by Kharonus** [comment]
I'd like to ignore the linter issue pointed out here. I just reformatted the line breaks in here, which is while he now complains, I introduced this `has_an_belongs_to_many`. alternatively @ulferts or @cbliard could tell me, that it is completely safe to change this relation to satisfy rubocop without any big issues. ^^

**Review by ulferts — CHANGES_REQUESTED** [review]
It is still possible to reproduce the bug by having a user that has the `:manage_members` or `:manage_user` permission and the queried for user is not a member of any project the querying user is also a member in. 

This is due to using the `in_visible_project` scope in the `PrincipalLoader` (which in turn is used by the `AssignedToFilter`) and the `visible` scope in the `MemberFilter` on principals.

I think this problem can be fixed by using the `visible` scope in the `PrincipalLoader`. That scope does switch depending on the permissions the querying user has.

**Comment by Kharonus** [comment]
Good find, will fix that.

**Comment by cbliard** [comment]
> I'd like to ignore the linter issue pointed out here. I just reformatted the line breaks in here, which is while he now complains, I introduced this `has_an_belongs_to_many`. alternatively @ulferts or @cbliard could tell me, that it is completely safe to change this relation to satisfy rubocop without any big issues. ^^

I wouldn't care too much for this rubocop lint issue.

Indeed `has_many :through` could be used and that means that a model `CustomFieldProject` should be introduced, very much like `Storages::ProjectStorage`: declare the `has_many` on both models, the `belongs_to` on the join model, then the `has_many :through` can be declared.

I don't feel like it's worth it. If it is then the other HABTM relations should be updated too, for consistency.

**Comment by Kharonus** [comment]
fine for me, then we have to deal with this PR being red due to this rubocop issue ;)

**Review by ulferts — APPROVED** [review]
:+1:

**Pull request merged**
