### PR TITLE
[old branch] reimplements context_menu with jQuery

### PR DESCRIPTION
**Pull request by tessi**
:information_source:  This is a maintenance PullRequest<sup>1</sup>

**The following actions may be done:**
- [ ] find the branch maintainer (or someone who cares enough)
- [ ] find/create a work package on openproject.org for this PR
- [ ] decide if the commits in this branch are still meant to be integrated
- [ ] delete the branch if the proposed change shall not be integrated
- [ ] rebase the branch on a current `dev`; test it

<sup>1</sup>: This PR was created to reduce the huge number of stale branches (branches which are older than 6 month and don't have a pull request). The goal is to give those branches a platform for review and discussion and -- on the long term -- either integrate or delete them.

### CODE REVIEW

**Comment by myabc** [comment]
I wouldn't merge this PR as-is, as we will be reworking the context menu as an Angular directive. However, I'd gladly cannibalise parts of the code: https://www.openproject.org/work_packages/5507

**Comment by myabc** [comment]
I rebased this work and incorporated it into the `feature/ng-context-menu` branch.

**Comment by mfrister** [comment]
@myabc Can we close this PR then?

**Comment by myabc** [comment]
@meeee ja

**Pull request closed without merging**
