### PR TITLE
Cleanup work package representation

### PR DESCRIPTION
**Pull request by Azure7111**
https://community.openproject.org/work_packages/17753

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://feature-cleanup-work-package-representation.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://feature-cleanup-work-package-representation.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by Azure7111** [comment]
@0xF013 You might want to have a close look at these changes, because @NobodysNightmare mentioned, that they might interfere with your current work. As in how you get version/project information from the API.

**Comment by myabc** [comment]
:+1: LGTM... are you ok with this @0xF013?

**Comment by 0xF013** [comment]
@myabc @Azure7111 will take a look after #2554

**Comment by 0xF013** [comment]
looks good so far

**Comment by 0xF013** [comment]
@myabc protractor tests are green locally on chrome

**Comment by myabc** [comment]
@0xF013 does that mean it works?

**Comment by 0xF013** [comment]
@myabc let's way for travis

**Comment by 0xF013** [comment]
needs review

**Pull request merged**
