### PR TITLE
[33163] Add work package filter for child work packages

### PR DESCRIPTION
**Pull request by bsatarnejad**
Adding parent WP to the filters that is used for both work packages and boards.

https://community.openproject.com/projects/openproject/work_packages/33163/activity

### CODE REVIEW

**Review by ulferts — CHANGES_REQUESTED** [review]
Right now, by default, only 10 work packages are fetched to be displayed as candidates for the parent filter:

image

In a project with more than 10 work packages in it, this would become unusable. 

What we would need in order for the filter to become usable again is for the available values to be loaded asynchronously. So while the user types, the values matching the search string are fetched from the backend and are then presented to the user.

You can see this happening in the boards view for a "Parent Child"-board:

image

**Comment by wielinde** [comment]
Hey @bsatarnejad, I converted this PR into "draft" so that we know that you are not waiting for a review. Please change that again whenever you think the PR is ready to be reviewed.

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/4b22bd8f22450ac424eda28f93296df3950545c6/frontend/src/app/components/filters/query-filter/query-filter.component.ts#L37">frontend/src/app/components/filters/query-filter/query-filter.component.ts#L37</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by aleixsuau — CHANGES_REQUESTED** [review]
Hi @bsatarnejad ,
Good work, it is working and I know you have stick to the patterns that OpenProject has been following. We would like to start following the 'Components Architecture' patterns that Angular promotes so I'd recommend you start applying them in this pull request. They are also the front-end industry standard right now so they are good to know and practice anyway.

Here go some comments to help you get there and about other things. Don't hesitate to reach me with any questions. We can pair programming if you want.

*   Try to think in terms of components architecture: stateful (smart) and stateless (dumb) components that communicate between them mostly via @Inputs and @Outpus:
    *   Avoid inheritance if not necessary (most of the cases): \
Inheritance forces to create new components that extend the parent in order to extend or modify its default behavior. In this case, you create the ‘wp-filter-searchable-multiselect-value’ in order to have specific filtering by project if it exists. This leads to having more components (one per filtering?), tightly coupled between them, which leads to more code to read, test, maintain… and it’s more difficult to reason about the code when you have to keep open a lot of files. \

    *   Try to make reusable components: \
I think we could make this component more reusable by:
        *   Creating a “filters” input which allows passing directly the filters from the parent component: \
&lt;wp-filter-searchable-multiselect-value [filters]=”[['is_milestone', '=', false]]”>&lt;/wp-filter-searchable-multiselect-value>
        *   Creating a “filterKey” and “filterValue” and “filterOperator” @Inputs that would allow the component to filter by dynamic values passed from the parent: \
&lt;wp-filter-searchable-multiselect-value filterKey=”project” filterOperator=”=” [filterValue]=”currentProject.id”>&lt;/wp-filter-searchable-multiselect-value>
        *   Creating default useful filters config inside the component so we can use it directly without having to pass @Inputs.
        *   It’s important to remember that @Input bindings ([]) are dynamics, so the component needs to handle these changes. \
 \
        * Creating a component this way we won’t need to develop any extra code in order to apply it to any other filtering because all is passed via @Inputs. It would also allow to extract from the component any logic (ie: CurrentProjectService) that doesn’t belong to its generic functionality (filtering), making it less stateful and easier to test and reason about. \
 \
        * You can read more about these patterns here: [https://blog.angular-university.io/angular-2-smart-components-vs-presentation-components-whats-the-difference-when-to-use-each-and-why](https://blog.angular-university.io/angular-2-smart-components-vs-presentation-components-whats-the-difference-when-to-use-each-and-why) \

*   In order to avoid showing the ‘parent’ filter on WpTableConfigurationFiltersTab, it would be better to just pass down the ‘filters’ that QueryFiltersComponent has to show (excluding the ‘parent’ filter from the filters @Input that WpTableConfigurationFiltersTab passes down). Passing down an extra fromConfigTable @Input two levels down works, but it’s not generic, it has nothing to do with the component’s functionality and ties the component to the context, and requires to add code in 5 different files. \

*   Avoid using setTimeout if not necessary (used in FilterSearchableMultiselectValueComponent.repositionDropdown()):
    *   I guess that the component was not positioned in the right place, but I couldn’t reproduce the issue. The only @Ouput that I saw was emitted was ‘open’ and the component was always in the right place. Anyways, if it would be needed, run it outside of angular in order to avoid triggering change detection on the entire app: \

````
this.ngZone.runOutsideAngular(()=>{
	setTimeout(() => {
        const component = (this.ngSelectInstance) as any;
        if (component && component.dropdownPanel) {
          component.dropdownPanel._updatePosition();
        }
        // Trigger change detection onñy for this component and its children
        this.changeDetectorRef.detectChanges();
      }, 20);

});
````
*   You can read more about this here: [https://angular.io/guide/zone](https://angular.io/guide/zone) \

*   Avoid using third-party libraries if not necessary:
    *   castArray

Thanks!

**Comment by bsatarnejad** [comment]
> Hi @bsatarnejad ,
> Good work, it is working and I know you have stick to the patterns that OpenProject has been following. We would like to start following the 'Components Architecture' patterns that Angular promotes so I'd recommend you start applying them in this pull request. They are also the front-end industry standard right now so they are good to know and practice anyway.
> 
> Here go some comments to help you get there and about other things. Don't hesitate to reach me with any questions. We can pair programming if you want.
> 
> * Try to think in terms of components architecture: stateful (smart) and stateless (dumb) components that communicate between them mostly via @inputs and @Outpus:
>   
>   * Avoid inheritance if not necessary (most of the cases): 
>     Inheritance forces to create new components that extend the parent in order to extend or modify its default behavior. In this case, you create the ‘wp-filter-searchable-multiselect-value’ in order to have specific filtering by project if it exists. This leads to having more components (one per filtering?), tightly coupled between them, which leads to more code to read, test, maintain… and it’s more difficult to reason about the code when you have to keep open a lot of files. \
>   * Try to make reusable components: 
>     I think we could make this component more reusable by:
>     
>     * Creating a “filters” input which allows passing directly the filters from the parent component: 
>       <wp-filter-searchable-multiselect-value [filters]=”[['is_milestone', '=', false]]”></wp-filter-searchable-multiselect-value>
>     * Creating a “filterKey” and “filterValue” and “filterOperator” @inputs that would allow the component to filter by dynamic values passed from the parent: 
>       <wp-filter-searchable-multiselect-value filterKey=”project” filterOperator=”=” [filterValue]=”currentProject.id”></wp-filter-searchable-multiselect-value>
>     * Creating default useful filters config inside the component so we can use it directly without having to pass @inputs.
>     * It’s important to remember that @input bindings ([]) are dynamics, so the component needs to handle these changes. 
>        \
>     * Creating a component this way we won’t need to develop any extra code in order to apply it to any other filtering because all is passed via @inputs. It would also allow to extract from the component any logic (ie: CurrentProjectService) that doesn’t belong to its generic functionality (filtering), making it less stateful and easier to test and reason about. 
>        \
>     * You can read more about these patterns here: https://blog.angular-university.io/angular-2-smart-components-vs-presentation-components-whats-the-difference-when-to-use-each-and-why \
> * In order to avoid showing the ‘parent’ filter on WpTableConfigurationFiltersTab, it would be better to just pass down the ‘filters’ that QueryFiltersComponent has to show (excluding the ‘parent’ filter from the filters @input that WpTableConfigurationFiltersTab passes down). Passing down an extra fromConfigTable @input two levels down works, but it’s not generic, it has nothing to do with the component’s functionality and ties the component to the context, and requires to add code in 5 different files. \
> * Avoid using setTimeout if not necessary (used in FilterSearchableMultiselectValueComponent.repositionDropdown()):
>   
>   * I guess that the component was not positioned in the right place, but I couldn’t reproduce the issue. The only @Ouput that I saw was emitted was ‘open’ and the component was always in the right place. Anyways, if it would be needed, run it outside of angular in order to avoid triggering change detection on the entire app: \
> 
> ```
> this.ngZone.runOutsideAngular(()=>{
> 	setTimeout(() => {
>         const component = (this.ngSelectInstance) as any;
>         if (component && component.dropdownPanel) {
>           component.dropdownPanel._updatePosition();
>         }
>         // Trigger change detection onñy for this component and its children
>         this.changeDetectorRef.detectChanges();
>       }, 20);
> 
> });
> ```
> 
> * You can read more about this here: https://angular.io/guide/zone \
> * Avoid using third-party libraries if not necessary:
>   
>   * castArray
> 
> Thanks!

Hi @aleixsuau  Thanks for your feedback, i have a few questions,
You mean i should only create a component for filtering WPs? If we want to have a component for filtering for example users, how can it be implemented? By current implementation, we only need to write a function for fetching the data from the server each time per each search. So we will write less code, if i am correct? But what i got from your comment, if we want to create a new component for user filter, we should write all the codes written in filter-searchable-multiselect-value component + a function to fetch its data?

I think adding filters @input is a great idea and makes it really reuseable.
Another question from my side is that if we add filters @input that is an array for filtering, why do we need to  filterKey, filterValue and filterOperator separately?

**Comment by bsatarnejad** [comment]
I will close this PR, because it is implemented in a better way in https://github.com/opf/openproject/pull/8826

**Pull request closed without merging**
