### PR TITLE
Timeline performance improvements

### PR DESCRIPTION
**Pull request by romanroe**

### CODE REVIEW

**Comment by ulferts** [comment]
Way better @romanroe 👍 

Instead of the the two seconds it took when toggling hierarchy mode, it now less than one. And I couldn't spot any negative effects of the change when scrolling.

**Comment by ulferts** [comment]
While the code and the functionality are looking good, there are a lot of code styling changes in there that do not conform to our `tslint.json`, most notably:
* double quotes instead of single quotes
* space before type declaration

While I don't care to much about a particular styling, I care about having a consistent styling throughout the codebase. It might be that your IDE does no longer include the `tslint.json` as intended.

**Comment by romanroe** [comment]
@ulferts It seems that my code formatter applied the wrong settings. Will fix the double quotes. Re. the space before type declaration: This is IMHO the TypeScript default, some IDEs cant even do it differently. Hence I suggest that we apply this rule.

**Comment by oliverguenther** [comment]
> This is IMHO the TypeScript default, some IDEs cant even do it differently. Hence I suggest that we apply this rule.

I've discussed with Jens and we both prefer the non-space version as its currently in the tslint since it visually couples the definition and its type declaration. I only know of the VS code editor that did not support it in TS 2.2. since its not part of the language service. However, our current editors all support it I reckon.

**Comment by romanroe** [comment]
2 vs 1 :-)

I've changed my WebStorm accordingly. We could consider to check in these settings.

**Comment by oliverguenther** [comment]
LGTM

**Pull request merged**
