### PR TITLE
Embed openproject-edition addon to use latest gltf2xkt version

### PR DESCRIPTION
**Pull request by crohr**
This would allow to more easily change versions of BIM dependencies without impacting existing installations.

/cc @wielinde

### CODE REVIEW

**Comment by oliverguenther** [comment]
I'm fine with tightly coupled packager dependencies to be merged into the core (we have packaging/scripts in there, too). But then I'd appreciate moving addon-openproject in here as well as it too is tightly coupled to the rake tasks

**Comment by crohr** [comment]
@oliverguenther sure, makes sense, I'll add it

**Comment by crohr** [comment]
@oliverguenther I also added the addon-repositories, which is specific to OpenProject as well.

**Comment by crohr** [comment]
I'll trigger a package build for this branch, then merge once I have tested that it still works.

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
