### PR TITLE
always clone when using currentParams.now; add some explanatory comments #44831

### PR DESCRIPTION
**Pull request by srkunze**
https://community.openproject.org/projects/openproject/work_packages/44831/activity

### CODE REVIEW

**Comment by ulferts** [comment]
@srkunze can you please also rebase/merge this PR?

**Comment by srkunze** [comment]
@ulferts Same thoughts on this. Sooner applying this fix, the better.

And how can we add a spec for this to prevent future re-introduction?

**Comment by oliverguenther** [comment]
Hi @srkunze , could you elaborate on what the buggy behavior is? I can then try to craft a feature spec for it.
To have a PR applied to the next patch release 12.3.3, you need to select `release/12.3` as the base/target branch of this PR and rebase the PR.

**Comment by srkunze** [comment]
@oliverguenther ~~I thought I did rebase it to release/12.3. Is that not correct?~~ Got it.

About the erroneous behavior:
While implementing #11573 I noticed that currentParams.now changed while zooming in and out. So I dug deeper and found that we are have the possibility to change the moment object by assigning it to another variable (although declared as readonly).

https://momentjscom.readthedocs.io/en/latest/moment/02-get-set/21-max/ speaks of a returned "instance" not a copy of the given inputs. So the min/max operation inadvertently returns the "currentParams.now" instance and after the forEach method, we change whatever instance is in newParams.dateDisplayStart and newParams.dateDisplayEnd.

So, a spec should just check that the .now property remains constant after zooming in or out.

**Comment by srkunze** [comment]
One additional note: the optical incorrect behavior was:

- a wandering today line in the Gantt chart
- an ever increasing right end or decreasing left end of the Gantt chart

**Comment by srkunze** [comment]
Maybe we can proceed like in #11575 and add specs later to at least fix the existing problematic behavior.

Still I am very interested in how a spec for this would look like. :-)

**Review by oliverguenther — APPROVED** [review]
LGTM. I haven't found a way to visually test the line, and we don't have any frontend specs set up in this area that we could extend for this case.

**Pull request merged**
