### PR TITLE
Gantt calendar weeks not according to settings

### PR DESCRIPTION
**Pull request by srkunze**
https://community.openproject.org/projects/openproject/work_packages/41327/activity

### CODE REVIEW

**Review by ulferts — APPROVED** [review]
The change seems solid @srkunze. Also, when testing it, the results seem to match what is expected.

As we had some hiccups on the CI, would you be so kind to rebase/merge your change to the latest dev to give the CI another run?

**Comment by ulferts** [comment]
Additionally, if you want to have the fix sooner, you'd need to rebase to the `release/12.3` branch and target that.

**Comment by srkunze** [comment]
@ulferts I hope I got this right because I think this fix helps sooner than later.

**Comment by srkunze** [comment]
@ulferts Additionally, does it make some sense to add a spec for this? I am not sure how to write one, though. :-/

**Comment by srkunze** [comment]
saw the edit button too late ...

**Comment by ulferts** [comment]
> Additionally, does it make some sense to add a spec for this?

@srkunze, it definitely would make sense to write one since it broke in the first place. So if you feel up to it, I'd welcome it very much.

But since the behaviour is already in the code base and this fixes the immediate problem, I'm gonna merge this once the specs are green. They probably just failed randomly so nothing for you to do here.

**Review by ulferts — APPROVED** [review]

**Pull request merged**
