### PR TITLE
Added avatars to users

### PR DESCRIPTION
**Pull request by mtakac2**

### CODE REVIEW

**Comment by manwithtwowatches** [comment]
@mtakac watchers will also have an avatarUrl because they are users, right?

**Comment by mtakac2** [comment]
@manwithtwowatches right but I'll add it in separate PR.

**Comment by manwithtwowatches** [comment]
That's just flickering stuff. I'm happy to merge this.

**Comment by mtakac2** [comment]
Cool - go ahead then ;)

**Pull request merged**
