### PR TITLE
[#59354] add missing dot to fix scope

### PR DESCRIPTION
**Pull request by Kharonus**
# Ticket
[OP#59354](https://community.openproject.org/work_packages/59354)

# What are you trying to accomplish?
- fix the scope

# What approach did you choose and why?
- fix the damn scope

### CODE REVIEW

**Comment by NobodysNightmare** [comment]
Do we have any unit tests in this area of the code that could have spotted this mistake? Should we add some?

**Review by akabiru — APPROVED** [review]
🔨

**Comment by Kharonus** [comment]
That is a valid point. I admit, I struggled, because I do no agree with the design of the custom fields. Their models have way too much logic and responsibilities.

~But I found a unit test for this controller and will add test cases for the scopes.~

Wait, no, the test I found is for the work package model. I will create a new model test, but will only add scope tests for now.

**Review by NobodysNightmare — APPROVED** [review]
Great, thanks for adding the tests. As far as I can tell they look good.

**Pull request merged**
