### PR TITLE
Switch to RBPDF

### PR DESCRIPTION
**Pull request by myabc**
See #1819 

http://www.redmine.org/issues/17570

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-rbpdf.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@ulferts this _works for me_ through manual testing. Do we want to invest time in adding spec coverage?

**Comment by floriank** [comment]
If it costs a day, I'd say lets do it - but move it into a future milestone.

**Comment by marutosi** [comment]
https://community.openproject.org/work_packages/14431

**Pull request closed without merging**
