### PR TITLE
[API] Return proper error when adding invalid relations

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work package

https://community.openproject.org/work_packages/19265
## Description

This should make the API respond properly to bad relations...

The relations endpoint needs some serious attention, though. I've created a ticket ^^

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-proper-error-for-invalid-relations.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-proper-error-for-invalid-relations.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@NobodysNightmare shit. I merged too soon – into `dev` – and had to cherry-pick the commit into `release/4.1`. I'm afraid the patch will now appear twice in history.

**Comment by floriank** [comment]
couldn't you just slice the commit off and force push `dev`? @myabc

**Comment by myabc** [comment]
@floriank we don't force push `dev`

(except when we do :wink:  )

**Comment by floriank** [comment]
quick, nobody is looking!

**Comment by NobodysNightmare** [comment]
I am always messing up with that target branch ^^

Sorry for that!

**Pull request merged**
