### PR TITLE
limit aggregation to one journable

### PR DESCRIPTION
**Pull request by ulferts**
With only .where("#{table_name}.id = ?", notes_id) appended, the DB would aggregated all (from all journables of all types) and then select the one that is necessary. This takes a considerable amount of time.

The commit will limit the aggregation to the journalizable the journal with the specified notes_id belongs to.

https://community.openproject.org/work_packages/21823

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-fix-performance-on-activity.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ulferts-fix-performance-on-activity.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
FYI @NobodysNightmare

**Comment by oliverguenther** [comment]
While I'm still having difficulties in parsing the whole aggregated journal SQL building (I prefer to read the actual logged SQL, to be honest), I see that reducing the aggregation to the related journalizable does result in a significant improvement in the local SQL wall I've been seeing since the aggregated journals landed.

Overall, this looks very solid to me :+1:.

@ulferts Out of interest: Is this the sole culprit for the timeout on community, or did you find other related issues?

**Comment by ulferts** [comment]
@oliverguenther no I have not seen anything that is in the same league. However, I haven't been able to identify why issuing multiple updates result in an significantly longer (exponential?) response time. There are 3 DB queries concerning journal aggregation issued for one update:
1) Get the AggregatedJournal to see if updating it is legit.
2) After updating the native Journal, reload the AggregatedJournal
3) Get the predecessor of the AggregatedJournal to build the diff that is then serialized to form the response to the PATCH.
I believe that subsequent requests interleave with the 3 DB queries of the first request and for reasons<sup>TM</sup> (might have to do with table locking but I don't know why locking is necessary for the reading) this blocks the second and the third SQL query of the first request. But that is just a theory. Given that the queries perform really fast now, I don't think this to be a major issue any more. Future might prove me wrong, however.

**Pull request merged**
