### PR TITLE
RSpec 3.3 Upgrade

### PR DESCRIPTION
**Pull request by myabc**
Continuation of #2682.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-rspec-3-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-rspec-3-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Pending travis approval, this is good to merge.

**Comment by myabc** [comment]
The two cuke failures were fixed in #3145

**Comment by ulferts** [comment]
Merging this although the cukes failed as those two where caused by another PR (and should be fixed by now) - #3145

**Comment by ulferts** [comment]
@myabc again beat me to it.

**Pull request merged**
