### PR TITLE
Fixes for pagination on small viewports

### PR DESCRIPTION
**Pull request by myabc**
https://www.openproject.org/work_packages/15375

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-15375-pagination-per-page-options-hidden.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by ulferts** [comment]
@myabc any chance you can prevent the two blocks (selected range and per page) to overlay one another?

image

It's not that bad and I will can merge this in any case as this here is better than what it used to be.

**Comment by myabc** [comment]
@ulferts will take another look

**Comment by myabc** [comment]
@ulferts I would have liked a CSS solution to show fewer pages on smaller viewports, but haven't managed it yet - in the meantime, I did a little more cleanup and reduced the default number of pages shown (see 9fda75cc).

**Pull request merged**
