### PR TITLE
Use date display field for card dates

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.org/work_packages/51858

### CODE REVIEW

**Review by HDinger — CHANGES_REQUESTED** [review]
The timezone issue is correctly fixed. However, there are some things that do not work correctly/like before:

* When start and end date are the same, the card abbeviated that before. Now it writes the date twice:
Bildschirmfoto 2024-01-23 um 01 43 32

Bildschirmfoto 2024-01-23 um 01 44 10

* When there is only a start date set, the card should show _DATE -_ . Now it is only showing the dash:
Bildschirmfoto 2024-01-23 um 01 40 35

**Comment by oliverguenther** [comment]
Bildschirmfoto 2024-01-22 um 16 16 49

Thanks for the feedback. They now show all cases correctly. single view and card is now consistent with the wanted exceptions of:

- The placeholder being empty for cards, but `-` for single view
- The long month names

The cards also now show milestone dates correctly, which wasn't the case before

**Review by HDinger — COMMENTED** [review]
The changes affect not only the cards but also the WP view. I assume, that this is not wanted, but we might have to double check with the product team.

**Before**
Bildschirmfoto 2024-01-23 um 08 43 22
Bildschirmfoto 2024-01-23 um 08 43 12

**After**
Bildschirmfoto 2024-01-23 um 08 41 42
Bildschirmfoto 2024-01-23 um 08 42 17

**Comment by oliverguenther** [comment]
@HDinger I've restored previous behavior with the exception of when the dates are equal. It is reduced to a single value then which I think makes sense.

**Comment by HDinger** [comment]
> @HDinger I've restored previous behavior with the exception of when the dates are equal. It is reduced to a single value then which I think makes sense.

I am not so sure about this, especially since the highlighting is lost. Before the, due date was highlighted if it is today or in the past. With the current solution this is lost. I guess it is sufficient if we re-add the highlighting to the date, but I guess we should double check with the product team.
Bildschirmfoto 2024-01-23 um 08 43 12

Bildschirmfoto 2024-01-24 um 22 34 09

**Pull request merged**
