### PR TITLE
[21494] Design issues on danger zone

### PR DESCRIPTION
**Pull request by HDinger**
This PR gives the icon a little margin to align it correctly. This is especially needed for FF under Windows. However it is useful for the other browser when the content gets zoomed. 
Further the header text for the danger zone of repos has changed, too.

https://community.openproject.org/work_packages/21494/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21494-design-issues-danger-zone.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21494-design-issues-danger-zone.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
#### Before

danger_before

#### After

danger_after

**Comment by mk84** [comment]
@HDinger Looks good, but tests are failing.

**Comment by HDinger** [comment]
@ulferts just remarked that the accessibility label for the input on the danger zone for WP is missing and tests on CI break. So do not merge before I fixed this.

**Comment by HDinger** [comment]
:ballot_box_with_check: I added the label and tests on CI were fixed from @ulferts . 
@mk84 Do you want to have a look again?

**Pull request merged**
