### PR TITLE
Restrict columns in group by dialog to groupable columns

### PR DESCRIPTION
**Pull request by tilt**
https://www.openproject.org/work_packages/8246

### CODE REVIEW

**Comment by myabc** [comment]
@tilt Cool. Will you handle the disabling the option for non-groupable columns in the column context menu separately?

**Comment by tilt** [comment]
disabling?

**Comment by tilt** [comment]
do you mean the de-selection of the group-by criterion?

**Comment by tilt** [comment]
OK fixed that as well

**Comment by myabc** [comment]
@tilt I believe the failed test is one of our "Flickering" friends… will merge regardless.

**Comment by tilt** [comment]
Thx, I appreciate that

**Pull request merged**
