### PR TITLE
Use new packager installer

### PR DESCRIPTION
**Pull request by kgalli**
This PR introduces a new dependency free (debconf) installation wizard. It also includes an add-on for the legacy installer (for migration to new wizard) and a definition to use ruby to 2.1.3.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-packager-new-installer-stable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by tessi** [comment]
:+1: for ruby 2.1.3

I can't judge the rest.

**Comment by tessi** [comment]
I see this is to be merged into `release/3.0` (thus I'll mark this PR as hotfix).
Will this also be merged into `release/4.0` and `dev`?

**Comment by kgalli** [comment]
@tessi your are right. Unfortunately ruby 2.1.4 is not supported by packager right now. I think we should merge this PR and add ruby 2.1.4 as soon as it is supported by packager.

**Comment by tessi** [comment]
@crohr is that right? Don't we have ruby 2.1.4 support on packager?

**Comment by tessi** [comment]
I'll merge this nonetheless (as we can add 2.1.4 support later)

**Comment by crohr** [comment]
@kgalli @tessi Ruby 2.1.4 is now available on Packager.io (http://blog.packager.io/post/101338638891/ruby-2-1-4-available) ;)

**Comment by myabc** [comment]
:yum:

**Comment by tessi** [comment]
@crohr You're really fast!

**Comment by crohr** [comment]
Automation helps :)

**Pull request merged**
