### PR TITLE
Docs update for 12.4

### PR DESCRIPTION
**Pull request by birthe**
[#44327] Make 2FA available in the community edition

https://community.openproject.org/work_packages/44327

This PR is work in progress:
- [x] The screenshots for date alerts need to be added
- [x] The screenshot for the Nofication center (menu section with date alerts) need to be updated
- [x] The screenshots for the Team planner need to be updated to include new work week.

Added by @psatyal:

- [x] Update Team planner text and images to correspond to changes in 12.4 since the original release

### CODE REVIEW

**Comment by birthe** [comment]
Hello @as-op I have changed the headline: /docs/getting-started/my-account/#two-factor-authentication-premium-feature and removed the premium feature. Could you please check if we have some links to this part of the documentation. I didn't find any.

**Comment by birthe** [comment]
Hi @psatyal, I created a new PR for 12.4 to include the final changes for the release. Feel free to commit directly to this PR for any changes to the documentation for 12.4.

**Comment by psatyal** [comment]
Hi @birthe, I had already created a draft PR for the changes to date alerts (changes complete) and team planner (on-going):
https://github.com/opf/openproject/pull/11633 

 I'll see if I can move those commits into this PR somehow, once I'm done with the changes to Team Planner. I'm sure this isn't too complicated to do.

**Comment by as-op** [comment]
I found some anchor changes (some are unrelated to PR). Fixed them myself into this PR as I was at right places anyway.

**Comment by psatyal** [comment]
Hi team, my last few commits did the following:

- Updated the _Notification settings_ user guide page to include date alerts + added screenshots
- Updated the _Team planner_ user guide page with rewritten text and all-new screenshots (lots had changed from 12.2)
- Updated the _Notification_ user guide page with new screenshots that include date alert, and the word "Involvement" being changed to "Reason".

@as-op Could you check the links again please, just in case? (Thanks again!)
@birthe Could I ask you to please review the text, please? It's quite possible that typos and errors will have slipt past my read-through.

Thank you!

Edit: I can't seem to add @birthe as a reviewer for some reason, perhaps because it's your PR?

**Review by as-op — APPROVED** [review]

**Comment by birthe** [comment]
@psatyal: I changed (sometimes shortened) and corrected a few things I found. There is one screenshot to be updated (Double Watcher in the Project-specific notification settings).

**Comment by psatyal** [comment]
Hi @birthe, thank you for the review. And thanks @MayaBerd for the typo corrections:

I made these changes page:

**Notification settings**
- Updated the screenshot
- Added a note about the "x days before" being natural days and not non-working days (as we spoke about in yesterday's weekly)

**Notification page**
- Added a table of contents
- Updated the structure of the page and phrasing in some areas for clarity (I'd previously only updated the screenshots and modified one section; reading back, I thought we could make this page clearner and more precise)

**Comment by psatyal** [comment]
Added text to Nextcloud admin docs about setting user defaults. The user guide already had it covered.

https://community.openproject.org/projects/documentation/work_packages/44923/activity

**Comment by psatyal** [comment]
Hi @birthe, added these details to the date alerts section. Could you please review?

- Recurrent overdue notifications replacing previous ones
- Date alerts generated at 1am
- 3 days ago means a WP due in 2 days won't generate a date alert

**Comment by psatyal** [comment]
Thank you for fixing the typos/errors, @birthe!

Cheers
Parimal

**Pull request merged**
