### PR TITLE
added: missing items in czech translate for costs module

### PR DESCRIPTION
**Pull request by tuxmartin**

### CODE REVIEW

**Comment by tuxmartin** [comment]
Can you please fix it in the next 11.x.x release? Thank you.

**Comment by ulferts** [comment]
Hi @tuxmartin,

and thank you for the PR. 

The translations are not originally maintained within this repository but merely pulled from crowdin. This should make it even easier for you to make the required changes:

https://crowdin.com/project/openproject

They will then be pulled into the code base automatically.

I am therefore closing this PR as its changes would be overwritten again.

**Comment by tuxmartin** [comment]
Hi @ulferts,

I added these two string to https://crowdin.com/translate/openproject/.

Is there any chance that they will get to the next release of 11.0.x?

https://crowdin.com/translate/openproject/1640/en-cs?filter=basic&value=0#q=Time%20and%20costs (`Time and costs`) is importatnt for me.

Thank you!

**Comment by ulferts** [comment]
As the scripts pull daily, those changes will make it into the next release.

**Comment by ulferts** [comment]
Worked: https://github.com/opf/openproject/blob/release/11.0/modules/costs/config/locales/crowdin/cs.yml#L85 :smile:

**Pull request closed without merging**
