### PR TITLE
[20325] Replace dynamic finders

### PR DESCRIPTION
**Pull request by myabc**
:warning: **Includes commits from #2104. Please review, merge first.**

https://community.openproject.org/work_packages/20325

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-20325-rails4-deprecated-dynamic-finders.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-20325-rails4-deprecated-dynamic-finders.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by marutosi** [comment]
https://github.com/opf/openproject/pull/3176#issuecomment-115654587

> Only if your changes depend on eachother (e.g. if you could only update a, when b is also updated) you should create a single PR.

**Comment by marutosi** [comment]
You are wrong.

**Comment by marutosi** [comment]
```
$ hg update 3.0.3
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
$ cat README.rdoc | head -1
= Redmine
$ find . -type f | grep -v .hg | xargs grep find_by | wc
    550    2424   54611
```

**Comment by marutosi** [comment]
It is easy to know what are deprecated (#2935).

**Comment by marutosi** [comment]
```
$ find . -type f | grep -v .hg | xargs grep find_by_ | wc
    550    2424   54611
```

**Comment by myabc** [comment]
@marutosi 

> It is easy to know what are deprecated (#2935).

Travis builds time out with this enabled.

**Comment by marutosi** [comment]
> Travis builds time out with this enabled.

Why not run on your machine?

**Comment by marutosi** [comment]
Rails3 deprecated replacing on Rails2.
http://www.redmine.org/projects/redmine/repository/revisions/6714

**Comment by myabc** [comment]
@marutosi thank you for (rightly) pointing out that not all dynamic finders are deprecated. However, for the sake of consistency, I've removed all dynamic finders anyway. Commit message updated appropriately.

**Comment by myabc** [comment]
@marutosi 

> Why not run on your machine?

I do that too.

**Comment by marutosi** [comment]
Rails4 deprecated replacing on Rails3.
http://www.redmine.org/projects/redmine/repository/revisions/12495

**Comment by myabc** [comment]
Closing in favour of #3194.

**Pull request closed without merging**
