### PR TITLE
removed obsolete invitations controller

### PR DESCRIPTION
**Pull request by machisuji**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://machisuji-fix-obsolete-invitations-controller.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://machisuji-fix-obsolete-invitations-controller.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@machisuji what about the routes?

**Comment by machisuji** [comment]
Good point.

**Comment by ulferts** [comment]
LGTM, wait for travis and merge at will.

**Pull request merged**
