### PR TITLE
Only sortable columns will now have option to sort in UI.

### PR DESCRIPTION
**Pull request by manwithtwowatches**
https://www.openproject.org/work_packages/9836

### CODE REVIEW

**Comment by manwithtwowatches** [comment]
@tilt I have made it so that the select2 lists don't show columns if they have already been selected in one of the other lists. What I'm not sure about though is getting the blank entry in there. Select2 has an option for this (allowClear, i think) but the angular wrapper doesn't seem to allow for the passing of the options hash to the constructor so i'm not sure how to achieve this. Let me know if you have any ideas.

**Comment by tilt** [comment]
@manwithtwowatches Oh I've done the same, picked up the ticket for it... I'll go on then and merge all stuff together

**Comment by manwithtwowatches** [comment]
@tilt ah bad communication on my part. damn home office:/

**Comment by tilt** [comment]
never mind

**Comment by tilt** [comment]
I'll integrate this branch with feature/round-off-sorting-dialog-8280 now

**Comment by tilt** [comment]
included in #1473

**Comment by tilt** [comment]
P.S.: @manwithtwowatches we excluded different columns, you the ones that aren't sortable, me the ones already selected. So no duplicate work was done here

**Pull request closed without merging**
