### PR TITLE
Fix/work package attributes in ie

### PR DESCRIPTION
**Pull request by ulferts**
Fixes displaying work package's attributes in IE. 
- https://community.openproject.org/work_packages/18933
- https://community.openproject.org/work_packages/18923

On top of that, it prevents labels from being hidden by their input or from scroll bars applied to them when the browser window width is reduced.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-fix-work-package-attributes-in-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ulferts-fix-work-package-attributes-in-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
18933 :+1:

**Comment by floriank** [comment]
18923 :+1: 

Let's wait for Travis though.

**Comment by floriank** [comment]
@ulferts can you rebase this and fix the hound complaints?

**Pull request merged**
