### PR TITLE
fix work package filter collapsed by default

### PR DESCRIPTION
**Pull request by 0xF013**
[`* `#15420` fix work package filter collapsed by default`](http://www.openproject.org/work_packages/15420)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://0xf013-feature-15420-work-package-filter-collapsed-by-default.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@0xF013 unfortunately some feature specs will need to be updated.

**Comment by 0xF013** [comment]
@myabc Amended

**Comment by myabc** [comment]
@0xF013 Great! (that was fast)

**Comment by myabc** [comment]
@0xF013 still seeing some failures. Are you able to fix these specs?

**Comment by 0xF013** [comment]
@myabc I am on it now. Trying to reproduce locally

**Pull request merged**
