### PR TITLE
Bugfix: IPv6 localhost is not working

### PR DESCRIPTION
**Pull request by nickmessing**
IPv6 localhost looks like "::" or "::1" wich is not possible to open in browser, using "[0:0:0:0:0:0:0:1]" instead.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nickmessing-bugfix-ipv6-protractor-tests.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nickmessing-bugfix-ipv6-protractor-tests.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
First of all :+1: for better IPv6 support ^^

But on to my real question: I can't seem to believe that a browser would reject a valid IPv6 address like, e.g. `::1`.

It seems like the problem could be, that IPv6 addresses **in general** are not enclosed in `[]`.

Is that the case? i.e. shouldn't the fix be to enclose an address in `[]` if the address family is IPv6?

**Comment by NobodysNightmare** [comment]
And what about using hostnames in general? (i.e. `localhost` instead of `127.0.0.1` or `[::1]`)

**Comment by NobodysNightmare** [comment]
I see two problems with the code (in its state before your PR):
1. It does not enclose IPv6 addresses correctly
2. I _assume_ it will break if the server is listening on any interface (IPv4: `0.0.0.0`; IPv6: `::`)

Thus I'd propose to address both issues independently, currently you are only fixing very special cases.

**Comment by nickmessing** [comment]
@NobodysNightmare, I tried enclosing ::1 but browser still refuses to open it, about the localhost, yes, it's a better solution.

**Comment by nickmessing** [comment]
@NobodysNightmare, enclosing ::1 and :: both work, don't know why it didn't when I tried, that's the right fix, thank you.

**Comment by NobodysNightmare** [comment]
:+1: LGTM, waiting for travis to verify...

**Pull request merged**
