### PR TITLE
hound config that matches `dev`

### PR DESCRIPTION
**Pull request by linki**
**danger** `release/3.0` **danger**

so it doesn't complain that much @tessi @kgalli

### CODE REVIEW

**Comment by myabc** [comment]
:+1:

**Comment by ulferts** [comment]
@linki the **danger** could also be expressed by naming the branch with hotfix/hound_for_release and tagging it.

**Comment by linki** [comment]
@ulferts thx for the hint

**Comment by tessi** [comment]
Al Bundy approves!

Al Bundy approves!

**Pull request merged**
