### PR TITLE
Adding GitLab to application architecture documentation

### PR DESCRIPTION
**Pull request by MayaBerd**

### CODE REVIEW

**Review by akabiru — APPROVED** [review]
:shipit: ✨

**Comment by akabiru** [comment]
@MayaBerd - just an FYI that AFAIK the patch release was done and I'm not sure whether there is another one planned. So perhaps we base this into the `dev` branch. cc @dominic-braeunlein 

---

_[Release Calendar](https://community.openproject.org/projects/openproject/calendars/3562?cdate=2024-03-26&cview=dayGridMonth)_

**Comment by MayaBerd** [comment]
> @MayaBerd - just an FYI that AFAIK the patch release was done and I'm not sure whether there is another one planned. So perhaps we base this into the `dev` branch. cc @dominic-braeunlein
> 
> _[Release Calendar](https://community.openproject.org/projects/openproject/calendars/3562?cdate=2024-03-26&cview=dayGridMonth)_

I think that this should already have been a part of 13.4 release, since it "only" shows how the GitLab integration fits into OpenProject architecture. If we use the 'dev' branch, then it will only be published with 14.0

**Comment by akabiru** [comment]
> > @MayaBerd - just an FYI that AFAIK the patch release was done and I'm not sure whether there is another one planned. So perhaps we base this into the `dev` branch. cc @dominic-braeunlein
> > _[Release Calendar](https://community.openproject.org/projects/openproject/calendars/3562?cdate=2024-03-26&cview=dayGridMonth)_
> 
> I think that this should already have been a part of 13.4 release, since it "only" shows how the GitLab integration fits into OpenProject architecture. If we use the 'dev' branch, then it will only be published with 14.0

Ah yes, 13.4.1 is on the way apparently 👍🏾

**Pull request merged**
