### PR TITLE
19458 Upgrade Foundation for Apps to 1.1

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/19458

Also addresses:
- https://community.openproject.org/work_packages/19334 (partially)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-19458-foundation-apps-1-1-upgrade.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-19458-foundation-apps-1-1-upgrade.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
ie11_-_win8_1__clean_snapshot___running_

With this PR, the zoom slider is now displayed in both IE10 and 11. However, the positioning ~~and colour~~ is still incorrect (disclaimer in https://github.com/opf/openproject/pull/2689#issue-60857536 still applies).

**Comment by floriank** [comment]
@NobodysNightmare could you do the sweet sweet IE-review?

**Comment by floriank** [comment]
screenshot from 2015-04-09 16 35 09

Unfortunately this breaks the button highlight color for me :(

**Comment by myabc** [comment]
@floriank did you pull the latest commits? did you do a `bower install`?

**Comment by floriank** [comment]
Let me try a `bower i`.

**Comment by floriank** [comment]
Still, same result in Chrome :(

**Comment by floriank** [comment]
After removing `.sass-cache` and clearing `tmp`, It now works.

LGTM. :+1:

**Comment by NobodysNightmare** [comment]
Slider is still broken in IE 11:
slider-broken

**Comment by floriank** [comment]
@myabc - are these tests still flickering or did something actually break? I'd merge this but I have to recheck :-)

**Comment by floriank** [comment]
boom goes the dynamite.

**Pull request merged**
