### PR TITLE
update execjs to 2.4

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-exec-js.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-exec-js.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
I'd prefer to merge this into `release/4.1`. I'm irritated though by the fact there is no `CHANGELOG` for execjs.

**Comment by myabc** [comment]
Merged into `release/4.1`  (485fd96970393a75578bb3d27edc4b0cc4c5ba30).

**Comment by myabc** [comment]
@kgalli Checked execjs source. 2.4 should continue to support `export EXECJS_RUNTIME='Disabled'`: https://github.com/opf/openproject/pull/2692#issuecomment-78957528

**Pull request closed without merging**
