### PR TITLE
[38519] Global search short cut key "S" not working

### PR DESCRIPTION
**Pull request by HDinger**
Add the accesskey to trigger the search to global-search-input-component. 

https://community.openproject.org/projects/openproject/work_packages/38519/activity

### CODE REVIEW

**Review by oliverguenther — CHANGES_REQUESTED** [review]
Can't we add an input to the op-autocompleter though that forwards it to the ng-select? Setting an accesskey on the ng-select appears to have worked before, so that wold be my preferred solution rather than some extra knowledge in the keyboard service.

Also, a spec would be nice

**Comment by b12f** [comment]
Not sure how much work it'd be, but we could remove the jquery dependency from the keyboard directive here

**Review by oliverguenther — APPROVED** [review]
Changes LGTM now. Spec would still be nice

**Review by b12f — APPROVED** [review]
nice, lgtm

**Pull request merged**
