### PR TITLE
replacing instance variables

### PR DESCRIPTION
**Pull request by ulferts**
Mini refactoring to replace some instance variables by methods. By that the constructor was no longer necessary.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-access-control-refactor.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
On a very general level, +1 for avoiding ivars
Not sure how I feel about lazy-initialising ivars. Another option here would be to keep the ivar initialisation in `initialize` but DRY things up with `attr_reader`.

**Comment by ulferts** [comment]
@myabc what drawbacks do you see with lazy initialization?

**Comment by myabc** [comment]
@ulferts warnings in Ruby verbose mode… but that's not really a real world problem. 

In the end, I don't really mind which way we go, but we should maintain a consistent style.

**Comment by ulferts** [comment]
@myabc the reason I like doing it this way is that I am able to easily overwrite this in tests. I can create a subclass of the test object which overrides the method and by that inject a new dependency. Additionally, I try to avoid overriding the initializer whenever I can, because I fear forgetting to call `super`.

**Pull request merged**
