### PR TITLE
[32436] Add resizer to table and split view next to IFC viewer

### PR DESCRIPTION
**Pull request by HDinger**
### ToDo

- [x] Add resizer between IFC viewer and WP list
- [x] Add minimum width for the viewer 
- [x] Fix issues:
  - [x] Right content can increase that much that the the wohl page grows (when the minimum of the left side was reached)
  - [x] The WP page does not correctly recognise the current partition state
  - [x] Dragging the resizer further to the left than the element can increase, leads to confusing behaviour when starting to resize again.

### CODE REVIEW

**Comment by HDinger** [comment]
Ticket:
https://community.openproject.com/projects/openproject/work_packages/32436/activity

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/38030bb1c7e6915e4811c8c4e056dca0b66fa4e1/frontend/src/app/components/resizer/wp-resizer.component.ts#L35">frontend/src/app/components/resizer/wp-resizer.component.ts#L35</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/38030bb1c7e6915e4811c8c4e056dca0b66fa4e1/frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts#L16">frontend/src/app/components/wp-table/embedded/wp-embedded-table.component.ts#L16</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by oliverguenther — APPROVED** [review]
LGTM :+1:

**Comment by HDinger** [comment]
I would wait with the merge on https://github.com/opf/openproject/pull/8071. There, the create routes are simplified and I think it's easier to resolve the conflicts here.

**Comment by oliverguenther** [comment]
The other PR has conflicts anyway, I'll fix them over there

**Pull request merged**
