### PR TITLE
Removed an extra line in the calender which should only be there if a…

### PR DESCRIPTION
**Pull request by HDinger**
… filter was selected.

https://community.openproject.org/work_packages/20704

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-20704-remove-extra-line-calender.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-20704-remove-extra-line-calender.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Hi Henriette, welcome on board! This change breaks the following spec: [spec/features/accessibility/work_packages/calendar_toggable_fieldsets_spec.rb](https://github.com/opf/openproject/blob/dev/spec/features/accessibility/work_packages/calendar_toggable_fieldsets_spec.rb), as it expects the fieldset to be expanded initially.

The spec is easily fixed with the following patch:

``` patch
diff --git a/spec/features/accessibility/work_packages/calendar_toggable_fieldsets_spec.rb b/spec/features/accessibility/work_packages/calendar_toggable_fieldsets_spec.rb
index 24195a0..17d268c 100644
--- a/spec/features/accessibility/work_packages/calendar_toggable_fieldsets_spec.rb
+++ b/spec/features/accessibility/work_packages/calendar_toggable_fieldsets_spec.rb
@@ -45,7 +45,7 @@ describe 'Work package calendar index', type: :feature do
     end

     describe 'Filter fieldset', js: true do
-      it_behaves_like 'toggable fieldset initially expanded' do
+      it_behaves_like 'toggable fieldset initially collapsed' do
         let(:fieldset_name) { 'Filters' }
       end
     end
```

**Comment by oliverguenther** [comment]
The branch you use for this pull request is based on an older branch of `release/4.3`. You'll have to rebase it against `release/4.3`, because otherwise you introduce a number of commits to this PR which are already present on `release/4.3`

**Comment by oliverguenther** [comment]
I've just tested this and the initial state is correct:
- Filters are empty and thus collapsed
- The separator line is hidden

When adding a filter and pressing apply however, I'd expect the  filter section to be expanded.
But instead, the filters are also collapsed.

If they indeed should be shown, this patch should do the trick

``` diff
diff --git a/app/views/work_packages/calendars/index.html.erb b/app/views/work_packages/calendars/index.html.erb
index 923fc9e..75cb164 100644
--- a/app/views/work_packages/calendars/index.html.erb
+++ b/app/views/work_packages/calendars/index.html.erb
@@ -29,9 +29,10 @@ See doc/COPYRIGHT.rdoc for more details.
 <%= toolbar title: (@query.new_record? ? l(:label_calendar) : h(@query.name)) %>
 <%= form_tag(work_packages_calendar_index_path, :method => :get, :id => 'query_form') do %>
   <%= hidden_field_tag('project_id', @project.to_param) if @project%>
-  <fieldset id="filters" class="form--fieldset -collapsible collapsed" >
+  <% query_empty = @query.filters.empty? %>
+  <fieldset id="filters" class="form--fieldset -collapsible <%= query_empty ? 'collapsed' : '' %>" >
     <legend class="form--fieldset-legend" onclick="toggleFieldset(this);"><a href="javascript:"><%= l(:label_filter_plural) %></a></legend>
-    <div class="" style="display: none;">
+    <div class="" <%= raw query_empty ? 'style="display: none;"' : '' %>>
       <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
     </div>
   </fieldset>
```

**Comment by ulferts** [comment]
I think that it is working as specified. In order to make it work in a way consistent with the work packages table would require some larger amount of work and frankly, some hacking at a place we do not place our focus on right now.

**Pull request merged**
