### PR TITLE
Bugfix: Local var same with parameter

### PR DESCRIPTION
**Pull request by nickmessing**
Simple code improvement.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nickmessing-bugfix-local-var-same-with-parameter.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nickmessing-bugfix-local-var-same-with-parameter.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
:+1:

**Comment by floriank** [comment]
:+1:

**Comment by myabc** [comment]
Merging. Travis problems were unrelated. No need to rebase.

**Pull request merged**
