### PR TITLE
Add initial Hound configuration

### PR DESCRIPTION
**Pull request by myabc**

### CODE REVIEW

**Comment by machisuji** [comment]
What's our policy on dot position in multi-method chains?
I for one prefer leading as opposed to trailing (which is part of the PR): http://pastebin.com/9JXgmB3B

**Comment by myabc** [comment]
@machisuji Rubocop's default is leading, but Hound overrides this to prefer trailing.
https://github.com/thoughtbot/hound/blob/master/config/rubocop.yml
https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L201

I'd personally prefer leading. Marginally.

**Comment by tessi** [comment]
A also prefer leading dots marginally.

**Comment by machisuji** [comment]
Would everyone be alright with me changing that to leading and merging the PR then? @myabc @tessi

**Comment by myabc** [comment]
@machisuji 

> Would everyone be alright with me changing that to leading and merging the PR then? 

Yes! :+1:

**Pull request merged**
