### PR TITLE
Nextcloud documentation user setup

### PR DESCRIPTION
**Pull request by marcalcobe**
I've included the documentation step by step on how users can on a personal level connect/login in order to use the Nextcloud integration.
@psatyal can you please double check it?

### CODE REVIEW

**Comment by marcalcobe** [comment]
https://community.openproject.org/work_packages/43777/activity

**Review by psatyal — APPROVED** [review]
I've reviewed and updated your docs @marcalcobe for clarity and grammar 👍 Ok to merge on my end.

**Comment by alexanderadam** [comment]
Nice, is there also a possibility to prefill File storage Nextcloud settings on OpenProject via ENV variables?
If so: would it be possible to document them as well?
If not: would this be a valid feature request?

**Comment by Kharonus** [comment]
Ahoy @alexanderadam,

thank you for putting some thoughts into it, how we could improve this very young feature. At least for now, it is not possible to preconfigure your system with env variables, to setup the storage.

This is mainly due to the reason, that there is a lot of runtime checks done when configuring a storage. To name them:

- URL is checked, if there is already a storage configured with this URL (url is a second identifier for a storage entity within the system)
- URL is queried to check if
  - there is a nextcloud responding at this URL
  - the nextcloud storage has the required minimum version
  - the nextcloud storage is configured to receive and handle bearer tokens
- after putting a valid URL, a OAuth App is created on OP side. It is due to a security decision, that the secret of newly created, confidential oauth apps are shown only once and then are hashed in the database. So you have no means to read them later on. Hence it is needed to read the secret while creating it, to insert it into the nextcloud settings.

Due to these reasons, I find it rather hard to think about a preconfiguration of the file storages. But this does not mean, that we are not thinking about other possibilities of configuring this feature in future. We also need to observe the usage, and evaluate, how it is accepted by the users. ;)

Best
Eric

**Comment by marcalcobe** [comment]
Hi @opf/doc-writers,
Can we merge this PR? Or do you want to review it?

**Comment by lindenthal** [comment]
> Hi @opf/doc-writers, Can we merge this PR? Or do you want to review it?

Hi @marcalcobe,

Deploying an updated docs is still better than having wrong docs online. If am doing a review here this would be the fourth review round. We need to streamline this process and enable everybody in the team to commit doc fixes with confidence.

**Comment by marcalcobe** [comment]
Hi @lindenthal, yes I agree that having documentation is better than having nothing. Unfortunately we didn't know if we are able to merge our own PR or if it is always needed a review from doc-writers no matter what. From now I understand we can merge documentation PRs if we are confident about them.

**Comment by lindenthal** [comment]
Hi @marcalcobe,

yes, I think you and @psatyal have all the skills to merge with confidence.
It is very inefficient to have multiple review stages for docs. This is different for requirements, legal documents and security sensitive topics.

Best
Niels

**Comment by psatyal** [comment]
Hi @marcalcobe, @lindenthal:

Well now that that's cleared up, @as-op has deployed the update and it's now live: https://www.openproject.org/docs/user-guide/nextcloud-integration/

Cheers
Parimal

**Pull request merged**
