### PR TITLE
Remove warning about unsupported browser

### PR DESCRIPTION
**Pull request by kalvdans**
The warning was incorrectly shown for supported, but untested, browsers. Trust the operating systems own methods for nagging users to update their browser.

This PR was triggered when I suddenly saw the warning and couldn't find the corresponding change in code that require updated browser. Then I found https://github.com/opf/openproject/pull/13035 and understood that it just means untested browser instead of unsupported.

I think it is not worth the trouble to maintain code no one is asking for, so this PR removes it. Ping @oliverguenther and @HDinger .

### CODE REVIEW

**Comment by Eric-Guo** [comment]
Guess can also remove gem "browser", I just bump it at #15437 😢

**Comment by kalvdans** [comment]
> Guess can also remove gem "browser", I just bump it at #15437 😢

Is it unused? Nice, do you want me to do it in this PR or a follow-up PR?

**Comment by HDinger** [comment]
Hi @kalvdans 

We strongly want to encourage our users to use OpenProject within an up-to-date browser. There are several reasons for this. Firstly, as you say, we naturally **test and develop** in current browsers and can therefore guarantee the best possible product. But it's not just about testing, it's really also about what we **support**. For example, we will no longer fix bugs that occur in the Internet Explorer. And we will also not fix errors that only occur in versions that are lower than what is in that supported list.
Therefore, it is important to display this warning. We cannot rely on the operating system to provide sufficient warnings either, because such messages can be quickly clicked away and even switched off. I think we have left enough time for the updates, Chromium is now at version 121 and we show the warning on versions below 109. Firefox is already at 126 and the warning is displayed for versions below 101. 

If you are hosting OpenProject yourself, you can disable this warning with an [environment variable](https://www.openproject.org/docs/installation-and-operations/configuration/environment/#supported-environment-variables). However, be aware that this will hide **all** banners, also those warning about pening migrations or deprecations.

**Comment by kalvdans** [comment]
@HDinger Thanks for your long explanation. It was not clear to me that this was about commercial support, I thought it was Browser API:s that openproject depend on. I would be good if you could add the explanation you just wrote as a comment in browser_helper.rb to help others like me :)

Thanks for the environment variable tip.

**Pull request closed without merging**
