### PR TITLE
17412 priority editable

### PR DESCRIPTION
**Pull request by 0xF013**
[`* `#17412` priority editable`](http://community.openproject.org/work_packages/17412)
based on #2478

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://0xf013-feature-17412-priority-editable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://0xf013-feature-17412-priority-editable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Some protractor tests fail

**Comment by 0xF013** [comment]
@ulferts will mark this as ready as soon as #2478 is merged in

**Comment by ulferts** [comment]
LGTM. Free to merge if travis agrees

**Comment by ulferts** [comment]
@0xF013 seems like Travis does not agree.

**Comment by 0xF013** [comment]
@ulferts it's a typo, will fix it today

**Comment by 0xF013** [comment]
@ulferts green

**Pull request merged**
