### PR TITLE
Meets #10712: Missing subfolder in url for some modules

### PR DESCRIPTION
**Pull request by netfighter**
[`* `#10712` Missing subfolder in url for some modules`](https://www.openproject.org/work_packages/10712)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://netfighter-feature-10712-missing-subfolder-in-url.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by ulferts** [comment]
Those changes break the work package detail page. I'll have to ask @myabc for the why.

**Comment by ulferts** [comment]
image
E.g the route to the assigned user is wrong containing the RAILS_RELATIVE_URL_ROOT twice

**Comment by hschink** [comment]
Closed in favor for #1984

**Pull request closed without merging**
