### PR TITLE
[21863] Widget-box styles on projects overview

### PR DESCRIPTION
**Pull request by mk84**
https://community.openproject.org/work_packages/21863/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mk84-21863-widget-box-styles-on-projects-overview.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mk84-21863-widget-box-styles-on-projects-overview.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
I think we should place the description either separately above the boxes, or inside a box of its own. In its current state, it looks somehow out of place.

seeded_project_-_overview_-_openproject

**Comment by mk84** [comment]
@oliverguenther You're right – I moved the description above the widget boxes. Waiting for travis now.

**Comment by oliverguenther** [comment]
The description looks good, thanks! I've found one more tiny nuissance: the distance between the boxes is not the same horizontally as it is vertically. The bigger distance (horizontal) is consistent with the homescreen.
seeded_project_-_overview_-_openproject

**Comment by oliverguenther** [comment]
Thanks for the update. Looks good and Travis agrees, as well. :+1:

**Pull request merged**
