### PR TITLE
Feature/rails3 databasecleaner autostrategy

### PR DESCRIPTION
**Pull request by sschu**
Picks the database cleaner strategy for spec and cucumber for each test based on the currently selected
test driver and uses the slower truncation strategy only when javascript is enabled and selenium is used
causing concurrent database accesses

### CODE REVIEW

**Comment by tessi** [comment]
Please test your changes with postgresql again. The specs worry me. They give a transaction warning per test.

<pre>
$ rake spec
/home/philipp/.rvm/rubies/ruby-1.9.3-p392/bin/ruby -S rspec ./spec/controllers/custom_fields_controller_spec.rb ./spec/controllers/projects_controller_spec.rb ./spec/controllers/users_controller_spec.rb ./spec/controllers/wiki_controller_spec.rb ./spec/controllers/wiki_menu_authentication_spec.rb ./spec/lib/acts_as_journalized/journaled_spec.rb ./spec/lib/acts_as_watchable/lib/acts_as_watchable/routes_spec.rb ./spec/lib/redcloth/redcloth_spec.rb ./spec/lib/redmine/themes/default_theme_spec.rb ./spec/lib/redmine/themes/theme_spec.rb ./spec/lib/redmine/themes/view_helpers_spec.rb ./spec/lib/redmine/themes_spec.rb ./spec/models/custom_field_spec.rb ./spec/models/deleted_user_spec.rb ./spec/models/issue_spec.rb ./spec/models/project_spec.rb ./spec/models/role_spec.rb ./spec/models/user_deletion_spec.rb ./spec/models/user_spec.rb ./spec/models/wiki_menu_item_spec.rb ./spec/routing/users_routing_spec.rb ./spec/routing/watchers_spec.rb ./spec/routing/wiki_routing_spec.rb ./spec/views/wiki/new.html.erb_spec.rb
.WARNING:  there is already a transaction in progress
.WARNING:  there is already a transaction in progress
.WARNING:  there is already a transaction in progress
.WARNING:  there is already a transaction in progress
.WARNING:  there is already a transaction in progress
.WARNING:  there is already a transaction in progress
.WARNING:  there is already a transaction in progress
.WARNING:  there is already a transaction in progress
[...]
</pre>

It seems postgresql cannot handle the DatabaseCleaner strategy you use.
Otherwise the tests seem to run w/o problems.

**Comment by mfrister** [comment]
@sschu @cnrk What's the status of this pull request?

**Comment by sschu** [comment]
This was more of a test balloon. Considering it might also break things in addition to speeding up, we
might just close it for now and revisit it later as part of an endeavour to speed up our tests.
What do you think?

**Comment by mfrister** [comment]
:+1:

**Comment by sschu** [comment]
OK, I am going to close this for now...

**Pull request closed without merging**
