### PR TITLE
store sessions in the cache by default all the time

### PR DESCRIPTION
**Pull request by linki**
let's store session data in whatever is used for the server-side cache as it's more secure than cookie based store.

### CODE REVIEW

**Comment by linki** [comment]
```
[1] pry(main)> Rails.application.config.cache_store
=> [:file_store, ".../openproject/tmp/cache/"]
```

in dev and production defined by Rails itself. a cleaner version (add defaults to `configuration.yml` as well as `configuration.rb`) needs some refactoring, as these stores take extra parameters. the current solution only works for `memcache` and is implemented quite... interesting...

=> lets do that in a different PR

**Comment by linki** [comment]
ping @meeee

**Comment by mfrister** [comment]
Waiting for manual tests, let me know when you're done :)

**Comment by mfrister** [comment]
:+1:

**Pull request merged**
