### PR TITLE
Feature/add foundation js

### PR DESCRIPTION
**Pull request by ulferts**
Add foundation's js parts into the built pipeline and the angular app. 

The modal functionality is required by @HDinger to be used on the application tour.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-feature-add-foundation-js.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://ulferts-feature-add-foundation-js.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@HDinger I elaborated the initial solution so you should base whatever you have on the current HEAD of the branch.

@furinvader, @oliverguenther please be extra watchful when merging this PR. Everything seems to be working but I am not overly experienced yet with using webpack.

**Comment by lindenthal** [comment]
Can we also use this to replace the modal in the timelines that is used for the create work package modal?

**Comment by ulferts** [comment]
Closing in favor of #4464

**Pull request closed without merging**
