### PR TITLE
[51402] Date field on work package too narrow

### PR DESCRIPTION
**Pull request by HDinger**
Use flex to ensure that the field is wide enough (e.g. on WP create form). 

https://community.openproject.org/projects/openproject/work_packages/51402/activity

### CODE REVIEW

**Comment by ulferts** [comment]
It would be nice if we could find some solution between "the field is too narrow" and "the field spans the whole width"

image

With the change, this now in some cases has a lot of empty space in the input. It would have to be a fixed max value which runs the danger of not working in some locales. But I find that acceptable to avoid a lot of empty input.

**Comment by oliverguenther** [comment]
@ulferts The other fields also become full width when edited, so this is consistent

**Review by oliverguenther — APPROVED** [review]

**Comment by oliverguenther** [comment]
Wrong target branch, I've cherry-picked it here: https://github.com/opf/openproject/commit/0c112a6bb2

**Comment by HDinger** [comment]
> Wrong target branch, I've cherry-picked it here: [0c112a6bb2](https://github.com/opf/openproject/commit/0c112a6bb2)

Thanks @oliverguenther ! 🙇

**Pull request merged**
