### PR TITLE
Add a format to display lastname and firstname without space

### PR DESCRIPTION
**Pull request by longyn**
Add a format to display Chinese username without space between lastname and firstname

So the end user can easy to `@` and search other people.

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @longyn , thanks for the addition. This makes sense and looks good to me. There are a few steps missing with regards to filtering and sorting where this addition will fail currently:

- https://github.com/opf/openproject/blob/dev/app/models/principals/scopes/ordered_by_name.rb#L56-L68
- https://github.com/opf/openproject/blob/dev/app/models/queries/filters/shared/user_name_filter.rb#L70-L81

Also, here's a test that tests the correct order when using this filter: https://github.com/opf/openproject/blob/dev/spec/models/principals/scopes/ordered_by_name_spec.rb#L69

I'll try to add to this PR when I find the time to finish it.

Lastly, I also added a feature ticket so we can add this to the release notes: [OP#40759](https://community.openproject.org/wp/40759)

**Comment by longyn** [comment]
Hi @oliverguenther, code updated according to your reply.

**Review by oliverguenther — APPROVED** [review]
LGTM, thanks @longyn

**Comment by piegamesde** [comment]
Why can't we just make a single "display name" field? This would not only make the distinction superfluous, it would also accommodate [mononymous people](https://en.wikipedia.org/wiki/Mononymous_person).

**Pull request merged**
