### PR TITLE
Add note on secret token

### PR DESCRIPTION
**Pull request by zepheiryan**
Followed this guide and got a broken server until I came across the section in the latest manual install guide about Rails' forced environment usage for setting its secret_key_base value.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://zepheiryan-patch-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://zepheiryan-patch-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Thanks for the PR, @zepheiryan.

**Comment by ulferts** [comment]
I just saw, that the PR is issued against stable/5. Can you please reissue it against release/5.0?

**Comment by zepheiryan** [comment]
See #4197.

I ended up here by following the GitHub button on the actual published page on openproject.org.  (Which also makes sense that it wants to direct people to the branch it's published off of).

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (60/50 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:49321 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
    by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
    (Exim 4.86)
    (envelope-from noreply@github.com)
    id 1aarpD-0008Ih-Ql
    for fred@ventureacceleration.com; Tue, 01 Mar 2016 16:27:23 -0500
Date: Tue, 01 Mar 2016 08:38:37 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
    s=pf2014; t=1456850317;
    bh=hBLCzVqwFdWIbBI+ED9MUl2yzVdLgsn6fS8CzDCSD48=;
    h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
     List-Archive:List-Post:List-Unsubscribe:From;
    b=CwTSQg1yfOTDM0FGKQb0RNSs6GBoAHVZj0q8Ymw9voVz0gwV+0MtQAarXnHFuhYzp
     E8Qh/JGrjgWviP8JJ0CtjHaUQE5a4I1meQJ0kisBRT0hmyMpDugkDVhgr3whPOAH+k
     ujgMvwCm/3tsW/QZeYpN/GrBx0xr/o1iIIANq38k=

**Pull request closed without merging**
