### PR TITLE
[55251] Favorite colum margin is too big on project list

### PR DESCRIPTION
**Pull request by HDinger**
Introduce icon-only class for table headers, which do not need the min-width of 40px and should ideally be centered

https://community.openproject.org/projects/openproject/work_packages/55251/activity

### CODE REVIEW

**Review by cbliard — CHANGES_REQUESTED** [review]
When there are a lot of columns, it's ok.

When there are not that many columns, each column expands itself and the favorite column is larger than needed. It may be ok though but I think its size should stay narrow.

Another thing which does not look good is that the styling is applied to the `th`, but not to the `td`, so the stars are not aligned which feels wrong too.

image

**Comment by HDinger** [comment]
Cood catches @cbliard 👍  I think a addressed all issues. Could you  please double check?

**Review by cbliard — APPROVED** [review]
Works fine now 👍

**Comment by cbliard** [comment]
rubocop is failing for things not being in the modified lines,
and the tests are passing locally, so I assume they are flaky tests.

Merging

**Pull request merged**
