### PR TITLE
Remove  translations for unsupported languages

### PR DESCRIPTION
**Pull request by tessi**
At the moment we are a relatively small community. We don't speak most
languages, which where supported previously. This resulted in a lot of
differences in quality and quantity of our translations.

We happily add languages again, if we find a maintainer for that
language.

### CODE REVIEW

**Comment by tessi** [comment]
Probably we should discuss this with some stackholders

**Comment by tessi** [comment]
see the discussion at: https://www.openproject.org/issues/522

**Comment by GarstgerUnhold** [comment]
- <[1, 7]> expected but was <[7, 6]> test/unit/lib/redmine/helpers/calendar_test.rb:21:in `test_monthly'
- <[1, 7]> expected but was <7, 6]>. test/unit/lib/redmine/helpers/calendar_test.rb:33:in `test_weekly'
- <:fr> expected but was <nil>. test/unit/lib/redmine/i18n_test.rb:132:in `block in test_valid_language'
- <false> is not true. test/unit/mail_handler_test.rb:252:in `test_add_issue_with_localized_attributes'
- <nil> is not true. test/functional/admin_controller_test.rb:70:in `test_load_default_configuration_data'
- <false> is not true. test/functional/user_mailer_test.rb:460:in `block in test_mailer_should_not_change_locale'
- <:fr> expected but was <:en>. test/functional/welcome_controller_test.rb:45:in `test_browser_language'
- <:"zh-TW"> expected but was <:en>. test/functional/welcome_controller_test.rb:52:in `test_browser_language_alternate'
- <:fr> expected but was <:en>. test/functional/welcome_controller_test.rb:59:in `test_browser_language_alternate_not_valid'
- <nil> is not true. test/functional/wiki_controller_test.rb:149:in `test_update_page_with_failure'
- <nil> is not true. test/integration/application_test.rb:28:in `test_set_localization'

@tessi, those are the tests that appear to be/are related to this PR and are failing.

cukes are failing too. features/step_definitions/i18n_steps.rb are a good place to start looking. Most of it is an Ambiguous match on English (line:59), so it may be related to some kind of fallback, rendering :fr to :en.

**Comment by GarstgerUnhold** [comment]
This PR does not get tested by Travis, closing it in favor of a new one.

**Pull request closed without merging**
