### PR TITLE
teach me

### PR DESCRIPTION
**Pull request by machisuji**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://teatro.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://teatro.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
“You cannot teach a man anything, you can only help him find it within himself.” - Galileo Galilei

**Comment by floriank** [comment]
"Teach a man to make a  fire and he's warm for the day. But set fire to him and he's warm for the rest of his life." - unknown.

@ulferts @machisuji I need some quick context for this.

**Comment by floriank** [comment]
After a little bit of conversation and some search I could not find a method to create a Teatro stage without a PR.

Can we close this?

**Comment by machisuji** [comment]
Alright!

**Pull request closed without merging**
