### PR TITLE
[#8449] Fix errors mentioned by JSHint

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by mfrister** [comment]
Please stop reopening pull requests we close.

**Comment by myabc** [comment]
@marutosi We realise there is some differences in opinion concerning our workflow. As I mentioned the other day, we are working on improving things on our end. However, I don't think further discussion on GitHub will get us very far. Are you available for an IRC/Skype chat?

**Comment by marutosi** [comment]
I lived in Japan and I am not good at English, so I cannot join IRC/Skype.

**Comment by myabc** [comment]
> I lived in Japan and I am not good at English, so I cannot join IRC/Skype.

I don't buy it.

**Comment by marutosi** [comment]
http://en.wikipedia.org/wiki/Japan_Standard_Time

**Comment by myabc** [comment]
Good morning to you too.

**Comment by marutosi** [comment]
Japan is midnight, good night.

**Comment by marutosi** [comment]
http://24timezones.com/
a

**Comment by myabc** [comment]
@marutosi my mistake, good night.

**Pull request closed without merging**
