### PR TITLE
Refactor: register query filters without repeating query arg

### PR DESCRIPTION
**Pull request by cbliard**
@ulferts I was in this part of the code and thought it would look simpler and DRYer like this.
Is it worth it?

### CODE REVIEW

**Comment by ulferts** [comment]
Looks good @cbliard. Do you want to apply it to the rest of the places, then? One could probably even do one more and have the registration figure out the correct namespace for the filters/orders since they are somewhat standardized. The registration would then only look like:

```
::Queries::Register.register(ProjectQuery) do
    filter :ancestor
    order :default
end
```

But now that I see it written down I have my doubts since the developer would have to do the translation in her/his head. What do you think?

**Comment by cbliard** [comment]
Yes, I'd like to apply it everywhere, to remove duplication of the `query` parameter. Just wanted some feedback about if the approach is valid and useful before going further.

About automatically discovering the classes, I'm not sure. I do not know the domain enough to understand if that's desirable or not. Also I find the code less straightforward. And in the case of test and development with lazy loading of classes, it may not work at all: the descendants are not loaded because not referenced yet.

**Comment by ulferts** [comment]
All right, then let's leave it at your original proposal. I like it.

**Comment by cbliard** [comment]
a218a0e would need extra care as I _think_ it correctly registers the default order for `Queries::Groups::GroupQuery` but I have not seen any bug exhibited or any failing test for this modification.

**Review by ulferts — APPROVED** [review]
Looks good @cbliard :+1:

The duplicate registration of the `DefaultOrder` for the `MemberQuery` must have been a mistake on my part. Strange that no error was raised, though. The  `DefaultOrder` includes the one by `id` which I thought is applied by default to guarantee a consistent ordering especially to avoid duplicates when paging.  

But after some digging [at the place](https://github.com/opf/openproject/blob/dev/app/models/queries/base_query.rb#L186) I now know that the `DefaultOrder` is not involved in this as AR is used directly.

So apparently, the ordering is currently not covered by our tests.

**Pull request merged**
