### PR TITLE
[25512] More prominent work package status selector (2)

### PR DESCRIPTION
**Pull request by HDinger**
This makes the status selector more prominent. 

### Things to do

- [x] Apply new styling.
  - [x] The status selector shall be on the left of the info row.
  - [x] The label has been removed.
- [x] When clicking on the button a dropdown with possible status shall be shown.
- [x] Keep functionality (when changing the status it shall be stored)
- [x] Handle permissions correctly.
- [x] Take care of all forms (split vs full, create vs show) 
- [x] Fix broken tests

* (Correct focus handling for accessibility (see WP create button) )

https://community.openproject.com/projects/openproject/work_packages/25512/activity

### CODE REVIEW

**Comment by HDinger** [comment]
### Current state
bildschirmfoto 2017-11-03 um 16 43 40

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/10d44d5af60b231bcfa80c110af38e6cba517ae4) (deployed commit: 15d041543dfa2a0c66a9a1b9946f1863592e18b5).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/45696458a99160adc8b98e86bf69aefaccdcda68) (deployed commit: b0fa46485e8c6ab785d86cc3a241631d83297d98).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/507be6b27e68320a1cdcbb1515696f6327da3faf) (deployed commit: f22d28590f9e95e314d1c8ed4682f759c3652ec3).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/63824ae5e5c6a6b9ed3b9bc8bb1792f8103aaaba) (deployed commit: f22d28590f9e95e314d1c8ed4682f759c3652ec3).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/839ab1bb71c676d0f5202ca249354fa04a258d38) (deployed commit: f22d28590f9e95e314d1c8ed4682f759c3652ec3).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7a206a9694e398926742b2337577039c2386f166) (deployed commit: 7c5784c1c0ddd85b53018c77d5ac2545df1aa223).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4400c9a1fe7151c1d781c37a97338cfe15db6c16) (deployed commit: b80cc7f113a876f368be26af1cc7cac1aa3e3a03).

**Comment by HDinger** [comment]
Since the focus handling seems to be an issue of the contextMenu library I took it out of the scope. This issue is recorded in https://community.openproject.com/projects/openproject/work_packages/26621/activity

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/38beb6b23e311eea8de5f893099b2ffe02bc0f91) (deployed commit: ec8a138b39bd83f40845780a5e8516ccebb2daaa).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/19aaf556ea32dd04f4337b7f8531169674f4a9c7) (deployed commit: ec8a138b39bd83f40845780a5e8516ccebb2daaa).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/3f1c0dbadefcf4c33598a3c344057bcd576b5e20) (deployed commit: ec8a138b39bd83f40845780a5e8516ccebb2daaa).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7b1df546c7c089a50c7e1ab17f768f3e33ee9368) (deployed commit: bc39725165afa056d6a92386f0095e362fb6b8db).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/453bfd7bb5c87e0352f88314a4c25392e2fb9c86) (deployed commit: 77f480c8847083c7fa6f09e6113bdb84d02a3932).

**Review by oliverguenther — APPROVED** [review]
👍  LGTM. Merging after travis

**Pull request merged**
