### PR TITLE
tell travis to test in ruby2.0

### PR DESCRIPTION
**Pull request by tessi**

### CODE REVIEW

**Comment by apfelfabrik** [comment]
Travis will use the `.travis.yml` from this PR when testing it, right? Or will it use the one from `feature/rails3` that we want to merge into?

**Comment by tessi** [comment]
It _should_ use the `.travis.yml` in this branch

**Comment by apfelfabrik** [comment]
By now I can confirm that it _does_ use ruby 2.0. Let's wait for the result.

**Comment by tessi** [comment]
weird... API v2 and our theming seem to have a problem with rub2.0

<pre><code>
...
 42) VersionsController#index with showing completed versions
Failure/Error: get :index, :project_id => project, :completed => '1'
ActionView::Template::Error:
Stub received unexpected message :identifier with (no args)
# ./lib/open_project/themes/theme_finder.rb:25:in `block in registered_themes'
# ./lib/open_project/themes/theme_finder.rb:24:in `each'
# ./lib/open_project/themes/theme_finder.rb:24:in `each_with_object'
# ./lib/open_project/themes/theme_finder.rb:24:in `registered_themes'
# ./lib/open_project/themes/theme_finder.rb:28:in `fetch'
# ./lib/open_project/themes.rb:24:in `theme'
# ./lib/open_project/themes.rb:32:in `current_theme'
# ./lib/open_project/themes/view_helpers.rb:22:in `current_theme'
# ./lib/open_project/themes/view_helpers.rb:36:in `image_path'
# ./app/views/versions/index.html.erb:21:in `block in _app_views_versions_index_html_erb__3113688831530435966_110113880'
# ./app/views/versions/index.html.erb:19:in `each'
# ./app/views/versions/index.html.erb:19:in `_app_views_versions_index_html_erb__3113688831530435966_110113880'
# ./spec/controllers/versions_controller_spec.rb:55:in `block (4 levels) in <top (required)>'
...
101) /api/v2/projects/index.api.rsb with some projects available renders the _project template for each assigned project
Failure/Error: render
NoMethodError:
super: no superclass method `render' for #<#<Class:0x0000000b897190>:0x000000167abcd0>
# ./spec/views/api/v2/projects/index_api_rsb_spec.rb:71:in `block (3 levels) in <top (required)>'
...
</code></pre>

**Comment by tessi** [comment]
33 specs still failing - 32 API v2 specs. One other thing:

<pre><code>
...
 32) api/v2/reportings/show.api.rsb with an assigned reporting renders the _reporting template once
Failure/Error: render
NoMethodError:
super: no superclass method `render' for #&lt;#&lt;Class:0x0000000d7f4358>:0x00000013ccb1f0>
# ./spec/views/api/v2/reportings/show_api_rsb_spec.rb:42:in `block (3 levels) in &lt;top (required)>'
33) my/page renders the timelog block
Failure/Error: td.should have_link("#{issue.type.name} ##{issue.id}", :href => work_package_path(issue))
Capybara::ExpectationNotMet:
expected to find link "Type No. 550 #1642" but there were no matches
# ./spec/views/my/page.html.erb_spec.rb:36:in `block (3 levels) in &lt;top (required)>'
# ./spec/views/my/page.html.erb_spec.rb:35:in `block (2 levels) in &lt;top (required)>'
</code></pre>

**Comment by tessi** [comment]
The API thing seems to be the result of an outdated rspec version. Unfortunately, when updating rspec to the latest and greatest other (but less) failures come to live.

**Comment by apfelfabrik** [comment]
There was no need for me to change a single thing in the code to switch to 2.0 with all tests are passing flawlessly. I have therefore removed the parameter change and updated ALL THE gems. When this one turns out green, we can have a closer look into what is actually needed.

**Comment by apfelfabrik** [comment]
Force-pushed a setup that works on my machine.

**Comment by apfelfabrik** [comment]
One more try at this one, after [system requirements](https://www.openproject.org/projects/openproject/wiki/Systemrequirements) state ruby 2.0 as supported.

**Comment by sschu** [comment]
When I use the same Gemfile.lock as this PR, I get the same errors. Using my own does not give errors.

**Comment by apfelfabrik** [comment]
@sschu, would you mind sharing your Gemfile.lock?

**Comment by ulferts** [comment]
closing this in favor of #714

**Pull request closed without merging**
