### PR TITLE
Fix reversed comments display on WP legacy view

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work package

https://community.openproject.org/work_packages/21410

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-fix-reverse-order.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-fix-reverse-order.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@NobodysNightmare whoops! I must have missed this one when removing mutator methods (53a224bf764516195fa42f49412bfe614eb3a579). N.B. I don't think there's any test coverage for this particular code path :wink:

**Comment by oliverguenther** [comment]
@myabc I think mutators are arguably the hardest to update with rails 4.1, this one is so easy to miss and obviously lacking coverage.

**Comment by NobodysNightmare** [comment]
Thinking about it, shouldn't I remove the mutator entirely?

Something like

``` ruby
changes = work_package.changesets.visible
                .includes({ repository: { project: :enabled_modules } }, :user)

if current_user.wants_comments_in_reverse_order?
  changes.reverse
else
  changes.to_a # to_a to make sure that we always return an array, not sometimes array, sometimes relation
end
```

**Comment by NobodysNightmare** [comment]
The code even was under spec, but the parts were mocked out with an array, so it wouldn't fail...

**Comment by basiszwo** [comment]
To be honest, that's one of the main reasons I don't like working with mocks :unamused: 
Good we found it though.

**Comment by myabc** [comment]
@NobodysNightmare personally, I find that the original reads better.

**Pull request merged**
