### PR TITLE
Use HalResource for WP creation

### PR DESCRIPTION
**Pull request by furinvader**
#### WP create
- [x] create a new work package using `HalResource` (this is actually already done, but has to be tested after the large amount of changes)
#### Relations
- fix parent relation group
  - [x] display parent
  - [x] change parent 
  - [x] remove parent 
  - [x] Changing the parent should update the table
- fix child relations group
  - [x] display children
  - [x] remove child
  - [x] add child
    - ~~go back to relations tab after creation~~ not desired behaviour
- [x] fix adding regular relations
- [x] fix removing regular relations
  - [x] #4530 Implement `delete()` method to the `apiV3`'s services Restangular base (Restangular only knows `remove()` for `DELETE` operations) - This can be moved to another commit, as it is a missing feature of the `halTransform` service.
#### Other
- [x] #4548 Implement a better way to have correctly typed linked resources
- [x] fix Specs
- [x] fix unit tests
#### Bugs
- switching to another work package does not load its relations
  - [x] Use 2088dfa to make `workPackage.relations` a `CollectionResource`
- [x] after deleting the parent, adding a new one is broken
- [x] focus jumps to top when changing a value in create mode. _Fixed in https://github.com/opf/openproject/pull/4567_
- [x]  after reloading the table, new child/parent work packages are displayed incorrectly _Fixed in https://github.com/opf/openproject/pull/4568_
- [x] using the "show all attributes"/"show less" works only once on the create page
-  ~~toggling "show all attributes"/"show less" will close the date fields (this bug probably originates in dev as the date fields are not opened when entering the edit mode~~ _extracted into https://community.openproject.com/work_packages/23538/activity_
- ~~Date pickers are opened when clicking create (this looks weird and blocks editing other fields). The date pickers should only be displayed when clicking inside the date inputs.~~ _extracted into https://community.openproject.com/work_packages/23538/activity_
- [x] the internal id created in the resource (e.g. "#NEW-1466501316229") is displayed on the page. fixed in https://github.com/furinvader/openproject/pull/24
- [x] selecting a value in a dropdown causes a JS error in the console: `Cannot read property '$source' of undefined`. This is causes by WorkPackageResource.modified_fields which does not correctly handle empty attributes. This might also be the case in dev. This bug will probably interfere with the caching. _Fixed in https://github.com/opf/openproject/pull/4566_
- [x] Edit mode remains active when switching to other work packages. Occurs on dev, fixed with https://github.com/opf/openproject/pull/4569
  - [x] This is also true when being in the create form and clicking cancel. Fixed in https://github.com/furinvader/openproject/pull/23
#### Optional
- Refactor the relation groups: parent and child relations should have their own directive as they differ too much to fit in the current directive implementation
- Implement `wpSearchRelated` service and directive (used for autocompletion in relations)
- Implement a general `halResourceCache` service
- Couple the `wpCache` service with the `WorkPackageResource` for consistency
- **!** Implement tests for the new components

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://furinvader-feature-api-wp-new.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://furinvader-feature-api-wp-new.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by furinvader** [comment]
POSITIVE
- Fixed custom field spec
- Refactored `RelationsHandler` for WPs
- Added crucial functionality to `HalResource`

NEGATIVE
- Change in `HalResource` class breaks inline-create functionality. The current implementation of the inline-create feature makes it hard to debug.

**Comment by romanroe** [comment]
@furinvader Status Update please. Positives/negatives?

**Comment by furinvader** [comment]
Commits are WIP right now: Important code ist commented out for better overview.
- Made relations related directives use the HalResource API
- Refactored some of the directives and services:
  - Implemented relations service to remove code from the directive's controller
  - Implemented relation group service (based on the `RelationsHandler` class)

**Comment by furinvader** [comment]
DONE: Fix removing regular relations

**Comment by furinvader** [comment]
DONE: Fix adding regular relations

**Comment by furinvader** [comment]
UPDATE: Fix: Switching to another work package does not load its relations
In the work packages list result, there are no linked or embedded relations, so we would have to request the single work package to retrieve those.
@ulferts Is going to add the relations as links of the list result resource.

**Comment by furinvader** [comment]
UPDATE: _Fix parent relation group_
Adding todos:
- display parent
- change parent
- remove parent

**Comment by furinvader** [comment]
DONE: _Fix parent relation group -> display parent_

**Comment by furinvader** [comment]
DONE: _Fix parent relation group -> add parent_

It's also possible to change the parent now.

**Comment by furinvader** [comment]
DONE: _Fix parent relation group -> remove parent_

UPDATE:
Add todo
- Changing the parent should update the table

**Comment by furinvader** [comment]
DONE: _Changing the parent should update the table_

**Comment by furinvader** [comment]
UPDATE:
Add todos
- display children
- remove child
- add child

**Comment by furinvader** [comment]
DONE: _display children_

**Comment by furinvader** [comment]
UPDATE:
Todo
- Fix: after deleting the parent, adding a new one is broken

**Comment by furinvader** [comment]
UPDATE:
Removing children is quite buggy, as the `HalResource.$load()` should return a promise with a loaded and correctly transformed resource rather than returning itself.

Also, it is questionable wether `$load()` should update the current resource, because it won't be transformed.

Adding todo:
- Implement a better way to load correctly transformed resources

**Comment by furinvader** [comment]
UPDATE: still working on _Implement a better way to have correctly typed linked resources_

I'm about to make linked resource types configurable, so that their type is correctly determined despite them not being loaded.
As it is a general change, this is a topic for a new PR.

**Comment by furinvader** [comment]
UPDATE: Openend #4548

**Comment by furinvader** [comment]
DONE: _#4548 Implement a better way to have correctly typed linked resources_

The branch of the PR that resolves the issue is updated and ready to merge.

**Comment by furinvader** [comment]
UPDATE:
There is still a minor bug in #4548 - going to fix it

**Comment by furinvader** [comment]
DONE: _Implement a better way to have correctly typed linked resources_

**Comment by furinvader** [comment]
UPDATE: _after deleting the parent, adding a new one is broken_

This issue is resolved by the PR mentioned above.

**Comment by furinvader** [comment]
DONE: _remove child relations_

**Comment by furinvader** [comment]
DONE: _add child relations_

Adding child relations with the new create form is now possible.
The parent WP does not get updated, though.
This should be resolved with the changes provided by @ulferts and some work on my side.

**Comment by furinvader** [comment]
DONE: _switching to another work package does not load its relations_
Running smoothly now

**Comment by furinvader** [comment]
UPDATE:
Add todos: 
- Fix unit tests

Add optional todos:
- Refactor the relation groups: parent and child relations should have their own directive as they differ too much to fit in the current directive implementation
- Implement `wpSearchRelated` service and directive (used for autocompletion in relations)
- Implement a general `halResourceCache` service
- Couple the `wpCache` service with the `WorkPackageResource` for consistency
- **!** Implement tests for the new components

**Comment by furinvader** [comment]
DONE: _Fix unit tests_

**Comment by oliverguenther** [comment]
I've pushed a fix for the `create_child_spec` due to the required changes in the wp create service. Travis should agree now.

**Comment by oliverguenther** [comment]
I force pushed a fix for the new and edit spec. I'm giving this another whirl and merge this when travis agrees now that all issues marked for this PR are addressed.

**Pull request merged**
