### PR TITLE
improved drawing of timeline relation lines

### PR DESCRIPTION
**Pull request by romanroe**

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b82d9894a1230f87314f096d6d783b0e269290c5) (deployed commit: 3c6d6f3a5137c090b25b03d55c6d024796839b27).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/e555bf48a2b568ddb7bfa24f222f511fda61e740) (deployed commit: 3c6d6f3a5137c090b25b03d55c6d024796839b27).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/d56c69186bc9eb3168c4e199223ff1bfb2e0ce2b) (deployed commit: 5eaea7594ca50b3b2a03817122fdcbba13159ed2).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/a3039a9fe39aa4982c4183535396e1ab13bbcabd) (deployed commit: ad295836332a0aeb030684587844d53e0e4d750e).

**Comment by oliverguenther** [comment]
I've opened a separate PR to release/7.1 in https://github.com/opf/openproject/pull/5663

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/1249d3048bccd561b3dc43c8ce497624bcbf7148) (deployed commit: 3e6cb6faf872bb0cd80f59afc541dbb3fe6a3bdf).

**Pull request closed without merging**
