### PR TITLE
[Feature] 14597 Wrong hover name in relations table

### PR DESCRIPTION
**Pull request by hschink**
[`* `#14597` Wrong hover in relations table`](https://www.openproject.org/work_packages/14597)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-14597-wrong-hover-name-in-relations-table.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by manwithtwowatches** [comment]
@hschink This looks fine but travis crashed and i'm too scared to merge it

**Comment by ulferts** [comment]
Just one tiny detail, that may be out of scope. When no one is assigned, there is a blank space. This blank space, as the rest of the space occupied by the related work package is titled (hovered) with the name of the relation (e.g. preceeds). 

I guess it would make sense to display a "-" when no one is assigned to be consistent with the rest of the WPs attributes and hover title it accordingly (e.g. "none")

**Comment by ulferts** [comment]
Discussed with @hschink to be done later.

**Pull request merged**
