### PR TITLE
Make open project running under Ruby 3.3

### PR DESCRIPTION
**Pull request by Eric-Guo**
Just fix [Anonymous block parameter](https://rubyreferences.github.io/rubychanges/3.3.html#anonymous-parameters-forwarding-inside-blocks-are-disallowed) is also used within block (SyntaxError)

### CODE REVIEW

**Comment by klaustopher** [comment]
Hey @Eric-Guo, looking into the issue a bit more, there has been a discussion in the [Rubocop repo](https://github.com/rubocop/rubocop/issues/12571) and the current errors that are shown are due to a bug in Ruby 3.3.0 and this will be fixed in 3.3.1. See https://bugs.ruby-lang.org/issues/20090. Issues like those are why we have not upgraded the Ruby version for OpenProject yet.

As soon as 3.3.1 is out, we will re-evaluate if we can switch over to the new version.

Could I ask what your specific use case is to force OP to run under 3.3?

**Comment by Eric-Guo** [comment]
Not yet, the reason to change is just because I using Mac and brew to install ruby and ruby version is 3.3, without this PR, I can not start up the OP in my local env. 😃

**Comment by ulferts** [comment]
Hi @Eric-Guo,

most people on a Mac developing OpenProject [use something like rbenv](https://www.openproject.org/docs/development/development-environment-osx/#install-ruby) for managing the ruby version. Would that be an option for you in the meantime?

Regards
Jens

**Comment by Eric-Guo** [comment]
Yeah, but I'm still prefer one ruby version for all (10+ rails) projects I maintained, anyway I'm glad to known openproject know this issue better than me.

**Pull request closed without merging**
