### PR TITLE
inplace error styles

### PR DESCRIPTION
**Pull request by 0xF013**
https://community.openproject.org/work_packages/19680
https://community.openproject.org/work_packages/19681

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://0xf013-fix-inplace-error-styles.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://0xf013-fix-inplace-error-styles.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
The colors of the error messages are a little controversial:
- The visual says to use these colors (I picked them from the raw image):http://leaverou.github.io/contrast-ratio/#%23cb403b-on-%23fedada
- Our Accessibility checklist says that the colors of the visual don't have enough contrast (we require at least **7:1**)

So I would tend to accept either:
- something that follows the visual "by the letter" (i.e. bad accessibility, but at least as required)
- something that has enough contrast to be accessible per our guidelines (e.g. http://leaverou.github.io/contrast-ratio/#%23444-on-%23fedada)

The current state provided here is neither: http://leaverou.github.io/contrast-ratio/#%23555-on-%23fedada (still a better "score" than the visual)

colors

**Comment by NobodysNightmare** [comment]
My favorite would currently be `#444` as foreground color, as I've already seen other visuals that use a black-ish foreground color in error messages, so that would also be more consistent and `#444` is a little more than enough contrast.

**Comment by myabc** [comment]
regardless, we should variabilise the colours.

**Comment by 0xF013** [comment]
changed to # 444, although I can't tell the difference

**Comment by NobodysNightmare** [comment]
Oh and apparently for the type the error message gets hit by another CSS rule and gets blue:

blue-color

The offending rule seems to be this:

``` CSS
.work-packages--details--type {
  display: block;
  padding: 0 1rem;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  -ms-overflow-style: -ms-autohiding-scrollbar;
  -webkit-flex: 1 1 auto;
  -ms-flex: 1 1 auto;
  flex: 1 1 auto;
  -webkit-flex: 0 0 auto;
  -ms-flex: 0 0 auto;
  flex: 0 0 auto;
  overflow: visible;
  overflow-y: visible;
  padding: 0;
  color: #06799F;
}
```

edit: I will check whether https://github.com/opf/openproject/commit/7dd50f3b95b88107ceda8adb986a71b39aca10f4 did also fix this issue...

**Comment by NobodysNightmare** [comment]
> changed to #444, although I can't tell the difference

Thanks! :)

I diffed it briefly and the difference is noticable, but not big.
The reason is more like: When someone checks the accessibility by the rulebook, will he/she find an offense or not?

**Comment by myabc** [comment]
> The offending rule seems to be this:

Can that rule now be deleted, now that type is treated like any other field?

**Comment by 0xF013** [comment]
@myabc zug-zug

**Comment by NobodysNightmare** [comment]
> Can that rule now be deleted, now that type is treated like any other field?

I'd say yes. The only other occurence of the type is also normally colored...

Will re-test.

**Pull request merged**
