### PR TITLE
17485 Relation auto-completion broken with relative URL

### PR DESCRIPTION
**Pull request by hschink**
[`* `#17485` Relation auto-completion broken with relative URL`](https://community.openproject.org/work_packages/17485)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://hotfix-17485-relation-autocomplete-broken-with-relative-url.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@hschink would you mind rebasing this?

**Comment by hschink** [comment]
@myabc Thanks for the hint! I just rebased the PR.

**Comment by myabc** [comment]
@hschink thanks!

**Pull request merged**
