### PR TITLE
Ignore copied engine migrations

### PR DESCRIPTION
**Pull request by tessi**
OpenProject engines copy their migrations into the db/migrations directory. To make core-development live easier, I propose to ignore migrations.

If a core migrations need to be added to version control, use `git add -f`.

### CODE REVIEW

**Comment by cratz** [comment]
I don't like the approach that a foced action is required to add a normal file. We should instead create a rake task to handle this stuff or provide a easy way to generate a configuraton which we should do anyway.

**Comment by tessi** [comment]
Can you elaborate a little on what the rake task should do? The problem I face at the moment is, that I see gazillions of migration files (coming from other engines) when I do <code>git status</code>. I don't see where a rake task can help me here.

**Comment by cratz** [comment]
I had in mind that the task runs all copy-migration tasks from the plugins (specified in Gemfile.plugins) and than add all new files from 'db/migrate/' to '.git/info/exclude' when not already included. The first step is optional.

**Comment by tessi** [comment]
Thanks, sounds promising.

**Pull request closed without merging**
