### PR TITLE
[21858] Wrong positioning of (un)check all in permissions view

### PR DESCRIPTION
**Pull request by HDinger**
This rearranges the permission groups so that each one is toggleable and has its own checkAll-functionality.

https://community.openproject.org/work_packages/21858/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21858-wrong-positioning-of-check-all-in-permissions.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21858-wrong-positioning-of-check-all-in-permissions.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
#### Before

bildschirmfoto 2015-12-18 um 14 09 43

#### After

bildschirmfoto 2015-12-18 um 14 07 10

**Comment by HDinger** [comment]
https://community.openproject.org/work_packages/21858/activity

**Comment by HDinger** [comment]
Since the global roles plugin overrides the core there is a separate PR for that: https://github.com/finnlabs/openproject-global_roles/pull/57

**Comment by mk84** [comment]
Tests are failing on the global_roles plugin and I can't fix them. As it is related to this PR I haven't merged this yet. https://github.com/finnlabs/openproject-global_roles/pull/57

**Pull request merged**
