### PR TITLE
Added basic support for TypeScript

### PR DESCRIPTION
**Pull request by romanroe**
Basic support for TypeScript. Source Maps are not working yet. I assume that this has to be enabled in WebPack. I will check this.

https://community.openproject.org/work_packages/21913/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://romanroe-typescript-support.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://romanroe-typescript-support.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by lindenthal** [comment]
@romanroe : can you please rebase this PR and assure the tests are green?

Thanks
Niels

**Comment by romanroe** [comment]
Yes, will check!

**Comment by romanroe** [comment]
I added two new dependencies and followed these guidelines: https://github.com/opf/openproject/tree/dev/frontend/doc#changing-or-updating-dependencies.

However, instead of "npm install" I had to do 

npm install --save typescript
npm install --save ts-loader

Also, the created npm-shrinkwrap.json seems to be much more verbose than the one currently used.

**Comment by ulferts** [comment]
> Also, the created npm-shrinkwrap.json seems to be much more verbose than the one currently used.

Did you run `./scripts/clean-shrinkwrap.js` as specified by https://github.com/opf/openproject/blob/dev/frontend/doc/README.md#changing-or-updating-dependencies?

> However, instead of "npm install" I had to do
> npm install --save typescript
> npm install --save ts-loader

Would that also be necessary for users wanting to install OpenProject after this is merged? We would then have to update our testing and delivery pipeline.

**Comment by oliverguenther** [comment]
I've fixed the shrinkwrap similar to the ng-annotate PR over at https://github.com/opf/openproject/pull/3947.

**Pull request closed without merging**
