### PR TITLE
dockerize

### PR DESCRIPTION
**Pull request by crohr**
This is used by the community edition to be deployed as a docker container, but it probably makes sense to merge this upstream so that everyone can benefit from it.

/cc @machisuji @oliverguenther

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://crohr-feature-dockerfile.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://crohr-feature-dockerfile.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by crohr** [comment]
This also means that we need to define additional gems in the main Gemfile if we don't want to use `Gemfile.local`

**Comment by oliverguenther** [comment]
Do we really need the fixed dependency on `passenger`? We might also want to introduce this as an optional group (`optional: true`) once bundler 1.10 is is old enough that it landed on all of our systems.

**Comment by crohr** [comment]
@oliverguenther you mean fixed in the sense that it is required by the `web` script, or in the sense that it is in the Gemfile?

**Comment by oliverguenther** [comment]
I meant that we could put it (along with the other Gems we don't need in a _regular_ installation) in a separate group outside of :production so we can extend the manual installation guide to exclude this group by default, i.e., `bundle install --without <the other groups we don't install there> dockerized`.

Then, we can later define this group as `:optional`, so that users wishing to install with them (as well as your docker script) will have to explicitly install them with `--with dockerized`. This is quite a new feature ([bundler 1.10](http://bundler.io/blog/2015/06/24/version-1-10-released.html)), and I've had issues trying to bring it into the core the last time due to older deployment bundlers.

What do you think? Is this possible from your side ? (it should not require other changes in this PR other than the Gemfile).

**Comment by crohr** [comment]
@oliverguenther I think it would be fine for our systems. I just gave you access to my repo so you can perform the change.

**Comment by oliverguenther** [comment]
@crohr Thanks, I've just pushed the changes.

**Comment by crohr** [comment]
@oliverguenther thanks a lot, just tested the image and it still works. Merge whenever you see fit.

**Comment by oliverguenther** [comment]
Great. I'd like to merge this immediately after 5.0.7. is fixed from `release/5.0`, just to make sure.

**Comment by crohr** [comment]
One spec failed, but it should be good to merge still.

**Pull request merged**
