### PR TITLE
feature #25517 Allow custom favicon and touch icon upload

### PR DESCRIPTION
**Pull request by wielinde**
https://community.openproject.com/projects/openproject/work_packages/25517/activity

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7d5525099213db5e903f7d023c8528b680d0bb05) (deployed commit: c7e17f9ba4ed983d22fe33ce2777e8cd4c6eac3a).

**Comment by oliverguenther** [comment]
I'm getting an internal error on the upload on PullPreview


```
Showing app/views/layouts/base.html.erb where line #59 raised:

No route matches {:action=>"touch_icon_download", :controller=>"custom_styles", :digest=>1497530899, :filename=>nil, :layout=>nil} missing required keys: [:filename]
Extracted source (around line #59):
              
        <% end %>
        <% if CustomStyle.current.favicon.present? %>
          <link rel="apple-touch-icon" sizes="180x180" href="<%= custom_style_touch_icon_path(digest: CustomStyle.current.digest, filename: CustomStyle.current.touch_icon_identifier) %>">
        <% end %>
      <% end %>
    <% end %>  

```

**Comment by wielinde** [comment]
@oliverguenther I am pretty sure to have found and fixed the bug. Could you please check it when the pullpreview is available?

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/63a6bd25505f6c933715ce55a862b9196895d3d7) (deployed commit: bd075799297756fc0c9c2542269c785e91da17ba).

**Comment by oliverguenther** [comment]
Only checked the mobile icon on my Android, but LGTM now 👍

**Pull request merged**
