### PR TITLE
Use path helper in details controller to get static author path.

### PR DESCRIPTION
**Pull request by manwithtwowatches**
https://www.openproject.org/work_packages/14699

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-user-link-in-wp-details-header.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by manwithtwowatches** [comment]
This will suffer the same fate as https://github.com/opf/openproject/pull/1720 so after that is merged i will make a commit in this branch which handles deleted/anon users in the details header.

**Comment by ulferts** [comment]
@manwithtwowatches, #1720 is merged, so you can proceed.

**Comment by ulferts** [comment]
@manwithtwowatches, the path to the users are all fine. But for reasons<sup>TM</sup> I can no longer remove watchers from the work package as the path then lacks the host.

**Comment by manwithtwowatches** [comment]
@ulferts @hschink I'm not able to recreate this. The path in the link isn't the one being used anyway - it's looking on the object for the remove watcher api link. If someone has a second to show me this not working on their machine that would be helpful.

**Comment by ulferts** [comment]
@manwithtwowatches :+1: actually fixed by merging the dev branch. So there was probably a bug in the dev branch that has been fixed.

**Pull request merged**
