### PR TITLE
[21569] Cursor offset in project search (IE)

### PR DESCRIPTION
**Pull request by HDinger**
This sets the box model so that it is the same for all browser. Further it fixes the thereby changed styles. 

https://community.openproject.org/work_packages/21569/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21569-cursor-offset-project-search-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21569-cursor-offset-project-search-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
**Before**

cursor_offset

**After**

cursor_correct

**Comment by NobodysNightmare** [comment]
As discussed we will wait for merge of https://github.com/opf/openproject/pull/3542, before having a look here again...

**Comment by NobodysNightmare** [comment]
LGTM, but as discussed lets not merge it before @mk84 arrives in the office (also we have to wait for travis)

**Comment by mk84** [comment]
Looks good :+1:

**Pull request merged**
