### PR TITLE
[41948] Global project select optimisations

### PR DESCRIPTION
**Pull request by HDinger**
### ToDo

- [x] The action bar buttons are not centred horizontally
- [x] The button for creating a new project should be green
- [x] Niels: The focus is not in the search field when clicking on "Select a project".

**Mobile**
- [x] There is a zoom when entering the text field (iOS)
- [x] Only the text is a link target. It should rather be the entire row. (see [this ticket](https://community.openproject.org/projects/openproject/work_packages/43063/activity))
- [x] The modal title is not visible because the browser url bar overlaps it
- [x] The action bar buttons don't have space between them.
- [x] Niels: There is space between the main navigation and the select menu.

**Out of scope**
* ~~While searching for a project the parent projects aren't greyed out as specified (this is also happening in the include projects~~ Will be done in the scope of https://github.com/opf/openproject/pull/10872
* ~~Auto completion removed focus (iOS)~~ **Edit**: Not reproducible for me and thus out of scope for this PR

Fixes [comment#24](https://community.openproject.org/projects/openproject/work_packages/41948#activity-24), [comment#25](https://community.openproject.org/projects/openproject/work_packages/41948#activity-25), and [comment#26](https://community.openproject.org/projects/openproject/work_packages/41948#activity-26) in 
https://community.openproject.org/projects/openproject/work_packages/41948/activity

Also fixes https://community.openproject.org/projects/openproject/work_packages/43063/activity

⚠️ Should be merged **after** #10872

### CODE REVIEW

**Review by oliverguenther — APPROVED** [review]
*accidentally hit approve instead of request changes*

**Review by oliverguenther — CHANGES_REQUESTED** [review]
Mostly LGTM, there is a small remark that is a bit annoying when not clicking directly on the text

- [x] Not the entire area is clickable, only the text. there is an area at the top and bottom that is still not clickable
Peek 2022-07-05 13-49

**Comment by HDinger** [comment]
i fixed the issue @oliverguenther found. Further, the link effects has been removed to match the figma specification.

⚠️ We should wait with the merge until #10872 is through since there are merge conflicts to be expected

**Review by oliverguenther — APPROVED** [review]

**Comment by oliverguenther** [comment]
I'll take over the other PR and resolve the conflicts, as it still has broken tests

**Pull request merged**
