### PR TITLE
Rails4:  Removed useless :lang option

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-rails4-tabular-form-builder.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by linki** [comment]
specs fail but I'm not closing this because it will be re-opened anyway. instead tagging it with `won't fix` and watch it slowly moving down... good times, really awesome.

**Comment by marutosi** [comment]
> specs fail

spec passes.

https://travis-ci.org/opf/openproject/builds/41370501

**Comment by linki** [comment]
some tests are probably allowed to fail since it's the rails 4 branch.

but uhm... how should i know? damn, we need a description field for pull requests...

**Comment by marutosi** [comment]
> we need a description field for pull requests

It is in commit logs.

**Comment by kgalli** [comment]
@marutosi I don't like seeing/reading the same conversation over and over again. So please add a description as a summary of your commits. If you don't understand why this is necessary you might want to think about why github is showing the description field for every PR instead of pointing directly to the commit logs.

**Comment by marutosi** [comment]
I don't know why you use github.
Commit log is git feature.
"github  description" is github feature.
If github will close service, description will be lost.

**Comment by linki** [comment]
just do it @marutosi. we take that risk

**Comment by myabc** [comment]
nike-red-just-do-it-logo

**Comment by kgalli** [comment]
:+1:

**Comment by marutosi** [comment]
Sorry, I love adidas.
http://www.albirex.co.jp/tools/page_store/news_3083.html

**Comment by marutosi** [comment]
Are you kidding?
https://github.com/opf/openproject/commit/f5bb0067f0340b915dc6e75eabac29a587f26869

**Comment by marutosi** [comment]
#2492

**Pull request closed without merging**
