### PR TITLE
fix personal activity broken

### PR DESCRIPTION
**Pull request by 0xF013**
[`* `#15352` fix personal activity broken`](http://www.openproject.org/work_packages/15352)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://0xf013-feature-15352-personal-activity-broken.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by marutosi** [comment]
Why for dev not stable?

**Comment by 0xF013** [comment]
@marutosi the ticket is marked as for dev.

**Comment by marutosi** [comment]
I mean that why **bug fix** is for dev not to stable?

**Comment by ulferts** [comment]
@0xF013 please see https://www.openproject.org/work_packages/15352 for additional feedback.

**Comment by 0xF013** [comment]
@ulferts can I somehow trigger the build again? it doesn't say why it fails

**Comment by ulferts** [comment]
@0xF013 We did some test with Shippable which leads to the failing tests here. @linki took a look at the corresponding travis run (https://travis-ci.org/opf/openproject/builds/34682285) and it is looking all good. Might be a good chance to add that grouping :smile:

**Comment by 0xF013** [comment]
@ulferts grouping is working locally, just not yet test-covered:)

**Comment by ulferts** [comment]
:+1: thanks for doing the grouping fix.

**Pull request merged**
