### PR TITLE
[FIX] Relative root url path handling 4115

### PR DESCRIPTION
**Pull request by hschink**
Implements [ticket 4115](https://www.openproject.org/work_packages/4115)
- `#4115` [Subdirectory] Broken Redirects

:exclamation: Don't forget to merge into release branch

### CODE REVIEW

**Comment by mugwump** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/528f351813d637200e02ef84/compare/fix/relative_root_url_path_handling_4115">analyzed this pull request</a>.

**Comment by mugwump** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/528f35c8c7f3a33b7d03cde8/compare/fix/relative_root_url_path_handling_4115">analyzed this pull request</a>.

**Comment by ulferts** [comment]
Does this address #873?

**Comment by hschink** [comment]
@ulferts #873 is still valid!

**Comment by hschink** [comment]
Closed in favor for PR against `release/3.0`

**Pull request closed without merging**
