### PR TITLE
remove Rails2 Ruby1.9 utf8nize!

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by mfrister** [comment]
@marutosi You provided the [fix for chiliproject](https://github.com/opf/openproject/commit/21a45b4e52f0fcd80849f3b8ac08e8472eca74bd), can you explain why utf8nize! is no longer necessary?

This seems to be a related issue: https://www.chiliproject.org/issues/676, although I can't get from it on why it was necessary.

**Comment by marutosi** [comment]
> remove **Rails2 Ruby1.9** utf8nize!

**Comment by mfrister** [comment]
I understood that.

The question is, why is it no longer necessary for Rails 3 and/or Ruby 2?

**Comment by marutosi** [comment]
http://www.redmine.org/projects/redmine/repository/revisions/9536

**Comment by mfrister** [comment]
Not the explanation I was looking for, but that Redmine removed this two years ago seems to be a good enough indicator to me that things won't break with this.

Thanks!

**Comment by tessi** [comment]
@marutosi thanks for your contribution! But _please_ post any new pull requests against the `dev` branch. Any insightful PR description would also help us in processing your PRs faster :)

**Comment by marutosi** [comment]
> But please post any new pull requests against the dev branch. 

Why?

Do you all understand git-flow?

**Comment by mfrister** [comment]
@marutosi: Please describe the issue you have with our workflow instead of questioning it in general. I will ignore all further general questions.

**Comment by marutosi** [comment]
> Please describe the issue you have with our workflow instead of questioning it in general.

https://github.com/opf/openproject/pull/1152#issuecomment-41257997

**Comment by NobodysNightmare** [comment]
@marutosi: Feature branches go into dev which goes into stable... not the other way around...

This is defined by git flow and you should know that

**Comment by tessi** [comment]
@marutosi we use a derivation of the git-flow you're probably referencing



We work in feature branches and merge them into the `dev` branch. We also have release branches (e.g. `feature/release3.0`). We merge feature branches back into our `dev` branch from time to time. As seen in the image, no PR whatsoever should be posted against the `stable` branch.

Everyone here has probably ignored the process from time to time in the past - however, we strongly encurage you (and everyone else in the team) to stick to it.

I hope that clears it up and resolves some misunderstandings :)

**Comment by tessi** [comment]
BTW: the process is documented here https://www.openproject.org/projects/openproject/wiki/Git_Branching_Model

**Comment by marutosi** [comment]
What branch should user use?
Is it stable?

**Comment by marutosi** [comment]
Why did not you merge release/3.0 branch to stable?

**Comment by NobodysNightmare** [comment]
All Pull Requests should be based on dev.

If you are using open project in production use the `stable` branch. If you want to see how the next features will look like, try the `dev` branch, it is where the magic happens, but it might not be as stable as the `stable` branch.

**Comment by marutosi** [comment]
> All Pull Requests should be based on dev.

Why?

Based on git-flow, hot-fix is based on stable.

Do you all understand git-flow?

**Comment by NobodysNightmare** [comment]
More precisely: _Usually_ your PR will go against dev.
Exceptions (not exhaustive):
- hot fixes
- fixes going directly into release-branches

This also means: _Usually_ (this is all non-critical things) your PR will **not** go into `stable` directly, but via the dev branch.

**Comment by marutosi** [comment]
This pull request is **hot fixes**.

**Comment by NobodysNightmare** [comment]
I don't think, that it is critical and therefore a hotfix is needed.

If you think it **is** a hotfix, then follow @tessi 's tip and use the description of the PR the next time to elaborate **why** you believe it is critical to include your change ASAP.

**Comment by marutosi** [comment]
I described this pull request subject **Rails2**.
So, this pull request is **hot fix**.

**Comment by NobodysNightmare** [comment]
I don't understand how your subject in any form indicates **why** something about your PR is **critical**...

**Comment by marutosi** [comment]
It is very **critical**.

**Comment by NobodysNightmare** [comment]
why?

**Comment by marutosi** [comment]
https://github.com/opf/openproject/blob/17cfbdc32b0/config/application.rb#L94

**Comment by NobodysNightmare** [comment]
This is a line of code.

More specific:
- which evil could happen if your change was included in a month and not today? (that is: why is it **hot**)
- are there **risks** (e.g. security-vulnerablilties) that your PR eliminates?

**Comment by marutosi** [comment]
performance regression.

**Comment by NobodysNightmare** [comment]
Sometimes I wish you would write whole sentences, this would help me understand you.

However IMHO performance issues (of this kind) are not critical and can wait a month or two.

**Comment by marutosi** [comment]
This code should be removed before release.
So, this is hot fix.
There is no risk for users.
Why should users wait for months?
Where is release plan?

**Comment by marutosi** [comment]
Git-flow is for **inner-house product**.
I cannot understand why you use **modified** git-flow.
Is your software inner-house product?

**Comment by marutosi** [comment]
GitHub Flow
http://scottchacon.com/2011/08/31/github-flow.html

> Issues with git-flow
> 
> I have heard a number of opinions from people along the lines of not liking that new feature branches are started off of develop rather than master, or the way it handles hotfixes, but those are fairly minor.
> 
> One of the bigger issues for me is that it’s more complicated than I think most developers and development teams actually require.

**Comment by marutosi** [comment]
> GitHub Flow
> 
> So, why don’t we use git-flow at GitHub? Well, the main issue is that we deploy all the time. The git-flow process is designed largely around the “release”. We don’t really have “releases” because we deploy to production every day – often several times a day. We can do so through our chat room robot, which is the same place our CI results are displayed. We try to make the process of testing and shipping as simple as possible so that every employee feels comfortable doing it.

**Comment by marutosi** [comment]
> Conclusion
> 
> Git itself is fairly complex to understand, making the workflow that you use with it more complex than necessary is simply adding more mental overhead to everybody’s day. I would always advocate using the simplest possible system that will work for your team and doing so until it doesn’t work anymore and then adding complexity only as absolutely needed.
> 
> For teams that have to do formal releases on a longer term interval (a few weeks to a few months between releases), and be able to do hot-fixes and maintenance branches and other things that arise from shipping so infrequently, git-flow makes sense and I would highly advocate it’s use.
> 
> For teams that have set up a culture of shipping, who push to production every day, who are constantly testing and deploying, I would advocate picking something simpler like GitHub Flow.

**Comment by tessi** [comment]
Thanks @marutosi for talking in sentences and for providing us a more detailed argumentation.

I want to address some of your (not yet answered) questions:

---

1.

> I cannot understand why you use **modified** git-flow.

We just modified the name of the development and stable branch (they are 'development' and 'master' in the original git-flow, but we name them 'dev' and 'stable'). The original git-flow workflow is the same.

That being said about our modification, please read on about _why_ we use git-flow.

---

2.

> Is your software inner-house product?

It depends, you might have observed that OpenProject is open source :) So everyone is free to use and modify OpenProject (under the usual terms) - so it is not in-house only. However, there are companies (e.g. finnlabs) who use OpenProject in-house. There is a humongous list of requirements especially big companies have for the software they use. Having separate releases on long term intervals (~ 3 month) is one of our ways to better cope with that.

---

3.

> Git-flow is for inner-house product.

and:

> > For teams that have to do formal releases on a longer term interval (a few weeks to a few months between releases), and be able to do hot-fixes and maintenance branches and other things that arise from shipping so infrequently, git-flow makes sense and I would highly advocate it’s use.

Well, you've just found a very good source of information with github-flow. OpenProject happens to be a project with "formal [official] releases on a longer term interval". As you've probably seen: in that case "git-flow makes sense and [the github-flow author] would highly advocate it’s use".

---

4.

> Where is release plan?

We have a timeline which also lists our future release dates [here](https://www.openproject.org/projects/openproject/timelines/36).

**Comment by marutosi** [comment]
Again, why should your **open source** software users use **buggy** software **for months**?

http://mercurial.selenic.com/wiki/TimeBasedReleasePlan

> **Major releases**
> Starting with 2.0, Mercurial now follows a 3-month cycle with the following release dates:
> 
> **Minor releases**
> Minor releases will be made by tagging the current state of the stable branch, which is continually kept in a production-ready state
> minor releases will be made on or **about the first of every month**
> 
> **Rules for code freeze and stable branch commits**
> Because the code freeze is on the stable branch, the rules for each are the same. The following are allowed:
> 
> bug fixes
> error message improvements
> doc fixes
> template fixes
> improved translations
> Things that don't belong on the stable

Mercurial users can always use **stable branch** in pulling and **checking out** from
Mercurial official repository.
http://selenic.com/repo/hg-stable

**Comment by NobodysNightmare** [comment]
Maybe this is a point where we have to improve. The only options you **currently** have are:
- stable (should be reliable, but only releases every few month)
- dev (updates regularly/daily, but might not be production ready)

You can argue, that we should anticipate shorter release-cycles (for your example project this is **one month** between minor releases).

However, this still means that we need to take PRs into the dev branch, because we can only call it stable, when we know it is stable.

**Comment by marutosi** [comment]
> However, there are companies (e.g. finnlabs) who use OpenProject in-house. There is a humongous list of requirements especially big companies have for the software they use. Having separate releases on long term intervals (~ 3 month) is one of our ways to better cope with that.

It is non sense.
Because **Facebook** uses and **develops** **Mercurial**.
https://code.facebook.com/posts/218678814984400/scaling-mercurial-at-facebook/

**Comment by marutosi** [comment]
<pre>
$ hg tip --template='{rev} {node}\n'
21188 d36440d843284ba546858b241da9cc4817811fe5
$ hg log --template='{author|email}\n' | grep '@fb.com' | wc
    941     941   15643
$ hg log --template='{author|email}\n' | grep '@fb.com' | sort | uniq | wc
     24      24     376
</pre>

**Pull request merged**
