### PR TITLE
Fix/wrong context menu styling

### PR DESCRIPTION
**Pull request by zzmedia**
https://www.openproject.org/work_packages/7296

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-wrong-context-menu-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by ulferts** [comment]
@myabc karma tests fail

**Comment by myabc** [comment]
@ulferts Karma tests should be fixed. Also squashed a couple commits.

**Comment by ulferts** [comment]
Nitpicking now but the margins seem to be different:

image

**Comment by myabc** [comment]
(@ulferts they were never the same)

**Pull request merged**
