### PR TITLE
Timeline labels

### PR DESCRIPTION
**Pull request by romanroe**
https://community.openproject.com/projects/openproject/work_packages/24982/activity

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/5ce14c4bbea428e86c6a20d74df5f7013ff63bbb) (deployed commit: b2b99c2ff0c4d7780cf0b77ec22be96e92507810).

**Comment by romanroe** [comment]
@ulferts @oliverguenther I just pushed my latest changes. 
@lindenthal FYI

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b24cf86f347152df68d98e3d3cd862848bb0bde4) (deployed commit: 9fa506fee241322be915454ca45fa72ffc4edf03).

**Comment by lindenthal** [comment]
@romanroe on Win 10 Chrome the labels seems not be aligned vertically. Can you please check? 

image

I also suggest to increase the font size.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4eaadb27458ad76aa619d6f325079e25d3612156) (deployed commit: 9fa506fee241322be915454ca45fa72ffc4edf03).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/a9e63b4ca765c2e42d46f8ee960b786fc09f529e) (deployed commit: d44252621828205625eb6833e41205caaba3842f).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/194d239a0d488e6cac73fcdb75941664280f87b0) (deployed commit: ae9b4cf51619ad36dc7f8bc6c6532065164c54b0).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4870f3ca47ea9856a8b4a7b2570cce37721bd50c) (deployed commit: 32c1a2609cd1685c83ee74014401e09ef542a928).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b66432f3b239cebd41dc83cb24039bf40f81a992) (deployed commit: 4d0fc0f2eab65e1b6d458b6f069dabf9d496fdb5).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/6155423257495261d51dcec0e2b90aeec3ed8436) (deployed commit: f561b1f2b475fb38f794e15479f9b7dd38f4271a).

**Comment by oliverguenther** [comment]
Looks good to me feature wise. Please remove the commented code before we merge this.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/2dfe48b26adc287a3ae2e97f5854617406af3563) (deployed commit: f561b1f2b475fb38f794e15479f9b7dd38f4271a).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/be9e2f50524c89e647455d718b9821c7fd4acdc6) (deployed commit: 31af9e86a0c885e1cc0836ae8676fd108f1584d2).

**Pull request merged**
