### PR TITLE
Fix and standardize board routes

### PR DESCRIPTION
**Pull request by oliverguenther**
- [x] Remove special `overview` route as now all routes are Rails. This was introduced to not break the angular-based index route
- [x] Standardize permission checks for global/local routes
- [x] Re-add the dynamic state param to allow frontend state (Fixes https://community.openproject.org/work_packages/49678)
- [x] Add regression test

### CODE REVIEW

**Comment by aaron-contreras** [comment]
@oliverguenther This seems to be why the specs are failing: https://github.com/opf/openproject/blob/daccef3bb1c5d04e4cd7e771f1fcee4828575a29/frontend/src/app/core/setup/globals/onboarding/onboarding_tour.ts#L73-L75

The `*_view` menu item naming was expected. I'm unsure as to the direction we'd want to go with the naming convention because calendars and team planners also adopt this `*_view` pattern to their menu item naming.

**Comment by oliverguenther** [comment]
@aaron-contreras As the global menu for boards is called `boards`, I wanted to keep that consistent. Calling it a view doesn't really make sense after all, as only calendars and team planners are actual `View` resources.

**Review by dombesz — APPROVED** [review]
LGTM 👍
I fixed a bug where the tour arrow wasn't pointing to the "Boards" menu point. The reason was that there are 2 menu items called `.boards-menu-item`, I narrowed it down to the sidebar.

**Comment by aaron-contreras** [comment]
Love this!

**Pull request merged**
