### PR TITLE
[21603] Apply new icon styling

### PR DESCRIPTION
**Pull request by HDinger**
This updates the icon font. Therefore all classes need to be updated and eventually styles fixed. An overview of the changed classes can be found the file 'icon-font-classes.xlsx'.

Note: All plugins need to be updated too!

https://community.openproject.org/work_packages/21603/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-task-21603-apply-new-icon-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://hdinger-task-21603-apply-new-icon-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
[icon-font-classes.xlsx](https://github.com/opf/openproject/files/39881/icon-font-classes.xlsx)

**Comment by HDinger** [comment]
@mk84 I updated the used icon classes in core and every plugin I found in the configs of core, org, community and enterprise. So from my side, I am through. Can you have a look at it? The overview of changed and deleted icons is in the file 'icon-font-classes.xlsx'.

**Comment by basiszwo** [comment]
I ran all specs in core, community edition and myproject. I consider this tested well enough.

**Comment by mk84** [comment]
@HDinger I reviewed your stuff and have some notes:

`icon-book2` has been removed but is used in
https://github.com/opf/openproject/blob/release/5.0/app/views/boards/show.html.erb#L139

Those icons were renamed but not documented in the xlsx file and wrong replaced:
`icon-issue-assignedtome` => `icon-assigned-to-me` (but replaced with icon-issue-assigend-to-me)
`icon-issue-reportedbyme` => `icon-reported-by-me` (but replaced with icon-issue-reported-by-me)
`icon-issue-watched` => `icon-preview` (but replaced with icon-watched)

Why did you remove `icon-ticket2` from the sass file?
Regarding the xlsx this icon is still in the font.

Why did you changed `icon-google-plus` to `icon-google-plus-1` ?
Why did you changed `icon-compare` to `icon-compare2` ?

I also had a quick glance on the UI and saw that some icons are missing or wrong:
e.g. the wrong search icon in the projects dropdown; the missing dropdown arrows in the menu; the missing checkmark in the inplace edit; the missing watch icon. And the dropdown arrows inside buttons are bigger than before.
icon_update_screen

I'm not sure how to test this effective to ensure that every icon on the whole application (incl. all plugins) will be correct after the update. The problem is that some icons changed their name and size and so it's possible that some of them will be missing or have a wrong size.

**Comment by HDinger** [comment]
@mk84 I included your feedback. Regarding the changes in the sass-file (especially icon-ticket2, icon-google-plus-1, icon-compare2): these changes were made by Christoph and I assume that they were typos since their naming doesn't make sense and is different in the xls-file. 
I agree that the testing is very difficult. I guess we covered the naming very well, but the size issues will probably only be seen later when the icons are in use. Unfortunately I have no other idea at the moment  how to detect the efficiently before the merge.

**Comment by oliverguenther** [comment]
The homescreen arrow icons do look kind of weird compared to the previous version. @mk84 What do you think?

openproject

**Comment by mk84** [comment]
@oliverguenther Yes, I share your thoughts. I checked the updated styleguide in this PR and saw that the previous arrow was dropped from the icon font (but only the one for the right direction).

**Comment by oliverguenther** [comment]
I've included the latest fix to the icon font by Christoph and extracted the actual icon class definitions into a separate file (in order to speed up future changes to the icon font definitions themselves).

There may still be lots of smaller issues, thus I suggest we merge this and the plugin PRs as soon as 5.0.5 is released in order to get us exposed to the icon changes and detect them until the next patch release.

**Pull request merged**
