### PR TITLE
[24930] Rework project sidebar

### PR DESCRIPTION
**Pull request by HDinger**
This changes the behavior and styling of the sidebar.

**ToDos**
*Design according to the visuals*
- [x] change colors
- [x] collapsed state (unchanged)
- [x] expanded state

*Further taks*
- [x] Accessibility check (especially contrast ratio)
- [x] Check mobile page
- [x] Check for other themes

https://community.openproject.com/projects/openproject/work_packages/24930/activity

### CODE REVIEW

**Comment by HDinger** [comment]
### VISUAL
02-redesign-project-sidebar

### BEFORE
bildschirmfoto 2017-03-29 um 15 02 55

### AFTER
bildschirmfoto 2017-03-30 um 15 32 21

**Comment by HDinger** [comment]
Since it is not clear whether the color of the sidebar shall change when the design is changed, it stays as it is for the moment. This can be implemented later so that the sidebar is always a darker version of the primary color 
(`darken(desaturate(adjust-hue($primary-color, -0.1181), 39.2921), 25.2941`)

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/3aa8dc909144709606f0e60800db0326a3903d4f) (deployed commit: 6cdfd92177abfe6dec18cd3217c716871d5880ef).

**Comment by oliverguenther** [comment]
Rebased on dev. LGTM on both default and myproject theme 👍

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
