### PR TITLE
Implemented treating assignees and responsibles differently so there

### PR DESCRIPTION
**Pull request by sschu**
are no (non-functional) group responsibles anymore

Implements https://www.openproject.org/work_packages/3854, please review and add changelog entry

### CODE REVIEW

**Comment by hschink** [comment]
@sschu, the only (minimal) issue I recognized is that in the work package edit view assignee and responsible are not sorted the same way.

**Comment by sschu** [comment]
I added a commit unifying the sorting behaviour, thanks for catching that.

**Comment by hschink** [comment]
Note to myself: **Don't forget the changelog entry**

**Comment by hschink** [comment]
@sschu Am I missing something or haven't you pushed your commit?

**Pull request merged**
