### PR TITLE
Use spot-button for add-assignee in team-planner

### PR DESCRIPTION
**Pull request by b12f**
Closes https://community.openproject.org/work_packages/41853/activity

### CODE REVIEW

**Review by HDinger — CHANGES_REQUESTED** [review]
👍 for the button in the team planner. However, in the ticket there is also the "Create new work package" in the list view mentioned. This part is missing here.

**Review by HDinger — APPROVED** [review]

**Comment by Kharonus** [comment]
both buttons still clash with the surrounding paddings when outlined. Is this known?

**Comment by cbliard** [comment]
Is it expected that the team planner view is taller now? It is filling the window vertically. I find it better but I'm not sure if that's intended or not.

image

VS

image

Apart from that, the buttons are behaving correctly during hover and when clicking.

**Comment by b12f** [comment]
> Is it expected that the team planner view is taller now?

Was a side-effect of removing weird scrolling issues. Was not introduced by this PR and should have been solved by https://github.com/opf/openproject/pull/10524

**Comment by cbliard** [comment]
So can it be merged?

**Comment by HDinger** [comment]
No, there have been some discussions with the product team and we need to do some adjustments

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
