### PR TITLE
remove Gemfile.lock

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by linki** [comment]
:weary:

**Comment by myabc** [comment]
image

**Comment by marutosi** [comment]
http://www.redmine.org/issues/10683

**Comment by linki** [comment]
removing Gemfile.lock is not a solution, just a workaround with several disadvantages. maybe we need to provide multiple versions of the Gemfile and Gemfile.lock for different platforms. Like many gems do it in order to work with different versions of Rails, e.g. https://github.com/svenfuchs/i18n/tree/master/gemfiles

**Comment by linki** [comment]
for reference: https://github.com/thoughtbot/appraisal

i can't find anything on that but wouldn't it be cool to use appraisal's concept to provide multiple Gemfiles for different platforms, @myabc?

**Pull request closed without merging**
