### PR TITLE
Show comments of initial journal

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work package

https://community.openproject.org/work_packages/21114
## Description

Since the aggregation of journals, it is possible that a comment becomes part of the journal that created a work package.
It also makes sense to comment on the creation of a work package (e.g. to assign it right after creating it).

Therefore this PR allows to see the comment for the WP creation, in case there is one.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-show-initial-comments.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-show-initial-comments.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Code looks good and also the generated emails look good.

There is however a discrepancy between what is shown on the overview tab compared to the activity tab. The activity tab is the way it is supposed to be.

### Overview

image

### Activity

image

**Comment by ulferts** [comment]
Beautiful - waiting for travis.

**Comment by ulferts** [comment]
spec failure is only due to code coverage.

**Pull request merged**
