### PR TITLE
[21444] wong link color

### PR DESCRIPTION
**Pull request by HDinger**
This sets the link color for the icon and the text.

https://community.openproject.org/work_packages/21444

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21444-wong-link-color.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21444-wong-link-color.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
before:

link_wrong

after:

link_after

**Comment by HDinger** [comment]
@NobodysNightmare can you please have a look at this?

**Comment by oliverguenther** [comment]
:+1: Works as expected

**Pull request merged**
