### PR TITLE
[24221] Arrow for children work packages is too low

### PR DESCRIPTION
**Pull request by HDinger**
This aligns the arrow indicating a child WP in the WP table.

https://community.openproject.com/work_packages/24221/activity

### CODE REVIEW

**Comment by HDinger** [comment]
#### Before
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.32.19.png

#### After
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.36.00.png

**Comment by HDinger** [comment]
#### Before
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.32.19.png

#### After
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.36.00.png

**Comment by HDinger** [comment]
#### Before
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.32.19.png

#### After
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.36.00.png

**Comment by HDinger** [comment]
#### Before
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.32.19.png

#### After
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.36.00.png

**Comment by HDinger** [comment]
#### Before
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.32.19.png

#### After
/Users/test/Desktop/Bildschirmfoto 2016-11-04 um 11.36.00.png

**Comment by HDinger** [comment]
#### Before

bildschirmfoto 2016-11-04 um 11 32 19

#### After

bildschirmfoto 2016-11-04 um 11 36 00

**Comment by oliverguenther** [comment]
Tested in IE11, Edge , FF + Chrome 👍

**Pull request merged**
