### PR TITLE
updated icon font (2)

### PR DESCRIPTION
**Pull request by HDinger**
added more icons

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-feature-update-icon-font.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-feature-update-icon-font.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@basiszwo can you please take a look at this?

**Comment by basiszwo** [comment]
at least we have the ones I was asking for. Can you check if there are still others missing? Or did you check already with this PR?

**Comment by HDinger** [comment]
I just saw at least one more, I will take a closer look...

**Comment by HDinger** [comment]
I think all icons are referenced now.

**Comment by basiszwo** [comment]
ok, great

**Pull request merged**
