### PR TITLE
update acts_as_list version to 0.4

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-0-acts-as-list-0-4-0.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-0-acts-as-list-0-4-0.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
I am not really sure how this will affect the application as there are quite a lot of models using this gem. 

Is there a changelog or anything @marutosi ?

Also, latest version seems to be `0.6.0`

**Comment by marutosi** [comment]
> Also, latest version seems to be 0.6.0

#2583

**Comment by floriank** [comment]
Well then, lets wait for the test results.

**Pull request closed without merging**
