### PR TITLE
17748 Update angular-modal: fix opening modal more than once

### PR DESCRIPTION
**Pull request by myabc**
Fixes support for Angular 1.3 ($animate API changes). See:
https://github.com/btford/angular-modal/pull/30

https://community.openproject.org/work_packages/17748

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-17748-unable-to-open-modal-more-once.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by hschink** [comment]
If I try to open the same modal several times, the modal behaves like opening on the first time but not on the second time but yet again on the third time and so on and so on. So there is a kind of alteration whether it is possible to open the modal or not.

**Comment by 0xF013** [comment]
https://github.com/finnlabs/angular-modal/pull/2

**Comment by 0xF013** [comment]
@hschink @myabc temporarily enabled my repo in bower.json. You can test (works for me)

**Comment by ulferts** [comment]
@0xF013, @myabc works for me, too. (Win7 + IE, Mac + Chrome)

**Pull request merged**
