### PR TITLE
Timeline init auto zoom

### PR DESCRIPTION
**Pull request by romanroe**

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/0dcfe30089c32a6fc61a2622a8179dcdbfea32dd) (deployed commit: 370f83e85a9261d4d44730fb3b2ca5ecf1933352).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/d8ba4e95dbd848ac5419829416923fee42a0edd9) (deployed commit: e55f2c7fad34039b1d7cbe6946cb650492483d95).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/36ace1dd505f3d971f55ca7f7fc5a6d710dbe5f9) (deployed commit: d63330d1694a22fbfdb6a1a77befe98f3d68d1dc).

**Review by oliverguenther — DISMISSED** [review]
Code-wise, LGTM. It doesn't seem to properly set the auto-zoom , however.

A quick example on the default data zooms out too far, even though the next zoom level is sufficient to show everything:


anim

Also, even though it does zoom out, the zoom in button is still disabled, so I cannot return to the maximum zoom

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/768ab24ba6b8cad7c98a3c08a93c27060a8eaedc) (deployed commit: 3217c5047896ca9722530a722c929b8a58c1c600).

**Review by oliverguenther — APPROVED** [review]

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/1e20e3943d05b001c2b37e751d6a6a127a067ef9) (deployed commit: 4c4912958cac1792162f75e25a72f64864a99f08).

**Pull request merged**
