### PR TITLE
add newline to CONTRIBUTING.md (#3096)

### PR DESCRIPTION
**Pull request by marutosi**
It is too hard to review on **poor** GitHub pull request UI.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-4-1-long-line-contributing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-4-1-long-line-contributing.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
If you have non functional changes I'd advise on using `[ci skip]` in either the commit message or the description, as to prevent an unnecessary run of the test suite.

If you want to run Travis for all of your changes, consider adding Travis to your fork of openproject, which should be possible after #2638.

**Comment by marutosi** [comment]
What is status?

**Comment by floriank** [comment]
Should be good to merge. Any thoughts @NobodysNightmare ?

**Comment by NobodysNightmare** [comment]
LGTM :+1: 

The formatted output does not change, it merely improves the readability in source mode, which is a good thing.

**Pull request merged**
