### PR TITLE
[21886] Broken filter layout

### PR DESCRIPTION
**Pull request by HDinger**
This fixes the following style issues in the filter layout:
- [x] The controls wee not correctly displayed in IE
- [x] The labels overlapped the input fields
- [x] The input field was smaller than the select fields on small screens in IE 

https://community.openproject.org/work_packages/21886/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21886-broken-filter-layout-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21886-broken-filter-layout-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
#### Before

filter_ie

_And_
input_before

#### After

filter_after

_And_
input_after

**Comment by mk84** [comment]
@HDinger Looks good but the search filters are misaligned now.

bildschirmfoto 2015-10-30 um 16 28 35

**Comment by HDinger** [comment]
@mk84 I fixed the mentioned issues: I have forgotten to set the `max-width` at one place and to limit the `padding` only to the right side.

**Comment by mk84** [comment]
LGTM, but travis is failing

**Pull request merged**
