### PR TITLE
update unicorn version

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-4-0-unicorn-version.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-4-0-unicorn-version.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
You need to learn to either split your PRs (not include the other PRs in this one).

Or you need to learn to call your PRs "update all the Gems"...

However, you also did not provide a description, so you should know I would close your PR.

**Comment by marutosi** [comment]
> You need to learn to either split your PRs (not include the other PRs in this one).

Are you kidding?

**Comment by marutosi** [comment]
> However, you also did not provide a description,

Are you kidding?

**Comment by marutosi** [comment]
> You need to learn to either split your PRs

Please tell me how to do.

Have you sent PRs to major open source project?

**Comment by marutosi** [comment]
> >    You need to learn to either split your PRs
> 
> Please tell me how to do.

If it is possible.

**Comment by marutosi** [comment]
> However, you also did not provide a description, so you should know I would close your PR.

Why not reject #3182?

**Comment by NobodysNightmare** [comment]
> > You need to learn to either split your PRs (not include the other PRs in this one).
> > Are you kidding?

no

> > However, you also did not provide a description,
> > Are you kidding?

nope, citing your PR:

> _No description provided._
> 
> > You need to learn to either split your PRs
> > Please tell me how to do.

Easy: 
1. Checkout the branch you want your fix to be applied to
2. create a new branch
3. do your fix
4. create a PR
5. for further fixes, start over at **point 1** (i.e. checkout the release branch again, don't start on your feature branch)

Only if your changes depend on eachother (e.g. if you could only update **a**, when **b** is also updated) you should create a **single PR**. Note: In that case please do also **not** create a PR only including **b**, because you will spam travis with a lot of unneccessary builds and having lots of open PRs will not increase the likelyhood of them being merged.

> Have you sent PRs to major open source project?

I don't know anyone called _Major Open Source Project_, but I bet he is a nice guy.
Yes I already sent contributions to various OS projects. Some accept my changes, some seem to ignore them, some decline them.
If anything I offer is declined I might argue whether it wouldn't help. But if they insist on declining, then I accept their decision. After all I don't need to sell my help. They want or or they don't.

> Why not reject [INSERT-PR-WITH-MISSING-DESCRIPTION-HERE]?

In your specific case: I did not see it and I think it needs a description. I will ask for a description first in that case. What makes me reject your PRs instantly is that **you don't learn**. I repeatedly asked you to do all those things and you keep on repeating your mistakes, you keep on re-opening declined PRs. That makes me feel like you don't want to help, but you want to troll.

If that is not the case: Ask yourself why I got that impression, because I did.

Have a nice day sir!

**Comment by marutosi** [comment]
> Easy:
> 1. Checkout the branch you want your fix to be applied to
> 2. create a new branch
> 3. do your fix
> 4. create a PR
> 5. for further fixes, start over at point 1 (i.e. checkout the release branch again, don't start on your feature branch)

I did.

> you should create a single PR.

Why?

> because you will spam travis with a lot of unneccessary builds and having lots of open PRs will not increase the likelyhood of them being merged.

It is travis defect.
https://github.com/travis-ci/travis-ci/issues/4114

**Comment by marutosi** [comment]
>  you don't learn

You don't learn.
https://github.com/opf/openproject/pull/3098#issuecomment-110634603

**Comment by marutosi** [comment]
> That makes me feel like you don't want to help

That makes me feel like you don't want to help.

**Comment by marutosi** [comment]
> Ask yourself why I got that impression

Ask yourself why your project has very few opensource contributors.

**Comment by marutosi** [comment]
> Only if your changes depend on eachother (e.g. if you could only update a, when b is also updated) you should create a single PR.

#3186

**Pull request closed without merging**
