### PR TITLE
Meets #18897: Design error pages in Openproject-multitenancy

### PR DESCRIPTION
**Pull request by slawa85**
[`* `#18897` Design error pages in Openproject-multitenancy`](https://community.openproject.org/work_packages/18897)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://netfighter-feature-multitenancy--error-page-stylizing-documenta.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://netfighter-feature-multitenancy--error-page-stylizing-documenta.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by slawa85** [comment]
This PR is related to this one https://github.com/finnlabs/openproject-multitenancy/pull/25

**Comment by ulferts** [comment]
@slawa85 this functionality only exists in combination with openproject-multitenancy right? So the documentation should be placed there IMO.

**Comment by ulferts** [comment]
@slawa85 any rational for doing this? Otherwise I would like to close this PR.

**Comment by slawa85** [comment]
@ulferts I'll move to openproject-multitenancy then

**Comment by slawa85** [comment]
@ulferts I moved the info regardin OP multitenancy here https://github.com/finnlabs/openproject-multitenancy/blob/feature/18897-Design-error-pages-Openproject-multitenancy/README.md

**Comment by ulferts** [comment]
Thanks @slawa85. Can this here be closed then?

**Pull request closed without merging**
