### PR TITLE
[29632] changed send() name argument from symbol to string

### PR DESCRIPTION
**Pull request by brycejlowe**
See the details in OpenProject Workpackage [29632](https://community.openproject.com/projects/openproject/work_packages/details/29632/overview), I have converted the name argument from a symbol to a string to match what subscribe is expecting.

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @brycejlowe , thanks for the PR. Wouldn't we want to cast to string then in this method here for completeness? https://github.com/opf/openproject/blob/dev/lib/open_project/notifications.rb#L81

Best,
Oliver

**Comment by oliverguenther** [comment]
Hi @brycejlowe , one spec expectation is breaking due to the change, could you take a look at those? https://travis-ci.org/opf/openproject/builds/499491659?utm_source=github_status&utm_medium=notification

**Comment by brycejlowe** [comment]
Hi @oliverguenther, my apologies, I just got back from a trip and will address this as soon as I can.  Thanks.

**Comment by oliverguenther** [comment]
I opened a new PR to stringify the notification in the send method rather than in the source usage. This should take care of the breaking tests.

https://github.com/opf/openproject/pull/7537

**Pull request closed without merging**
