### PR TITLE
Remove implicit globals in Timelines

### PR DESCRIPTION
**Pull request by myabc**
Continuation of work started in #2183. However, this PR is against dev as I did not this is too risky for a hotfix.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-remove-js-globals-in-timelines.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
For when we want to structure code that does not interface with Angular, it might be better to use ES6/CommonJS modules rather than Angular's module system. / WDYT @0xF013?

**Comment by 0xF013** [comment]
@myabc I have yet to understand what advantages do angular modules bring, so I second whatever you are going to do with them. Do you want to add some browserify/traceur stuff?

**Comment by myabc** [comment]
Setting milestone to 4.2.

**Pull request closed without merging**
