### PR TITLE
fix internal error opening budgets (by fixing avatar rendering in ActualLaborBudgetItemsComponent)

### PR DESCRIPTION
**Pull request by machisuji**
# Ticket
(https://community.openproject.org/projects/openproject/work_packages/57905/activity)

# Merge checklist

- [x] Added/updated tests

### CODE REVIEW

**Review by oliverguenther — CHANGES_REQUESTED** [review]
This change was deliberately introduced as part of https://github.com/opf/openproject/pull/16327 /  [OP#55974](https://community.openproject.org/work_packages/55974), as otherwise, deleted user was shown for groups and placeholder users.

**Comment by oliverguenther** [comment]
It seems we have both user and principal references: https://github.com/opf/openproject/blob/4911b8a14921efe0c552ab2029389ac12bcaefcb/modules/budgets/app/models/labor_budget_item.rb#L31-L32

**Comment by machisuji** [comment]
> It seems we have both user and principal references:
> 
> https://github.com/opf/openproject/blob/4911b8a14921efe0c552ab2029389ac12bcaefcb/modules/budgets/app/models/labor_budget_item.rb#L31-L32

According to the appsignal trace there is no `.principal` on the time entry.

```
undefined method `principal' for an instance of TimeEntry
```

Which is why I just changed it to user. Shouldn't that be the same?

**Review by oliverguenther — APPROVED** [review]
Double-checked, sorry my bad. This is indeed correct

**Comment by oliverguenther** [comment]
> Which is why I just changed it to user. Shouldn't that be the same?

For the planned costs, it's possible to select groups and placeholder users. It's not possible to do that for logged time, which makes sense.

So the actual labor costs can only show time entries.

**Pull request merged**
