### PR TITLE
awesome_nested_set: use github 2-1-stable branch

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by linki** [comment]
@marutosi after rebasing on `dev` you need to clean up your branch to only include the relevant commits

**Comment by marutosi** [comment]
> after rebasing on dev you need to clean up your branch to only include the relevant commits

I cannot because .travis.yml has only branches.

**Comment by marutosi** [comment]
> after rebasing on dev you need to clean up your branch to only include the relevant commits

I send new pull request #1362.

**Comment by linki** [comment]
@marutosi I'd would like to ask you very kindly to propose any uncritial pull requests against the `dev` branch in the future. You cannot include any unrelated commits in those PRs. Your PRs WILL be picked up by travis without any further modifications necessary to the `travis.yml` file.

Please have a look at my test PR: https://github.com/opf/openproject/pull/1366

**Comment by linki** [comment]
I also want to point to our admittedly hidden guide on contributing https://www.openproject.org/projects/openproject/wiki/Git_Workflow

besides others it states: "Create a pull request against opf/openproject **with a clear description of the problem being solved and how you solved it**"

**Pull request closed without merging**
