### PR TITLE
19623 display control elements on one element only; fix title

### PR DESCRIPTION
**Pull request by 0xF013**
https://community.openproject.org/work_packages/19623
https://community.openproject.org/work_packages/19827

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://0xf013-feature-19623-there-can-be-only-one-editable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://0xf013-feature-19623-there-can-be-only-one-editable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
When I use my keyboard (via Tab/Backtab) instead of the mouse, the controls don't move with me...

Repro:
1. put two fields into edit mode
2. tab into currently unfocussed field

**Comment by 0xF013** [comment]
@NobodysNightmare could it be that you are trying to tab through a ui-select? there is or should be a WP regarding needing 3 tabs or so to go through an ui-select

**Comment by 0xF013** [comment]
@NobodysNightmare or you mean that the controls are not toggled?

**Comment by NobodysNightmare** [comment]
The controls are not toggled.

I also noticed the other thing, but could not imagine that this is the fault of this PR.

**Comment by NobodysNightmare** [comment]
Probably because you are using `ng-click` and you want to use `ng-focus` or something frontendy ^^

**Comment by NobodysNightmare** [comment]
Not waiting for travis. It is broken anyway...

**Pull request merged**
