### PR TITLE
Fix timelines form layout trailing label & fieldsets

### PR DESCRIPTION
**Pull request by ulferts**
Contains
- general form extension to allow for setting explicit max-width on form-[typo of input]-container elements. the element will get a max-width so it will still shrink if there is not enough space. There are a couple of modifier classes I added and from which one can choose the desired width. The max-width value within the modifier class is more or less arbitrary. I am willing to make amends there.
- select2 elements within such a width-limited container will have the width of the container. We should remove the explicit width for select2 but that is outside the scope of this PR.
- The modifier class is applied to timelines so that the trailing "ago" label is fixed
-  The standard form--fieldsets are used in timelines

Should finally close https://community.openproject.org/work_packages/18934

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-fix-timelines-form-layout-trailing-label.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ulferts-fix-timelines-form-layout-trailing-label.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
This will currently break for me when i try to access the timeline form (edit/new) when in accessibility mode.

**Comment by ulferts** [comment]
The accessibility mode is fixed now and I additionally increased the robustness of the tabular form builder for cases where no active record object is used and no label is specified.

**Comment by floriank** [comment]
:+1: 

Let's wait for Travis, though.

**Comment by ulferts** [comment]
Travis complains but both tests look to be failing invalidly as their DB counterpart passes. I restarted both.

**Comment by ulferts** [comment]
@floriank, travis is green now.

**Pull request merged**
