### PR TITLE
Pin rubocop-rspec to v2 until rubocop-inflector ready

### PR DESCRIPTION
**Pull request by Eric-Guo**

### CODE REVIEW

**Comment by klaustopher** [comment]
Do you have a link to an issue that is encountered with `rubocop-inflector` and `rubocop-rspec 3.x`? [PR that updates `rubocop-rspec`](https://github.com/opf/openproject/pull/15829) shows no errors and there is [no issue on the `rubocop-inflector`](https://github.com/aeroastro/rubocop-inflector/issues) repo

**Comment by Eric-Guo** [comment]
Not yet, I just manually add rubocop-rspec 3.x removed rubocop-capybara, rubocop-factory_bot, rubocop-rspec_rails:

```diff
-gem "rubocop-rspec", "~> 2.31", require: false # rubocop-inflector 0.2.1 not ready for 3.0
+gem "rubocop-rspec", require: false
+gem "rubocop-capybara", require: false
+gem "rubocop-factory_bot", require: false
+gem "rubocop-rspec_rails", require: false
```

Then find `ruby-lsp` break in VScode (actually I'm using cursor.sh):

```log
2024-06-12 17:06:04.833 [info] (openproject) Finished initializing Ruby LSP!

2024-06-12 17:06:05.058 [info] (openproject) Activating Ruby LSP Rails addon v0.3.7
Ruby LSP Rails booting server

2024-06-12 17:06:05.527 [info] (openproject) Error processing initialized: /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-inflector-0.2.1/lib/rubocop/inflector/extensions/rspec.rb:18:in `<module:RSpec>': uninitialized constant RuboCop::Cop::RSpec::FilePath (NameError)

        ::RuboCop::Cop::RSpec::FilePath.prepend Cop::RSpec::FilePath
                             ^^^^^^^^^^
Did you mean?  RuboCop::FilePatterns
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-inflector-0.2.1/lib/rubocop/inflector/extensions/rspec.rb:6:in `<module:Extensions>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-inflector-0.2.1/lib/rubocop/inflector/extensions/rspec.rb:5:in `<module:Inflector>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-inflector-0.2.1/lib/rubocop/inflector/extensions/rspec.rb:4:in `<module:RuboCop>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-inflector-0.2.1/lib/rubocop/inflector/extensions/rspec.rb:3:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /opt/homebrew/Cellar/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-inflector-0.2.1/lib/rubocop-inflector.rb:10:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /opt/homebrew/Cellar/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:35:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:21:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
	from <internal:kernel>:90:in `tap'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:52:in `load_file'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:111:in `configuration_from_file'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_store.rb:68:in `for_dir'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/rubocop-1.64.1/lib/rubocop/config_store.rb:47:in `for_pwd'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/lib/ruby_lsp/requests/support/rubocop_runner.rb:84:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11429/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11429/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/lib/ruby_lsp/requests/support/rubocop_formatter.rb:15:in `new'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/lib/ruby_lsp/requests/support/rubocop_formatter.rb:15:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11429/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11429/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/lib/ruby_lsp/server.rb:248:in `new'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/lib/ruby_lsp/server.rb:248:in `run_initialized'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11429/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11429/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/lib/ruby_lsp/server.rb:26:in `process_message'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/lib/ruby_lsp/base_server.rb:66:in `block in start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/language_server-protocol-3.17.0.3/lib/language_server/protocol/transport/io/reader.rb:20:in `read'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/lib/ruby_lsp/base_server.rb:39:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11429/lib/types/private/methods/_methods.rb:279:in `bind_call'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11429/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.17.3/exe/ruby-lsp:110:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/ruby-lsp:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/ruby-lsp:25:in `<top (required)>'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:455:in `exec'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:29:in `start'
	from /opt/homebrew/Cellar/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
	from /opt/homebrew/lib/ruby/site_ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/homebrew/Cellar/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `<main>'

2024-06-12 17:06:13.345 [info] (openproject) Finished booting Ruby LSP Rails server
```

Then finally give up.

**Comment by Eric-Guo** [comment]
Seems this is not a very easy problem to resolve, at least for me.

**Comment by klaustopher** [comment]
Ah, the `FilePath` cop has been removed, see https://github.com/rubocop/rubocop-rspec/pull/1877, so the inflector gem would need to patch on `RSpec/SpecFilePathFormat`

**Comment by Eric-Guo** [comment]
I will be very glad if you could fix it, so close this PR.

**Comment by klaustopher** [comment]
There has been a PR open on the inflector repo since last year to move the monkey patch over to the new class: https://github.com/aeroastro/rubocop-inflector/pull/5 No activity for a while ... Maybe it is time to drop that dependency

**Comment by klaustopher** [comment]
PR is open at https://github.com/opf/openproject/pull/15833

**Comment by Eric-Guo** [comment]
Thanks @klaustopher VSCode works after remove rubocop-inflector

**Comment by klaustopher** [comment]
No problem

**Pull request closed without merging**
