### PR TITLE
Style fix: Replace do…end with {} in expect blocks

### PR DESCRIPTION
**Pull request by myabc**
Dedicated to @hschink

### CODE REVIEW

**Comment by mfrister** [comment]
Why would we want to use {} for multi-line blocks?

**Comment by myabc** [comment]
@meeee 
- simple answer: @hschink finds it ugly.
- long answer: there are mixed schools of thoughts on this. The [Ruby Style Guide]:(https://github.com/bbatsov/ruby-style-guide#syntax) agrees that `do..end` is preferred for multi-line blocks but also states:
  
  > Avoid do...end when chaining.
  
  I personally prefer the [convention laid out by Avdi Grimm](http://devblog.avdi.org/2011/07/26/the-procedurefunction-block-convention-in-ruby/) though.

**Comment by mfrister** [comment]
@myabc I see. I don't have a strong preference here, but when changing this, we should update the styleguide we use and our Rubocop configuration.

On our [code review page](https://www.openproject.org/projects/openproject/wiki/Code_Review_Guidelines), I linked to the Community Style guide. If we want to deviate from this, I suggest we fork it and adapt it.

**Comment by linki** [comment]
:+1: for Avdi Grimm's convention

**Comment by hschink** [comment]
As this is dedicated to me I have to leave an opinion (I guess): Actually, I only liked to point out that we are using the first approach Avdi Grimm describes in our spec suite (thus, I don't find it ugly but I find it's different to what we do now). Personally, I have no feelings about this topic, though I currently follow the same (first) approach.

**Comment by mfrister** [comment]
@linki What was the resolution for the discussion here?

**Comment by linki** [comment]
i think the changes are very valueable and `Avoid do...end when chaining.` (our current style guide) is applicable to the changes @myabc did, sort of. but i agree, we should find a style everybody agrees with.

**Comment by mfrister** [comment]
It also says:

>  Avoid using {...} for multi-line blocks (multiline chaining is always ugly).

Rubocop also doesn't like this. 

There's no point in reverting this now, but I guess the next time we should avoid multiline chaining with blocks.

**Comment by linki** [comment]
ok, how do we resolve the `expect {}.to` stuff then. single line or no chaining?

**Comment by myabc** [comment]
`expect {}.to` is idiomatic RSpec. We can't not chain here.

**Comment by mfrister** [comment]
Ok, then let's use it.

What do you think about creating a separate `.rubocop.yml` in the spec folder and deactivating the "don't use {} for multi-line blocks" rule there?

**Pull request merged**
