### PR TITLE
Reduce table font size (work packages and other tables)

### PR DESCRIPTION
**Pull request by myabc**
:warning: ~~**This PR supersedes #2514**~~

https://community.openproject.org/work_packages/18675

Also addresses:
- https://community.openproject.org/work_packages/19099

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-fix-18675-adjust-table-font-sizes.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-fix-18675-adjust-table-font-sizes.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
@myabc - I highly appreciate the amount of work you put into this, but is the title (and therefore the scope) of the PR still in scope of what's actually happening? :laughing:

**Comment by NobodysNightmare** [comment]
Whats up here? No response and failing tests... Can I help?

**Comment by myabc** [comment]
@floriank @NobodysNightmare will split this into more discreet PRs… #2766 is ready for review.

**Pull request closed without merging**
