### PR TITLE
Feature/le awesome watchers implementation returns

### PR DESCRIPTION
**Pull request by ulferts**
This is a rebase + takeover of https://github.com/opf/openproject/pull/3371. It amends, what I deemed necessary to fix:
- Keyboard access to deletion
- Introduces a confirmation directive that is employed to ask the user before deleting an attachment.
- Recreates ability to follow the links in watchers/atttachments. By that it becomes possible again to download an attachment and to go to the user page.
- Focuses the ui-select element for watcher selection upon opening initially and after a watcher has been added.
- Fixes path to download an attachment (presented by @oliverguenther)
  
  https://community.openproject.org/work_packages/20725

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-feature-le-awesome-watchers-implementation-returns.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ulferts-feature-le-awesome-watchers-implementation-returns.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Keyboard access and confirmation works fine, and so does the focusing (mostly).
When focusing on the delete link (not the span), the focus outline ends up being cut off on most sides due overflow being hidden on `.inplace-editing--trigger-container`.

See the following screenshot. Its not exactly clear to the user where the focus currently relies. I'm not  sure whether the overflow is really necessary (or could be applied only to the filename span instead). 

Otherwise a quick solution would be to use a border instead of outline. I've also thought about making these actions more prominent to the user, e.g., by using a red outline to denote a _dangerous_ action, but I also see the various implementations of focus outlines in various browser and the changed outline may be confusing.

bildschirmfoto 2015-08-29 um 23 14 50

**Comment by ulferts** [comment]
Thanks for the feedback @oliverguenther. I'll give removing the overflow: hidden css a try.

**Comment by ulferts** [comment]
Defining `overflow: visible` does have one side effect. The focus for inplace-edit used to be a gray border, same as for hovering:

image

This was looking pretty neat. With the overflow being possible, the blue hover overlays the gray border:

image

While it was looking neat, I still think that it is better to be consistent and I therefore prefer the blue border. Opinions?

**Comment by oliverguenther** [comment]
I indeed liked that hover state. Just for clarification: Shouldn't the blue outline only appear when focussing the element?

Note that we can still remove the outline for that container element (using `:focus`), if we deem the border to be enough to be accessible. (cf. http://outlinenone.com/).

This should be something that allows to distinguish hover from focus state on these wrappers.

**Comment by ulferts** [comment]
Don't know if we misunderstood one another. The blue box only appears on focus (tabbing). On hover (mouseover), it is still the gray line.

**Comment by oliverguenther** [comment]
Ah, yes - I misunderstood, sorry. Had another look myself, and this is absolutely fine for me.

**Pull request merged**
