### PR TITLE
[#42074] Docs: "npm run serve:public" with colon not dash

### PR DESCRIPTION
**Pull request by wielinde**
https://community.openproject.org/work_packages/42074

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @wielinde , the PR appears to be empty?

**Comment by HDinger** [comment]
Please also consider to commit doc fixes to the release branch, so that they are deployed faster.

**Comment by wielinde** [comment]
> Hi @wielinde , the PR appears to be empty?

It's Monday. After holidays. I am sorry.

**Comment by wielinde** [comment]
> Please also consider to commit doc fixes to the release branch, so that they are deployed faster.

@HDinger I wasn't sure if that affects 12.0, too. Apparently it does. Changed this PR's base to `release/12.0`

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
