### PR TITLE
[Rails4] Removed useless :lang option

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-rails4-tabular-form-builder.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by linki** [comment]
way too many commits in here for what the title suggests.

**Comment by marutosi** [comment]
https://github.com/opf/openproject/commit/f5bb0067f0340b915dc6e75eabac29a587f26869

**Comment by marutosi** [comment]
#2492

**Pull request closed without merging**
