### PR TITLE
17193 Work package attribute styling

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/17193

Continuation of #2311.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://feature-17193-work-package-attribute-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://feature-17193-work-package-attribute-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@ulferts this is ready for review.

**Comment by ulferts** [comment]
I like what you did with regards to generalisation and getting rid of floats.

image

I am missing two things in this screenshot:
1) The "show all" button is not shown at all. This is only true for some work packages. It seems to be related to the work package having an assignee or not. I don't get how your change should have changed the behaviour there but it apparently does.
2) The "edit button"  is positioned way too much to the right 

As for the "show all" button:
image

My interpretation of what the styleguide calls "Button active" is the state when the functionality behind that button is in the "on" setting. So as long as all attributes are shown, the button should be in the "button active" state, regardless of whether the mouse hovers over the button or not. Currently, the button falls back to the "Button hover" styling when the functionality is "on" and the mouse does not hover over the button.

The button's vertical alignment is IMO not correct. From how I understand the styleguide, the button's text should be aligned with the "Details" heading. 

The buttons lower border/shadow is cut of when not hovering over the element.

**Comment by myabc** [comment]
> The button's vertical alignment is IMO not correct. From how I understand the styleguide, the button's text should be aligned with the "Details" heading.

Done in 5a0d004.

**Comment by myabc** [comment]
@ulferts –

> 1) The "show all" button is not shown at all. This is only true for some work packages. It seems to be related to the work package having an assignee or not. I don't get how your change should have changed the behaviour there but it apparently does.

I have yet to be able to reproduce this locally.

> My interpretation of what the styleguide calls "Button active" is the state when the functionality behind that button is in the "on" setting. So as long as all attributes are shown, the button should be in the "button active" state, regardless of whether the mouse hovers over the button or not. Currently, the button falls back to the "Button hover" styling when the functionality is "on" and the mouse does not hover over the button.

Please check if 155a3fc makes the hover state conform…

**Comment by ulferts** [comment]
The "show all" button problem is not related to this PR and is fixed in #2425.

**Comment by ulferts** [comment]
image

My understanding of this is:
1) When not everything is shown and the user does not hover over the button: "Show all" is displayed with styling "Button default". Works
2) When everything is shown and the user does not hover over the button: "Hide all" is displayed with styling "Button active". Currently the background is not gray and the inset shadow is different.
3) When not everything is shown and the user does hover over the button: "Show all" is displayed with styling "Button hover". There currently is no border displayed (same as "Button default").
4) When everything is shown and the user does hover over the button: "Hide all" is displayed. The styling is not defined I guess. I'd either go for "Button active" + "Button hover" (preferred) or "Button hover".

Alignment looks good, thanks.

**Comment by myabc** [comment]
@ulferts 

> 2) When everything is shown and the user does not hover over the button: "Hide all" is displayed with styling "Button active". Currently the background is not gray and the inset shadow is different.

I changed the background to grey. The inset shadow matches shadow used in other buttons in the application:
seeded_project_-_work_packages_-_openproject

> 3) When not everything is shown and the user does hover over the button: "Show all" is displayed with styling "Button hover". There currently is no border displayed (same as "Button default").

Changed.

> 4) When everything is shown and the user does hover over the button: "Hide all" is displayed. The styling is not defined I guess. I'd either go for "Button active" + "Button hover" (preferred) or "Button hover".

Changed (see 53cca72).

**Comment by ulferts** [comment]
> I changed the background to grey. The inset shadow matches shadow used in other buttons in the application

Good, then consistency wins the day. And why not for a change.

LGTM :+1:

**Pull request merged**
