### PR TITLE
[19759] Use viewport height to restrict filters in WP List

### PR DESCRIPTION
**Pull request by floriank**
This PR also addresses the requirements of https://community.openproject.org/work_packages/19579.

These issues have already been addressed in #2943, but this could provide a better solution to the problem.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-fix-19759-use-viewport-height.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-fix-19759-use-viewport-height.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
:+1:

**Comment by NobodysNightmare** [comment]
I favor this approach over #2943 :+1:

**Comment by NobodysNightmare** [comment]
Merge-fever took control of me :smiling_imp:

**Pull request merged**
