### PR TITLE
[#42027] Improve 2FA Documentation  https://community.openproject.org…

### PR DESCRIPTION
**Pull request by ghost**
…/work_packages/42027

[#42027] Improve 2FA Documentation

https://community.openproject.org/work_packages/42027

### CODE REVIEW

**Comment by ghost** [comment]
@machisuji if you do not know and we shall not wait for Oliver then we could ask Jens. He seems to be involved a little in that topic as i have seen his tags in the files about 2fa on the opf repo

**Comment by HDinger** [comment]
@adam-op Are you sure you want to add that to the `release/12.1` branch? The current one is `release/12.2`.

**Comment by ghost** [comment]
Please review only the last commit of adam-op, the other commits must have been reviewed already.

**Comment by as-op** [comment]
Pull request has been recreated to release/12.2 at https://github.com/opf/openproject/pull/11041

**Pull request closed without merging**
