### PR TITLE
[25709] Toolbar to close to header (forums entry)

### PR DESCRIPTION
**Pull request by HDinger**
This applies the toolbar class to a message in a forum.

https://community.openproject.com/projects/openproject/work_packages/25709/activity

### CODE REVIEW

**Comment by HDinger** [comment]
#### Before
bildschirmfoto 2017-06-30 um 09 21 41

#### After
bildschirmfoto 2017-06-30 um 09 21 33

**Comment by oliverguenther** [comment]
bildschirmfoto 2017-06-30 um 13 37 37

Fix LGTM, however the reply / quote buttons are crossing the border when no gravatar icon is shown. Could you check if there's an easy fix without creating a separate ticket for that?

**Comment by HDinger** [comment]
@oliverguenther I added two css-rules which should take care of that.

**Comment by oliverguenther** [comment]
👍

**Pull request merged**
