### PR TITLE
allow for duplicate menu entries

### PR DESCRIPTION
**Pull request by machisuji**
WP [#15447](https://www.openproject.org/work_packages/15447)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-duplicate-menu-entries.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by ulferts** [comment]
@machisuji the failing cuke is doing so legitimately. With the changes, the active menu item is not selected correctly when it should select a query menu item. Without it being selected, the "Work packages" submenu is not opened, and therefore the menu item is not visible.

You will have to adapt https://github.com/opf/openproject/blob/release/3.0/app/controllers/work_packages_controller.rb#L42
in order to achieve this.

Might be a good idea to introduce a method used by both, so that this error is not repeated.

**Comment by machisuji** [comment]
@ulferts Yes, I noticed that issue. Thanks for the pointer.

**Comment by machisuji** [comment]
This should also go into dev (4.x).

**Comment by ulferts** [comment]
@machisuji looks good now, any chance for some specs?

**Comment by machisuji** [comment]
@ulferts Ah true yes. I shall add a spec for adding query menu items with identical names.

**Pull request merged**
