### PR TITLE
[16364] Work package fullscreen view

### PR DESCRIPTION
**Pull request by basiszwo**
This PR superseeds https://github.com/opf/openproject/pull/3366

See https://community.openproject.org/work_packages/16364 for general task description (though it does not fully apply).
#### Tasks
- [x] changing the type needs to update the available fields / statuses / options (@furinvader)
- [x] assignee and responsible person are not displayed in fullscreen and split view when setting then in edit view before (@furinvader)
- [x] requesting `/work_packages/54` needs to work (`/projects/seeded_project/work_packages/54/activity` also) (@furinvader)
- [x] work package links are url escaped. this breaks opening them in new tab / window (@furinvader)
- [x] fullscreen button does not load first work package when in list view (@furinvader)
- [x] create work package button does not work on full screen view => we tmp disabled it  (@furinvader)
- [x] [breadcrumb does not show project](https://github.com/opf/openproject/pull/3366#issuecomment-140994275) => project scope missing (@basiszwo)
- [x] work package link from search page is wrong (@basiszwo)
- [x] [Request-loop for non-existing work packages](https://github.com/opf/openproject/pull/3366#issuecomment-140998345)
- [x] lots of js errors when visiting work package logged out
- [x] show loading spinner until work package is fully loaded
- [x] define min width of right panel (@mk84)
- [x] [toolbar line-breaking](https://github.com/opf/openproject/pull/3366#issuecomment-141000902) (@mk84)
- [x] [rendering of anchors](https://github.com/opf/openproject/pull/3366#issuecomment-141015332)(@mk84)
- [x] [Can't change view on small resolutions](https://github.com/opf/openproject/pull/3366#issuecomment-140995420)

### CODE REVIEW

**Comment by ulferts** [comment]
- [ ] When being on the full screen view e.g. on https://community.openproject.org/projects/openproject/work_packages/21510/activity

image

A click on any of the queries that are part of the project menu will result in the query_id becoming a query parameter in the url e.g. https://community.openproject.org/projects/openproject/work_packages/21510/activity?query_id=730

This url is wrong because the user will stay on the page instead of going to the work package list.

This is also true when clicking on the top level menu item "Work packages"

**Comment by ulferts** [comment]
- [ ] The headers for the tabs "Activity", "Relations and "Watchers" collapse when the viewport is narrow: 

image

**Comment by ulferts** [comment]
- [ ] The links in the work packages list on the subject and the id of each work package contain escaped slashes

image

A simple click on the link will work because angular does handle it. When clicking to open a new tab (e.g. cmd + click, ctrl + click) will cause a 404, however:

image

The fact, that there are duplicated slashes (when unescaped before the `projects` part is wrong but is handled by the browser.

**Comment by ulferts** [comment]
- [ ] The loading of work packages in the full screen view is slow and because there is no loading spinner, I was wondering whether there was a bug when I followed a deep link for the first time and only a blank screen was presented to me. 

I have taken a deeper look into the network traffic for https://community.openproject.org/projects/openproject/work_packages/18820
and noticed two parts which, when addressed would speed up the loading tremendously. Right now, loading the work package takes 12 seconds. 

1) The work package is fetched from the API twice (https://community.openproject.org/api/v3/work_packages/18820)

image

Each request for the work package is taking too long by itself (2.6s and 4.3s) and this is something that needs to be addressed as well @NobodysNightmare. Maybe there is something that can be improved apart from removing the embedded resources. But both of them together result in 7 seconds of wait time in which the front end can do nothing. Loading it only once would speed up the page by itself.

2) For every activity (currently 48 on the example work package), the user belonging to the activity is fetched from the backend resulting in 4 seconds of time spent communicating with the backend. 

image

As a lot of activity comes from the same user, the response could be cached in the front end so that user information is fetched only once.

**Comment by ulferts** [comment]
~~There is a viewport width for which the menu to the top right wraps to the next line:~~
image

_EDIT_ Closed as duplicate

**Comment by basiszwo** [comment]
@ulferts I will try to address your feedback
- url escaping is already mentioned in the task list. thanks. 
- duplicate loading of resources: this is sth. that is already part of the split view. I talked about this with Florian in June already ... doesn't make it better though.
- narrow-ness of tabs: thanks
- query as part of url: cannot reproduce

**Comment by NobodysNightmare** [comment]
## Wrong links in search

### Reproduction
1. open the global search (hotkey `s`)
2. search for the subject of a work package (or anything that will open the [search results](https://community.openproject.org/search?utf8=%E2%9C%93&q=test&scope=all&submit=OK&all_words=1&work_packages=1) page)
3. click on the link for a work package

### Expected
- the link is valid
- following the link will show me the work package

### Actual
- The link does not seem to open the work package
- it has an (for me) unexpected path, e.g. `https://community.openproject.org/work_packages/show/21546` (mind the additional `show` directory)

**Comment by RobinWagner** [comment]
<h1> Images not scaled properly in Firefox

Images do no scale properly in Firefox when embedded in the description. They are displayed in full size (scrolling necessary):
ff-image

Scaled correctly in Chrome / IE:
chrome - image

**Comment by mk84** [comment]
`Images not scaled properly in Firefox` can't be reproduced neither by me nor by @RobinWagner.

**Comment by ulferts** [comment]
Please take heed of #3572 which fixes the routing (esp. deep links).

**Comment by lindenthal** [comment]
We will not be able to fix all existing bugs before we merge this PR. I therefore removed this task from the description.

**Pull request merged**
