### PR TITLE
Feature/add server side timeline filters

### PR DESCRIPTION
**Pull request by apfelfabrik**

### CODE REVIEW

**Comment by ulferts** [comment]
While you are at it, could you please add :status to the list of models for eager loading:
About line 206 in the api/v2/planning_elements_controller.rb

> @planning_elements = @planning_elements.all(:include => [:type, :project])

**Comment by apfelfabrik** [comment]
@ulferts the eager loading change was performed in 7d306f7.

**Comment by hschink** [comment]
Route specs are missing for `statuses_controller`! :alien:

**Comment by apfelfabrik** [comment]
Specs? Nah.

**Pull request merged**
