### PR TITLE
[security] fixed back url verification

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by marutosi** [comment]
http://www.redmine.org/news/90

**Comment by marutosi** [comment]
http://www.redmine.org/projects/redmine/wiki/Security_Advisories/13

**Comment by tessi** [comment]
Thanks for bringing this up. Do you have any special reason for proposing this PR against the `migrate/1.5_to_2.4` branch?

**Comment by marutosi** [comment]
Because it is alive branch.

<pre>
$ git log gh-finn/migrate/1.5_to_2.4  | cat
commit c77befef9149a58347855ebdaa83d02c0834a7ce
Author: Markus Kahl <xxxxxxxxx>
Date:   Wed Mar 19 18:58:26 2014 +0100
    Swap migrations "add changes from journal details..." and "build initial journals..."
    
    This reverts commit 67cc4bee1bd22cdff8d8ea13361b6ce835bc6f9f.
commit 67cc4bee1bd22cdff8d8ea13361b6ce835bc6f9f
Author: Markus Kahl <xxxxxxxx>
Date:   Wed Mar 19 15:04:31 2014 +0100
    fixed migration order to make initial journal creation work
commit 589aeeb853999fd2742a0dbaed8f8dc6357c066c
Author: Markus Kahl <xxxxxx>
Date:   Wed Jan 15 16:26:42 2014 +0100
    added rake task for deletion of obsolete tables
commit 2bff298cd9b0c05e0e1fc28b0958b053e55f75bd
Author: Christian Ratz <xxxxxx>
Date:   Fri Jan 10 15:57:40 2014 +0100
    added unicorn to Gemfile
commit fa1ef6e266e5276146ca7cc82f73f5e132bdf1f0
Author: Markus Kahl <xxxxxxx>
Date:   Wed Dec 18 10:21:41 2013 +0000
    fixed broken tear-down migration
</pre>

**Comment by tessi** [comment]
Alright. If     liveliness is your point, then you should be please that I reposted this PR against the `dev` branch - it is much more lively. :)

Please post all further pull requests against the `dev` branch, as statet in our [contribution documentation](https://www.openproject.org/projects/openproject/wiki/Contribution)

**Pull request closed without merging**
