### PR TITLE
Fixing that only first fold of screen was printed

### PR DESCRIPTION
**Pull request by wielinde**
Affected both Chrome and FF.

https://community.openproject.com/projects/openproject/work_packages/25944/activity

### CODE REVIEW

**Comment by wielinde** [comment]
@RobinWagner Could you please play around with printing in FF and Chrome? Special care for the work package list is important, as this was the main concern of that bug. However, all other parts of the system were affected too (and should work better now).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/510ec595769773d8403c2d16d793e5671a8ee747) (deployed commit: aa2811ebd699ac765b665a76681639cf335d29ce).

**Comment by RobinWagner** [comment]
Hi @wielinde, work packages below the fold are now also included in the PDF export. The work package page looks quite good in the export and most other pages look decent as well.

I noticed the following errors (mostly occurred for both Chrome and Firefox - unless otherwise noted):

1. When many columns are displayed (e.g. more than 8), the remaining columns are cut off on the right. (That's probably a behavior we have to live with unless we continue the remaining columns on the next print page.)

export_columns1

2. The timeline is not shown in the PDF export - even if there are few or no work package columns displayed. Before, the timeline was shown in the export (even though it was cut off on the right). It will certainly be a challenge to display the timeline in a good way in the export (especially if there are a lot of columns and a lot of elements spaced out in the timeline on the right) but I think it is quite important to users to export the timeline. There is even a feature request for this which is quite popular: https://community.openproject.com/projects/openproject/work_packages/15444/activity

export_columns3

3. Similar to the timeline the split screen is not exported when activated.

export_columns4

4. When exporting the fullscreen view, the "Create" button is not shown in green but only with a green outline (this is a minor point and may depend on the browser export itself).

export_columns5

5. In Firefox the exported wiki page seems to be missing several lines (this does not happen in Chrome).

export_columns6

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/a169f4a3527cef20355a0415bca346c1a7a99083) (deployed commit: aa2811ebd699ac765b665a76681639cf335d29ce).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/3940f83b39763e4bf5e00eb08ce76bf3b5117fc7) (deployed commit: 16581bee9adf76c4ec330a50124649e48a5db423).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/1530c56643ec3c4e0f92bb18efe3b13684f1f3e2) (deployed commit: e04bf8026cd098754573297613d5c3a5f6a495e5).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/0a498848614ca823537355f1b62b08364842fb75) (deployed commit: a53147b3677e052ad190af0af54565b478a7e650).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c87bb95f61e402aaba05b99613ca2a23d41f328b) (deployed commit: d679bc21b4067dc0ee704eb237609a0247a38448).

**Comment by oliverguenther** [comment]
Looks good enough to me 👍

**Pull request merged**
