### PR TITLE
Add correct styles to table in relations tab

### PR DESCRIPTION
**Pull request by zzmedia**
- added correct styles to table in relation tab
- added some paddings

https://www.openproject.org/work_packages/14684

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://fix-relations-tab-styling-issues.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by ulferts** [comment]
The table layout is different between the "Attachments" and the "Relations" tab. Can we somehow harmonise this?

**Comment by zzmedia** [comment]
@ulferts: yep, I think the best would be to have a class for this table-layout inside the details-pane, I will put it in the styleguide

**Comment by myabc** [comment]
will close in favour of #1717

**Pull request closed without merging**
