### PR TITLE
adding attachments to work package descriptions by drag and drop

### PR DESCRIPTION
**Pull request by ghost**
## In response to feature request [#22511](https://community.openproject.org/work_packages/22511/activity)

workPackageDndFileHandler: adds drag and drop functionality for work package inline description

**Features:** 
- handles drop events on  `<textarea>` elements of work packages  and can distinguish between:
  - **local files:** initiates file upload (single file or upload queue)
  - **external urls:** become inserted as default weblink
  - **external image files:** become inserted as inline image
  - **attachments from current work package:** become inserted as attachment link
  - **attachments (imagefiles) from current work package:** become inserted as inline image

there is an _experimental_ version included as well which lets the user decide on how to embed images (inline or as an attachment / web link). 

[Screencast of experimental version on YouTube](https://www.youtube.com/watch?v=tR_SDw4UxzI&feature=youtu.be)

For easy switching between both versions the related part in index.js has been left in as comment block.

**Acceptance criteria:**
- [x] Description field is in **edit mode**
- [x] Description field is in **show mode** 

Functionality for show mode will be added with a small extra directive that hooks into the _show mode_ version and simply switches the inplace-edit-field to _edit mode_ so we won't have to maintain duplicate code. Needs further testing and will be integrated with the next commit.

**ToDO**
- [x] Upload in create form
- [x] Upload of the first picture in show view
- [x] After adding the first attachment in show view the file section is still hidden. The user needs to press "show all" to the see attachment
- [ ] Rebase
- [ ] Make tests on Travis green

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://happschinson-dev.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://happschinson-dev.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ghost** [comment]
Works fine on Safari (Mac) but needs fixes for cross browser compatibility.
I'll try to fix it asap!

**Comment by lindenthal** [comment]
@happschinson:
- the screencast seems to be private. Can you please check this?
- can you please test this feature and the open bugs to the checklist in the description?

**Comment by ghost** [comment]
Hi @lindenthal !  

screencast should be working now :+1: 
browser compatibility tested without any errors on Windows 10 with:
- IE 11 (latest)
- Chrome (latest)
- Firefox (latest)

... and on Mac (El Capitan)
- Safari (latest)
- Chrome (latest)

However, teatro throws an error because of an undefined $stateParams key (workpackage id returned by workPackageService). Could this be a problem which can be narrowed down to the use of teatro maybe @TeatroIO  ?

**Comment by lindenthal** [comment]
Hi @happschinson 

can you please have a look at the tests on Travis?

Thanks
Niels

**Comment by ghost** [comment]
@lindenthal 
sure, I'll check it this afternoon as soon as I get home. Thanks!

**Comment by ulferts** [comment]
Thanks for the PR @happschinson. Given the limitations on the backend with regards to the attachments, it already feels quite solid.

I am probably not suited the most to judge code quality in the JS world so I am therefore focussing on the functionality. Following is a list of bugs I have spotted:
- The list of attachments on the WorkPackage is not updated when uploading a file via dnd. Only after I have reloaded the page by the usual means (refresh, adding another attachment, switching work package), is the list updated.
- The list of file types is [hard coded](https://github.com/opf/openproject/pull/4091/files#diff-3191d7d69cfa627aa3c7319ad31a70edR77) which is fine given that the configuration API does not yet reveal it. We should extend the API outside of the scope of this PR. The problem is that the check on the file type is case sensitive. So while an image named 'something.png' is inlined (-> '!something.png!'), the file 'something.PNG' is not (-> 'attachment:something.png')
- The uploading is only working for existing work packages. On a work package that is not yet created (e.g. http://localhost:3000/projects/{project_id}/work_packages/new?type={id}) a js error is logged. 

~~A bug that is out of scope of this PR is that the textile renderer does not render the usage of attachment:something.png correctly. I'll open a work package on openproject.org for that.~~ Edit: Couldn't reproduce this any more.

My take on the karma test failures is, that the `WorkPackageCommentDirective` uses the `EditWikiTextArea` directive which the PR extended to also rely on the `WorkPackageDndFileHandlerDirective`. That is good functionality-wise as it allows the user to upload attachments also by dnd of files into the comment field. But it adds an additional dependency which must be covered by the test.

Speaking of tests, there are no tests for the `WorkPackageDndFileHandlerDirective`. Can you please provide some?

@furinvader can you please give this PR a glance regarding code quality?

**Comment by ghost** [comment]
@ulferts 
thanks for the detailed review!
I'll try to include your suggestions in my next commits by monday.

**Comment by furinvader** [comment]
Hi @happschinson, thank you very much for your well documented PR!

We do not use `jsdoc` nor `ngdoc` currently, although we might change that based on your recommendation.

Your implementation looks quite good to me. You seem to have added the drag&drop feature by hand - without using any external modules/directives.
This is remarkable, as it's quite a hassle, but I'd like to know why you have decided not to use an external tool.

**Comment by furinvader** [comment]
As for my further comments, I have to apologise, because they should have been documented.

**TypeScript**
We use TypeScript for several reasons (ES6, type definitions, Angular 2 support ...)
You may implement your controllers using ES6 classes - in `attachments-simple-modal.controller.js`, for example.
Simply rename the `.ts` file ending and you're good to go.

You can find some TS examples in `/fronted/app/components/wp-buttons`.

**/frontend/app/components**
You should put new angular components here (as you did with `attachments-simple-modal.controller.js`), so you don't have to annotate the injector dependencies by hand.
If you're not sure where to put them, you can simply add another subfolder.
Put the test files tests there, too.

The other directory are considered 'legacy' and will be moved to `/frontend/app/components`.

If you have any questions, please feel free to ask. I'd be happy to help!

**Comment by ghost** [comment]
@furinvader 
Hi!
Thanks for your feedback! 
The show view needed some rebuilding of the directive anyways and after reading your comments I tried to put everything in the right place - thanks a lot for the hints! When I'm done with everything I'll come back to you with some questions about the unit tests.

Glad you  liked the code in general and that you took the time to review!

**Comment by lindenthal** [comment]
Hi @happschinson,

Can you pleae rebase this branch and update to the lastest version: In the current version a couple of things do not seem to work. I added this to the ToDo list in the description.

Thanks
Niels

**Comment by ulferts** [comment]
Closed in favor of #4155

**Pull request closed without merging**
