### PR TITLE
remove rmagick from .travis.yml

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-rmagick.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-rmagick.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
@myabc - Was there a reason we removed it in the first place?

**Comment by myabc** [comment]
@floriank there's no longer a RMagick group. See PR #998

**Comment by NobodysNightmare** [comment]
@floriank @myabc That means it is good to merge?

**Comment by NobodysNightmare** [comment]
@marutosi Except for you never providing a description, even if you have useful PRs...

**Comment by myabc** [comment]
@NobodysNightmare yep.

**Pull request merged**
