### PR TITLE
Feature/jquery ajax indicator

### PR DESCRIPTION
**Pull request by GarstgerUnhold**
As apparent from https://github.com/opf/openproject/pull/82, the old Prototype Ajax.Responders don't cut it anymore, e.g. they won't notice Ajax calls from a jquery transport. Because there is an ongoing, albeit slowish, switch to jquery, we'll need something more stable.
This attempts to capture the csrf-token fix of the old prototype implementation, too.

### CODE REVIEW

**Comment by nkenneweg** [comment]
@GarstgerUnhold Is there any ajax-request which relies on this feature? When you remove the old Prototype Code, is it possible that some old Prototype requests break?

**Comment by nkenneweg** [comment]
Is it necessary to remove the prototype code? can we not just keep it until we are sure that prototype is gone for good?

**Comment by GarstgerUnhold** [comment]
From what I've seen, the jQuery Ajax Code seems to work just fine with Prototype Requests, so having to maintain two versions seems odd to me. But reverting that last commit is not that big an impact, I guess.
On the first question: the stuff in https://github.com/opf/openproject/pull/82 does not work without this PR (i.e. the spinner won't show, it's not as dramatic as I made it sound), that's why I proposed it in the first place.

**Comment by nkenneweg** [comment]
Had to revert because it breaks code in the issues view.
In the issues view we still use the Prototype code to add Versions dynamically.

**Pull request merged**
