### PR TITLE
[21520] Unify distance to border in select2-choices

### PR DESCRIPTION
**Pull request by HDinger**
This unifies the distance to border and other elements in select2-choices.

https://community.openproject.org/work_packages/21520

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21520-unify-distance-to-border-select2-choices.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21520-unify-distance-to-border-select2-choices.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
**Before**

select2_false

**After**

select2_after

**Comment by NobodysNightmare** [comment]
Talking about unified distances:

Why did you choose a 5px horizontal margin and a 7px vetical margin? I'd have expected them to be the same ^^

However, a user study with two participants (my seat neighbours) showed that your version (5px/7px) is more appealing than mine (7px/7px)...

**Comment by NobodysNightmare** [comment]
LGTM, waiting for travis :horse:

**Pull request merged**
