### PR TITLE
Remove therubyracer dependency

### PR DESCRIPTION
**Pull request by myabc**
Node.js is now a requirement for asset pre-compilation.

### CODE REVIEW

**Comment by mfrister** [comment]
I'd really love to merge this PR, but you categorized it as a feature and we have stabilization phase.

I can't think of a reason why this would break things, but as this concerns deployments, middle of a stabilization phase might still be a bad time to merge this.

@myabc @cratz @kgalli Opinions?

**Comment by myabc** [comment]
@meeee the thorny issue of what's a `feature`. I agree that we shouldn't merge user-facing features in the stabilisation phase. However, this and #1821 are really cleanup of dead code and dependencies that I'd rather not see shipped in a release.

**Comment by myabc** [comment]
I'd also add that in the past I've had issues with outdated versions of this gem + newer compiler toolchains. If Ruby Racer makes it into the release, this is something we would have to support.

**Comment by mfrister** [comment]
@cratz seems to be ok with this:

> [01/09/14 15:25:02] Christian Ratz: im dev sollte das keine probleme machen

:+1:

**Comment by myabc** [comment]
Thanks! :dancer:

**Pull request merged**
