### PR TITLE
[21952] Fix invalid date when switching from phase to milestone

### PR DESCRIPTION
**Pull request by furinvader**
https://community.openproject.org/work_packages/21952/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://furinvader-bugs-21952-invalid-date-when-switching-types.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://furinvader-bugs-21952-invalid-date-when-switching-types.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@furinvader can you please rebase this one. The only reason for that is so that travis picks up this branch again.

**Comment by oliverguenther** [comment]
I've re-checked the bug locally on this branch and its fixed. Merge at will after rebase + travis :+1:

**Comment by oliverguenther** [comment]
Correctly sets the date:
1. From phase to milestone: Uses the date for start and end date
2. From milestone to phase: Uses the end data for date

**Pull request merged**
