### PR TITLE
Bug fixing, space creation 

### PR DESCRIPTION
**Pull request by CEEANPROJEC**

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @CEEANPROJEC, please don't create pull requests that have no further information. What do you want to achieve with this that eslint/rubocop does not offer already?

**Comment by CEEANPROJEC** [comment]
I sign contributor license agreement from a different email, I rectified that.is that what you mean Mr Guenther.

**Comment by oliverguenther** [comment]
@CEEANPROJEC you're adding a workflow to this project. What are you trying to do with it? We have linters and tests.

**Comment by CEEANPROJEC** [comment]
Ok sorry for that, I already signed CLA so do I qualify for merging ?.

**Comment by oliverguenther** [comment]
Please start out here:

https://www.openproject.org/docs/development/submit-feature-idea/
https://www.openproject.org/docs/development/report-a-bug/

Once you have a ticket in OpenProject that you'd like to work one, you can submit a pull request to work on it.

There's also a document on how to create a pull request, what it should contain, and how to get it reviewed by us:
https://www.openproject.org/docs/development/code-review-guidelines/#preparing-your-pull-request

Cheers
Oliver from OpenProject

**Pull request closed without merging**
