### PR TITLE
Rails4: Gemfile: awesome_nested_set: use gem

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-rails4-awesome-nested-set.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by ulferts** [comment]
Closing as this would update rails to 4.0.9 and according to travis, this does not work.

**Comment by marutosi** [comment]
> Closing as this would update rails to 4.0.9 and according to travis, this does not work.

Does Rails 4 branch work on travis???

**Comment by ulferts** [comment]
@marutosi not as far as I know

**Comment by marutosi** [comment]
> Closing as this would update rails to 4.0.9 and according to travis, this does not work.

Why do not you accept #1861 ?

**Pull request closed without merging**
