### PR TITLE
Angular 4 support and upgraded timeline header directive 

### PR DESCRIPTION
**Pull request by romanroe**

### CODE REVIEW

**Comment by romanroe** [comment]
@oliverguenther Please take a look. This PR contains the Angular4 integration and the first upgraded directive (timeline header).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/8bd5a95ddededeb71562fdb4850e3d2a3676986f) (deployed commit: 8e2dd5d654308fa98b57888dc4d1f66b26ea3b04).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/f1db0f40a2a8e36c542c831a1cbb57c2227901df) (deployed commit: 2ee6afcd8aba464a500d51170ff3987bade3940c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/ffd3403bcfda3e032318dc9a58f255f2ec8bfe8a) (deployed commit: 9db80c836363eff9d90f57b7160185d45d4bb62c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7420a1d7545f06d59739723fb0f3561ba6d4dad6) (deployed commit: 9db80c836363eff9d90f57b7160185d45d4bb62c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b7abbeabb03688f94ce965d877097769b09933bc) (deployed commit: 9db80c836363eff9d90f57b7160185d45d4bb62c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/3521d5ca8212a76b1527ef5b87c39f765876dbb2) (deployed commit: 9db80c836363eff9d90f57b7160185d45d4bb62c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/528b2da14feb319a725a5b6a6fd3a7b5ab913a6b) (deployed commit: 9db80c836363eff9d90f57b7160185d45d4bb62c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/8bd570bbc3eb7eeeb3ef2fc9adc6d0d9e9241f49) (deployed commit: a915ed4567ab178d7b32775a4cba911f6c815c42).

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
