### PR TITLE
[#52292] OpenProject behind prefix some assests still loaded from webroot

### PR DESCRIPTION
**Pull request by dominic-braeunlein**
https://community.openproject.org/work_packages/52292

Remove `/` from `frontend_asset_path` to allow for url prefix to take effect.

### CODE REVIEW

**Review by machisuji — CHANGES_REQUESTED** [review]
Thanks for the fix! Looks good to me. However, do you think we could add a spec for this?

**Comment by dominic-braeunlein** [comment]
@machisuji Good point. I will add a test

**Comment by ba1ash** [comment]
@machisuji have an extra look, pls.

**Review by machisuji — APPROVED** [review]
👍

**Pull request merged**
