### PR TITLE
Allow users to access the project site when they only allowed to access WorkPackages

### PR DESCRIPTION
**Pull request by klaustopher**
Fixes https://community.openproject.org/work_packages/51267

### CODE REVIEW

**Review by ulferts — CHANGES_REQUESTED** [review]
I believe the approach in here where the calling user would need to have all the permissions defined in the allowed lambda is too restrictive. Take the work_package_table widget for example. It requires having either the `save_queries` or `manage_public_queries` permission. There will be projects where few users have that, e.g. on community. But even without those permissions, the user are rightfully still allowed to see the work packages such widgets show as they have the `view_work_packages` permission. And if they don't then the widget will be empty so no information will leak. The same is true for the members widget. The `allowed` lambda was only meant to restrict the available widgets on administration. There, a user without the `save_queries` permission wouldn't be allowed to use the `work_packages_table` widget because the system would prevent the creation of a query which is necessary for the widget to work. But once the query is set up, the results of the query can be used by all users, each according to their permission sets. 

Removing all the widgets the user is not allowed to see will additionally pose a problem when two people with different permission sets administrate the same overview page. The person with fewer permissions will be tempted to fill the gaps not knowing that in fact there are no gaps which will lead to errors being reported the user cannot understand. 

But I might well miss information on the scenario where users with only shared work packages access the overview page. Why was it necessary to remove the widgets in this scenario?

**Comment by ulferts** [comment]
~~There might be a simpler solution rather then working within the overview page. A user with only shared work packages doesn't necessarily have to see the overview page at all. We could modify the~~ `OverviewsController` ~~to check whether the user is allowed to see the overview page. If not, we redirect the user to the first module the user is allowed to see.~~

Does not work because the information will still get out via the API.

**Comment by klaustopher** [comment]
I can remove it, no problem. The problem I saw was that the widgets Project Description, Project Status would leak information when being displayed to users who only have WP access. I will remove this. Maybe we can refactor the `allowed_to` to `allowed_to_add` or something, that makes the intention clearer

**Comment by klaustopher** [comment]
Removed the widget filtering. Thanks for helping me better understand what it's about :)

**Comment by ulferts** [comment]
> I can remove it, no problem. The problem I saw was that the widgets Project Description, Project Status would leak information when being displayed to users who only have WP access. I will remove this. Maybe we can refactor the `allowed_to` to `allowed_to_add` or something, that makes the intention clearer

Yes, in hindsight, using a different name would have been better. 

And you are right about the Project description and Project status. That information should not get out. The problem with you being right is that we need to filter that at a different layer, in the API response. And with that information being filtered out, the widgets will then no longer be able to show the information which is desired but the widgets are not set up to do it, yet.

I'll open a ticket to remove the information from the project resource.

**Comment by klaustopher** [comment]
Will take a look at this as well. Thanks for pointing out. Is this ok to merge then?

**Review by ulferts — APPROVED** [review]

**Pull request merged**
