### PR TITLE
[31698] Check if querySpace is initialized already to avoid reloading

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.com/wp/31698

### CODE REVIEW

**Review by HDinger — CHANGES_REQUESTED** [review]
When changing e.g. the type in full screen, and then going back, the table does not reload. Thus the changes are not displayed in the table.

**Comment by PLR143** [comment]
Hi dev's and folks,

I want to install for internal private usage a openproject installation. I have Centos 7 installed and I deactivated the firewall and SElinux. I created a new user with sudo privileges but I can't install OpenProject because of this error

DATABASE UNSUPPORTED ERROR

Database server is not PostgreSql. As OpenProject uses non standard ANSI-SQL for performance optimizations, using a different DBMS will break and is thus prevented.

Please help me

**Comment by oliverguenther** [comment]
Hi @PLR143 , I assume you were the one to also reach out via contact form. I have replied to you there. Please use our community forums for installation support: https://community.openproject.com/projects/openproject/forums/9

**Comment by oliverguenther** [comment]
Turns out we didnt get the latest version from cache ever to create the initial index from the `queries.results.elements`. I added this in the initial index building and that should be enough to always draw the freshest work packages

**Review by HDinger — APPROVED** [review]
👍

**Pull request merged**
