### PR TITLE
Invite user modal fixes

### PR DESCRIPTION
**Pull request by b12f**
- [x] Assignee -> Add user button in dropdown should not be green (use footer styles)
- [x] Buttons to the right inside the modal
- [x] Next button als highlight
- [x] Das X zum close ist gefühlt ist zu weit innen
- [x] Improve styles for validation error messages; smaller font, align spacings (especially principal type select)
- [x] `ng-select` `esc` click shouldn't close the modal
- [x] Fix mobile styles and scroll behaviour
- [x] Invitation message input should have larger height
- [x] Invitation message should show newlines in summary page
- [x] Learn more about roles and permissions -> large L
- [x] Review Invitation, Send Invitation -> small i
- [x] Invitation message should autofocus
- [x] With newly invited users, show the email address instead of the name on the success screen

To be done in a following PR:
- [ ] Project list should show the projects for which you have the `manage_members` right
- [ ] If opening the invite-user-modal, check whether you have rights to invite users to the project handed in, otherwise default to no project selected
https://community.openproject.org/projects/openproject/work_packages/35521/activity?query_id=2810

### CODE REVIEW

**Comment by wielinde** [comment]
@b12f Many things look so much better now, thanks. If you don't mind I keep adding stuff here

image
On mobile the "Change e-mail address or select an existing user" link has a weird position. The whole page is pretty much left aligned, but that link seems to have some padding/margin on the left. Also it seems that the two text lines a pretty close. However, that might be just an illusion.

**Comment by wielinde** [comment]
"learn more about..." link still has lowercase L although it is the beginning of a sentence
image

**Comment by wielinde** [comment]
@b12f Would it be possible to make the invitation message text area grow with the input so that a user does not have to scroll within the input field?

**Comment by wielinde** [comment]
@b12f I believe currently inviting a principal from within an assignee drop down does add but not select that invited principal directly in that drop down after closing the modal. Is that addressed somewhere else or shall this PR have a look at it?

**Comment by b12f** [comment]
Hi @wielinde I've adressed most of your comments except

> @b12f I believe currently inviting a principal from within an assignee drop down does add but not select that invited principal directly in that drop down after closing the modal. Is that addressed somewhere else or shall this PR have a look at it?

I'd like to adress this somewhere else so we can merge these fixes early. Mind reviewing the rest so this can get merged?

**Comment by wielinde** [comment]
Hey @b12f, Thank you for all these fixes. I didn't review the code. I clicked through the app instead (QA style).

Ich checked the list in this PR's description.

1. Hitting ESC in ng-select (projects drop down) still closes the whole modal.
2. The "Change e-mail address or select different user" still looks weird on mobile. It has a line break with the text centered. I'd say lets get rid of this clunky long button/link and use an X icon instead.
image
3. On mobile (tested Android Chrome) the modal is bigger than the viewport. The close/cancel X at the top and the Next button at the buttom are both half cut off.
image
4. On mobile (tested Android Chrome) selecting the user from the drop down is hardly possible as it opens to the top while seemingly having space towards the bottom.
image
5. **Probably the most important bug:** When I type an email address in the user drop down it always wants to invite the user even if there is already a user with that mail address. I checked the server responses for the type-ahead and the correct results are there. So it is a front end issue.
6. Repeating it here to simply not forget: The created user is not selected in the assignee drop down from which the modal was triggered

Please feel free treat each of the bullets in separate PRs and already merge what you have here.

**Comment by b12f** [comment]
> **Probably the most important bug:** When I type an email address in the user drop down it always wants to invite the user even if there is already a user with that mail address. I checked the server responses for the type-ahead and the correct results are there. So it is a front end issue.

This happens because I'm using the principals API to search. It only provides a filter by name, not email address or similar (Not sure where you checked the server responses, I'm seeing 0 results for `asdf@`, even though I have a user with `asdf@asdf.nl` as the email address locally.) The easy fix is to have a broader filter to apply on the principals search. Any ideas @ulferts ?

**Pull request merged**
