### PR TITLE
wrong bundler version

### PR DESCRIPTION
**Pull request by binb4sh**

### CODE REVIEW

**Comment by oliverguenther** [comment]
I think we would want  to have the latest bundler version installed. Is there a specific reason why you pin the version?

**Comment by binb4sh** [comment]
> I think we would want to have the latest bundler version installed. Is there a specific reason why you pin the version?

Because of the bundler version is specificed in the [Gemfile.lock](https://github.com/opf/openproject-ce/blob/stable/8/Gemfile.lock) file: 
```
  warden-basic_auth (~> 0.2.1)
  webmock (~> 3.1.0)
  will_paginate (~> 3.1.0)

RUBY VERSION
   ruby 2.5.1p57

BUNDLED WITH
   1.17.1
```

An error will occur if other bundler version installed.

**Comment by oliverguenther** [comment]
The `BUNDLED WITH` directive will be updated with the newest bundler version updating the lockfile. If the version does not match when installing, a warning is emitted. Are you sure it's not that warning you're seeing? I have not seen an error when bundling with a mismatching version.

**Comment by binb4sh** [comment]
I got this: 
`find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)`
the same problem like this:
https://stackoverflow.com/questions/54042692/rbenv-find-spec-for-exe-cant-find-gem-bundler-0-a-with-executable-bun/54049241

**Comment by oliverguenther** [comment]
We're currently bumping bundler to 2.0.1 so it is indeed correct to use that version. I have added that to the manual installation guide. That way we won't have to control the bundler version manually.
https://github.com/opf/openproject/commit/64d8bc4f48

Thanks for your input!

**Pull request closed without merging**
