### PR TITLE
[34591] Dynamic text matcher to output base URL for formattables

### PR DESCRIPTION
**Pull request by oliverguenther**
Allows to use `settingVariable:base_url` to output the formatted current base url. This helps when seeding data with values we don't yet know.

[OP#34591](https://community.openproject.org/wp/34591)

### CODE REVIEW

**Review by HDinger — COMMENTED** [review]
The emails are correctly shown, however in the administration it now looks like this:
Bildschirmfoto 2021-07-28 um 11 08 49

This certainly looks strange for normal users. Maybe we can display this as inline code so that it is clear that something is still happening with it. How do you think about that?

**Comment by oliverguenther** [comment]
> The emails are correctly shown, however in the administration it now looks like this:
> Bildschirmfoto 2021-07-28 um 11 08 49
> 
> This certainly looks strange for normal users. Maybe we can display this as inline code so that it is clear that something is still happening with it. How do you think about that?

That wouldn't really work as it meant reworking the way it renders as HTML. We could alter the format to something like ``{{opSetting:base_url}}` to make it clearer it's a variable? @machisuji What's your take on that?

**Comment by HDinger** [comment]
> That wouldn't really work as it meant reworking the way it renders as HTML. We could alter the format to something like ``{{opSetting:base_url}}` to make it clearer it's a variable? @machisuji What's your take on that?

Sounds good to me 👍

**Comment by machisuji** [comment]
> > The emails are correctly shown, however in the administration it now looks like this:
> > Bildschirmfoto 2021-07-28 um 11 08 49
> > This certainly looks strange for normal users. Maybe we can display this as inline code so that it is clear that something is still happening with it. How do you think about that?
> 
> That wouldn't really work as it meant reworking the way it renders as HTML. We could alter the format to something like ``{{opSetting:base_url}}` to make it clearer it's a variable? @machisuji What's your take on that?

I approve of this.

**Comment by oliverguenther** [comment]
Done. The syntax is different from the other macros which look like `workPackageValue:attribute` but I'm fine with adding this explicit template-syntax like style and maybe slowly moving to that style instead.

**Review by HDinger — APPROVED** [review]
Fine to merge from my side 👍

**Pull request merged**
