### PR TITLE
[21725] Cursor offset in input fields (IE)

### PR DESCRIPTION
**Pull request by HDinger**
This sets the line-height of input fields to 100% for a correct alignment of the text in IE.

https://community.openproject.org/work_packages/21725/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21725-cursor-offset-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21725-cursor-offset-ie.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
#### Before

cursor_wrong

#### After

curor_after

**Comment by mk84** [comment]
@HDinger please rebase your branch

**Comment by HDinger** [comment]
@mk84 done

**Pull request merged**
