### PR TITLE
[WIP] Allowed basic update of WP's custom fields

### PR DESCRIPTION
**Pull request by mtakac2**

### CODE REVIEW

**Comment by myabc** [comment]
There should be a test for this.

**Comment by mtakac2** [comment]
@myabc [WIP] - Work In Progress...

**Comment by myabc** [comment]
Rebased.

**Comment by ulferts** [comment]
@hschink please close this if you agree that this will no longer be required.

**Comment by myabc** [comment]
@ulferts we no longer need these commits.

**Pull request closed without merging**
