### PR TITLE
Bump `test-prof` to 1.3.0

### PR DESCRIPTION
**Pull request by aaron-contreras**
Test-prof's changelog: https://github.com/test-prof/test-prof/blob/master/CHANGELOG.md#130-2023-11-21

* Updates Gemfile version specifier to `~> 1.3.0`
* Runs `bundle update test-prof`

### CODE REVIEW

**Comment by aaron-contreras** [comment]
A flaky spec marked as pending was expected to fail but passed. This is being addressed in https://github.com/opf/openproject/pull/14304

**Comment by klaustopher** [comment]
@dependabot rebase

**Comment by aaron-contreras** [comment]
Fixed!

**Comment by ulferts** [comment]
👍

**Pull request merged**
