### PR TITLE
Spike/api hyperagent

### PR DESCRIPTION
**Pull request by manwithtwowatches**
https://www.openproject.org/work_packages/8326

Details pannel looks like crap but we are working on this in another branch which we need this for.

### CODE REVIEW

**Comment by manwithtwowatches** [comment]
@tilt @myabc  The only way I could think of to get around the problem with hyperagent.js not playing with jQuery compatibility mode was to fork it. This probably isn't an acceptable long term solution so ideas welcome.

**Comment by myabc** [comment]
@manwithtwowatches why did you close?

**Comment by manwithtwowatches** [comment]
@myabc because it was rebased onto dev when i had merged in Marek's branch that you unmerged, if you see what i mean. i want to rebase it again.

**Comment by myabc** [comment]
@manwithtwowatches ok understood.

**Pull request closed without merging**
