### PR TITLE
17552 Fix font rendering for Windows 7: remove Lato SVG variant, Chrome hacks.

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/8753
https://community.openproject.org/work_packages/17552

Reverts #1266, relates to #1174.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://hotfix-17129-chrome-font-rendering.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
This is mostly guesswork here, as I've not been able to reproduce the most serious issue on any Windows 7 box. On Chrome 39 (Windows 7), before and after:

before svg

after no svg

**Comment by ulferts** [comment]
It looks OK on my machine as well with the same limitation you have @myabc of not being able to reproduce the problem. I am wondering now, whether we should issue an unsupported browser warning if chrome is used with version < 37.

**Comment by xfalcox** [comment]
Guys I still have the problem 4.0.4 on Firefox 31.2.0 ESR on Windows 7 SP1.

Any idea?

open_project_font_bug

**Pull request merged**
