### PR TITLE
[52561] Fix user filter on activity page

### PR DESCRIPTION
**Pull request by cbliard**
https://community.openproject.org/wp/52561

### CODE REVIEW

**Comment by dombesz** [comment]
I'm not entirely sure if this is working as expected. I just changed the title of  a work package with a separate user and it shows up in my activity saying the project was changed.

image

If I go to the project's activities, I can see it was done by a different user.

image

**Comment by cbliard** [comment]
@dombesz I'm not sure that's another user: in the second screenshot, I can't find the same activity entry as in the first screenshot. The timestamp 10:22 AM is nowhere to be found.
I suspect this activity is a project activity. Can you display the project activity as in your second screenshot but checking the "project attributes" in the sidebar?
I did not manage to reproduce it on my end.

**Comment by dombesz** [comment]
Thanks @cbliard , you are correct. There was a change on the project by "OpenProject admin" that I retracted a bit later.

**Review by dombesz — APPROVED** [review]
Thanks @cbliard . LGTM!👍
Edit: I re-ran the CI, feel free to merge once it's green.

**Pull request merged**
