### PR TITLE
Bug/25378/subject and back button not aligned correctly

### PR DESCRIPTION
**Pull request by wielinde**
https://community.openproject.com/projects/openproject/work_packages/25378/activity

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/96f6b84156779da47021e937dfd3143fb5f4f5b5) (deployed commit: ef763f2cbe33952da221bfe59638cb09197f1d3d).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/628f1c1e6e31faa361f6699fedcdbe055a45b380) (deployed commit: f2cb81933682496df929cba9253ca064a1168c04).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/d31e277ab7f98ca5fd58c3eb5ad83111884f251e) (deployed commit: fd12570a8d72fcec8b25367758d7df95c07a0d7c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/137e30b46269b10b82a0246d5a2e35e197426215) (deployed commit: 3c3031e3c2612a4c8f7e7b180ff6cc0b5782cb88).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4b541b294059998d71e41a360e440a339b9d9938) (deployed commit: 226a8e6d52fe32e0c79b2ab11fd98364b73e6d95).

**Comment by oliverguenther** [comment]
You'll need to rebase this branch on release/7.0 to avoid the additional commits

**Pull request merged**
