### PR TITLE
[20170] order the options in the modal selects

### PR DESCRIPTION
**Pull request by floriank**
This will order the select options alphabetically, as requested in https://community.openproject.org/work_packages/20170.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-fix-20170-sorting-in-wp-list-menus.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-fix-20170-sorting-in-wp-list-menus.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@floriank looks good, but the spec failures look legit (whether an actual problem or only an outdated spec expectation I cannot say. The cuke failures should go away when rebasing/merging with current release/4.2 HEAD

**Comment by floriank** [comment]
rebased, let's see what travis has to say.

**Comment by floriank** [comment]
I am not sure what causes the spec fail actually as I cannot reproduce it locally.

**Comment by floriank** [comment]
@ulferts @NobodysNightmare @Azure7111 can one of you check if you can reproduce the travis errors locally?

**Comment by Azure7111** [comment]
I ran the failing test locally and it seems to be just fine

**Comment by floriank** [comment]
Okay, let me retry this ...

Edit: Wait: did it ran green or did it run "fine", i.e. reproducibly failing?

**Comment by floriank** [comment]
Okay, found the issue after some digging:
1. the window size used depends on the previous test
2. "Version" is one of the later items in the list of options
3. when a smaller window is used, the option is not visible and thereby not clickable
4. test fails on these premises

Note: the test will not fail when it is run standalone as the default window size for most of our workstations is still sufficient

Whomever merges this: I used the shared context i introduced in https://github.com/floriank/openproject/commit/8147a82a717ab937cd0e808f0fb504552c370334. this file has been moved on the `dev` branch, which will lead to a merge conflict when merging back to `dev`

**Comment by floriank** [comment]
This is getting out of hand.  (ノಠ益ಠ)ノ彡┻━┻

**Comment by ulferts** [comment]
@floriank I created a PR https://github.com/floriank/openproject/pull/3 to this branch that fixed the problems on my test runs. Please merge it - and if travis passes, feel free to merge this one as well.

**Pull request merged**
