### PR TITLE
Whitespace fixes throughout the application

### PR DESCRIPTION
**Pull request by myabc**
Removing tabs, trailing space and the like.

### CODE REVIEW

**Comment by marutosi** [comment]
> >    Stupid.
> >    Should not be in description.
> >    All deails should be in ticket and revisions.
> 
> even better! where are your tickets? i've never seen one, have a link?
> anyway, just pasting the summary of your pull request in the description field doesn't hurt, right?!

#1362
Where is ticket link?

**Comment by myabc** [comment]
@marutosi there is no ticket for this PR. I believe this is _self-documenting code_ :smile:

**Comment by cratz** [comment]
:heart:

**Comment by kgalli** [comment]
:+1:

**Pull request merged**
