### PR TITLE
[33203] Fix: pdf cut-off after first page

### PR DESCRIPTION
**Pull request by ingamai**
See ticket: https://community.openproject.com/projects/openproject/work_packages/33203

### CODE REVIEW

**Comment by ingamai** [comment]
@HDinger When the work packages list has nearly the same height as the page (but is slightly longer), it sometimes causes an empty page at the end. But I thought that this was not that problematic. 
But it took me quite a while to figure out why Firefox would only display the first page: Mainly the browser specific classes in the css file were placed on the html instead of the body where they are actually set. 
I tested this solution for Chrome, Firefox, Opera and Safari.

**Review by HDinger — CHANGES_REQUESTED** [review]
There are still some things that do not work correctly:

* Using the new (chromium-based) edge, there is still only one page displayed.

* In Chrome, the table does not span the complete width.
Bildschirmfoto 2020-05-29 um 10 03 44

* In Firefox, there is also only the first page of the WP full view printed. 

* In Firefox, there is still the button bar of the split screen printed below the table:
Bildschirmfoto 2020-05-29 um 10 01 47

In general I am wondering whether we still need some parts of the code, especially those already marked as Hack. I think it may be worth to check this, too.

**Comment by ulferts** [comment]
As the fix is now targeted for 10.6.1, please change the merge base to release/10.6, @ingamai.

**Comment by ingamai** [comment]
> There are still some things that do not work correctly:
> 
> * Using the new (chromium-based) edge, there is still only one page displayed.
> * In Chrome, the table does not span the complete width.
> 
> * In Firefox, there is also only the first page of the WP full view printed.
> * In Firefox, there is still the button bar of the split screen printed below the table:
> 
> In general I am wondering whether we still need some parts of the code, especially those already marked as Hack. I think it may be worth to check this, too.

@HDinger I could not reproduce the bug in the new edge browser. Maybe you only tried to print the first 20 entries? 
But I hope I could resolve the rest of the issues mentioned above and clean up the code a bit :)

**Review by HDinger — APPROVED** [review]

**Pull request merged**
