### PR TITLE
Technical Debt #23506: Improve code style in attachments directive/service

### PR DESCRIPTION
**Pull request by manuschiller**
[Technical Debt #23506: Improve code style in attachments directive/service](https://community.openproject.com/work_packages/23506/activity)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://manuschiller-23506.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://manuschiller-23506.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by manuschiller** [comment]
@romanroe 
POSITIVE: changes caused only minor problems so far. nothing unexpected.
wip

**Comment by manuschiller** [comment]
@romanroe 
POSITIVE: changes done. 
testing

**Comment by oliverguenther** [comment]
@manuschiller Are you still working on the TS warnings or is this ready?

**Comment by furinvader** [comment]
Hey guys,
as I have prepared a massive amount of changes in #4562 for the attachments feature related components, this PR has to be closed.

There I have refactored the code to an extent where you definitely will have conflicts, @manuschiller.

Please rebase to dev as soon as #4562 is merged.

**Pull request closed without merging**
