### PR TITLE
Add "WS" (Web Service) definition in setting descriptions

### PR DESCRIPTION
**Pull request by follower**
AFAICT there is nowhere that the "WS" abbreviation in the settings description is defined which makes it a very obtuse setting for an outsider evaluating repository support.

I only deduced that "WS" stands for "Web Service" from looking at http://www.redmine.org/projects/redmine/wiki/HowTo_Automate_repository_creation (assuming my assumptions are correct).

It might even be better to spell it out as "SOAP Web Service".

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://follower-patch-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://follower-patch-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
@follower , thanks for your contribution! 
I agree what 'WS' does not clarify the intent of this checkbox.
I don't think we need the abbreviation at all (nor note that the web service uses SOAP, for that matter).

What is your opinion of the following wording?

`Enable repository management web service`

**Comment by NobodysNightmare** [comment]
I agree with @oliverguenther. We do not need the abbreviation at all. I personally don't mind whether it is a "web service for x" or an "x web service".

**Comment by follower** [comment]
I think the "Enable repository management web service" wording is an improvement. It would probably still benefit from further explanation in the accompanying documentation though. e.g. something along the lines of "The repository management web service enables X, Y & Z by using FOO. You should enable this setting if you want to A, B, C."

**Comment by oliverguenther** [comment]
@follower Thanks again for your input. [I've opened another PR](https://github.com/opf/openproject/pull/3265) with the above wording and a very brief introduction on what the web service actually does.

**Comment by follower** [comment]
:+1:

**Pull request closed without merging**
