### PR TITLE
Feature/angular calendar

### PR DESCRIPTION
**Pull request by ulferts**
Reworks the calendars view to reuse most of the work package table functionality but replacing the table with a calendars component.

[ng-fullcalendar](https://www.npmjs.com/package/ng-fullcalendar) is used for the calendar which is a wrapper around [FullCalendar](https://fullcalendar.io/).

The functionality should be identical to the existing calendars view with the exception of adding the capability to display individual weeks. Additionally it will look way nicer and more modern.

image

### ToDo

- [x] Tooltip on hover
- [x] Linking work packages (move to wp on click)
- [x] Handle having too many results
- [x] Setting locale 
- [x] Setting week start date
- [x] Detect weeks in url in case of reloading

### WorkPackage

https://community.openproject.com/wp/28931

### CODE REVIEW

**Comment by oliverguenther** [comment]
Mostly LGTM, but I found the following two issues:

1.  There is a border around the query results due to border added to `.ui-...`

bildschirmfoto 2018-11-05 um 18 16 45


2. The tooltip on calendar entries is not cleared when double clicking and moving to the work package view.
bildschirmfoto 2018-11-05 um 18 17 57

**Comment by jonathansn** [comment]
When is this feature available?

**Comment by ulferts** [comment]
@jonathansn we plan to merge it into dev shortly which would have it released as part of 8.2. I added a work package in community so that the progress can be tracked more easily.

We don't have a release date for 8.2 yet but it shouldn't be too long away. The [list of topics open for the release](https://community.openproject.com/projects/openproject/work_packages?query_id=1283) is not very long.

**Comment by ulferts** [comment]
I addressed the bugs you mentioned @oliverguenther and merged dev so that the pull should be good now. 

It would be nice of you to squash the commits upon merging.

**Pull request merged**
