### PR TITLE
introduce request_store to ensure that the current user doesn't leak acr...

### PR DESCRIPTION
**Pull request by marutosi**
...oss request boundaries (#16685)

Contributed by Holger Just.

git-svn-id: http://svn.redmine.org/redmine/trunk@13110 e93f8b46-1217-0410-a6f0-8f06a7374b81

### CODE REVIEW

**Comment by linki** [comment]
would you care finding out what causes the cukes to fail?

**Comment by marutosi** [comment]
I don't know.

**Comment by linki** [comment]
it seems to be a problem with the selenium based cukes running in a separate thread as RequestStore uses a thread local variable internally.

@marutosi any chance you want to take another swing at this?

**Comment by machisuji** [comment]
@marutosi Isn't the only relevant commit here [6434f6d](https://github.com/marutosi/openproject/commit/6434f6d7ac415eb1d69d4310862de720cd432a90)?

**Comment by marutosi** [comment]
Sorry, your project is not thread free.

**Comment by linki** [comment]
correct, it has at least one.

**Comment by linki** [comment]
@marutosi, what do you mean with your explanation?

I think, even in a single-threaded setup the vulnerability of leaking the value of `User.current` into the next request exists. Redmine is not thread-safe either (I assume you meant that by "thread free") and there you applied the fix.

**Comment by marutosi** [comment]
http://www.redmine.org/issues/12097

**Comment by linki** [comment]
sure, but what about http://www.redmine.org/issues/16685?

quoting Holger:

> there were several issues where the User.current was not properly initialized and thus the setting from the request before it was used
> 
> This ensures that the current user always needs to be set explicitly and can't be taken from previous requests

still applies, doesn't it?

**Comment by marutosi** [comment]
No.

**Comment by linki** [comment]
and why is that? (hint: "it's obvious" is not a valid answer)

**Comment by marutosi** [comment]
http://www.redmine.org/projects/redmine/repository/revisions/10911

**Comment by linki** [comment]
try again

**Pull request closed without merging**
