### PR TITLE
Fix (re-enable) autoprefixing with autoprefixer-rails

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/19015
https://community.openproject.org/work_packages/19047
https://community.openproject.org/work_packages/18754

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-fix-reenable-autoprefixer-rails.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-fix-reenable-autoprefixer-rails.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
https://twitter.com/jonleighton/status/179542450547851265

> How to disable ExecJS in production: upgrade to 1.3.0 and set ENV['EXECJS_RUNTIME'] = 'Disabled' before Bundler.require

@kgalli is it possible for us to set `ENV['EXECJS_RUNTIME'] = 'Disabled'`? we could also create our own `OPENPROJECT_`configuration option, but this would be more work: currently `configuration.rb` is loaded after `Bundler.require`.

**Comment by kgalli** [comment]
@myabc I think that could be used as work around. However this should't be our final solution. I hope someday we can get rid of the `autoprefixer-rails` gem. So this is temporary right?

**Comment by myabc** [comment]
@kgalli that's the plan, but I don't have an ETA for that (see WP [18328](https://community.openproject.org/work_packages/18328#note-5))

**Comment by myabc** [comment]
@ulferts any thoughts?

**Comment by myabc** [comment]
@kgalli @ulferts The first part of the alternate solution is now implemented as #2698. The second part would be making `rake assets:precompile` invoke the relevant gulp task and a reasonable amount of work to ensure plugins/themes work correctly. Let's discuss the right approach on Monday.

**Comment by ulferts** [comment]
@kgalli this is pending your clearance. Please write a short note once you consider this mergeable.

**Comment by kgalli** [comment]
@ulferts Feel free to merge this PR.

**Pull request merged**
