### PR TITLE
[24174] Filter work packages by datetime and datetime range

### PR DESCRIPTION
**Pull request by silkentrance**
Filter by datetime and datetime range.

https://community.openproject.com/work_packages/24174

See also previous PRs under #5071, #5128

### CODE REVIEW

**Comment by silkentrance** [comment]
@ulferts as you requested

**Comment by ulferts** [comment]
@silkentrance there seems to be some misunderstanding, what I requested is having a PR consisting of only the Date filters. The DateTime filters should be placed in a different PR. At least based on the naming of the commits, that would mean having  8c1631f in one PR and 50c3344
in a different one.

**Comment by ulferts** [comment]
@silkentrance sorry, my bad. I now understand the PR structure. Thanks a lot.

**Comment by ulferts** [comment]
@silkentrance I have taken another look at the functionality. IMO, the following has to happen:

* Filter by DateTime (UTC) instead of Date in the DB
* Calculate the UTC DateTime out of the Date in the front end, when
  * Filtering
  * Saving the query
* When loading a saved query, calculate the localized DateTime out of the saved UTC DateTime and present it to the user
  * As we have a Date representing a DateTime (or actually a DateTime interval) we need to notify the user that while the software is presenting a Date, that Date can be different than what the user might think it is. E.g. User A created the filter in Asia. Now when User B loads the filter in the Americas, the system should show that difference in order to clarify why work packages from two days are presented. @lindenthal proposed displaying the time zone the filter was created in to the filter configuration. We could for example append it to the values input. Because I want to avoid having to store the time zone explicitly, I would welcome if we would be able to deduce the time zone out of the value.     
* Because the "updated on" filter does only work on the work_packages table, it is currently not possible to filter for work packages that have been updated in a given time interval, we should rename the filter to "last updated on".

**Comment by silkentrance** [comment]
@ulferts ATM this is implemented as follows

- The filtering in the DB uses the Datetime object from the filter which has the timezone of the user attached who created / updated the filter and then that localized datetime object is transformed to the server's configured timezone, whether this is UTC or a different timezone
- In the frontend, and since we currently do not know the server's timezone, from the date a datetime object will be calculated, with the timezone of the user, which is then passed to the server
- On loading such a filter, the original timezone information from the user who created that filter or updated it, will be present, from which then the datetime object will be transformed to the current user's configured timezone, or UTC, if no such timezone is configured
- This already works, I have tried loading and updating filters from different timezones, the results had been satisfying

What would work is

- in the frontend, calculate the UTC datetime and pass this to the server instead of passing a datetime object with the timezone of the current user
- on the server, and since we must not assume that it always uses UTC for storing the datetime objects, that UTC date needs to be transformed to the server's local timezone upon query

**Comment by silkentrance** [comment]
@ulferts Purporting the timezone information is what is currently implemented, which gets lost if we store only the UTC datetime information, which of course has ZULU as its timezone, or +0:00.

In addition, one cannot know which geographical location that timezone is associated with, it is just numbers, e.g. +10:00 and so on, unless we use the formatting additions. See http://momentjs.com/timezone/docs/#/using-timezones/formatting/ for more information.

I would consider this an extension to the filter, say in addition to the UTC datetime we will store the extended timezone information, e.g.

```
filterData = [
  {datetime: ..., timezone: 'Europe/Berlin'},
  {datetime: ..., timezone: 'America/New York'}
]
```

and for users having no timezone configured, this will then be just 'UTC'.


I'd propose a change to ConfigurationService along that way, which will return 'UTC' on timezone() if no timezone is configured, otherwise the configured timezone. That way we could eliminate isTimezoneSet() and simplify the code here and there.

**Comment by silkentrance** [comment]
@ulferts I just found that in query-filters.directive.html it was still using transform-date-value instead of transform-date-utc="begin-of-day" for the =d operator. I think that this caused the problem you have been talking about. Let's see...

**Comment by silkentrance** [comment]
@ulferts as for the datetime picker, I noticed that there is an accessible version of the jQueryUI Datepicker: https://hanshillen.github.io/jqtest/#goto_datepicker and there is also http://www.jqueryscript.net/demo/Customizable-jQuery-Timepicker-Plugin-timepicker/ which supports the datepair plugin that in turn allows pairing of date/time pickers for selecting ranges. The latter is also accessible by means of keyboard navigation. For screen readers this might need some additional work...

**Comment by oliverguenther** [comment]
Superseded by https://github.com/opf/openproject/pull/5320

**Pull request closed without merging**
