### PR TITLE
feature #25069 Add button with settings in work package create form

### PR DESCRIPTION
**Pull request by wielinde**
https://community.openproject.com/projects/openproject/work_packages/25069

### CODE REVIEW

**Comment by oliverguenther** [comment]
If you're in global create and selected a project where you have the appropriate permissions, the drop-down remains empty.

**Review by oliverguenther — CHANGES_REQUESTED** [review]
If you're in the global create and select a project for the new work package, the dropdown remains empty even though it is now basically in a project context.

**Comment by wielinde** [comment]
@oliverguenther Well, I probably understood you wrong and skipped that. Now I added the links for the global WP creation, too.

**Comment by oliverguenther** [comment]
LGTM now, thanks! 👍

**Review by oliverguenther — APPROVED** [review]

**Pull request merged**
