### PR TITLE
updated library AngularJS to 1.5.3

### PR DESCRIPTION
**Pull request by romanroe**
https://community.openproject.com/work_packages/21758

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://romanroe-angular15.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://romanroe-angular15.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Had a peek at the errors introduced by the bump. It seems that Prototype.js, which is still used in some legacy parts of the application ( 😞  ) overrides `Function.prototype.bind` which is incompatible with some calls of Angular and breaks immediately.

**Comment by romanroe** [comment]
You beat me to it :-) I was going to write exactly the same....

Changing the loading order of Prototype<->Angular _could_ help. How can I change the order?

**Comment by oliverguenther** [comment]
I tried that (Should suffice to switch the `bundles` include around in `app/assets/application.js.erb`, but get the same error.

**Comment by oliverguenther** [comment]
Closing since this depends on prototype, and the contents of the PR are rather small, I'll reopen this when it's ready.

**Pull request closed without merging**
