### PR TITLE
Set moment locale globally

### PR DESCRIPTION
**Pull request by b12f**
This sets the moment locale to the application locale globally, ensuring that moment uses the right translation strings
wherever applicable. However, since we only work with languages (en), and not real locales (en-US), the first day of
year calculation has to default to some option. This commit defaults to ISO 8601 for every language and locale.

Closes https://community.openproject.org/projects/openproject/work_packages/36346/activity

### CODE REVIEW

**Comment by RobinWagner** [comment]
Hi @b12f,
Thank you for addressing this bug.
We have quite a few customers/users in the US. This change would likely mean that for them the displayed calendar week would not be correct anymore, right? (Since their definition for the first week of the year is different.)

**Comment by b12f** [comment]
@RobinWagner I'm actually unsure which way around it is currently (e.g. if `en` currently defaults to US or GB), but yes, this defaults to GB/EU standards.

**Comment by oliverguenther** [comment]
As right now we don't differentiate between `en-US` and `en-GB` locales mainly due to the translations not being enabled for either specific language, we can't pass the desired locale to the frontend. It shouldn't be too much effort to add both specific languages though. As an alternative, I'd suggest adding a setting similar to start of day  under display settings, where we also allow overriding some locale specific settings (date format , time format, start day of week)

**Comment by b12f** [comment]
I guess it would be a bigger fix at that point, going towards the direction of https://community.openproject.org/projects/openproject/work_packages/35664/activity

Just adding en-US and en-GB and just passing the same translation files for now could be an option, but it's probably better to have two different settings; language and locale.

Alternatively of course, exposing all these options (start of week, start of year, date format, etc.) directly to the user is an option, but I think we'd get overwhelmed by the specifics of it very quickly.

**Comment by oliverguenther** [comment]
I added a commit to expose the first week of year computation. There appear to be only two relevant values in all of moment.js locales: Either the first Monday (US, arabic) or Thursday (ISO/EU) in the year is used. As we already have the date of week property, we can then compute the moment.js `doy` value.

**Comment by oliverguenther** [comment]
This needs a backend review now, any takers @opf/backend ?

**Pull request merged**
