### PR TITLE
[OPF#1063] Feature/rails3 add time helper (for impermanent memberships)

### PR DESCRIPTION
**Pull request by sschu**
OpenProject Issue: https://www.openproject.org/issues/1063
Also adds step to set pagination for cukes

### CODE REVIEW

**Comment by mfrister** [comment]
I'd like to have a unit test for the format_time_as_date helper.

**Comment by sschu** [comment]
Unit test added...

**Comment by mfrister** [comment]
Thanks for the spec :)

The changelog entry is missing ;)

While you're at it, I'd also love some documentation for the `format_time_as_date` helper. Just a few lines that describe what the function does, as it's not immediately clear to me why it deals with certain time objects like it does. I can see it from the tests, but I shouldn't need to read them to understand what the function does.

Looks good otherwise :+1:

**Comment by sschu** [comment]
Documentation and changelog entry added...

**Pull request merged**
