### PR TITLE
remove vendored select2 in favor of select2-rails gem

### PR DESCRIPTION
**Pull request by GarstgerUnhold**

### CODE REVIEW

**Comment by GarstgerUnhold** [comment]
If you experience problems (other than stuff related to asset pipeline or select2-rails specifics) https://github.com/opf/openproject/pull/61 is probably a better place to adress them.

**Comment by nkenneweg** [comment]
This breaks nearly every select2, making the width of the selection part 0.

**Comment by nkenneweg** [comment]
I fixed the gem on a version smaller than 3.3.2. because 3.4 breaks our code.

**Comment by nkenneweg** [comment]
@GarstgerUnhold Merge at will.

**Comment by ulferts** [comment]
I reverted the merge as it broke the application heavily. Not yet sure about the reason but there are a lot of gem updates in Gemfile.lock which are unrelated to select2.

**Pull request merged**
