### PR TITLE
[chore] maintained status collection api specification

### PR DESCRIPTION
**Pull request by sbu-WBT**
In the same style as #14379

### CODE REVIEW

**Review by machisuji — CHANGES_REQUESTED** [review]
@sbu-WBT Thanks for the PR! Looks good. There is just one thing missing (which is why `scripts/api/validate_spec` is failing) and that is the reference to the status collection in `docs/api/apiv3/openapi-spec.yml` which has to be added under `components.examples` like this:

```
StatusCollection:
  $ref: './components/examples/status_collection.yml'
```

Could you please add that?

**Comment by Kharonus** [comment]
Looks very good, thanks for adopting the styles!

as @machisuji says, the reference in the root file for the example is missing, after adding that, CI should be green.

If you are interested in running this check locally, the script is located at `./script/api/validate_spec`. You'll need `node` runtime for it.

**Review by machisuji — CHANGES_REQUESTED** [review]
@sbu-WBT This fails validation as follows.

```
[1] tmp/oas-generated.yml:22711:13 at #/components/schemas/StatusCollectionModel/allOf/1/properties/_links/self

Property `self` is not expected here.

Did you mean:
  - allOf
  - oneOf
  - if
  - else
  - xml

2270[9](https://github.com/opf/openproject/actions/runs/7183511033/job/19563444506?pr=14388#step:5:10) | properties:
227[10](https://github.com/opf/openproject/actions/runs/7183511033/job/19563444506?pr=14388#step:5:11) |   _links:
227[11](https://github.com/opf/openproject/actions/runs/7183511033/job/19563444506?pr=14388#step:5:12) |     self:
227[12](https://github.com/opf/openproject/actions/runs/7183511033/job/19563444506?pr=14388#step:5:13) |       allOf:
227[13](https://github.com/opf/openproject/actions/runs/7183511033/job/19563444506?pr=14388#step:5:14) |       - "$ref": "#/components/schemas/Link"
```

Could you please look into that? You can run `scripts/api/validate_spec` to see errors locally.

Also if you want this change to be released sooner than later, please make sure to base it on `release/13.1` and not `dev`. Currently it's the latter, so please rebase it onto the former. I can then change the target branch for the PR to `release/13.1`.

**Comment by sbu-WBT** [comment]
It should be fixed!

The thing with running the script I don't want to install ruby just to run this one script

**Comment by Kharonus** [comment]
Ahoi @sbu-WBT , happy new year to you!

After christmas and new years break I can continue to attend your PR.

I can understand that you want to keep your system clear of dependencies you do not need.

If you have docker, we also provide a `docker-compose.yml`, which you can use to run

```shell
docker compose run --rm backend sh -c './script/api/validate_spec'
```

this should work without ever setting up the database and the whole stack.

**Comment by Kharonus** [comment]
Ah, me thinks, the CI is failing, because there was a bump of the ruby version in the meantime (from 3.2.1 to 3.2.2). Can you rebase your branch on the current dev?

**Comment by sbu-WBT** [comment]
> Ahoi @sbu-WBT , happy new year to you!
> 
> After christmas and new years break I can continue to attend your PR.
> 
> I can understand that you want to keep your system clear of dependencies you do not need.
> 
> If you have docker, we also provide a `docker-compose.yml`, which you can use to run
> 
> ```shell
> docker compose run --rm backend sh -c './script/api/validate_spec'
> ```
> 
> this should work without ever setting up the database and the whole stack.

I tried it and this came out:

```
time="2024-01-03T10:41:05+01:00" level=warning msg="The \"DEV_GID\" variable is not set. Defaulting to a blank string."
time="2024-01-03T10:41:05+01:00" level=warning msg="The \"DEV_UID\" variable is not set. Defaulting to a blank string."
time="2024-01-03T10:41:05+01:00" level=warning msg="The \"DEV_UID\" variable is not set. Defaulting to a blank string."
time="2024-01-03T10:41:05+01:00" level=warning msg="The \"DEV_GID\" variable is not set. Defaulting to a blank string."
invalid interpolation format for x-op-backend.environment.LOCAL_DEV_CHECK.
You may need to escape any $ with another $.
required variable LOCAL_DEV_CHECK is missing a value: The docker-compose file for OpenProject has moved to https://github.com/opf/openproject-deploy
```

**Comment by Kharonus** [comment]
Alright, CI run is green.

If you are nevertheless interested in running the script validation locally, you can basically go through a shortened version of our [docker dev setup](https://www.openproject.org/docs/development/development-environment-docker/#quickstart).

```shell
git clone https://github.com/opf/openproject.git
cd openproject
cp .env.example .env

# and directly run the validation script, without further setup
docker compose run --rm backend sh -c './script/api/validate_spec'
```

The important difference is, that the executing shell will now halt due to the npm package `@redocly/openapi-cli` not being installed (it usually is part of the `package.json` of the backend container). This can be solved by simply putting a `y` for "yes" into the shell and hitting enter, which will interactively install that package globally into the running container (and of course will be gone once the container is removed).

You should see now a script validation, even though your docker dev environment is not fully setup.

**Pull request merged**
