### PR TITLE
[WIP][FIX] MySQL data migration

### PR DESCRIPTION
**Pull request by hschink**
Implemented to accomplish [ticket 2644](https://www.openproject.org/work_packages/2644) (OPF)

Fixes collation error for `custom_values` table

### CODE REVIEW

**Comment by mfrister** [comment]
I'd still love to know why we need this exactly on these tables but nowhere else. Any ideas?

**Comment by hschink** [comment]
I have no explanation for this at the moment, sorry.

**Comment by mfrister** [comment]
I'm not comfortable with merging this as long as we don't know why we need this. I actually think I shouldn't have merged the first PR modifying a table collation.

**Comment by sschu** [comment]
It looks like this is only necessary on a development machine but it works without it in tests. Therefore, we are going to leave it here for now in case we need it. We should close it when it is no longer necessary.

**Comment by hschink** [comment]
I close this PR as the issue is documented in [comment 15 of ticket 2644](https://www.openproject.org/work_packages/2644#note-15).

**Comment by mfrister** [comment]
@hschink What do you think about removing the rake task you wrote earlier for a similar problem we can't reproduce on a production machine?

**Comment by hschink** [comment]
@meeee good point: I guess I just remove it from the dev branch?

**Comment by mfrister** [comment]
Yep

**Pull request closed without merging**
