### PR TITLE
recovery new lines of md

### PR DESCRIPTION
**Pull request by marutosi**
https://github.com/opf/openproject/pull/3108

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-1-new-line-upgrade-guide.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-1-new-line-upgrade-guide.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by marutosi** [comment]
What is status?

**Comment by floriank** [comment]
I am afraid, we cannot merge this, as the documents within `./doc/` are synched to `openproject.org` (e.g. [here](https://www.openproject.org/open-source/manual-installation/manual-installation-op-4-1/)), where the markdown is rendered via a separate Markdown processor, which introduces paragraphs for line breaks.

While I appreciate the cleanup, this would probably break the website at the moment, which we cannot really do (and there is no quick workaround from the website's side)

@ulferts @NobodysNightmare thoughts? I have talked to @MayaBerd about this and this might not be a good idea to merge.

**Comment by NobodysNightmare** [comment]
@floriank I think it is not line breaks that separate paragraphs, but empty lines, using the rich diff of GitHub you can see the effective changes of this PR quite well. Regarding the usefulness of this PR: I can't really tell.

IDC much about the line length of the markdown, as long as it is a reasonable value (something above 100 characters). The layout of the rendered markdown is pretty much a matter of taste, too...

**Comment by floriank** [comment]
Well, according to @MayaBerd the commits that this PR reverts were specifically introduced to prevent rendering problems of the markdown in the OpenProject.org context.

**Comment by NobodysNightmare** [comment]
Did not realize that those were reverts...

I'd close this PR then based upon your explanation.

**Pull request closed without merging**
