### PR TITLE
Always hide main menu on mobiles on page load

### PR DESCRIPTION
**Pull request by wielinde**
https://community.openproject.com/projects/openproject/work_packages/25496/activity

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/9b51eb725ae70d7176c880bed6d05450483bc714) (deployed commit: 6c4b0dbaae3060af7a2589dd3a0b5da7f3234318).

**Comment by RobinWagner** [comment]
Hi @wielinde,

hiding the side menu works properly 👍 
I noticed a couple of smaller bugs - most of which however already occur on the current release branch:

- Scrollbar shown in side menu (already exists on release)
bug_1-scrollbar

- Work package page does not use entire height of the page (already exists on release):
bug_2-work-package-page

- Side menu is briefly expanded when activating / deactivating a module (this is new but certainly an edge case):
bug_3-side-menu-expand

- On MS Edge there are two scrollbars shown when the content height is bigger than the page height:
bug_4-scrollbar-activity-edge

**Comment by wielinde** [comment]
@RobinWagner Oops, I think I either forgot to rebase this branch to the latest branch or I reached out to you before merging the new flex-based layout. However, you did not get the latest core code together with the changes of this PR.

So from all the (valid!) issues that you reported, none is introduced by this PR. Maybe the jumping of the main menu toggle after module activation/deactivation, right?

**Comment by wielinde** [comment]
The jumping of the toggle comes due to the fact that the menu get's hidden after the everything is loaded and the JS gets executed. It is not optimal but that solution was quick and thus cheap.

**Pull request merged**
