### PR TITLE
Feature/21754 log time for other users

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.org/wp/21754

Continued from https://github.com/opf/openproject/pull/10879

### CODE REVIEW

**Comment by oliverguenther** [comment]
> AWS Error: Sorry, there is not enough capacity to fulfill your instance request. Please reduce the number of instances in your request, or wait for additional capacity to become available. You can also try launching an instance by selecting a smaller Lightsail plan (which you can resize at a later stage).

@lindenthal Pullpreview fails to start because no spot instance could be reserved. Maybe we can do the same as on the github runners @crohr to fall back to smaller instances?

**Review by HDinger — CHANGES_REQUESTED** [review]
Regarding the specification from the ticket, I found some issues:

- [x] The permissions are not correctly named. "Log time for other users" is wrong, as well "Log own time". I don't know about the other ones, but I would have expected them to be named similarly ("Edit own time", "Edit time for other users" etc)
Bildschirmfoto 2022-07-21 um 08 07 32

- [x] The primary button should be on the right side
Bildschirmfoto 2022-07-21 um 08 12 07

- [x] I have a user with the following permissions. Although I should only be able to log time for myself, I am still able to select another user in the modal. The whole "User" field should not be visible to me.
Bildschirmfoto 2022-07-21 um 08 17 39

- [ ] Low priority: When I need to invite another person first, the spent time modal is closed after the invitation process. Ideally, I could invite someone and directly continue to log time for him/her.

- [x] When I am on the cost reports page, and press the edit icon of an entry, the modal opens correctly. However, all user fields are opened automatically. (The same happens when editing an entry via the MyPage)
Bildschirmfoto 2022-07-21 um 08 24 13

- [ ] When editing an entry from the cost reports table, the buttons are in the wrong order, and the "Delete" button should be removed
Bildschirmfoto 2022-07-21 um 08 25 52 **asked in ticket for confirmation**

- [x] I don't know of that is intended behaviour or not: When I edit a time entry, that someone else originally logged, the "logged_by" column is not updated. It still shows the original creator of the time entry.

- [x] A user who is a member of the project, but cannot be set as assignee, is not found when trying to log time for him/her. I still think that this is not correct. In the ticket it is written "there is a new select field called “User", with autocomplete, showing all project members"

**Comment by oliverguenther** [comment]
>  Low priority: When I need to invite another person first, the spent time modal is closed after the invitation process. Ideally, I could invite someone and directly continue to log time for him/her.

I noticed this as well. The reason this happens is that the modal gets replaced. For that to work we'd need stackable modals

**Comment by oliverguenther** [comment]
>  I don't know of that is intended behaviour or not: When I edit a time entry, that someone else originally logged, the "logged_by" column is not updated. It still shows the original creator of the time entry.

Yes that should be changed. I updated it so that it will always reflecting the user updating the time entry

**Comment by psatyal** [comment]
Hi @HDinger and @oliverguenther, 

Just tested the pullpreview by creating a new user (role: Member) and logging time for him as an Admin. I found some issues:

- [x] The labels of the buttons should be "Save" (vs "Create") and Cancel.
- [x] The two buttons should not have icons. 

Button labels and icon wrong

- [ ] When I access the Cost report page as admin, I don't see the edit and delete buttons for the time I just logged for user "Félix Forestier" (despite admin having the right "Edit time logs for other users" enabled, see screenshot).

No edit and delete icons

The admin does have the right to edit others' times

Cheers, 
Parimal

**Review by HDinger — COMMENTED** [review]
The changes were looking good so far 👍 

I guess that the issue of the missing icons Parimal mentioned is more a UX issue which existed before as you probably have to scroll to see them. I am currently checking with @psatyal whether that assumption is true.

So there is only the issues about the buttons left to do.

**Comment by psatyal** [comment]
Hi @HDinger, I can confirm that the buttons in the cost report are indeed there but were out of view (scroll right). Like Henriette mentioned, this is a problem out of scope of the PR. I suppose we could make the units and costs column narrower as a temp fix.

Do let me know when I can do a pull preview to review the buttons again. Thank you!

**Comment by oliverguenther** [comment]
@psatyal Thanks for the quick feedback, I believe I addressed your remarks

**Review by HDinger — APPROVED** [review]

**Pull request merged**
