### PR TITLE
[32457]Wrong display of work package widgets on project overview

### PR DESCRIPTION
**Pull request by bsatarnejad**
There should not be decimal numbers in axes.

https://community.openproject.com/projects/openproject/work_packages/32457/activity

### CODE REVIEW

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/de3da86ee25e163453d118786d540789829334e2/frontend/src/app/modules/work-package-graphs/embedded/wp-embedded-graph.component.ts#L17">frontend/src/app/modules/work-package-graphs/embedded/wp-embedded-graph.component.ts#L17</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ulferts — CHANGES_REQUESTED** [review]
Successfully forces the ticks to start at 0 but this leads to having the values with a decimal point displayed as 0:
image.

As the code is basically the same as above I do not know why it (probably) used before but now leads to the '0' values being displayed. The 'horizontalBar' type suffers from the same problem so it would be a good idea to fix this as well.

I played around with the code and altering the return value from `0` to `undefined` [removes the ticks we do not want to display altogether](https://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats) but requires updating the charting libraries (`ng2-charts`, `chart.js` and `@types/chart.js` in frontend/package.json) as Typescript balks otherwise.

Because the new code is very close to the one above, it makes sense to extract the code into a method.

@bsatarnejad, let me know if you want to do this in a joined session.

**Comment by bsatarnejad** [comment]
@ulferts Hi, Thanks for your comment. callback function returned only numbers before but now null or undefined is also acceptable. I create a separate method to set the axes of charts as you told, i think it now works. But i do not know how to update the charting libraries, is it necessary now?

**Comment by ulferts** [comment]
@bsatarnejad it is necessary as TypeScript will report a type error otherwise. That is why the tests went red on Travis.

The updating of the npm packages can be done by updating the version numbers in https://github.com/opf/openproject/blob/dev/frontend/package.json. The npm platform provides a means to find out the latest version (e.g. `2.9.20` for `@types/chart.js` - see https://www.npmjs.com/package/@types/chart.js). Let me know if that is enough of a pointer for you. If not, we can also do it together.

**Comment by ulferts** [comment]
Switched the base branch because of the package update as discussed with @bsatarnejad .

**Review by ulferts — APPROVED** [review]
Looks very good now @bsatarnejad, thanks.

**Comment by bsatarnejad** [comment]
@ulferts thank you, i did not understand why build fail happened again in second stage and also could not solve it.

**Pull request merged**
