### PR TITLE
[21998] Style new member screen

### PR DESCRIPTION
**Pull request by mk84**
https://community.openproject.org/work_packages/21998/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mk84-21998-style-new-member-screen.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mk84-21998-style-new-member-screen.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by mk84** [comment]
##### Before

member_before

##### After

member_after

---

##### In accessibility mode:

##### Before

member_impaired_before

##### After

member_impaired_after

**Comment by mk84** [comment]
As discussed with Niels, we use now a standard selectfield for roles.

bildschirmfoto 2015-11-12 um 10 42 55

**Comment by oliverguenther** [comment]
@mk84 I've taken care of the specs. Feature-wise, this looks good to me. Will merge after travis.

**Pull request merged**
