### PR TITLE
[32924]Remove horizontal line in several modules above buttons

### PR DESCRIPTION
**Pull request by bsatarnejad**
Remove additional horizontal line above buttons in news and forum module. I look for more same problems, i did not find more.

### CODE REVIEW

**Comment by bsatarnejad** [comment]
https://community.openproject.com/projects/openproject/work_packages/32924/activity

**Review by HDinger — COMMENTED** [review]
Hi @bsatarnejad 

Looks good overall. I found additional place where the line should be removed: project settings --> Work package categories --> + Category. Please have a look at the attached screenshot: 

Bildschirmfoto 2020-04-27 um 13 48 31

**Review by HDinger — APPROVED** [review]
Great 👍 Could you please change the target of this PR to "release/10.5" and rebase your branch accordingly? Afterwards, it is good to merge.

**Comment by HDinger** [comment]
Manually cherry-picked to release branch.

**Pull request closed without merging**
