### PR TITLE
[33936] Problem with watchers 

### PR DESCRIPTION
**Pull request by bsatarnejad**
Change how watchers data is returned to front-end, blocked users are not returned.

https://community.openproject.com/projects/openproject/work_packages/33936/activity

### CODE REVIEW

**Comment by bsatarnejad** [comment]
Hi @ulferts . Do you think the first error in Travis is related to what we changed? I tested it several times, each time, i have a different result.
I test the second one, it is green in local.

**Comment by ulferts** [comment]
Those tests are infamously flickering in the 10.6 branch. When cherry-picking your commit to dev, the specs are both stable.

**Comment by ulferts** [comment]
I removed the embedded watchers from the work package representer in https://github.com/opf/openproject/pull/8566

**Review by ulferts — APPROVED** [review]
👍

**Pull request merged**
