### PR TITLE
update Rails to 4.0.13

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-patch-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-patch-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
This currently fails across the board and would need fixing @marutosi .

**Comment by marutosi** [comment]
Are you kidding?

**Comment by NobodysNightmare** [comment]
I don't even know why you would want to merge something into one of **our** feature branches.

I am not sure of this one, but if I had to guess I would say @myabc was _spiking_ on a migration to rails 4.

As your PR does neither target dev nor any of our backport branches I am closing it.

P.S.: I think @floriank was not kidding and simply not noticing that you did a PR against an unstable feature branch...

**Comment by floriank** [comment]
@NobodysNightmare @marutosi Indeed. I did overlook it.

**Pull request closed without merging**
