### PR TITLE
type editable

### PR DESCRIPTION
**Pull request by 0xF013**
https://community.openproject.org/work_packages/16933

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://0xf013-feature-type-editable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://0xf013-feature-type-editable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
Looking good functional wise.

I see some issues on the visual side, which we should probably address in a follow-up PR. For all visual hints also see: http://clients.zzmedia.net/openproject/change-type/
- when an error is visible, the label should be centered vertically with regards to its edit field, not with regards to the edit field + the error
- error messages should be red (apparently with red font... please check [contrast/accessibility](http://leaverou.github.io/contrast-ratio/#%23cb403b-on-%23fedada) before really doing this)
- error messages should have an error icon

@0xF013 Shall we address those issues in a separate PR?

edit:
I moved all issues out into separate Bugs:
- https://community.openproject.org/work_packages/19680
- https://community.openproject.org/work_packages/19681

**Comment by 0xF013** [comment]
@NobodysNightmare I suspect those better be in a separate *epic* regarding styling the whole overview tab anew.

**Comment by 0xF013** [comment]
@NobodysNightmare in other words, I don't wanna do it

**Comment by NobodysNightmare** [comment]
~~When there are multiple required custom fields that need attention, you are focussing the last one.~~

~~Wouldn't it be more better to focus the first field that needs attention first? How is the order determines?~~

~~In other words: I'd rather like to tab forwards than backwards...~~

~~Is there anything accessibility says about that our does that not matter?~~

edit: talked to robin, the order is probably not important...

**Comment by 0xF013** [comment]
@NobodysNightmare the order is a side-effect of queueing the focusing using $timeout, that adds the focusing task in a queue, so the order is top to bottom. Accessibility doesn't care about that, but simple logic applies here indeed. I would rather do it when there is  a recorded bug since I imagine this is not going to be a major usecase.

**Comment by NobodysNightmare** [comment]
I C

**Comment by NobodysNightmare** [comment]
I have mixed feelings about boolean custom fields ([when they work](https://community.openproject.org/work_packages/19601)):

When I change to a type that has a required boolean CF, it is not saved and I am told to chose for that field. That is good.

But it feels wrong that I have to check it and uncheck it again, to be able to submit. On the other hand automatically setting it to false also seems wrong.

@0xF013 @myabc @floriank Any clever thoughts? I will probably merge anyway...

**Comment by NobodysNightmare** [comment]
waiting for travis.

But LGTM :+1:

**Pull request merged**
