### PR TITLE
[19559] Fixed vertical alignment of progress bar

### PR DESCRIPTION
**Pull request by HDinger**
Corrects the vertical alignment of the progress bar in the workpackage table.
https://community.openproject.org/work_packages/19559

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-19559-percentage-workpackagetable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-19559-percentage-workpackagetable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
:+1: 

@myabc @ulferts  I am not quite sure if the negative margin is the way to go - for me, this works in our supported browsers, so this might be okay.

**Comment by myabc** [comment]
@floriank I think it's ok. Table paddings, and text line-heights should be revisited by whoever takes over #2832.

**Comment by floriank** [comment]
@myabc - I'll probably will do this in the future, although we have to reprioritze the styling

**Pull request merged**
