### PR TITLE
make sure postgres is started

### PR DESCRIPTION
**Pull request by joshk**
it looks like the Docker workers have a small postgres bug, we are looking into it, this should fix it for now

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://joshk-patch-1.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by marutosi** [comment]
https://github.com/travis-ci/travis-ci/issues/2606

**Comment by myabc** [comment]
@joshk hey, thanks for looking into this! I'll probably squash this down, if you don't mind.

**Comment by joshk** [comment]
Tbh, not sure if this is actually needed. I found an issue with the worker which caused issues with services starting.

This should be humming away nicely now.

**Comment by myabc** [comment]
@joshk ok, will close for now. cheers!

**Pull request closed without merging**
