### PR TITLE
Add coveralls (coverage web service)

### PR DESCRIPTION
**Pull request by marutosi**
See: https://www.chiliproject.org/issues/1264

### CODE REVIEW

**Comment by tessi** [comment]
I really like the idea to add coveralls to our setup. I've already added  the coveralls hook for opf/openproject .

As far as I can tell, you have added coveralls support for unit tests only. We have rspec and cucumber tests, too. Is it possible to integrate them all?

**Comment by marutosi** [comment]
I don't know.

**Comment by linki** [comment]
"Any type of Ruby project or test framework supported by SimpleCov is supported by the Coveralls gem. This includes all your favorites, like RSpec, Cucumber, and Test::Unit."

https://coveralls.io/docs/ruby

**Comment by tessi** [comment]
See #151 

I cherry-picked @marutosi's commit and refactored until all tests were covered. I'll close this issue, as the code from this PR was merged into #151.

**Pull request closed without merging**
