### PR TITLE
19670 Style buttons (new flat L&F)

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/19670

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-19670-button-flat-l-f-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-19670-button-flat-l-f-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
From a code perspective, this looks okay and causes no major problems as far as I can tell.

Two points:
- I personally dislike the look and feel of the new buttons (the colour as well as the zoom effect of the icon)
- I think this should not go in before [the plugins are updated](https://community.openproject.org/work_packages/19675)

First point is irrelevant and just personal opinion, second point could be somewhat relevant

**Comment by floriank** [comment]
It was decided that this can be merged w/o the plugins.

However, there are two issues with some themes (which should probably be addressed there):
- The `green` should fall back to the magenta, which is also used for highlights

screenshot from 2015-04-28 17 53 36
- The highlighted color on hover currently falls back to blue 

crop

This can be addressed in a separate WP for the respective theme, so I think, this is good to merge :+1:

**Comment by myabc** [comment]
@floriank adding two variables in the MyProject theme – `$primary-color-dark` and `$success-color` –should do the trick:

``` sass
$primary-color-dark: darken($primary-color, 10%) // or some other value
$success-color: $primary-color
```

**Comment by floriank** [comment]
Thanks, i will create a PR for it!

**Pull request merged**
