### PR TITLE
updated generated plugin and docs

### PR DESCRIPTION
**Pull request by machisuji**
WP [#24528](https://community.openproject.com/projects/openproject/work_packages/24528/activity)

Updated the templates to generate a working (empty) plugin.

### CODE REVIEW

**Comment by machisuji** [comment]
I'm also working on an [example plugin](https://github.com/opf/openproject-proto_plugin) (WIP) that does include basic things (a controller, `en.yml`, `routes.rb`, uses hooks etc.). I wonder if we should make the template for the generated plugin include that stuff or if we should keep it as a separate plugin on github und reference it in the docs.

Any opinions on that @oliverguenther @ulferts ?

**Comment by machisuji** [comment]
@oliverguenther Also can you please have a look at the frontend section of the [documentation](https://github.com/opf/openproject/blob/70018d197bc2913ab87ae4086a37c50032141058/doc/development/create-openproject-plugin.md) on how to create a plugin? I think it's a good idea to include frontend stuff in the proto plugin too.

**Comment by oliverguenther** [comment]
> @oliverguenther Also can you please have a look at the frontend section of the documentation on how to create a plugin? I think it's a good idea to include frontend stuff in the proto plugin too.

Done

**Comment by oliverguenther** [comment]
I like the separate plugin example and think we should keep the generator simple. You could drop in the proto plugin and adjust it to your needs.

**Pull request merged**
