### PR TITLE
[25999] Make timeline labels configurable

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.com/wp/25999

**TODOS**

- [x] Columns are used to identify valid columns, we need to reject the relations columns from that set.
- [x] Add empty option.
- [x] Special treatment for milestones

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b6890c0575f087f9ff486047677a492b66c1c104) (deployed commit: 93dfd39b6318770c223942cb7116dd120f28656b).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/d37086228e440ee892c930b244f41eb71b258105) (deployed commit: 93dfd39b6318770c223942cb7116dd120f28656b).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/a4ae433e31acf8eeadb88418d43d87d8780ae96d) (deployed commit: 63f9103047657fe6acca13cdb7d693c67f0b3460).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/634ad32e029076abd2b516cf78d2a97834635ce8) (deployed commit: e6521768ded438f2a25e6c67e544c604fdf2e971).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/734a02a5b8141346e573ac4cebf2cdc1ff49b247) (deployed commit: ed1a0c87de46b917c43c465ab7313c7aaa76afdc).

**Comment by lindenthal** [comment]
Hi Oliver,

I like it a lot. 

I just added a reminder to have a look at milestones. I guess they need some special treatment.

image

Best
Niels

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/9a70fb36bfb02c401a90f53ee29ac58b710d466d) (deployed commit: 2aecba00f6d942e027e93bdbd7adbeb4596e92c3).

**Comment by lindenthal** [comment]
@oliverguenther the tooltip for the start date on the left is not aligned to the tooltip for the due date (FF and Chrome). Can you pleae have a look at this?
grafik

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/ec4963813224fcf6f1dc20c8de57eae1501de513) (deployed commit: fa5aa036503abf8d6853f8c3e737f6b553408a23).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/83cf8a1a543309274f732c89de8cff659b3b238c) (deployed commit: fa5aa036503abf8d6853f8c3e737f6b553408a23).

**Review by machisuji — COMMENTED** [review]
Code looks good as far as I can tell. Works too. With one caveat which I will address in a separate comment.

**Comment by machisuji** [comment]
screen shot 2017-08-25 at 13 26 36

Here I hovered over the 2nd work package after doing an update (to the first one). Usually the row should be highlighted with a blue background and the left/right labels should disappear with only the dates being shown. As you can see here, after an update the old labels remain and there is no blue highlight.

**Comment by oliverguenther** [comment]
The issue has already been resolved on dev https://github.com/opf/openproject/commit/48a44978392f498bfd42ada8a3ea7d8d44475dd0  and is just not merged into this branch.

**Pull request merged**
