### PR TITLE
Fix missing link on single cards

### PR DESCRIPTION
**Pull request by oliverguenther**
Work Package cards have a link to their ID to the full view, which was
handled by ui-router srefs. This was replaced in https://github.com/opf/openproject/pull/8544,
leaving the link without href to use with modifiers.

This PR restores the functionality of using modifiers to copy the
link/open in a new tab

### CODE REVIEW

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/c8563eda210c8aca6b88fe6b49a7e3d66e52ec08/frontend/src/app/modules/a11y/accessible-click.directive.spec.ts#L34">frontend/src/app/modules/a11y/accessible-click.directive.spec.ts#L34</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by b12f — APPROVED** [review]
LGTM, though I'm unsure if `SkipModifiers` as a bool is a nice API for the directive; perhaps being able to set the specific modifiers being skipped/selected would be better (like modifiers in vue). Something like `[accessibleClickSkipModifiers]="['ctrl', 'alt', ...]"

Long term I'd like us to think about removing the accessible click directive, and solving this with browser native tools like `[tabindex]`, `label`, `button`, and `a`.

**Comment by oliverguenther** [comment]
Thanks Ben for your remarks. 🙇 

> LGTM, though I'm unsure if SkipModifiers as a bool is a nice API for the directive; perhaps being able to set the specific 
modifiers being skipped/selected would be better (like modifiers in vue). Something like `[accessibleClickSkipModifiers]="['ctrl', 'alt', ...]"

I agree with your sentiment, but I'd rather not make the API more complex if there are no consumers. If we find that modifiers need to be toggable (which I don't see right now), we can refactor it into your suggestion.

> Long term I'd like us to think about removing the accessible click directive, and solving this with browser native tools like [tabindex], label, button, and a.

Fully agree. That's also a nicely isolated thing to refactor, which can be mapped one at a time.

**Comment by oliverguenther** [comment]
Interesting, I just tested how `a` without hrefs, but with `role=button` + `tabindex` would behave. It does not capture space and enter in the same fashion that buttons do: 

https://stackblitz.com/edit/js-wak89c?file=index.html

So if we cannot use a button for whatever reason, that directive will still have its place imho.

**Comment by b12f** [comment]
There's a reason spaces and buttons behave differently w/r/t space and enter, so I think we are currently breaking default behaviour instead of improving it.

**Comment by b12f** [comment]
However, I'd have to read up on that a bit more

**Pull request merged**
