### PR TITLE
Remove explicit statement of implicit getter

### PR DESCRIPTION
**Pull request by Azure7111**
An addition to #2794 
https://community.openproject.org/work_packages/18712

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://azure7111-fix-make-done-ratio-disappear.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://azure7111-fix-make-done-ratio-disappear.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by Azure7111** [comment]
@myabc Does this meet you expectation?

**Comment by myabc** [comment]
@Azure7111 ja

**Comment by myabc** [comment]
@Azure7111 cuke failures are not related to this PR, rather to Travis caching wrong dependencies.

**Pull request merged**
