### PR TITLE
remove branches from .travis.yml

### PR DESCRIPTION
**Pull request by marutosi**
It is too hard to run travis on forked branches.
It disturbs pull request process.

### CODE REVIEW

**Comment by mfrister** [comment]
Thanks for your pull request!

What exactly is the effect of removing the branch specification? We want Travis to only build feature branches once there is a pull request, since we don't have enough concurrent workers to continuously build them.

What's your goal? You have a branch with another name than feature/rails3 you want to test on Travis?

**Comment by marutosi** [comment]
> What's your goal? You have a branch with another name than feature/rails3 you want to test on Travis?

Yes.

**Comment by tessi** [comment]
I understand that we only have 5 (or so) concurrent travis workers, which might slow down our pull request testing, if we test too many things (=branches) at once.

On the other side. That's what Travis is for - test everything. I'd opt for accepting this PR - we might revert this PR if it causes too many problems (i doubt it). We might also talk to the Travis guys about adding another bunch of workers.

**Comment by linki** [comment]
prior to and during the rails 3 update the core tests for the old core (which is still the master branch) failed. the decision to only test the feature/rails3 branch comes from that time in order to make the travis build green. i don't know what the status of master is today, but probably the same!? it might be better to delay this PR until we finally merge feature/rails3 with master. any timeframe on that, btw?

**Comment by tessi** [comment]
I think travis still fails on `master`. However `feature/rails3` is our main branch now (so we probably still get a green batch in the README :)) and activity on `master` is low/non-existent anyways.

**Comment by tessi** [comment]
as there were merge conflicts, I cherry-picked your commit.

Thanks @marutosi !

**Pull request closed without merging**
