### PR TITLE
[chore] Update to OpenAPIv3.1

### PR DESCRIPTION
**Pull request by Kharonus**
- updated spec version
- removed unused models
- reduced warnings to <50

### CODE REVIEW

**Review by as-op — APPROVED** [review]
👍 Works fine with the websites OpenAPI rendering templates. All needed small changes e.g. for the attributes will be done in the website repo.

**Review by ulferts — CHANGES_REQUESTED** [review]
Not all of the deleted components/schemas file are empty, e.g.:
* docs/api/apiv3/components/schemas/time_entry_activity_model.yml
* docs/api/apiv3/components/schemas/customaction_model.yml
* docs/api/apiv3/components/schemas/form_model.yml

Please double check that the deletion is intended, @Kharonus.

**Comment by Kharonus** [comment]
They are not empty, but they were unused. I didn't scan for empty, but for unused schemas.

**Comment by Kharonus** [comment]
@ulferts Fixed
- time entry
- time entry activity
- custom action

schemas left to fix:
- grids 
- group
- help text
- membership
- notification setting 

schemas left to ignore (?):
- form

As discussed, I'd rather not put more changes into this single PR.
Should be solved in https://community.openproject.org/work_packages/48966

**Review by ulferts — APPROVED** [review]
Thanks a ton @Kharonus 🙇

**Pull request merged**
