### PR TITLE
Removes migrations in favor of their aggregation.

### PR DESCRIPTION
**Pull request by apfelfabrik**
Removes migrations that are included in ChiliProject 2.4.0 and replaces
them by a new, aggregated migrations migration. This migration checks
for all the previous ones and continues w/ either of the following:

 (1) No migrations that this migration aggregates have already been
     applied. In this case, run the aggregated migration.

 (2) All migrations that this migration aggregates have already
     been applied. In this case, remove the information about those
     migrations from the @@schema_migrations table and we're done.

 (3) Only a part of the migrations that this migration aggregates have
     already been applied. In this case, fail miserably.

### CODE REVIEW

**Comment by apfelfabrik** [comment]
Works on my machine :+1:

**Comment by apfelfabrik** [comment]
Works on my machine, again! :+1:

**Comment by apfelfabrik** [comment]
Rebased once more! :+1:

**Comment by sschu** [comment]
What can possibly go wrong?

**Pull request merged**
