### PR TITLE
[31480] Text tables in widgets cannot be scrolled 

### PR DESCRIPTION
**Pull request by HDinger**
Allow inner scrolling on project description widget

https://community.openproject.com/projects/openproject/work_packages/31480/activity

### CODE REVIEW

**Comment by ulferts** [comment]
This does not address the same shortcoming in the custom text and the project status widget, @HDinger. In both, I expect tables or larger images to be quite common.

**Comment by HDinger** [comment]
In custom text and the project status widgets, there are no tables allowed. Images are only allowed in custom text widgets. I can add the class there, too. I'm a bit conservative because I don't want long words to lead to a scroll bar.

**Comment by ulferts** [comment]
> In custom text and the project status widgets, there are no tables allowed

Guess we should tell that to the code :smile:

image

But seriously, having a table in the project status and the custom text makes a lot of sense IMO so we should rather enable it.

**Comment by HDinger** [comment]
> Guess we should tell that to the code 😄

Haha, okay convinced 😂 I'll add the classes.

**Comment by ulferts** [comment]
But admittedly, @HDinger, the edit abilities differ between rails and angular currently. I'd suggest:
* No tables in custom fields
* tables in custom text
* tables in project status
* tables in project description

Opinions?

**Comment by HDinger** [comment]
> * No tables in custom fields
> * tables in custom text
> * tables in project status
> * tables in project description
> 
> Opinions?

I'm not sure if anyone needs a table in the project description or status, but it probably won't hurt. So it's okay for me.

**Comment by ulferts** [comment]
We then need to harmonize the two edit possibilities but that is outside of the scope of this PR. I'll open up a wp.

**Pull request merged**
