### PR TITLE
Main menu with submodule navigation

### PR DESCRIPTION
**Pull request by wielinde**
https://community.openproject.com/wp/26824

- [ ] The arrow is shown delayed
- [ ] Change width of sidebar by drag and drop

### CODE REVIEW

**Comment by HDinger** [comment]
@wielinde I had a short click-through with this and found a few issues:

* When the Wiki Title is quite long it is not truncated 
bildschirmfoto 2018-04-06 um 13 21 57

* When I click on repository (which has a child element and thus an arrow, too) I get the following. Please note that I am on the repository page, but the element is not on the second level hierarchy. I am not sure whether this has something to do with the error I get. Can you have a look at your local machine?
bildschirmfoto 2018-04-06 um 13 43 49

* When I go back to the first level hierarchy I would like to highlight the section I am coming from. So for example when I have been on the "All open WP" page and navigate back, the "Work Package" item shall be highlighted. This s probably not so important for the standard user, but we need it for the accessibility mode. Thus blind users know where they are without having to know the content.

Some more Accessibility issues:

* The arrows need a more specific label. The first one does not have one at all, and the other one is name "up". I guess "back" is better here. The forward button should have something like "_Modulename_: more", "go to submenu of _Modulname_" or something similar.
* When you go back (by keyboard) the focus is lost
* When you select an entry (e.g "all open") by keyboard the focus is lost.
* When you go forward the focus is on the first element, which is correct. However the back arrow is only reachable by tabbing one step back. This is not intuitive for blind users. The best behavior would be that the focus is on the first element, you can tab through all elements and after the last one the focus goes to the back arrow.

**Comment by lindenthal** [comment]
Hi @wielinde,

I just had a look at Henriette‘s remarks. I think we should drop the feature of custom wiki menu items. One feature less that can break.

@all: any thoughts on this?

Best
Niels

**Comment by HDinger** [comment]
I would not remove the custom menu items because of several issues:

* Removing it will not remove the problem I mentioned above. Overflowing text can also happen with WP queries. 
* The custom menu items are commonly used for better structuring of the wiki and will probably be missed.
* There would still be modules that have two hierarchy levels (e.g. WP). So it would not reduce the layout structure of the sidebar. Since this is somehow independent of the sidebar, we should think separately about it. I would however not remove it in the scope of this change.

Nevertheless I have no clue about the implantation difficulties with these extra items. When it is really complicated to add them to the navigation, we should make the decision beforehand to avoid doubled work.  (@wielinde ?)

**Comment by lindenthal** [comment]
> Removing it will not remove the problem I mentioned above. Overflowing text can also happen with WP queries .

OK

> The custom menu items are commonly used for better structuring of the wiki and will probably be missed.

> There would still be modules that have two hierarchy levels (e.g. WP). So it would not reduce the layout structure of the sidebar. Since this is somehow independent of the sidebar, we should think separately about it. I would however not remove it in the scope of this change.

Also for the work packages module all the menu items will be removed from the first level. In the second level we will consolidate this menu with the dropdown above the table.

I am fine to address this in a separate PR.

**Comment by wielinde** [comment]
I just pushed my latest changes in which I addressed:

- Cutting off long names with dots (ellipsis)
- Show menu toggle only on hover so that it does not reach into the content

**Comment by oliverguenther** [comment]
> The custom menu items are commonly used for better structuring of the wiki and will probably be missed.

Fully agree on this one. It's particularly often used at MyProject with the user guide and more.

**Pull request closed without merging**
