### PR TITLE
[18330] Refactor, simplify heading styles

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/18330
- https://community.openproject.org/work_packages/19402
- https://community.openproject.org/work_packages/19398
- https://community.openproject.org/work_packages/19397
- https://community.openproject.org/work_packages/19394
- https://community.openproject.org/work_packages/19393
- https://community.openproject.org/work_packages/19391

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-18330-typography-heading-styles.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-18330-typography-heading-styles.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
Same reason as: https://github.com/opf/openproject/pull/2832#issuecomment-97355274

**Comment by floriank** [comment]
This will be on hold for now - refactoring will be moved to `4.2` - i opened #3000 to deal with the aligning of the headings

**Comment by myabc** [comment]
https://community.openproject.org/work_packages/19402
https://community.openproject.org/work_packages/19398
https://community.openproject.org/work_packages/19397
https://community.openproject.org/work_packages/19394
https://community.openproject.org/work_packages/19393
https://community.openproject.org/work_packages/19391

**Pull request closed without merging**
