### PR TITLE
update coderay version

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-dev-coderay.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-dev-coderay.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@marutosi If you're going to update the dependency, you should also re-generate the stylesheet provided by CodeRay. See commit 5106aa7fd.

**Comment by marutosi** [comment]
http://www.redmine.org/issues/7495

**Comment by myabc** [comment]
@marutosi that doesn't address my comment.

**Comment by marutosi** [comment]
Why?

**Comment by NobodysNightmare** [comment]
Also: Why are you using different versions of coderay for `release/4.0` (1.0.9) and `dev` (1.1.0)? (You made two PRs)

**Comment by myabc** [comment]
@marutosi 

> Why?

https://github.com/opf/openproject/pull/2496#issuecomment-72732684

**Comment by marutosi** [comment]
> Also: Why are you using different versions of coderay for release/4.0 (1.0.9) and dev (1.1.0)? (You made two PRs)

http://semver.org/

**Pull request closed without merging**
