### PR TITLE
[#57052] Add optimistic locking to oauth_client_tokens

### PR DESCRIPTION
**Pull request by ba1ash**
# What are you trying to accomplish?

I try to prevent race condition on `oauth_client_token` updates. This race condition can lead to an inconsistent state when OP has already dead refresh_token which NC does not accept. Then user has to go through OAuth grant flow again. 

# What approach did you choose and why?

I enable optimistic locking for `oauth_client_tokens`. It prevents a race condition for update and destroy calls. `ActiveRecord::StaleObjectError` is raised then. The exception is caught and retry happens once. 
https://api.rubyonrails.org/v7.1.3.4/classes/ActiveRecord/Locking/Optimistic.html
image

# Ticket

https://community.openproject.org/wp/57052
# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

### CODE REVIEW

**Review by mereghost — APPROVED** [review]
LGTM!

Raising the error for now is good enough. This will allow us to double check if that's the main source of the problem and then address it for next release.

**Comment by wielinde** [comment]
Meeeeh, what shall a user do then? That problem is not created by the user. Can't be solved by the user. And it is fixable by us. We serve the users. Let's fix it for the users. And yes, it takes longer to build.

**Comment by ba1ash** [comment]
> Meeeeh, what shall a user do then? That problem is not created by the user. Can't be solved by the user. And it is fixable by us. We serve the users. Let's fix it for the users. And yes, it takes longer to build.

Sure, let's do it.

**Comment by mereghost** [comment]
> Meeeeh, what shall a user do then? That problem is not created by the user. Can't be solved by the user. And it is fixable by us. We serve the users. Let's fix it for the users. And yes, it takes longer to build.

Sure, my point was: we aren't even sure that this is the root cause right now. We might be fixing a straw man.

Ideally we could deploy this fix on a live, heavily used system like community as a step to diagnose the issue, while not being part of the release.

**Pull request merged**
