### PR TITLE
[20259] Styling enhancements in history section of details pane

### PR DESCRIPTION
**Pull request by campreb**
- Made 'Latest Activity' title use attribute group header
- Made 'Latest Activity' list use same classes as in 'Activity' pane
- Removed redundant stylesheet

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://campreb-feature-20259-styling-enhancements.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://campreb-feature-20259-styling-enhancements.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
I restarted the build.

**Comment by floriank** [comment]
There seems to be something wrong with the imports here, as the builds are actually broken,

**Comment by floriank** [comment]
You forgot to remove the import in `app/assets/stylesheets/default.css.sass:75` :wink:

**Comment by campreb** [comment]
😞oops, that was a bit embarrassing

**Comment by floriank** [comment]
no problem - i was just wondering why i could not start `gulp dev` and why the test suites were all failing.

**Pull request merged**
