### PR TITLE
Feature/share shown in all projects

### PR DESCRIPTION
**Pull request by manwithtwowatches**
https://www.openproject.org/work_packages/8227

Adding the shown_in_all_projects property to query was necessary because previously a query was visible in all projects if its project was set to nil. This worked ok when we have a separate save view for the query but it doesn't work anymore because the retrieve_query method assigns the currently scoped project to the query. The result is that it wasn't possible anymore to know if a query in fact had a nil project anymore.

An alternative would have been to change retrieve_query so that it didn't scope the query and then take care of the scoping in the front end but this would have broken a shitload of other stuff that uses retrieve_query and i didn't fancy fixing all the test etc.

Ultimately it's not that important because Marek is going to re-write all the query logic at some point soon.

### CODE REVIEW

**Comment by myabc** [comment]
@tilt thoughts on this?

**Comment by tilt** [comment]
@manwithtwowatches Sorry to ask again, but did we create the use case to have a query belonging to a project, which should on the other hand be visible everywhere? The original modeling I think was "query belongs to a project" if and only if "query is visible throughout all projects". Has this become an obstacle by sth we did?

**Comment by manwithtwowatches** [comment]
@tilt No we haven't created a new use case, it's just that the way it was implemented has become awkward now that we are using a single page app.

Maybe we should check with Robin because the more I think about it the less sense it makes. What I thought it meant was that you have "Page visible for others" which means it will always appear in the global queries section of the query select and will be scoped to whatever project the user is looking at. Then you have "Query is visible in all projects" which means that it doesn't get scoped to a particular project.

This doesn't make much sense now that I think about it. Would make more sense if global queries were not scoped to a project and "visible in all" meant that it always appeared as a custom query but was scoped to whatever project you're looking at. I'm going to ask Robin:>

**Comment by tilt** [comment]
I'm trying to understand this: So "global" / "custom" means "visible to all users" vs "private" and "visible in all projects" means what it says? The latter currently being modeled by the query having no project reference vs having one?

**Comment by manwithtwowatches** [comment]
I think so. The problem I encountered is that modelling the latter by having no project reference no longer makes sense on a single page app because the query gets scoped when it is loaded by the retrieve_query method so then you can no longer determine if it has a project reference or not.

**Comment by tilt** [comment]
And if we forward the project_id with the query params?

**Comment by manwithtwowatches** [comment]
Yes the other solution would be to not scope the query in the backend and then do the scoping in frontend, however i was reluctant to do this because retrieve_query is used in other places (i'm thinking plugins etc.) and i didn't want to rock the boat too much.

**Comment by tilt** [comment]
Yeah sound right but dangerous to change `retrieve_query` - if you want me to merge this or sth else tell me and I'll take a closer look

**Comment by manwithtwowatches** [comment]
I'll merge, and I also want to speak to Robin first because I have lost confidence somewhat.

**Comment by manwithtwowatches** [comment]
Robin Wagner: Hi Richard,
I think the option "Page visible for others" has already been implemented (should make pages / queries to global queries and allow other users to see them).
The option "Show in all projects" is basically the same option that already exists in openproject.org (there it's called "For all projects").
The precise behavior is probably easiest to find in the code but it basically allows queries / pages to be displayed in all projects.
[09:05:17] Robin Wagner: And the third option "Show page in menu" should allow to add a page / query to the project navigation.
Same behavior as "Add menu item" in openproject.org (when checked) and "Delete menu item" in openproject.org (when unchecked).

**Comment by manwithtwowatches** [comment]
so as it stands i have implemented it so that if you check "Show in all projects" then it will appear for everyone as a custom query, and if you check "Page visible for others" then it will appear as a global query. honestly i don't even quite see the point in this but as far as i can tell that's how it used to work.

**Comment by tilt** [comment]
I think Custom / global means private / for everyone. We should double-check this on .org before changing this behaviour

**Comment by manwithtwowatches** [comment]
ok so we've decided to just not implement this at all so i'm closing.

**Pull request closed without merging**
