### PR TITLE
WIP - [Wiki] Breadcrumbs for Search Results

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.org/projects/openproject/work_packages/38521/activity

### CODE REVIEW

**Comment by psatyal** [comment]
Hi @srkunze, 

Just had a look at the pull-preview. 

Before your PR (on edge right now):
wiki-search-old

With your PR (pullpreview):
wiki-search-new

Purely visually, your changes certainly make parsing the information easier!

There is however a semantic ambiguity (the same we faced when trying to work on Work package breadcrumbs): are the breadcrumbs showing project hierarchy or the wiki hierarchy?

For a user who doesn't know beforehand, is "Lorem ipsum" in the first result a project under "Demo project", or it it a parent wiki page to "Another lorem ipsum"? (It's the latter, but how should the user know?) What if the result is a second-level wiki in a second-level project? Should the breadcumbs show both project hierarchy and wiki hierarchy? 

One potential solution might be to put "(Wiki)" in quotes, similar to what you've done but for every wiki page in the hierarchy. @marcalcobe, what do you think?

**Comment by srkunze** [comment]
@psatyal Good to hear! :-)

If you want to hear my thoughts on this: in his day, I tried out the variant you proposed before I opened the pull request but I didn't like it for the following reasons. I therefore reduced the interaction-free interface to what you see in the pull-request.

My understanding so far is that:
- if a user really cares: hovering/long-press on mobile will reveal the necessary info (I assume this to be rarely needed)
- project names and wiki names might have a certain logic in their naming which improves the situation; (it's not the level that is important but the strings - at least this is what I was really missing initially)

If this really becomes an issue (to be measured somehow), providing a distinct separator between project names and wiki names like "p1 > p2 >> w1 > w2" would a less intrusive method. In this case, I still would avoid the repetition of (project)/(wik) because it distracts from the meaning-bearing strings like names and text snippets.

**Comment by marcalcobe** [comment]
Hi @psatyal and @srkunze,

First of all, I think the visual and interaction improves with this PR. On the other hand, in my opinion is not a definitive or perfect solution. For me there is multiple points that are making me hesitate of this approach:

1. As already mentioned, mixing the project hierarchy and the parent/children relations in the breadcrumb is not ideal. This problem is not only detected in Wiki but in other modules also. I think is not 100% critical though as the wiki pages are depending on a project so the information transmitted is not 100% wrong. Maybe an option here would be to add a project icon in front of the project name. Another solution would be to extract the project name from the breadcrumb an put it somewhere else (close to the time stamp maybe like in the notifications).
2. The repetition of the name of the wiki page (in the first example "Another lorem ipsum". Wouldn't it work better to have the breadcrumb on top of the name finalising with an arrow so the title of the wiki is bellow but understood as the last step of the breadcrumb itself?

My proposal would be something like this:
wiki_breadcrumbs

**Comment by psatyal** [comment]
Hi @srkunze and @marcalcobe,

Very interesting ideas. I think the way forward would be a combination of what you are saying:

- The first time is always the project name (with the project icon)
- This is regardless of if that project is a sub-project or not (it remains "root" for the wiki)
- After that, the breadcrumbs will show wiki hierarchy
- The breadcrumbs go on top, so that the actual name of the wiki page does not have to be repeated (thus avoiding having to specify "_(wiki)_", which is admittedly an inelegant solution).

Could you implement these changes, @srkunze?

Cheers
Parimal

**Pull request closed without merging**
