### PR TITLE
Fix OpenProject's use of faux italic, Upgrade to Lato v2.0

### PR DESCRIPTION
**Pull request by myabc**
Pictures speaks louder…

Before:
seeded_project_-_overview_-_openproject

After:
seeded_project_-_overview_-_openproject

The newer version of Lato continues to be available under the [SIL OPEN FONT LICENSE Version 1.1](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)

### CODE REVIEW

**Comment by mfrister** [comment]
Looks better :+1: 

Any idea why the font color looks so different in your second screenshot?
Space between characters now seems to be much narrower than before (at least in the headings), is that intended with Lato 2.0?

Also, we should check how this looks on Windows and Linux.

**Comment by linki** [comment]
windows 8
screen shot 2014-05-02 at 15 10 04

**Comment by myabc** [comment]
@linki thanks for testing!

**Comment by myabc** [comment]
> Any idea why the font color looks so different in your second screenshot?

I agree they **do** look very different. The colour specified (#06799f) remains the same. Just to check, I tried another typeface, Arial, and I perceived a similar difference in colour.

Before:
openproject

With Arial instead:
openproject

Note, in addition to _faux italic_, we previously also using a _faux bold_ on links. One explanation might be that the strokes on the _faux bold_ were not as heavy, each character being surrounded by more white space, and thus giving the appearance of being a lighter colour. (This is just a theory)

http://www.smashingmagazine.com/2012/07/11/avoiding-faux-weights-styles-google-web-fonts/

**Comment by myabc** [comment]
Computed color values are also identical (`rgb(6, 121, 159)`)

**Comment by tessi** [comment]
Ubuntu 14.04 (Gnome Shell, Firefox 29)

selection_033

**Comment by mfrister** [comment]
@myabc Thanks for looking into the color thing, I also think the font-weight is the reason for the difference.

I like the newer font much better, Windows and Linux look good and no one has objected for 10 days, so I'll merge this. :dancer:

**Comment by NobodysNightmare** [comment]
I am not sure if this PR is to blame, but my Chrome does not like the fonts:

not too good

**Comment by myabc** [comment]
Possibly. Why are you not seeing a background image?

**Comment by myabc** [comment]
(ignore the comment about the background image)

https://www.openproject.org/work_packages/7461

**Pull request merged**
