### PR TITLE
Custom logo upload for EE subscribers

### PR DESCRIPTION
**Pull request by oliverguenther**
Supersedes https://github.com/opf/openproject/pull/5112

### CODE REVIEW

**Comment by apfelfabrik** [comment]
So this includes the introduction of enterprise edition DRM from https://github.com/opf/openproject/pull/5134. Titled _"Custom logo upload"_. This is most shady.

It makes me frown. A lot.

**Comment by wielinde** [comment]
It is no DRM, even if you continue to call it like that. All code is provided. You can open, read, and modify it.

**Comment by apfelfabrik** [comment]
How would you call it? It's using [asymmetric encryption](https://github.com/opf/openproject/pull/5154/files#diff-af28417dbcf2442838cbd7c0830379ad) and license keys, disabling features when the [license doesn't validate](https://github.com/opf/openproject/pull/5154/files#diff-34d504574611db923d070b252029e069R35). That's DRM to me. To Wikipedia it's a [_'Common DRM technique'_](https://en.wikipedia.org/wiki/Digital_rights_management#Common_DRM_techniques).

The fact that this PR deliberately changed the wording from [`license`](https://github.com/opf/openproject/pull/5134/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R156) to [`token`](https://github.com/opf/openproject/pull/5154/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R156) makes it weirdly prominent that this is being framed as a wording issue. It's not.

> All code is provided. You can open, read, and modify it.

Would you mind pointing me to the source code of the [ruby gem `openproject-token`](https://rubygems.org/gems/openproject-token) this is currently installing? I can't find it anywhere.

**Comment by oliverguenther** [comment]
> Would you mind pointing me to the source code of the ruby gem openproject-token this is currently installing? I can't find it anywhere.

Sure!
`wget https://rubygems.org/downloads/openproject-token-1.0.0.gem && gem unpack openproject-token-1.0.0.gem`

The term `license` was removed to avoid the confusion between the software license and a subscription. It does not matter what you or we call it, the software license provides you the same rights either way.

**Comment by apfelfabrik** [comment]
@oliverguenther Any idea under what license that's distributed?

**Comment by schmidt** [comment]
The gem's metadata lists `GPLv3` by `OpenProject GmbH`. This is easily inspectable on https://rubygems.org/gem/openproject-token or with the `.gem` file itself (`gem specification *.gem`).

**Comment by apfelfabrik** [comment]
You're right, found it there.

**Comment by wielinde** [comment]
@apfelfabrik Thanks for checking and reporting. Apparently we did not publish the license file with the gem by mistake (which is MIT by the way, just as Ruby on Rails). 

@oliverguenther Could you please check that we include the file?

**Comment by wielinde** [comment]
@schmidt Hey, Gregor, thanks for helping out and unwittingly hinting out a confusion. @apfelfabrik 

@oliverguenther We need to check the meta data and adjust it there. It is MIT, if I am not wrong...

**Comment by oliverguenther** [comment]
The GPL license information itself was missing from the spec (apart from the gemspec declaration), I've released 1.0.1 to address that: https://rubygems.org/gems/openproject-token/versions/1.0.1

**Pull request merged**
