### PR TITLE
enabled ActiveRecord based session store

### PR DESCRIPTION
**Pull request by linki**
... and make it configurable

### CODE REVIEW

**Comment by linki** [comment]
https://www.openproject.org/work_packages/7056

**Comment by mfrister** [comment]
You'll also have to add the session_store parameter to lib/openproject/configuration.rb, otherwise you'll not be able to set it via environment variable.

Do we really want to change the default session store to cookie store? Before, it was the cache store for production.

**Comment by linki** [comment]
changed to `:cache_store` in production in `configuration.yml.example`

**Comment by mfrister** [comment]
@linki This still keeps the cookie store as default store for production. I can imagine we disucssed this and I've forgotten about it. Did we decide to do it this way?

**Comment by linki** [comment]
i discussed this with @cratz on friday and he agreed that cookie store is fine as default

**Comment by mfrister** [comment]
@tessi and I disagree.

Cookie store for production lowers security ([no server-side invalidation](https://www.openproject.org/work_packages/1718)) and I think we should have the best security we can get without too much hassle for users. If we want to simplify installation, we should use the cache store together with a file-based cache, but I think memcache is also ok.

**Comment by linki** [comment]
i just don't like `memcache` as default in development as it's another dependency just to get OP running, anything else is fine with me.

**Comment by mfrister** [comment]
Then let's use the filesystem store as cache store by default, this also makes production setup easier.

@tessi Are you ok with that? I think last time you didn't like the idea.

**Comment by tessi** [comment]
You probably have it right



I'm OK with that :)

**Comment by linki** [comment]
@meeee since this already got merged we need a new PR for this

as i'm always mixing this stuff up:

```
cache_store => file_store
session_store => cache_store
```

correct?

**Comment by mfrister** [comment]
Yep :)

**Pull request merged**
