### PR TITLE
4044 RSpec 3.2 Upgrade

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/4044

Continuation of #1461

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-rspec-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-rspec-3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
Hound is slightly confused…

**Comment by linki** [comment]
looks good to me except the one `pending` spec. what about it? does it fail?

**Comment by myabc** [comment]
@linki thanks for feedback. The `pending` spec does indeed fail. I'll need some help from @ulferts to figure out what the intended behaviour there should be.

**Comment by floriank** [comment]
I'd really like to press `merge` here _someday_.

Any additions, complaints, threats?

**Comment by ulferts** [comment]
No, don't. It is too short before the proposed release and I unfortunately have not yet, other than what I said I'd do, configured a CI run with all our plugins.

**Comment by floriank** [comment]
@ulferts I know that - I just wanted to keep the ball rolling.

**Comment by NobodysNightmare** [comment]
@myabc Any news here I should know about? I thought we wanted to press the button after the release?

**Comment by floriank** [comment]
My information was the same - I wondered a bit :confused:

**Pull request merged**
