### PR TITLE
[#14507] Gemfile: awesome_nested_set: use github 2-1-stable branch

### PR DESCRIPTION
**Pull request by marutosi**
https://www.openproject.org/work_packages/14507

There is no answer on #1863.
Comment of #2027 is non sense.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-awesome-nested-set.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by linki** [comment]
why do we need to remove `Gemfile.lock`?

**Comment by linki** [comment]
why is the monkey patch for awesome nested set (https://github.com/marutosi/openproject/commit/091f0297f198d979d6b904649df083818e3cb401) not needed anymore?

**Comment by marutosi** [comment]
> why is the monkey patch for awesome nested set (marutosi@091f029) not needed anymore?

https://github.com/collectiveidea/awesome_nested_set/pull/234

**Comment by marutosi** [comment]
> why do we need to remove Gemfile.lock?

It is non sense to manage auto generated file by SCM.

**Comment by linki** [comment]
I recommend you read up on the purpose and recommendations on using the `Gemfile.lock` (http://bundler.io/v1.7/rationale.html). It clearly states that it should be checked into version control.

the `Gemfile.lock` snapshots the fuzzy definitions in the `Gemfile` to specific the exact versions you use. it's **especially important** when you use gems via git branches like you suggest in this PR.

To give you an idea where the `Gemfile.lock` is useful: a typical deployment process bundles and then runs the specs on a CI. when everything passes the exact same versions of all dependencies needs to be deployed on many servers. Having a `Gemfile.lock` will ensure that the very same versions get installed on all of them.

**Comment by linki** [comment]
is it possible to use `awesome_nested_set ~>3.0` instead of the unreleased 2.1 branch?

**Comment by marutosi** [comment]
> is it possible to use awesome_nested_set ~>3.0 instead of the unreleased 2.1 branch?

No.

**Comment by marutosi** [comment]
> Gemfile.lock is useful

I disagree.
If you want to pin gem version, you should define in Gemfile.

**Comment by marutosi** [comment]
> Gemfile.lock is useful

Do you check https://gemnasium.com/opf/openproject ?

**Comment by linki** [comment]
> If you want to pin gem version, you should define in Gemfile.

then why the heck you don't do it?

> No.

why not, I'm curious

> Do you check https://gemnasium.com/opf/openproject ?

sometimes, why?

**Comment by marutosi** [comment]
> then why the heck you don't do it?

I did.

> why not, I'm curious

$ git clone git://github.com/collectiveidea/awesome_nested_set.git

> sometimes, why?

Why do you use **many** obsolete gems?

**Comment by linki** [comment]
> I did.

what are you talking about? https://github.com/marutosi/openproject/blob/finn/awesome_nested_set/Gemfile#L53

> $ git clone git://github.com/collectiveidea/awesome_nested_set.git

so what?

> Why do you use many obsolete gems?

we have limited resources here. If you want to help us with that, we would be grateful.

**Comment by marutosi** [comment]
> what are you talking about? https://github.com/marutosi/openproject/blob/finn/awesome_nested_set/Gemfile#L53

Yes.

> so what?

a

> we have limited resources here.

If you think so, you should remove Gemfile.lock.

> If you want to help us with that, we would be grateful.

No thank you.

**Comment by linki** [comment]
do you fix the tests?

**Comment by linki** [comment]
> Yes.

what version of `omniauth` will we use when I merge your PR?

**Comment by linki** [comment]
> If you think so, you should remove Gemfile.lock.

"Ignorance is bliss." - Matrix

**Comment by linki** [comment]
> No thank you.

very sad

**Comment by linki** [comment]
As mentioned, PR contains stuff we don't want. In addition, travis fails. Closing this.

**Comment by linki** [comment]
longer explanation here: https://community.openproject.org/work_packages/14507

**Pull request closed without merging**
