### PR TITLE
Use webpack-fail-plugin to bail on TS errors

### PR DESCRIPTION
**Pull request by oliverguenther**
Introduces the webpack-fail-plugin[1] to return a status code of `-1`
when compilation errors arose in a single build.

It does have its flaws, since it only checks for `--watch`, not its
alias `-w`, but that should be good enough for now.

[1] https://www.npmjs.com/package/webpack-fail-plugin

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-housekeeping-fail-on-webpack-errors.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://oliverguenther-housekeeping-fail-on-webpack-errors.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Opening the PR without fixing the warnings first to check it correctly fails. Also, only the main config is extended at the moment, since I won't fix all errors in the tests bundle right away.

**Comment by oliverguenther** [comment]
I've fixed all warnings with the exception of the intersection type `FileList & typeFixes.ArrayFix;`.

I can expose it fine on the directive, but since the test assigns it a regular array, I can't seem to get the cast right to accept it. @manuschiller or @romanroe, can you take a look at that?

**Comment by romanroe** [comment]
@oliverguenther Can you point me to the code line where you need the cast?

**Comment by oliverguenther** [comment]
```
ERROR in ./components/work-packages/wp-attachments/wp-attachments.directive.test.ts
(122,7): error TS2322: Type '{ type: string; }[]' is not assignable to type 'FileList & ArrayFix'.
Type '{ type: string; }[]' is not assignable to type 'FileList'.
Property 'item' is missing in type '{ type: string; }[]'.
```

```
ERROR in /home/travis/build/opf/openproject/frontend/app/components/work-packages/wp-attachments/wp-attachments.directive.ts
(39,3): error TS2322: Type 'undefined[]' is not assignable to type 'FileList & ArrayFix'.
```

**Pull request closed without merging**
