### PR TITLE
Make Ruby style consistent throughout the codebase

### PR DESCRIPTION
**Pull request by myabc**
Includes some small adjustments to Hound/Rubocop config.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-consistent-ruby-style.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@opf/developers should we be more liberal about long lines? or make it a goal to fix these manually as we refactor?

**Comment by kgalli** [comment]
@myabc I my opinion we should not be liberal about long lines . I think especially in ruby long lines of code are often a result of a long method chains including blocks. Such code is very hard to read and should be refactored anyhow. So I see the possibility to get better code by being not so liberal about long lines. So the question is how many characters we define as long?

**Comment by machisuji** [comment]
Looks good to me except for some minor whitespace issues like double spaces here and there.

As for line length: I think 80 is too short. But 100 (or 99) would be fine.

**Comment by myabc** [comment]
@kgalli Ok. I agree with you. In order to get this PR merged ASAP though, I
think we should keep reformatting long lines for another PR (or try to do
it bit by bit).

**Comment by kgalli** [comment]
@myabc right! We should merge this one and open a new one for reformatting long lines.

**Comment by NobodysNightmare** [comment]
I strongly agree that 80 is too short for today. For C# we went for 120
characters, but maybe Ruby is much more condensed so that you do not
need so loose limits ^^

Did someone try to analyze how long lines actually are? How many violate
60, 80, 100, 120, 150 characters?

P.S.: Am I the only one that is unable to open the PR in the web
browser? I always receive a **Unicorn!**, because the page is taking
"way too long to load".

Am 04.11.2014 13:05, schrieb Markus Kahl:

> Looks good to me except for some minor whitespace issues like double
> spaces here and there.
> 
> As for line length: I think 80 is too short. But 100 (or 99) would be
> fine.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opf/openproject/pull/2136#issuecomment-61630198.

## 

M. Sc. Jan Sandbrink
Finn GmbH
j.sandbrink@finn.de
Rosenthaler Str. 32
10178 Berlin
Telefon: +49 30 288 777 07
www.finn.de
Sitz Finn GmbH: Berlin, Amtsgericht Berlin-Charlottenburg, HRB 117935
Geschäftsführer: Niels Lindenthal
UStID: DE 211309779

**Comment by machisuji** [comment]
@NobodysNightmare It's too big for github to handle. I can see the conversation but not the files. Ruby is not quite as verbose as C#, so 120 isn't necessary. But it is more verbose than other languages for which 80 characters would be acceptable (cf. Haskell).

**Comment by machisuji** [comment]
So I think 100 would be a good compromise.

**Comment by myabc** [comment]
> Did someone try to analyze how long lines actually are? How many violate 60, 80, 100, 120, 150 characters?

No. We probably could/should.

80 is short, but it is standard for many [Ruby open-source projects](https://github.com/bbatsov/ruby-style-guide#80-character-limits). Many developers work in split panes, so that might also be one other reason for its continued popularity.

**Comment by myabc** [comment]
@NobodysNightmare 

> I always receive a **Unicorn!**, because the page is taking "way too long to load".

For me it's only sporadic :stuck_out_tongue:

**Comment by machisuji** [comment]
Are those devs working with 800x600 CRT monitors? Because I'm working with split views too and there's even room for 120 characters*. ;P

**Comment by NobodysNightmare** [comment]
IMHO 80 chars only works when your variables are called `f`, `i` and `s`.

For ruby I see problems with specs:
`it: "is a natural sentence that does not care about concise ruby-language"`, I don't know if there are
other comparable cases.

**Comment by myabc** [comment]
> Did someone try to analyze how long lines actually are? How many violate 60, 80, 100, 120, 150 characters?

Even allowing lines with 99 chars we have a large number of violations:

in `app`:

```
710   Metrics/LineLength
369   Metrics/AbcSize
95    Metrics/PerceivedComplexity
```

in `lib`:

```
413   Metrics/LineLength
329   Style/SpaceInsideParens
130   Style/IndentationWidth
```

**Pull request merged**
