### PR TITLE
Trigger CI

### PR DESCRIPTION
**Pull request by phil-davis**
CI failed in #9358 for no obvious reason.

This PR is just to trigger a run of CI to see if there are existing failures.

### CODE REVIEW

**Comment by phil-davis** [comment]
Unit tests take about 10 minutes.
Feature tests take about 15 minutes.

There are 2 test fails: https://github.com/opf/openproject/pull/9359/checks?check_run_id=2734908465
```
Failures:

  1) Create BCF with all permissions on the split page switching to list behaves like bcf details creation can create a new plain work package
     Got 0 failures and 2 other errors:
     Shared Example Group: "bcf details creation" called from ./modules/bim/spec/features/bcf/create_spec.rb:129
     Shared Example Group: "bcf details creation" called from ./modules/bim/spec/features/bcf/create_spec.rb:129

     1.1) Failure/Error: index_page.switch_view 'Cards'

          Capybara::ElementNotFound:
            Unable to find css ".menu-item"
...
     1.2) Failure/Error: example.run

          Aws::Sigv4::Errors::MissingCredentialsError:
            missing credentials, provide credentials with one of the following options:
              - :access_key_id and :secret_access_key
              - :credentials
              - :credentials_provider
```

1.2 might be because my PR is from a fork, so maybe the CI running "on my behalf" does not have access to the "secrets" like `secret_access_key`

1.1 might be a real fail?

**Comment by phil-davis** [comment]
@oliverguenther I am trying to create a bug report at https://community.openproject.org/projects/openproject/work_packages/new?type=1

But I get a "Saving the document failed" error:
Screenshot 2021-06-03 at 13-59-21 New work package OpenProject OpenProject Community

I don't see what data I have missed out. Is there something special that I need to do to create a bug report?

**Comment by oliverguenther** [comment]
Hi @phil-davis , there was a bug right before the release that caused numbered lists in the WYSIWYG to break. It's currently being deployed on community again. Sorry for the inconvenience. It should work in the next minutes, and you can remove any numbered list from your report in the meantime as a workaround.

**Comment by phil-davis** [comment]
> you can remove any numbered list from your report in the meantime as a workaround.

That worked: https://community.openproject.org/projects/openproject/work_packages/37565/activity

It's a bit of a catch-22 when there is a bug in the bug-submission system :)

**Comment by phil-davis** [comment]
Closing - this was just a demonstration of the existing problem in `dev` branch.

**Pull request closed without merging**
