### PR TITLE
Calculate how to partition the screen width between table and timeline

### PR DESCRIPTION
**Pull request by romanroe**

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/f809c0c72df8354051baca39373666baf8f24d19) (deployed commit: d4de961d317cf6f775f96386d1f17dac532c436a).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/e3685cf02f2eaf2d2749a8c27c5ffb1ae066fc8c) (deployed commit: d4de961d317cf6f775f96386d1f17dac532c436a).

**Comment by oliverguenther** [comment]
As discussed in slack, i suggest we merge and test this on edge for now.

**Comment by oliverguenther** [comment]
Ticket: https://community.openproject.com/projects/openproject/work_packages/25519/

**Pull request merged**
