### PR TITLE
[32739] Add context menu for BCF page

### PR DESCRIPTION
**Pull request by oliverguenther**
https://community.openproject.com/wp/32739

### CODE REVIEW

**Review by HDinger — COMMENTED** [review]
The context menu correctly appears. However there are some issues regarding the redirect. This does not necessarily have to be fixed in this PR, but I think it has to be done before it goes live. It does feel awkward. Here are the places that redirect to the wrong side (the WP side) after the action: 

* "Log Unit costs"
* "Copy" There is another problem: When I copy a BCF, the viewpoint is not copied. But there is already a separate ticket for that https://community.openproject.com/projects/openproject/work_packages/30619/activity
* "Delete" if you need to delete additional objects (like TimeEntries)
* "Create new child" even leads to the WP page in the Create form

**Comment by HDinger** [comment]
Now that I thought about it, maybe not all the entries are that important. I think "Copy" and "Create new child" should be fixed. The other two may also be handled later.

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/88d22fc522179eec21ab36341d48c5a4bf8f13cd/frontend/src/app/modules/bim/ifc_models/bcf/new-split/bcf-new-split.component.ts#L34">frontend/src/app/modules/bim/ifc_models/bcf/new-split/bcf-new-split.component.ts#L34</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oliverguenther** [comment]
Thanks. I created https://community.openproject.com/wp/32760 for the other two actions that need changes

**Pull request merged**
