### PR TITLE
[21676] Misaligned input fields on timeline edit

### PR DESCRIPTION
**Pull request by HDinger**
This PR gives the concerning select field the same margin as the input fields.

https://community.openproject.org/work_packages/21676/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-21676-misaligned-input-fields-in-timeline-edit.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-21676-misaligned-input-fields-in-timeline-edit.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
#### Before

misaligned_input

#### After

aligned_input

**Comment by HDinger** [comment]
@mk84 remarked that the fields are pixel accurate when zooming in Chrome, but not on normal view. I'm working on it...

##### Zoom

zoom

##### vs normal view

normal_view

**Comment by HDinger** [comment]
@mk84 : I've set the height of form-fields to 100% so that the fields have the same height everywhere. This fixes the bug in Chrome.

aligned_input

**Comment by mk84** [comment]
@HDinger But now it's misaligned in IE again :(

**Comment by HDinger** [comment]
@mk84 The layout broke when the text field was wrapped on small screens, independently of the browser. I inserted a centering for the flexboxes so that this should not occur any more.

**Pull request merged**
