### PR TITLE
Nextcloud Project Folders - Documentation

### PR DESCRIPTION
**Pull request by marcalcobe**
Include all the documentation related to the Project Folders functionalities.
Note that we might have some extra features entering 13.0 that will need documentation. They will be treated separately.

### CODE REVIEW

**Review by psatyal — APPROVED** [review]
Made a few changes here and there in a commit I just pushed, but looks good to me!

**Review by MayaBerd — APPROVED** [review]
@marcalcobe looks good, thank you! I've commited some minor fixes (typos and such) directly.

**Comment by marcalcobe** [comment]
Thanks all! I forgot to ask @as-op for the technical review!

**Comment by marcalcobe** [comment]
Hi all! @MayaBerd and @psatyal, the documentation on the administration setup part was missing. I've added it in my last commit. Please if you have time review that part also.

**Review by psatyal — APPROVED** [review]
Hi @marcalcobe. Pushed a few changes in the last commit. Looks good to me now!

**Review by MayaBerd — APPROVED** [review]
@marcalcobe thanks, looks good to me.

**Pull request merged**
