### PR TITLE
Bug/49947 project storage can be set to automatically managed while storage is not configured for it

### PR DESCRIPTION
**Pull request by akabiru**
#### https://community.openproject.org/work_packages/49947

When storage does not support automatic folder management, do not allow the automatic option when adding the storage into a project

Screenshot 2023-10-17 at 3 47 27 PM
Screenshot 2023-10-17 at 3 45 30 PM

### CODE REVIEW

**Comment by wielinde** [comment]
@akabiru Would it be possible and a good idea to base this PR agains `release/13.0`? Then it would get released with the next patch level release and thus prevent people from misconfiguring OpenProject.

**Comment by akabiru** [comment]
> @akabiru Would it be possible and a good idea to base this PR agains `release/13.0`? Then it would get released with the next patch level release and thus prevent people from misconfiguring OpenProject.

Sure @wielinde 👍🏾

**Comment by akabiru** [comment]
Closing in favor of https://github.com/opf/openproject/pull/13940

**Comment by akabiru** [comment]
Retain as fix is required in dev too

**Comment by akabiru** [comment]
@Kharonus I'll assume your approval from https://github.com/opf/openproject/pull/13940 if you have no objections 🙂

**Review by Kharonus — APPROVED** [review]
@akabiru Approval granted

**Pull request merged**
