### PR TITLE
Fix/selectable versions on wp cf

### PR DESCRIPTION
**Pull request by ulferts**
Fixes https://community.openproject.com/work_packages/28421

It also replaces the legacy specs for custom fields.

### CODE REVIEW

**Review by machisuji — APPROVED** [review]
:+1: Looking good. Can be merged once travis agrees.

**Review by machisuji — CHANGES_REQUESTED** [review]
Ok this actually seems to brake some queries using the shared versions somehow (see failed specs).

**Comment by ulferts** [comment]
@machisuji I adapted the breaking the breaking specs to now work with `shared_versions` so everything should be expected correctly now.

**Review by machisuji — COMMENTED** [review]
:+1:

**Review by machisuji — APPROVED** [review]

**Pull request merged**
