### PR TITLE
[#50172] fixed dotnet runtime for packaged installation

### PR DESCRIPTION
**Pull request by Kharonus**
- https://community.openproject.org/wp/50172
- removed insertion of Microsoft package sources for packaged installation for Ubuntu 22.04

### CODE REVIEW

**Comment by machisuji** [comment]
I have triggered a packager build for this branch: https://packager.io/gh/opf/openproject/builds/9716

**Review by machisuji — APPROVED** [review]
Therefor is missing an 'e' but everything else is good! Thanks for fixing the issue! 👍

**Comment by Kharonus** [comment]
Will merge it only after testing, if issue is truly fixed. ;)

**Comment by Kharonus** [comment]
@wielinde tested it and the issue is resolved.

**Pull request merged**
