### PR TITLE
Fixed column alignment bug

### PR DESCRIPTION
**Pull request by zzmedia**
- Fixed column alignment bug and added scrolling to the table
  https://www.openproject.org/work_packages/8234

### CODE REVIEW

**Comment by ulferts** [comment]
@zzmedia: The scroll bar is always shown even if everything fits on the screen (Chrome).

**Comment by ulferts** [comment]
@zzmedia: any update on this?

**Comment by zzmedia** [comment]
@ulferts: I'm not sure yet ... maybe this could be done inside the angular framework? what do you think @myabc ?

**Comment by myabc** [comment]
@zzmedia I believe I've found a simpler solution: the problem you were experience was a result of the usage of `display: table-cell` and `display: table` in parent divs around the table. [`table-layout: fixed`](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout#values-fixed) resolves this.

**Comment by myabc** [comment]
Fix now pushed to #1498.

**Pull request closed without merging**
