### PR TITLE
Deprecate ChiliProject constants

### PR DESCRIPTION
**Pull request by myabc**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://feature-deprecate-chili-project-constants.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://feature-deprecate-chili-project-constants.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@myabc this will break at least the impermanent membership plugin, but it should be easy to fix.

**Comment by myabc** [comment]
@ulferts 

> this will break at least the impermanent membership plugin, but it should be easy to fix.

It shouldn't break anything - the constant is still defined, just deprecated.

**Comment by ulferts** [comment]
@myabc I see. Didn't know of the DeprecatedConstantProxy

**Pull request merged**
