### PR TITLE
[FIX] Relative root url path handling 4115

### PR DESCRIPTION
**Pull request by hschink**
Implements [ticket 4797](https://www.openproject.org/work_packages/4797)
- `#4797` [Subdirectory] Broken Links

### CODE REVIEW

**Comment by machisuji** [comment]
I'd like some comments about the whole proc business. Before it was explained to me I had no clue why the hell you would do that.

**Comment by hschink** [comment]
I need to execute the `path_/url_helpers` in the view context because otherwise the sub path is not respected. To resolve the sub path, the helpers need a request which is only available in the view. That is the thing. :smile:

**Comment by machisuji** [comment]
This patch requires the following plugins to be adapted:
- openproject-about_me_text
- openproject-costs
- openproject-documents
- openproject-meeting

Won't merge for now. There is an alternative which requires less intrusive changes and does not break _openproject-about_me_text_: PR [#979](https://github.com/opf/openproject/pull/979)

**Comment by hschink** [comment]
Closed in favor for #979

**Pull request closed without merging**
