### PR TITLE
Fix/accessible error messages

### PR DESCRIPTION
**Pull request by ulferts**
Removes custom focusing that was introduced to present errors to users requiring assistive technologies e.g. screen readers. By assigning the `role="alert"` attribute to error messages and additionally having errors on fields as hidden text in the labels, there should be enough information to efficiently fix errors. 

https://community.openproject.com/work_packages/23284/activity
https://community.openproject.com/work_packages/23289/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-fix-accessible-error-messages.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://ulferts-fix-accessible-error-messages.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Works nicely on Jaws 17. 👍

**Comment by oliverguenther** [comment]
This broke a spec on mobile otp: https://travis-ci.com/finnlabs/openproject-myproject/jobs/42443878

**Comment by ulferts** [comment]
Will fix that one, thanks for pointing it out @oliverguenther.

**Pull request merged**
