### PR TITLE
remove spec/exemplars

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work package

This is intended to be house keeping: https://community.openproject.org/work_packages/18714
## Description

TBH: I have no idea what "exemplars" are, but they reside in the spec directory.
So I figure if they are important for the specs, removing them will break the specs...
If specs stay green it should be okay to remove them...
## Disclaimer

This is probably the most naive PR I ever issued ^^

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-remove-exemplars.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-remove-exemplars.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@NobodysNightmare it's not that easy, I'm afraid. You'll need to replace all usages (calls to `Model.generate!`) with `FactoryGirl.create` or similar.

**Comment by NobodysNightmare** [comment]
@myabc At least you know the words to grep for ;-)

Apparently we have 4 core specs depending on that mechanism and 76 legacy specs.

Did not check what plugins do, though :(

Thanks for the pointer to `Model.generate`

**Comment by ulferts** [comment]
Closing as this does not see any action and fails. Please reopen once the failures are fixed.

**Pull request closed without merging**
