### PR TITLE
[26277] Replace project autocompleter from select2 to jquery-ui

### PR DESCRIPTION
**Pull request by oliverguenther**
Replaced autocompletion with jquery-ui formatter/highlighter and fuzzy searching to micro libraries for that task (fuzzy, mark.js).
  
https://community.openproject.com/wp/26277

### CODE REVIEW

**Comment by ulferts** [comment]
### Bugs
#### Design changed

before:
image

after:
image

#### Ancestors of found project not displayed:
image

#### Dropdown not always displayed (e.g. when switching tabs)

image

#### Fuzzy search applied multiple times (not sure if it is a real world problem)

image

#### Fuzzy search finds more results than before (although I like it)

Despite the term not being part of the project name, the project is now returned as part of the results as the characters all exist in the correct order (but not necessarily directly after one another)

image

#### Selected project and dropdown displayed after selection (nitpicking)

image

### Thoughts

We could think about removing the accessibility mode behaviour here as the typeahead is supposed to be accessible.

**Comment by ulferts** [comment]
#### less padding in the list (e.g. padding left is now 10 instead of 17, line height now 20 instead of 24) -> less lofty 

before:
image

after:
image

#### pressing ESC closes selection 

image

#### Hover turns font color to blue 

has probably been an inconsistency before as the focused element was also turned highlighted in blue

#### matched substring highlighted by fuzzy now blue instead of standard font color (fine with me)

before:
image

after:
image

**Comment by wielinde** [comment]
Message "No results found" should have a border, just as if there were results.

image

Bonus: the left border outside of the input seems one pixel too thin.

**Comment by oliverguenther** [comment]
I won't address any further minor styling issues since we'll likely want to touch that area again. Maybe @HDinger you and I could check the dropdown sass code and clear up a bit there, its a mess!

I did address the escape and no-results border styles

**Comment by ulferts** [comment]
@oliverguenther this now looks fine enough for me. If @wielinde is ok with it, we should merge the code and address the remaining styling issues separately.

**Comment by wielinde** [comment]
@oliverguenther it looks good to me so far. However, I believe giving it some testing time might be wise as the fuzzy-thing sometimes gives unexpected but correct results. I love it BTW!. 

I just had a check: The `select` method receives an event that we can check for "event.metaKey". this allows could allow us to add "command+click" new tab logic. After merging your PR I might build that :-)

**Comment by ulferts** [comment]
Free to merge after travis' consent.

**Pull request merged**
