### PR TITLE
[21241] Refactor simple filters according to visual

### PR DESCRIPTION
**Pull request by HDinger**
This commit redesignes the simpleFilter component accordingly to the visuals

https://community.openproject.org/work_packages/21241

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-task-21241-refactor-simple-filters.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-task-21241-refactor-simple-filters.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
Looks good overall.

I've provided a small PR over at your place https://github.com/HDinger/openproject/pull/8 with some fixes to match the visual and some points I had with Niels a few weeks ago.
- Removed superfluous padding on control button
- Subjective better positioning of labels. This  is a bit different to the visual, however they are just too far apart for my understanding of a label.
- Used flex to position button closer to input
- Removed colons
- Removed top border
- Removed clear button

Compared to the visual, the apply button still is a little too far on the right due to the flex setting. Do you know a way to shrink the latest filter in that line to let the button get closer to it? 
I don't think this is really important, though, so if you don't find a quick, neat solution, I'd suggest to leave this as it is.

bildschirmfoto_2015-08-31_um_16_18_52

**Comment by HDinger** [comment]
One way is to set the 'justify-content' to flex-start so that between the elements there is no space. The button is then at least a bit closer, but the distance to the other elements shrink, too. 

Before:
space-between

After:
flex-start

In my eyes it looks better. What do you think?

**Comment by oliverguenther** [comment]
I too prefer the new style. My only concern were the labels, as I think their distance to the input is too big - however that concern applies to the original visual as well. I think your change is the better compromise.

**Comment by HDinger** [comment]
The button is now a bit closer. I think we should leave it that way, if it looks ok to you.

**Comment by oliverguenther** [comment]
Looks absolutely fine to me. :+1: Will merge after travis.

**Pull request merged**
