### PR TITLE
Revert "Add override restoring previous grid behaviour"

### PR DESCRIPTION
**Pull request by machisuji**
Reverting it as it breaks, at the very least, the meetings overview.
Perhaps the foundation bug has been fixed in the meantime.

This reverts commit 3dbfe0f7f625c3c6ff2cdf0d60351f9230dc2da5.

WP [#19596](https://community.openproject.org/work_packages/19596)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://machisuji-fix-flex-basis-hack.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://machisuji-fix-flex-basis-hack.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@machisuji I will go ahead and merge because this is a blocker – and my original workaround was not properly implemented.

Note: Merging this PR will cause columns on My Page to be rendered with the incorrect width:
openproject_and_revert__add_override_restoring_previous_grid_behaviour__by_machisuji_ _pull_request__2818_ _opf_openproject

I'll see if I can find a better solution.

**Comment by floriank** [comment]
Could this also relate to https://community.openproject.org/work_packages/19325?

**Comment by machisuji** [comment]
It doesn't seem to be related. At least I still can't see 2 columns anywhere with this merged.

**Comment by myabc** [comment]
There is an upstream issue for this now: https://github.com/zurb/foundation-apps/issues/575.

**Pull request merged**
