### PR TITLE
[20407] [Accessibility] The pop up for selecting the work package columns is difficult to perceive

### PR DESCRIPTION
**Pull request by HDinger**
This adds a new layout for the columns modal in accessibility mode. The other layout is too hard to access by keyboard. Thus there will be checkboxes for selecting the desired columns.

https://community.openproject.com/work_packages/20407/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-20407-the-pop-up-for-selecting-the-work-package-col.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-20407-the-pop-up-for-selecting-the-work-package-col.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by HDinger** [comment]
#### Normal view

bildschirmfoto 2016-04-22 um 16 45 17

#### Accessibility mode

bildschirmfoto 2016-04-22 um 16 45 06

**Comment by HDinger** [comment]
@oliverguenther This should work now. The only issue remaining is a missing focus when the modal is opened. But since this is an issue for nearly all our modals in WP view, I would suggest to leave it out here and handle it separately. What do you think?

**Comment by oliverguenther** [comment]
@HDinger We can employ `autofocus` to fix it , at least for this PR. I've pushed that change and will merge once travis agrees.

**Pull request merged**
