### PR TITLE
Fix #7137: last login not logged (omniauth)

### PR DESCRIPTION
**Pull request by machisuji**
Suggested change log entry:

```
* `#7137` Fix: No last connection for users authenticated with omniauth
```

WP [#7137](https://www.openproject.org/work_packages/7137)

### CODE REVIEW

**Comment by mfrister** [comment]
Cukes are broken.

**Comment by linki** [comment]
rebased on current origin/dev

**Comment by mfrister** [comment]
@machisuji You might need to adapt a certain plugin you recently fixed when changing the spec names.

**Comment by machisuji** [comment]
@meeee Created a PR adapting said plugin. Feel free to merge them both!

**Comment by linki** [comment]
much better than before :+1:

**Pull request merged**
