### PR TITLE
[20788] project menu is not pixel accurate

### PR DESCRIPTION
**Pull request by HDinger**
substracted the border width (like in the top menu) so that all lines are pixel accurate

https://community.openproject.org/work_packages/20788

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hdinger-fix-20788-project-menu-pixel-accurate.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hdinger-fix-20788-project-menu-pixel-accurate.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
that currently looks strange to me in chrome :(

screenshot from 2015-08-10 13 45 24

**Comment by NobodysNightmare** [comment]
Still not "pixel-perfect", we just traded one error for another:

### before this PR

good-pixels

### after this PR

bad-pixels

The border around the menu items, now does not fully cover the menu items anymore (the background color "bleeds" through).
This is most noticable for the highlighted menu items (the one with the dark blue background)

**Comment by NobodysNightmare** [comment]
Looking nice now!

**Pull request merged**
