### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by TribesTom**
Hi backup

Here is my new pull request.

Thanks.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://tribestom-stable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by ulferts** [comment]
Hopla @TribesTom, I guess you took some commit too much there. Can you please do the following git commands in your OP directory:

<pre>
git checkout stable  # go to stable branch
git checkout -b hotfix/fix_csv_export  # create a new brach called hotfix/fix_csv_export
git rebase -onto release/4.0 a2085f4 # rebase the new branch onto release/4.0 only taking the two commits you created
git push origin hotfix/fix_csv_export # push to github
</pre>

And issue a PR with the hotfix/csv_export branch of your OP repo against release/4.0 of the opf OP repo?

**Comment by TribesTom** [comment]
Hi back,

Here is a little problem instead of making again a mistake :

openproject$ git rebase --onto release/4.0 a2085f4
fatal: Needed a single revision
Does not point to a valid commit: release/4.0

2014-12-18 14:42 GMT+01:00 ulferts notifications@github.com:

**Comment by ulferts** [comment]
@TribesTom you haven't yet checked out release/4.0 locally.
replace `release/4.0` with `origin/release/4.0` and it should work

**Comment by ulferts** [comment]
Closed in favour of #2366

**Pull request closed without merging**
