### PR TITLE
[24152] Auto hide popups

### PR DESCRIPTION
**Pull request by silkentrance**
Auto hide popups.

https://community.openproject.com/work_packages/24152

### CODE REVIEW

**Comment by silkentrance** [comment]
The timeout for the popups to automatically remove themselves should be configurable on a per notification type basis. However, I do not know where to put that configuration and how to pass it to the frontend. And some notifications, e.g. errors, should not auto remove themselves at all but should be modal instead.

**Comment by oliverguenther** [comment]
We actually had notifications with an automatic timeout but had to remove it for (iirc) accessibility reasons. What would work if we make it configurable through the `ConfigurationService` and let users configure it in their user preferences. What do you think?

**Comment by silkentrance** [comment]
Of course, sounds good. Lets see how I can implement this.

**Comment by oliverguenther** [comment]
There is a `ConfigurationService` that is fed from the user preferences on every request. You could extend the `UserPreference` model and view on the `/my` page, and that value would automatically be forwarded to the frontend.

**Comment by silkentrance** [comment]
Done, now for the tests. Tests are done, too.

**Comment by silkentrance** [comment]
I have also updated the v3 api to support the new setting.

**Comment by silkentrance** [comment]
@oliverguenther note that this uses a hard coded timeout of 5000ms. If you want/need this to be configurable, just say so.

And please also check with your usability/accessibility/ux guys if the timeout should be different for different kinds of notifications. For example stuff like: errors should not simply just go away and must require user interaction.

**Comment by oliverguenther** [comment]
Looks good to me with the exception of two things:
1. Please add a translation at `activerecord.attributes.user_preference.auto_hide_popups`, as the translation is currently `humanize`d, which works without warning in english so its often missed.
2. The npm tests are failing due to the ConfigurationService not being mocked. It should suffice to add `'openproject.uiComponents'` into the definition of `opServicesModule` at `angular-modules.ts` (line 42).

Good to merge from my side after that! 👍  I'll discuss your point about error notifications but that should simply be an additional condition in your new code and we can add that afterwards.

**Comment by silkentrance** [comment]
@oliverguenther this was a bit more difficult. I had to refactor notifications service to a typescript module, along with the available tests for it. Second, I had to register the openproject.config module with the openproject.services module, so that the configuration services gets injected proper.

I hope you don't mind the rather minor refactorings, including also the refactoring of the available tests for upload notifications and the required changes made to the notification services' api.

**Comment by silkentrance** [comment]
@oliverguenther this is more involved. some subtle changes, I do not yet know which, caused this PR to not work at all. The notifications will not be removed/automatically hidden and require user interaction. I am still investigating that, but it seems as if the leading role of the data model was taken over by the ui...

before committing the PR I had some extra code in app/assets/javascripts/flash_messages.js which would also auto-hide/remove the notifications. Perhaps this has something to do with that.

**Comment by oliverguenther** [comment]
Hey @silkentrance , the changes look fine, I fixed an issue using $timeout and applied that feature to rails-based notifications (since the NotificationService only controls angular-based notifications).

Since I can't push to your fork, I've created a separate PR here: https://github.com/opf/openproject/pull/5055

**Pull request closed without merging**
