### PR TITLE
Fix 43832: "Reorder values alphabetically" does not work reliably

### PR DESCRIPTION
**Pull request by srkunze**
fixes [#43832](https://community.openproject.org/projects/openproject/work_packages/43832/activity)

### CODE REVIEW

**Comment by machisuji** [comment]
Thanks for the fix. Still have to look into the actual solution (why removing acts_as_list fixes the issue and if that has any other implications).

In the meantime, I only have a comment on the specs.
I think it's a good idea to use what is effectively property-based testing here.

Maybe it would make sense to introduce a gem for this, similar to Haskell's QuickCheck or Scala's ScalaCheck.
Does anyone know any actively maintained gems for Ruby?
A quick search yielded [prop_check](https://github.com/Qqwy/ruby-prop_check/) but that hasn't been updated in 2 years.

**Comment by srkunze** [comment]
@machisuji Thanks for the feedback. I will fix the styling issues and re-issue the commits.

I had a look at the gem you pointed at, but I am not convinced it helps us a lot in terms of readability or performance. :-/ Do you have something specific in mind?

**Review by ulferts — CHANGES_REQUESTED** [review]
The functionality works as expected, so thanks a lot @srkunze.

What also would have worked is wrap the calls to where the options are updated in like this

```
CustomOptions.acts_as_list_no_update do
  # perform bulk change
end
```

as [described in the gemfile's readme](https://github.com/brendon/acts_as_list#disabling-temporarily). 

But since we are always bulk changing the order, so that all the values are provided, removing the gem from the class altogether is even better.

The only reason why I request a change from you @srkunze is that by now the appropriate target branch has changed. In order for the fix to make it into a 12.3 release, the PR needs to target `release/12.3`.

**Comment by ulferts** [comment]
Closing in favor of #11471

**Comment by srkunze** [comment]
@ulferts Sorry for being unresponsive here. There were some holidays and other pressing issues to be resolved first. So thanks for merging.

**Pull request closed without merging**
