### PR TITLE
[32912] Add attributes company and domain to ee active trial screen

### PR DESCRIPTION
**Pull request by ingamai**
:warning: **This topic is related to PR https://github.com/finnlabs/openproject-token/pull/1** (ticket: https://community.openproject.com/projects/openproject/work_packages/33129)

See ticket: https://community.openproject.com/projects/openproject/work_packages/32912

### CODE REVIEW

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/6164133b0c21d81462f8e4057d0ea5bc650d1166/frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-saved-trial.component.ts#L34">frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-saved-trial.component.ts#L34</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/6164133b0c21d81462f8e4057d0ea5bc650d1166/frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.ts#L36">frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.ts#L36</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by HDinger — CHANGES_REQUESTED** [review]
Hi @ingamai 

as you already pointed out, this will break when having a token without the attributes "domain" and "company". However, there are many instances that already have an existing token, which won't get updated. So for them, this changes will lead to a 500 error:

Bildschirmfoto 2020-04-27 um 14 46 14

I think, we need a check if the data is available and show the two fields only in that case.

**Comment by ingamai** [comment]
@HDinger Right, I already wrote the differentiation in the html file and somehow forgot to add it in the .erb file. I now added a condition to check if a token has these attributes. So that the PR could theoretically be merged before the other without breaking anything

**Review by HDinger — APPROVED** [review]
Looks good 👍 I would still like to wait for the other PR to test it again with a complete token.

**Comment by ingamai** [comment]
@HDinger I opened a new PR https://github.com/opf/openproject/pull/8358 to merge this into release/10.5.

**Pull request closed without merging**
