### PR TITLE
Implement read-only work package attributes based on status

### PR DESCRIPTION
**Pull request by oliverguenther**
Implements read-only work packages with an active EE token.

Will show statuses that lock work packages by an additional icon in the dropdown

locked-1

When switching to that status, all fields except status are blocked. An icon is shown in the status dropdown which shows the same tooltip on hover.

locked-2

Also this PR:

- extracts the Statuses table into the common table cell

https://community.openproject.com/wp/28866

### CODE REVIEW

**Review by ulferts — CHANGES_REQUESTED** [review]
Implementation looks good and it also feels nice from a user's perspective.

Points I noted:

* The padlock icon gives a nice touch to the status. Unfortunately it is not displayed when switching from the table to the full view of a work package being in a locked state, probably due to the status not being fully loaded:
image
* The specification states that it should not be possible to add files if the work package is in a locked status. Currently, this is not prevented.
* Using bulk edit, work packages being in a locked state can be edited.

**Comment by oliverguenther** [comment]
> Using bulk edit, work packages being in a locked state can be edited.

This should be fixed in upstream already, since bulk controller now uses UpdateService on dev. This branch is behind that merge however, rebasing now.

**Comment by oliverguenther** [comment]
@ulferts I have addressed your remarks

**Comment by ulferts** [comment]
👍

**Review by ulferts — APPROVED** [review]

**Pull request merged**
