### PR TITLE
Remove (broken) Right to Left (RTL) stylesheets

### PR DESCRIPTION
**Pull request by myabc**
Unfortunately, development and maintenance of RTL stylesheets has not
kept pace with new styling and recent, extensive CSS refactoring.

Rather than offer broken support, it is preferable IMO to remove this
feature this feature for the time-being.

Relates to #190

https://community.openproject.org/work_packages/18714

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-remove-rtl-support.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-remove-rtl-support.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
This sounds discussable. What does broken mean?

"broken" as in "there are places where it doesn't work"?
or
"broken" as in "I can see no place where it works at all"?

**Comment by myabc** [comment]
> "broken" as in "there are places where it doesn't work"?
1. we're not supporting RTL _officially_ (I personally think this is a shame).
2. we're not testing RTL, either manually or in an automated way.
3. it cannot work because AFAICT `rtl.css` is not included on any page. I can't find it referenced in either the core or the translations plugin. We were including `context_menu_rtl.css` on the classic work packages show page though – which made no sense as we're not using a context menu on that page.
4. `rtl.css` overrides classes that no longer exist.

**Comment by cratz** [comment]
Whole RTL support was basically removed within this commit: e0ce81240a08ef4e59937ddaba9e8c7fb75236a
And not re-implemented after introducing Crowdin.

**Comment by myabc** [comment]
@cratz thanks for clarification!

**Comment by NobodysNightmare** [comment]
I will merge this into the `dev` branch. I don't see it critical to have this included in the `release/4.1` branch, but rather want to be on the safe side.
Don't want to break stuff only days before the release by removing unneeded code.

**Comment by myabc** [comment]
I don't think we should ship dead code.

**Comment by myabc** [comment]
FWIW we've had this discussion before previous releases and I was of
another opinion back there too: IMO low-risk cleanup is exactly what one
**should** be doing before a release.

**Comment by NobodysNightmare** [comment]
Then somebody else has to press the button, because I am not able to assess the risk of this cleanup.

**Comment by floriank** [comment]
@myabc I will merge this as soon as there is a ticket in the backlog to restore full RTL support

> I personally think this is a shame

As do I.

**Comment by myabc** [comment]
@floriank good idea: https://community.openproject.org/work_packages/19755

**Pull request merged**
