### PR TITLE
Speed up RSpec boot time by 30%

### PR DESCRIPTION
**Pull request by cbliard**
By passing `pre_count: true` to `DatabaseCleaner`, tables will be checked for existing rows before truncating. As we are using transactional strategy, tables are rolled back after the test suite and are empty, so pre counting the rows to prevent truncation saves time.

As tables are truncated only once at the beginning of the test suite, this saves boot time. When running
`time rspec spec/services/work_packages/shared/working_days_spec.rb:47`:

  * `pre_count: false` => 10,370 seconds total
    > Finished in 3.1 seconds (files took 6.14 seconds to load)

  * `pre_count: true`  =>  7,365 seconds total
    > Finished in 0.06816 seconds (files took 6.17 seconds to load)

### CODE REVIEW

**Comment by oliverguenther** [comment]
I'm wondering, do we really need DatabaseCleaner with transactions being in place? I can't think of a reason why unless for legacy specs

**Comment by cbliard** [comment]
I was wondering the same. I guess it is still useful if RSpec test get killed for some reason and the database is left with some data in it. But in that case I would assume the transaction is rolled back as well.

Maybe we could try removing it.

I'll look into why the tests are failing.

**Review by ulferts — CHANGES_REQUESTED** [review]
Admittedly I don't see the same performance gains on my machine but I understand that it makes senes to remove a step if it is no longer needed so I would merge it.

But speaking of getting rid of an unnecessary step, can you please add a comment to the Gemfile triggering us to remove `database_cleaner` once the legacy specs are removed?

**Comment by cbliard** [comment]
> But speaking of getting rid of an unnecessary step, can you please add a comment to the Gemfile triggering us to remove `database_cleaner` once the legacy specs are removed?

Yep done.

**Pull request merged**
