### PR TITLE
Fix i18n and nokogiri vulnerabilities

### PR DESCRIPTION
**Pull request by mfrister**
https://www.openproject.org/work_packages/7160

i18n: [0.6.8 is lowest 0.6.x version available](https://rubygems.org/gems/i18n), [Changelog](https://github.com/svenfuchs/i18n/commits/61f975bd862e2ce3a9f77fb5afdf11831fbcbb22)

nokogiri: [only had bugfixes](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.rdoc#1511--2013-12-14)

### CODE REVIEW

**Comment by myabc** [comment]
@meeee should we not specify the versions in the `Gemfile` itself?

**Comment by mfrister** [comment]
@myabc They're both not direct dependencies, so I didn't think it was a good idea to do that. Do you think otherwise?

**Comment by myabc** [comment]
@meeee I know. Handling indirect dependencies is tricky. 

Where security upgrades of an indirect dependency are sufficiently critical, I would be in favour of specifying the dependency in our `Gemfile` (perhaps with a note liking to the CVE number).

Of course, what _should_ happen is that the maintainer of the direct dependency updates their `.gemspec` (with a bit of lobbying from users, if necessary).  Looking at you, `activesupport`.

**Comment by mfrister** [comment]
@myabc I wasn't sure, but @ulferts shares your opinion, so I added them to the Gemfile :)

**Comment by myabc** [comment]
@meeee :+1: for requesting link to security advisory.

**Comment by mfrister** [comment]
As @marutosi pointed out with his pull request against stable (thanks!), this PR should go into release/3.0. Closing this one and creating a new PR.

**Pull request closed without merging**
