### PR TITLE
Feature/1899 send daily email summaries

### PR DESCRIPTION
**Pull request by ulferts**
Introduces daily digests. Users can configure to be notified for updates to work packages (that limitation can later on be loosened) and will then receive an email once per day.

https://community.openproject.org/projects/openproject/work_packages/1899

The `read_mail`/`reason_mail` as well as `read_mail_digest`/`reason_mail_digest` are currently not available via the API. The `read` flags for the mails are currently mostly used for housekeeping.

### Known limitations
* Currently only one reason is stored per channel ('ian', 'mail', 'mail_digest') when there could be multiple reasons a user receives a notification for (e.g. assignee + watcher). This limitation is currently kept due to the overhead a rework would cause. 
* The user cannot choose the time of the day an email is received. Instead, the time of sending is configured globally, in the admin settings. However time will be localized to the user's timezone. Therefore, 8 o'clock for a user with the +10 time zone will receive the digest at a different time than the user with a -10 time zone.
  * The admin setting is very plain. Instead of a time picker, an integer input is offered that allows to insert the minutes after midnight.
* Styling of the html email is much reduced compared to the specification. This is due to email clients not being consistent when interpreting html/css.
  * Avatars are not included at all. Including them would mean to either copy all avatars as attachments into the mail or having all avatars publicly available. Both are undesirable. One could include avatars available via gravatars but that would only cover part of the avatars and would require implementing the whole avatar functionality anew while facing styling issues. 
  * No changes have been made to the way journal notes and details are rendered within a mail. 

### TODO

* [x] Introduce email digest in data model of notifications & notification settings
* [x] Fill in `read_mail_digest` and `reason_mail_digest` along with the other attributes when a notification is generated based on a journal 
* [x] Introduce distinct `read_ian` and `read_mail` reasons to later on be able to distinguish. The reason a user receives an email might be different from the reason an in app notification is received for.
* [x] Generate singleton background worker once the first notification with `read_mail_digest: false` is created (`CreateService`). Use the setting & the user's time zone to determine the execution time. Only do this if there isn't a notification in the database yet for the same user and with `read_mail_digest: false` within the daily time frame. 
* [x] Within the background worker, generate a mail containing all the notifications having `read_mail_digest: false` grouped by project and work package

### CODE REVIEW

**Comment by lindenthal** [comment]
grafik
 Hi @ulferts,
 can you please rename the "Email digest" to "Daily email summary"? I think this should be the third option.
 
 Thanks
Niels

**Review by oliverguenther — CHANGES_REQUESTED** [review]
Code-wise, I have no remarks. This appears to be working as expected.

By triggering the digest job explicitly for my testing, I noticed it was possible to get empty digest messages. Judging from the way the digest is triggered, this is probably never happening in production but would still be nice to cancel the digest job in case there are no notifications.

I found it difficult to understand the trigger time of the digest in minutes starting midnight. What was the reason for that? Why not specify a HH::mm time instead that is applied to the local timezone? There should be no difference in saying "I want the digests to be sent at 8:00 local timezone of the user" vs "I want the digest to be sent at 480minutes past midnight in the local timezone".

**Comment by ulferts** [comment]
@oliverguenther thanks for the review:

> By triggering the digest job explicitly for my testing, I noticed it was possible to get empty digest messages. Judging from the way the digest is triggered, this is probably never happening in production but would still be nice to cancel the digest job in case there are no notifications.

I'll add a safeguard to get it canceled in this case.

> I found it difficult to understand the trigger time of the digest in minutes starting midnight. What was the reason for that? Why not specify a HH::mm time instead that is applied to the local timezone? There should be no difference in saying "I want the digests to be sent at 8:00 local timezone of the user" vs "I want the digest to be sent at 480minutes past midnight in the local timezone".

I agree that this would be desirable. It was simply because we don't have a time format yet for settings and I didn't want to invest in it now since it was the only setting we have for now.

**Review by oliverguenther — APPROVED** [review]
Approving just in case we decide to address some of the remarks separately

**Comment by ulferts** [comment]
@lindenthal 

> can you please rename the "Email digest" to "Daily email summary"? I think this should be the third option.

done.

**Pull request merged**
