### PR TITLE
Add basic pattern/doc for autocompleters in Lookbook

### PR DESCRIPTION
**Pull request by oliverguenther**

### CODE REVIEW

**Review by HDinger — COMMENTED** [review]
Looks good, thanks for the effort. 🥳  I renamed the file, so that we can ensure some kind of order in the sidebar. 
There are two other minor issues:

* The dropdown of the decorated example is overlapping the input. I assume that the position is wrongly calculated due to the iFrame context.
Bildschirmfoto 2024-03-11 um 10 18 08

* The WorkPackages example does not load any work packages in Firefox, in Chrome it is working correctly.

**Comment by oliverguenther** [comment]
> * The dropdown of the decorated example is overlapping the input. I assume that the position is wrongly calculated due to the iFrame context.

Yeah, I noticed that too but couldn't get it to work properly within the frame 🤷

**Comment by HDinger** [comment]
> > * The dropdown of the decorated example is overlapping the input. I assume that the position is wrongly calculated due to the iFrame context.
> 
> Yeah, I noticed that too but couldn't get it to work properly within the frame 🤷

I will give it a try, and merge if I don't find a feasable solution for it

**Comment by HDinger** [comment]
I did not find a way around that as well, so I left a note in the caption and will merge it for now. 👍

**Pull request merged**
