### PR TITLE
[25199] New table|timeline|split-view layout

### PR DESCRIPTION
**Pull request by oliverguenther**
**TODOS**

- [x] The `split screen to full screen` button can no longer be placed on top of the other containers. We should find an alternative where to place that.
- [x] Decide zoom control placement vs. will-change performance gains. **Moved to toolbar**
- ~~Placement of details icon / column add th~~ no immediate fix available. I suggest to leave it where it is until we discuss a solid solution without hacks.
- [x] Handle row changes in table and sync them to timeline (group-by, hierarchy)

https://community.openproject.com/projects/openproject/work_packages/25199/activity?query_id=896

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/f7d46884e15a3fd0fb59258d2a71ca1481963170) (deployed commit: 33dcfbdb11e96d68d9cde55802f83a73800a0807).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/e788ade9f9eb2fc6d4b2d01ab1509067d58fe020) (deployed commit: 1ee7653c1127aafe66987aa8f32ef2f73ea91b52).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/9662e7b2e7502c644c45d0290205132b02ad7052) (deployed commit: fd4b5b03c707b0b1c411d871b6d52c1e06106f5c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7bffa55fc945d4aa71a8bbc9cbcedad9a11960d8) (deployed commit: 01ad38517a56c4905edb9534084f16d946a63d3f).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b074571527b4086698bf24dfa54cf36cbe99ad96) (deployed commit: 172992dc128024b511931a68e071b1cd952f4dd6).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/fa7ad328ac9bfcf7428fef915b342dd4a88f1a31) (deployed commit: 596fd36f9953fca6b4074723b814d769a502e96c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/66a67f5cbdffc430775900ec0fa95a4a6aa8d8b1) (deployed commit: b0b24f914daa4823a3c3e3c209c796b45abd447f).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/75b237e53b4c149117c03b291b85eb8b78b061d0) (deployed commit: 9c7918add2b4b9aa400ea1d76558a44a82ab2eec).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/6b4a9a30d77c9e2c6ead4027d50734715630f8bc) (deployed commit: 9c7918add2b4b9aa400ea1d76558a44a82ab2eec).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/781b215c5ace82ddf945f141836c233fafb44c31) (deployed commit: c7546ecbf9473ec0ccc5fdf5f25ad0f8942b3b1c).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4e813873c3fdc750c13526b838bdd92bf37ff5d4) (deployed commit: 222b06f5f8bed047ebfc6be16851f161ceaecf3d).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/aee5b18dba5dfda06e8778b4407ff9a2ae8ab557) (deployed commit: e4377decd4fe663aa293c0336a8cddfec9ab56be).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c014cc70428a206b56ff0e50042cac093194f72f) (deployed commit: cac069941705fdc1e02caa0f5196ad0949a4697b).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/fa7453b4c0c2c0c446f4c011be00907a341d755a) (deployed commit: 5810b565074c9069871658908cddaaa6e63f7cd5).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/8ba4ece6377a1787d58eff036f9158c09407c0b7) (deployed commit: 8d6e4574524ea7f471ddfd9cea99234196a5a21a).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c7dfd574867401557ad09008537e86e861c5b137) (deployed commit: 4cf9790968c1fc29f05e2c6d63e92d877ace806a).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/0614fde7cd00d8d8141b154aea96f02b94f32804) (deployed commit: ab3a1a5d4e71dff74d291fc9d2bb9387d44c025a).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/ca25729f5d044981ac91ee5603a71e7cb8fe70df) (deployed commit: 1d153973b7c694e75826bd8ddcaff9592d5d70d3).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/c78880f5a8f869b2a9f7d270aa1e6adac0afea9d) (deployed commit: ce4bbf969ac05c2de3b8d5f0ede7c4647896e295).

**Comment by oliverguenther** [comment]
Merging in accordance with Roman and Niels, I'll fix the outstanding hierarchies issue on a separate PR.

**Pull request merged**
