### PR TITLE
update faker version

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-release-4-0-faker.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-release-4-0-faker.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@marutosi For test dependencies I prefer to be less specific about the version required. In other words:

``` ruby
gem 'faker', '~> 1.4'
```

**Comment by floriank** [comment]
Is this PR required to be created against the `release/4.0` branch? I can see this change for `dev`, but not the release @myabc @marutosi.

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Pull request closed without merging**
