### PR TITLE
Feature/split types form into tabs

### PR DESCRIPTION
**Pull request by wielinde**

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/e73ca47c1b509a7ba0f65e77de129db205e4dcd0) (deployed commit: 4875141b386280776fe2a7a4038b83571c0600e2).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/814d8674aa8a5290321ff4e84acd73f033c49a44) (deployed commit: 4a805fbef8f70fd0631f29a10241c616b5b88c3b).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/6725f08c88c83985d98a305d308fa74f803875e2) (deployed commit: 0acba977665a067878e019c685b9bc2b451e9783).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/14c57930d1339c04031d48669e6edc12d8558d2b) (deployed commit: 48a126bf5cc1ef67129168d40b61660d87cb1d16).

**Comment by machisuji** [comment]
Looking all good except for the projects tab where there are bullet points in front of the checkboxes. Good to go once that is fixed and travis is green.

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/86843e5e006c6ef402a02fcabad3eab6fe9250d5) (deployed commit: ee290a6c620d9722f9bb34073d929a8317103613).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/053185f8bb0049f8d3458cc4d6df4f5e1f8b6814) (deployed commit: ebea10a4cec2ba17224436a20b650363fc7dcbc5).

**Review by machisuji — APPROVED** [review]
👍

**Pull request merged**
