### PR TITLE
[21876] Scale page for smartphones

### PR DESCRIPTION
**Pull request by mk84**
https://community.openproject.org/work_packages/21876/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mk84-21876-scale-page-for-smartphones.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://mk84-21876-scale-page-for-smartphones.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@mk84 the PR removes the necessity to scroll horizontally and my quick test did not reveal anything breaking. 

There are two reasons why I am not merging this because I feel that especially the first one needs to be discussed (@oliverguenther, @basiszwo, @mk84, @furinvader, @lindenthal):
1) The PR introduces a meta-tag which tells the mobile browsers to make the page non human scaleable, meaning the user cannot zoom in/out. This will probably make it hard for some people to read text like the work package description or comments. The tag was intended for pages that provide zooming themselves, e.g. google maps.
2) The change in the min width is quite risky given that we want to release today. I didn't find anything but it might well be that I have not looked at the right places.

**Comment by mk84** [comment]
@ulferts We can remove the metatag that prevents zooming with the side-effect that the page will zoom in when you tap on an input field.

I really don't know the reason why there was a min-width introduced at all. The only thing that I recognized when I reduced the min-width was that the link to the user-menu dropdown on the right side moved under the blue menubar when the viewport was too small.

This is just a temporary solution to get rid of the horizontal scrolling on smartphones until the app will be full responsive.

**Comment by basiszwo** [comment]
Also reviewed. 
:+1: for removing the scaling tag. @mk84 will update the PR.

**Pull request merged**
