### PR TITLE
17056 Set up Sauce Labs for Protractor tests

### PR DESCRIPTION
**Pull request by myabc**
https://community.openproject.org/work_packages/17056
- [x] Basic setup
- [ ] only run Sauce Connect on JS jobs
- [ ] configure [screen resolution](https://docs.saucelabs.com/reference/test-configuration/#screen-res)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://feature-17056-protractor-sauce-labs.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
https://saucelabs.com/tests/cf6a6d1b140048cab03a80c511626919

**Comment by NobodysNightmare** [comment]
The same questions as for https://github.com/opf/openproject/pull/2784 apply:

I have no idea what this is:
- What is sauce labs?
- Why do we need it?
- Why is the WP description empty?

**Comment by myabc** [comment]
> - What is sauce labs?

https://saucelabs.com/

> - Why do we need it?

Travis only lets us test on one real browser, Firefox. We have no control over the version used.

Sauce Labs would let us run our JavaScript unit and integration (Karma, Protractor) on multiple browsers, including Windows/IE.

> - Why is the WP description empty?

I was in a rush…

**Comment by floriank** [comment]
Would this integrate with github? I never used saucelabs - I think it sounds cool and would add some Mehrwert, but having no experience with it, it would bug me, if i had to go there each time tests are run.

**Comment by myabc** [comment]
@floriank 

> Would this integrate with github?

It integrates with Travis.

There's a problem though: this doesn't work well with the new PR workflow introduced in https://github.com/opf/openproject/pull/2611. We won't be able to test PRs coming from forks. See http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

**Pull request closed without merging**
