### PR TITLE
Fix HTTP 500 on work package show

### PR DESCRIPTION
**Pull request by NobodysNightmare**
https://community.openproject.org/work_packages/19682

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-fix-500-on-wp-show.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-fix-500-on-wp-show.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
@myabc I'd consider not being able to see a work package as rather critical.

Therefore my suggestion would be to merge this without tests and if you like we can add tests later on.

**Comment by myabc** [comment]
:+1: fine.

**Comment by NobodysNightmare** [comment]
Not totally:

@myabc or whoever merges this. Please merge it into `release/4.1`. I started the branch off of there, but failed at making a PR against that branch -.-

**Pull request merged**
