### PR TITLE
references finnlabs rack-protection till jsrf protection closes body

### PR DESCRIPTION
**Pull request by ulferts**
[OP package](https://www.openproject.org/work_packages/3029)
- `#3029` JsonCsrf Protection: Next request after prevented attack fails and kills thread

### CODE REVIEW

**Comment by ulferts** [comment]
@meeee, you wanted the honours.

**Comment by GarstgerUnhold** [comment]
Please open a pull request for https://github.com/rkh/rack-protection as well, we should not maintain our custom gem for long.

**Comment by ulferts** [comment]
Writing @rkh just now. Not sure about the way he wants to deal with something like this, therefore the private message.

**Comment by mfrister** [comment]
:+1:

**Pull request merged**
