### PR TITLE
Delete dependencies link from project sidebar

### PR DESCRIPTION
**Pull request by why-el**
https://community.openproject.org/work_packages/21509/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://why-el-delete-deps-link.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://why-el-delete-deps-link.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
I discussed this with @basiszwo before but unfortunately, the WP on community did not get updated. I did that now. 

Can you please also remove the configuration option on the timelines edit form for the second grouping criterion.

**Comment by why-el** [comment]
I did and also deleted some js/cucumber code. I'll let Travis tell me what's going on.

**Comment by lindenthal** [comment]
Hi Wael, 
what is the status here?
Bests
Niels

**Comment by why-el** [comment]
Running the failed specs locally for some more feedback then I'll merge.

**Pull request merged**
