### PR TITLE
Custom logo upload for EE license owners

### PR DESCRIPTION
**Pull request by wielinde**
OK, I welcome feedback on this branch.

### CODE REVIEW

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7ff398680af3cc6515a16ce39433860062d8834c) (deployed commit: e3817653d218d32d4d7dc648ebf62ed27af819ac).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/e4782194afd763af855a3ac08fe08c4989d8cd61) (deployed commit: a985e2d6d2ac50f6049f2b3beaed1f52a912faef).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/7488eccce1b00380da3a44bcf1618b3cfd8fc304) (deployed commit: a985e2d6d2ac50f6049f2b3beaed1f52a912faef).

**Comment by crohr** [comment]
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b502620ee8d4d4acc827b45d90307b4fa04dc90a) (deployed commit: a985e2d6d2ac50f6049f2b3beaed1f52a912faef).

**Comment by oliverguenther** [comment]
Hi @wielinde , could you extract that PR into the separate features so that I can start reviewing, e.g., the license gem integration?

**Pull request closed without merging**
