### PR TITLE
Add possibility to use username or email to authenticate

### PR DESCRIPTION
**Pull request by alfred-sa**
Hello,

I have recently installed OpenProject and some users where confused about how to login. Some use their username, others their email address.
It is a common practice to accept both as login (see nextcloud for example), so I ended to add this possibility in OpenProject.

It is a very minor change and I don't know if I'm the only one who want that behaviour.

### CODE REVIEW

**Review by ulferts — CHANGES_REQUESTED** [review]
Hi @whuji and thanks for the PR. Sorry it took us so long. It has been a busy week with us working to release 10.3 and having the security release 10.2.2 to churn out.

I get the idea of the feature but it leaves me wondering whether it is a good idea to do so. And if I say I am wondering I actually mean that I don't know. 

There is the scenario where two users share the same password (given the tendency to use weak passwords like `1234567` I assume that scenario is not as far fetched as one might hope). Now if one of those users has the same value for login as the other user has for mail, the two accounts would not be distinguishable when determining the login. Any thoughts on that @whuji?

If we where to implement the feature we would probably have to ensure uniqueness not only with login and mail but also that the chosen login value is not the mail value of another user and vice versa.

And given that we already have a lot of systems out there that have existed for years we would need to ensure that such a data set has not already been created while no validation of the sort existed.

Other than that, we would of course need tests for that altered behaviour.

**Comment by alfred-sa** [comment]
Hi @ulferts 
It is a very common use case to accept both username and email as login. Of course, if we implement it on OpenProject, this commit is not sufficient, we need to add some checks and we need to forbid email addresses as username.
Maybe we can propose this behaviour as a configuration option, disabled by default, and check those requirements if the administrator enables it. If the requirements are not met, then we print an error and the administrator must implement the requirements by him-self.

**Comment by ulferts** [comment]
@whuji, yeah, that would be an option. Guarding that behaviour by a settings makes sense in any case I guess as the behaviour might oppose some enterprise's regulations.

Speaking of settings, there is a setting in OpenProject that sets the login name to be the email address by default (although admins can alter it later):

image

At least for the meantime, that might reduce the confusion you spoke about at first.

So given what you outlined, @whuji, I would be willing to accept a pull request implementing the feature. Let me know if you need anything.

**Comment by alfred-sa** [comment]
I saw this setting, we could alter it to add "username or email".
I will implement it but I don't have the time in the next weeks or so.

**Comment by oliverguenther** [comment]
Hey @whuji , we're closing this for now due to inactivity. Please reopen as soon as you continue working on it.

**Pull request closed without merging**
