### PR TITLE
add style for styleguide input=text input=password

### PR DESCRIPTION
**Pull request by vcostin**
[`* `#19223` UI Inputs: text and passwords in "Living Style Guide"`](http://community.openproject.org/work_packages/19223)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://vcostin-feature-19223-text-and-passwords-in-styleguide.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://vcostin-feature-19223-text-and-passwords-in-styleguide.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by floriank** [comment]
Looks good to me from a folder structure perspective - this can be changed later anyway, so: :+1:

**Comment by ulferts** [comment]
@vcostin needs rebase/merge

**Comment by myabc** [comment]
Styling elements directly is not, IMO, the right way to proceed. I'd like to keep this on hold.

**Comment by floriank** [comment]
I think this was only to to coordinate the folder structure @vcostin would use.

**Comment by vcostin** [comment]
This PR was for work tune for me, an example for github flow. I mentioned if I can create a PR that will not be merged. This branch can be deleted if is making confusion.

**Pull request closed without merging**
