### PR TITLE
CkEditor bumped to V25

### PR DESCRIPTION
**Pull request by aleixsuau**
https://community.openproject.com/work_packages/35797

This pull request:

- [x] Updates CkEditor to v25

### CODE REVIEW

**Comment by oliverguenther** [comment]
Hi @aleixsuau , as we already discussed on wednesday, v25 is already out https://github.com/ckeditor/ckeditor5/releases

Could you please update to that directly?

Best
Oliver

**Comment by oliverguenther** [comment]
related to ticket https://community.openproject.com/work_packages/35797

**Comment by aleixsuau** [comment]
OMG,  I confused the number. Sure, done.

**Review by oliverguenther — APPROVED** [review]
:+1:

**Pull request merged**
