### PR TITLE
Start correcting single quotes

### PR DESCRIPTION
**Pull request by toy**
This will probably create some conflicts with current PRs, but there is no way around it.

Finding the most changed files using:
```shell
git log --name-only --since="5 years" --pretty=format: Gemfile '*.rb' | grep -v '^$' | sort | uniq -c | sort -g | tail -n 10
```

### CODE REVIEW

**Comment by toy** [comment]
@cbliard I thought we should limit it to something smaller, like `/[a-z0-9.\-_]/`?

**Comment by cbliard** [comment]
@toy the warning was about having overlapping character classes in the character ranges. I only removed the duplicates to fix this warning. I did not question if `[a-zA-Z0-9_.\-]` (same as `[\w.\-]`) is actually relevant or if it should be limited to a shorter range. I assumed the range had been chosen for a reason and that there are valid uses of all the characters in the range.

And searching in history, c41ea1ed48b "Fix restricting the rev only to lowercase tags" changed `/[a-z0-9\.\-_]+/` to `/[\w0-9\.\-_]+/`. That's where the duplication first appeared, so I think `[\w.\-]` is ok.

**Comment by toy** [comment]
@cbliard Thanks for checking history

**Review by cbliard — APPROVED** [review]
We are finally moving forward with this. Thanks for taking care of it!

**Pull request merged**
