### PR TITLE
Remove webdrivers once more, let selenium handle chromedriver

### PR DESCRIPTION
**Pull request by oliverguenther**
In the tradition of https://github.com/opf/openproject/pull/13190, try again to remove webdrivers

### CODE REVIEW

**Comment by klaustopher** [comment]
Same problem :(

**Comment by aaron-contreras** [comment]
❗️❤️

**Comment by klaustopher** [comment]
Looks good 👍

**Review by klaustopher — APPROVED** [review]

**Comment by oliverguenther** [comment]
Restarted a few times, it seems to be happy. So the reason is an exception (e.g, retry) happening when switching between cuprite and non-cuprite. It then does not restart the chromedriver instance as expected.

**Comment by oliverguenther** [comment]
https://community.openproject.org/projects/openproject/work_packages/49773/activity?query_id=4623

**Pull request merged**
