### PR TITLE
change format of string-objects URL

### PR DESCRIPTION
**Pull request by NobodysNightmare**
## OpenProject work package

Fixes **another** issue with https://community.openproject.org/work_packages/18571.

Thanks to @Azure7111 for his rigorous testing ^^

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://nobodysnightmare-feature-string-objects-with-dots.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://nobodysnightmare-feature-string-objects-with-dots.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
:+1:

**Comment by myabc** [comment]
@NobodysNightmare specs fail :(

**Comment by NobodysNightmare** [comment]
Good thing! They must have noticed that I did not update the documentation ^^

**Pull request merged**
