### PR TITLE
Gemfile: pin globalize

### PR DESCRIPTION
**Pull request by marutosi**
https://github.com/opf/openproject/pull/2212#issuecomment-63673849

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-gemfile-globalize.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
:+1:

**Comment by myabc** [comment]
message_arigatou

**Comment by ulferts** [comment]
I merged #2236 with the restriction (=3.0.0) because I want to have as few changes to the backport branch as possible. For 4.0 I would rather have ~> 3.0.0 because change on a patch level should be possible here.

**Comment by myabc** [comment]
@marutosi please change to `~> 3.0.0`

**Pull request closed without merging**
