### PR TITLE
Update openproject-edition addon to use dotnet runtime 6.0

### PR DESCRIPTION
**Pull request by crohr**
https://community.openproject.org/work_packages/44339/activity

### CODE REVIEW

**Comment by oliverguenther** [comment]
:warning: please rebase onto `release/12.3` and change the target branch

**Review by wielinde — COMMENTED** [review]
@crohr The PR looks really good. However, I didn't run it anywhere. Did you test it on real instances with various distros? Or do you need me to get VMs for many distros and install the package? Would we need to move this PR to a Git branch that is prefixed with `packaging/`? So my question is basically regarding how to QA a PR like this one here.

**Comment by crohr** [comment]
> @crohr The PR looks really good. However, I didn't run it anywhere. Did you test it on real instances with various distros? Or do you need me to get VMs for many distros and install the package? Would we need to move this PR to a Git branch that is prefixed with `packaging/`? So my question is basically regarding how to QA a PR like this one here.

I'll take care of it, since I have tests in place that can conditionally fetch new versions of addons before they are packaged.

**Comment by wielinde** [comment]
> > @crohr The PR looks really good. However, I didn't run it anywhere. Did you test it on real instances with various distros? Or do you need me to get VMs for many distros and install the package? Would we need to move this PR to a Git branch that is prefixed with `packaging/`? So my question is basically regarding how to QA a PR like this one here.
> 
> I'll take care of it, since I have tests in place that can conditionally fetch new versions of addons before they are packaged.

Perfect. Thanks.

**Comment by crohr** [comment]
@wielinde I can confirm this works. There seems to be an unrelated issue on the SLES12 I'm testing on, but this shouldn't block from merging this.

**Pull request merged**
