### PR TITLE
Feature/add query schema

### PR DESCRIPTION
**Pull request by ulferts**
Extracts the schema part of #5157 to better handle the large chunk of work. As such, it implements:

https://community.openproject.com/projects/openproject/work_packages/24620

### Implementation approach

For most of the end points, the responses can be seen as part of the excerpt below which displays the schema part of the form response:

```
{
  "_type": "Schema",
  "_links": {
    "self": {
      "href": "/api/v3/projects/1/queries/schemas"
    }
  },
  "id": {
    "type": "Integer",
    "name": "ID",
    "required": true,
    "hasDefault": false,
    "writable": false,
  },
  "name": {
    "type": "String",
    "name": "Name",
    "required": true,
    "hasDefault": false,
    "writable": true,
    "minLength": 1,
    "maxLength": 255
  },
  "user": {
    "type": "User",
    "name": "User",
    "required": true,
    "hasDefault": false,
    "writable": false
  },
  "project": {
    "type": "Project",
    "name": "Project",
    "required": false,
    "hasDefault": false,
    "writable": true,
    "_links": {
      "allowedValues": {
        href: "/api/v3/queries/available_projects"
      }
    }
  },
  "public": {
    "type": "Boolean",
    "name": "Public",
    "required": false,
    "hasDefault": true,
    "writable": true
  },
  "sums": {
    "type": "Boolean",
    "name": "Display sums",
    "required": false,
    "hasDefault": true,
    "writable": true
  },
  "starred": {
    "type": "Boolean",
    "name": "Starred",
    "required": false,
    "hasDefault": true,
    "writable": true
  },
  "groupBy": {
    "type": “[]QueryGroupBy”,
    "name": "Group by",
    "required": false,
    "hasDefault": true,
    "writable": true,
    “_embedded”: {
      “allowedValues”: [
        {
          “type”: “GroupBy”,
          “id”: “status”,
          “name”: “Status”,
          “_links”: {
            “self”:
              “href”: “/api/v3/queries/group_bys/status”
        },
        <-- omitted for brevity -->
        {
          “type”: “GroupBy”,
          “id”: “assignee”,
          “name”: “Assignee”,
          “_links”: {
            “self”:
              “href”: “/api/v3/queries/group_bys/assignee”
        }
      ]
    },
    "_links": {
      “allowedValues”: [
        {
          “href”: “/api/v3/queries/group_bys/status”
          “title”: “Status"
        },
        <-- omitted for brevity -->
        {
          “href”: “/api/v3/queries/group_bys/assignee”
          “title”: “Assignee"
        }
      ]
    }
  },
  "filters": {
    "type": “[]QueryFilterInstance”,
    "name": "Filters",
    "required": true,
    "hasDefault": false,
    "writable": true,
    “_links”: {
     “schemas”: “/api/v3/projects/1/queries/filters_schemas”
  },
  "columns": {
    "type": “[]QueryColumn",
    "name": "Selected columns",
    "required": true,
    "hasDefault": false,
    "writable": true,
    “_embedded”: {
      “allowedValues”: [
        {
          “type”: “QueryColumn”,
          “id”: “status”,
          “name”: “Status”,
          “_links”: {
            “self”: {
              “href”: “/api/v3/queries/columns/status”
            }
        },
        {
          “type”: “QueryColumn”,
          “id”: “assignee”,
          “name”: “Assignee”,
          “_links”: {
            “self”: {
              “href”: “/api/v3/queries/columns/assignee”
            }
         },
         <-- omitted for brevity -->
         {
           “type”: “QueryColumn”,
           “id”: “customField1”,
           “name”: “List CF”,
           “_links”: {
             “self”: {
               “href”: “/api/v3/queries/columns/customField1”
             }
           }
         }
      ]
    },
    "_links": {
      “allowedValues”: [
        {
          “href”: “/api/v3/queries/columns/status”
          “title”: “Status"
        },
        {
          “href”: “/api/v3/queries/columns/assignee”
          “title”: “Assignee"
        },
        <-- omitted for brevity -->
        {
          “href”: “/api/v3/queries/columns/customField1”
          “title”: “List CF"
        }
      ]
    }
  },
  "sortBy": {
    "type": “[]QuerySortBy”,
    "name": “Sort criteria“,
    "required": true,
    "hasDefault": false,
    "writable": true,
    “_embedded”: {
      “allowedValues”: [
        {
          "_type": "QuerySortBy",
          "id": "status-asc",
          "name": "Status (Ascending)",
          "_links": {
            "self": {
              "href": "/api/v3/queries/sort_bys/status-asc",
              "title": "Status (Ascending)"
            },
            "column": {
              "href": "/api/v3/queries/columns/status",
              "title": "Status"
            },
            "direction": {
              "href": "urn:openproject-org:api:v3:queries:directions:asc",
              "title": "Ascending"
            }
          }
        },
        {
          "_type": "QuerySortBy",
          "id": "status-desc",
          "name": "Status (Descending)",
          "_links": {
            "self": {
              "href": "/api/v3/queries/sort_bys/status-desc",
              "title": "Status (Descending)"
            },
            "column": {
              "href": "/api/v3/queries/columns/status",
              "title": "Status"
            },
            "direction": {
              "href": "urn:openproject-org:api:v3:queries:directions:desc",
              "title": "Descending"
            }
          }
        },
        <-- omitted for brevity -->
        {
          "_type": "QuerySortBy",
          "id": "customField1-desc",
          "name": "List cf (Descending)",
          "_links": {
            "self": {
              "href": "/api/v3/queries/sort_bys/customField1-asc",
              "title": "List cf (Descending)"
            },
            "column": {
              "href": "/api/v3/queries/columns/customField1",
              "title": "List cf"
            },
            "direction": {
              "href": "urn:openproject-org:api:v3:queries:directions:desc",
              "title": "Descending"
            }
          }
        }
      ]
    },
    "_links": {
      "allowedValues": [
        {
          "href": “/api/v3/projects/1/queries/sort_bys/status-asc”,
          "title": "Status (Ascending)
        },
        {
          "href": “/api/v3/projects/1/queries/sort_bys/status-desc”,
          "title": "Status (Descending)
        }
        <-- omitted for brevity -->
        {
          "href": “/api/v3/projects/1/queries/sort_bys/customField1-desc”,
          "title": "List cf (Descending)
        }
      ]
    }
  },
  "results": {
    "type": "WorkPackageCollection",
    "name": "Results",
    "required": false,
    "hasDefault": true,
    "writable": false
  }
  "_embedded": {
    “filtersSchemas”: {
      “_type”: “Collection”,
      “total”: “15”,
      “count”: “15”,
      “_embedded”: {
        “elements”: [
          {
            “_type”: “StatusFilterSchema”,
            “_name”: “Status”,
            “name”: {
              "type": “String”,
              "name": “Name”,
              "required": true,
              "hasDefault": true,
              "writable": false
            },
            “filter”: {
              "type": “Filter”,
              "name": “Filter”,
              "required": true,
              "hasDefault": false,
              "writable": true,
              "_links": {
                "allowedValues": [
                  "/api/v3/queries/filters/status”
                ]
              }
            },
            “_dependencies”: {
              “_type”: “SchemaDependency”,
              “from”: “operator”,
              “to”: “values”,
              “options“: [
                {
                  “_type”: “SchemaDependencyOption”,
                  “_name”: “equals”,
                  “operator”: {
                    “type”: “FilterOperator”,
                    “name”: “Operator”,
                    “required”: true,
                    “writable”: true,
                    “hasDefault”: false,
                    “_links”: {
                     “allowedValues”: [
                       “/api/v3/queries/operators/=“
                     ]
                    }
                  },
                  “values”: {
                    “type”: “Status”,
                    “name”: “Value”,
                    “required”: true,
                    “writable”: true,
                    “hasDefault”: false
                    "_embedded": {
                      "allowedValues": [
                        {
                          "_type": "Status",
                          <-- omitted for brevity -->
                        },
                        <-- omitted for brevity -->
                      ]
                    “_links”: {
                      “allowedValues”: [
                        {
                          “href”: “/api/v3/statuses/1”
                          "title": "new"
                        }
                        <-- omitted for brevity -->
                      ]
                    }
                  }
                }
                <-- omitted for brevity -->
              ]
            }
          }
          <-- omitted for brevity -->
        ]
      }
    }
  }
}
```

### ToDos

- [x] `GET /api/v3/queries/schema`
- [x] `GET /api/v3/projects/:project_id/queries/schema`
- [x] Implement query schema representer
- [x] `GET /api/v3/queries/available_projects`
- [x] `GET /api/v3/queries/filters_schemas`
- [x] `GET /api/v3/projects/:project_id/queries/filters_schemas`
- [x] Implement query filter schema representer
- [x] `GET /api/v3/projects`
- [x] `GET /api/v3/principals`
- [x] `GET /api/v3/roles`
- [x] `GET /api/v3/roles/:id`
- [x] `GET /api/v3/versions`
- [x] Document

### CODE REVIEW

**Comment by ulferts** [comment]
Regarding code climate:

* I deactivated the BlockLength rubocop rule because given how roar is written, I deem it impossible to achieve the goal.
* The TODO is legitimate for the time being as we will not flesh out the roles representer right now.

**Comment by oliverguenther** [comment]
bildschirmfoto 2017-02-10 um 16 10 06


Some of the dependencies of various `QueryFilterInstanceSchema` are empty objects (cf., screenshot). What's the reasoning behind that?

**Comment by ulferts** [comment]
I wanted to acknowledge the existence of the value while communicating that when that value is selected, no additions to the schema are made. In case of the filters, this can then communicate that no `values` property exists for certain values of the `operator` property, while for other values an `[1]Integer` types `values` property exists. And for still other values, the `values` property will be of type `[2] DateTime`.

The alternative would have been to not have those values listed at all. But then the intend would not be as clear IMO.

**Comment by oliverguenther** [comment]
Okay, fine for me then. 👍

**Pull request merged**
