### PR TITLE
CSV export is fixed

### PR DESCRIPTION
**Pull request by TribesTom**
Hello here is the fix for bug : CVS export is fixed

https://community.openproject.org/work_packages/16813
Thanks

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://tribestom-stable.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by ulferts** [comment]
Thank you for the PR @TribesTom. We will take a look at it. The thing I noticed so far has nothing to do with the code. We don't issue PRs against the stable branch. The stable of OP is just a mirror for the current release (4.0.4 currently) that allows users to easily track the most current version of OP. If we where to merge your PR into stable, it would be overwritten by the next mirror merge from release/4.0 to stable.

Would you be so kind to open a new PR against release/4.0?

The failing specs might only have to do with some stubbing not working any more. I can take a look at those if you want to.

**Comment by ulferts** [comment]
@TribesTom, you should not use the user "Openproject" for the commits. That does not help with the git history when one wonders who to ask.

**Comment by TribesTom** [comment]
Sorry I'm not used to use participating developpement more than pull :p

2014-12-18 14:15 GMT+01:00 ulferts notifications@github.com:

**Comment by ulferts** [comment]
Closed in favour of #2366

**Pull request closed without merging**
