### PR TITLE
Fix for 500 of /projects URL which sorted by latest_activity_at

### PR DESCRIPTION
**Pull request by Eric-Guo**
I'm not sure this fix is right or not in implementation, but at least it resolve the 500 error at [THAPE staging server](https://plm-ppp.thape.com.cn/projects?query_id=my&sortBy=%5B%5B%22latest_activity_at%22%2C%22asc%22%5D%5D)

image

### CODE REVIEW

**Comment by klaustopher** [comment]
Could you write a proper bug report for the behavior you are seeing and when you encounter that error? Sorting by the last activity does not show a 500 here.

**Comment by klaustopher** [comment]
You could also add a failing spec, that we could start working off

**Comment by Eric-Guo** [comment]
OP#55783 [created](https://community.openproject.org/wp/55783).

**Comment by Eric-Guo** [comment]
@klaustopher I also add a spec, the implementation is correct, but the key problem is I have to introduce `Class Current < ActiveSupport::CurrentAttributes` to store the project model.

**Comment by klaustopher** [comment]
@Eric-Guo Thanks for the failing spec, can you try #15883 and see if this fixes your problem?

**Pull request closed without merging**
