### PR TITLE
[32766] Align checkboxes correctly

### PR DESCRIPTION
**Pull request by ingamai**
See tickets: 
https://community.openproject.com/projects/openproject/work_packages/32766
https://community.openproject.com/projects/openproject/work_packages/33488

### CODE REVIEW

**Review by HDinger — COMMENTED** [review]
Hi @ingamai looks good overall 👍 I have only minor remarks:

Lists, ToDo-Lists and Enumerations are not aligned (in comments and description):
Bildschirmfoto 2020-06-12 um 09 19 02
Bildschirmfoto 2020-06-12 um 09 19 15

When I have a very long word it is wrapped to a new line in the editor, but looks differently in the display mode. However, as this is an edge case and happens only in Chrome, I would classify this as low priority and nice to have.
Bildschirmfoto 2020-06-12 um 09 23 09

**Review by HDinger — COMMENTED** [review]
Hi @ingamai 
there is one thing left: enumerations are offset in the comments:
Bildschirmfoto 2020-06-18 um 14 20 46

Interestingly they are correctly aligned in the WP description

**Comment by ingamai** [comment]
> Hi @ingamai
> there is one thing left: enumerations are offset in the comments:
> Interestingly they are correctly aligned in the WP description


@HDinger There was an extra rule for the list margin in the comment section. I removed this and hope that this does not break anything. So now it looks like this:

Screenshot 2020-06-18 at 22 23 30

**Review by HDinger — APPROVED** [review]
👍

**Comment by HDinger** [comment]
Merging as the failing test is unrelated

**Pull request merged**
