### PR TITLE
Frontend style guide first round

### PR DESCRIPTION
**Pull request by aleixsuau**
https://community.openproject.com/projects/openproject/work_packages/35548

This pull request:

- [x] Creates a first proposal of the OpenProject frontend style guide.

### CODE REVIEW

**Comment by b12f** [comment]
Hi @aleixsuau, can you add the eslint config and ci checks as well?

**Comment by aleixsuau** [comment]
Hi @b12f  ,

This is a [separate work package](https://community.openproject.com/projects/openproject/work_packages/35907/relations?query_id=2563). I'm not used to this kind of configurations so it is probably better that you or Oliver do that.

**Review by b12f — APPROVED** [review]

**Review by oliverguenther — CHANGES_REQUESTED** [review]
Hi @aleixsuau , I suggest we get rid of the manual table of contents as the docs page will automatically generate one. This will be less effort to maintain and avoid errors in the long run.

Rest LGTM, thanks :+1:

**Comment by aleixsuau** [comment]
Hi @oliverguenther,

Thanks for your feedback, I didn't know that. Removed.

**Pull request merged**
