### PR TITLE
fix workpackage collapse icon is covered by scrollbar on windows system

### PR DESCRIPTION
**Pull request by 0xF013**
[`* `#16129` workpackage collapse icon is covered by scrollbar on windows system`](http://community.openproject.org/work_packages/16129)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://0xf013-feature-16129-wp-collapse-icon-is-covered-by-scrollbar-o.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by hschink** [comment]
This looks pretty good! I found two issues though:
1. The bottom of the scrollbar is not visible (see screenshot below).
2. The scrollbar does not disappear in Firefox (I guess this is a minor issue).

16129_scrollbar_bottom_not_visible

**Comment by 0xF013** [comment]
@hschink I forgot about Firefox, will check for a solution for it as well with a browser-specific rule.

**Comment by 0xF013** [comment]
@hschink I made the element's position relative, it would be cool to check if doesn't break anything (I tested in all browsers but maybe there are some cases).

About FF and Chrome on Windows: there is no solution with a custom CSS rule but there is a hack that puts the element into a wrapper with a strict width and the scrollbar is not visible but works. I am not sure if that is an acceptable or/and needed solution.

**Comment by ulferts** [comment]
@0xF013 looks good. About the hack: I guess we would first have to implement something to replace the scrollbar so that the user knows that he can scroll (.e.g small arrows at the top/bottom when he can scroll, omitting how far he can scroll). So no need for it now.

**Pull request merged**
