### PR TITLE
Removed minimum length requirement for filtering work packages based on textual attributes

### PR DESCRIPTION
**Pull request by hklement**
This resolves the following issue: https://community.openproject.org/work_packages/18278

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hklement-feature-work-packages-text-filter.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hklement-feature-work-packages-text-filter.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@hklement a lot's changed on dev since you created your branch.. would you mind rebasing against dev?

**Comment by hklement** [comment]
Okay, no problem.

**Comment by myabc** [comment]
@hklement thanks again. There are a few too many merge commits … :disappointed:  I think rebase would work better here.

**Comment by hklement** [comment]
Okay, I see your point. It should be fine this time.

**Comment by ulferts** [comment]
LGTM. Thanks.

**Comment by myabc** [comment]
@hklement @ulferts sorry for giving real feedback way too late (_mea culpa_). I think we should consider adding a debounce here. A subject with a single character is probably an edge-case. Firing off the request immediately will make for very sluggish filtering (and a lot of hits on our server!).

[This article](http://blog.thoughtram.io/angularjs/2014/10/19/exploring-angular-1.3-ng-model-options.html) has a nice description of how to configure debounce with `ng-model-options`.

**Comment by ulferts** [comment]
@myabc sorry, I assumed there already was one.

**Comment by myabc** [comment]
@ulferts no :crying_cat_face:

**Comment by myabc** [comment]
Created a small PR: #2491

**Pull request merged**
