### PR TITLE
Bug #25378 [release/7.0] subject and back button alignment

### PR DESCRIPTION
**Pull request by wielinde**
Extra branch for `release/7.0` for https://community.openproject.com/projects/openproject/work_packages/25378/activity

### CODE REVIEW

**Comment by oliverguenther** [comment]
Already merged from in https://github.com/opf/openproject/pull/5565 since mergable without conflict.

**Comment by wielinde** [comment]
@oliverguenther I am confused. Was not it the idea of having these commits in branch `release/7.0`? If you merged them, why can't I see them?

**Comment by oliverguenther** [comment]
You're right, i believed #5565 was still targeting release/7.0, but you confused me by switched the target to dev. We don't need two separate PRs if there is one targeting the release branch. Anyway, I've cherry-picked them to release/7.0 now.

**Comment by wielinde** [comment]
Oh, I see. Yes, I changed the target back to `dev` as there were too many non related commits otherwise. All good now. Thank you.

**Pull request closed without merging**
