### PR TITLE
adds the code climate badge to the readme

### PR DESCRIPTION
**Pull request by linki**
not a highscore, unfortunately

### CODE REVIEW

**Comment by myabc** [comment]
@linki I thought @meeee disabled coverage reporting? (see 57ec29eaa3f67f271561e0d2d980610c942691f0)

**Comment by mfrister** [comment]
Yep, and I opened a ticket on code climate's test reporter repo: https://github.com/codeclimate/ruby-test-reporter/issues/49

Seems they're working on it :)

**Comment by linki** [comment]
code climate offers two badges, one for the overall score - which seems to work fine - and one for coverage, which just displays "unknown" currently: https://codeclimate.com/github/opf/openproject/badges.

this pull requests only adds the badge for the former.

**Comment by myabc** [comment]
@linki ok thanks for clarification!

**Comment by linki** [comment]
@myabc i messed it up. this shows the badge for the master branch only, which is quite old. see https://github.com/opf/openproject/pull/1833 for the fix.

**Pull request merged**
