### PR TITLE
Editing of custom fields of type "Date"

### PR DESCRIPTION
**Pull request by knight-bubble**
[`* `#19614` Date custom fields are not editable`](http://community.openproject.org/work_packages/19614)
also
 [`* `#17219`  Inplace editing for custom values of format "Date"`](http://community.openproject.org/work_packages/17219)
and old discussions #2834

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://hirtie-maxim-feature-17219-custom-values-date-2.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://hirtie-maxim-feature-17219-custom-values-date-2.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by knight-bubble** [comment]
@floriank, it was did that way specially. In that way the datepicker doesn't trigger events, which changes the input values.

**Comment by knight-bubble** [comment]
And what about ng-change, I don't use it because it has to be used along with ng-model and it adds some troubles working with jQueryUI datepicker, I already forget what kind of troubles I had with it :disappointed_relieved:

**Comment by floriank** [comment]
The point on `ng-model` is of course correct - I forgot that.

**Comment by 0xF013** [comment]
the custom fields seems to be editable, but of course it pertains the issues that are going to be fixed in other PR's.

**Comment by knight-bubble** [comment]
@floriank that's what I do now, but it seems to not work.

**Comment by 0xF013** [comment]
I say we merge this to add the current datepicker functionality to the custom fields and deal with the issues (date format, focus etc.) in other PR's that are currently WIP. WDYT @myabc @floriank ?

**Comment by myabc** [comment]
@0xF013 sounds ok!

**Comment by floriank** [comment]
@0xF013 late to the party, but yeah.

**Pull request merged**
