### PR TITLE
[19714] Priority is no longer mandatory

### PR DESCRIPTION
**Pull request by basiszwo**
https://community.openproject.org/work_packages/19714/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://basiszwo-19714-priority.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://basiszwo-19714-priority.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by basiszwo** [comment]
@lindenthal is it a problem to merge this?

**Comment by ulferts** [comment]
The front end does still mark priority as being mandatory. This is due to the schema representer not specifying `required: false` around https://github.com/opf/openproject/blob/dev/lib/api/v3/work_packages/schema/work_package_schema_representer.rb#L167-L174

**Comment by ulferts** [comment]
The DB does still have a not null constraint on the `priority_id` field in the `work_packages` table. The same is true for the `work_packages_journals` table.

As a side note, there is no index on the priority_id field, which should exist as it is a foreign key.

**Comment by ulferts** [comment]
Work packages inherit the priority value from their children. The work package receives the maximum of the priority of it's children. With the introduction of null values there is an unspecified case now. If the child does not have a priority, what should the parent's priority be? It currently keeps the priority it has had before adding a child.

**Comment by ulferts** [comment]
The summary table does not list work packages without a priority:
image

**Comment by ulferts** [comment]
It is not possible to filter for work packages without a priority:
image

**Comment by lindenthal** [comment]
we also need to update the API documentation

**Comment by ulferts** [comment]
Closing as this is currently not actively pursued.

**Pull request closed without merging**
