### PR TITLE
19723 ui select timeline report cut off

### PR DESCRIPTION
**Pull request by vcostin**
https://community.openproject.org/work_packages/19723

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://vcostin-bug-19723-ui-select-timeline-report-cut-off.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://vcostin-bug-19723-ui-select-timeline-report-cut-off.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by myabc** [comment]
@vcostin I set this as WIP because of a) the caveats you listed b) I should be able to take care of this as part of WP [19766](https://community.openproject.org/work_packages/19766)

**Comment by floriank** [comment]
@myabc Is this then superseded by your upcoming PR for [19766](https://community.openproject.org/work_packages/19766)?

**Comment by myabc** [comment]
We need to revert 5dea05c and come up with a better solution.

**Comment by myabc** [comment]
Reverted (as https://github.com/opf/openproject/commit/3574c19696ad9f7020bfb489f9d6bb4ccdff9e37)

**Pull request merged**
