### PR TITLE
Do not change project when moving cards in Kanban board

### PR DESCRIPTION
**Pull request by cbliard**
https://community.openproject.org/wp/44895

The values to apply when moving cards were taken from filters, and if the project filter was present, it would set the project.

### CODE REVIEW

**Comment by cbliard** [comment]
I would need help to create a unit test for this.

**Comment by oliverguenther** [comment]
There's no way to unit test this, but I can help you set up a feature spec for it.

**Review by oliverguenther — APPROVED** [review]

**Review by oliverguenther — APPROVED** [review]

**Comment by cbliard** [comment]
Wouldn't the feature spec be a bit weird to read? The test name would look like 'Adding a project filter and moving cards between column does not change card columns'.
And I tried looking if it was possible to have the same kind of bug with other fields like assignee or priority, but I did not manage to reproduce it. Yet it goes through the `WorkPackageFilterValues`, passing in the query filters, so I do not understand why it does it for project filter, but not for other filters.

**Comment by cbliard** [comment]
It should be ok now. Thanks for your help @oliverguenther!

**Pull request merged**
