### PR TITLE
[55344] Fix close button label of drop-modal

### PR DESCRIPTION
**Pull request by cbliard**
https://community.openproject.org/wp/55344

### CODE REVIEW

**Review by HDinger — COMMENTED** [review]
I am wondering whether it would not be better, to either adapt the usage in code to `i18n.t('js.spot.drop_modal.Close')` or even use an existing string `i18n.t('js.button_close')`. 
When we change the key in the translation file, it will be treated as completely new object, meaning that for all other languages this will not be translated. What do you think?

**Comment by cbliard** [comment]
I thought that "Close" is not a complicated string to translate, so yeah, it will need retranslating if it was already translated. 

I also thought that it's a shame that this label `js.spot.drop_modal.Close` is the same as for `js.button_close` and that there is no clue in the key that it's for screen readers. Label could have been "Close modal", but probably just "Close" is enough for people being familiar with a screen reader.

And I also thought that `js.spot.drop_modal.Close` is incorrect anyway. i18n keys should always be lower case. Not sure if i18n-tasks has something to prevent that.

**Comment by HDinger** [comment]
> I also thought that it's a shame that this label js.spot.drop_modal.Close is the same as for js.button_close and that there is no clue in the key that it's for screen readers. Label could have been "Close modal", but probably just "Close" is enough for people being familiar with a screen reader.

I agree with that. So maybe we should take the opportunity, correct the key and change the text as well. Then it would have to be re-translated anyway.

**Comment by cbliard** [comment]
> > I also thought that it's a shame that this label js.spot.drop_modal.Close is the same as for js.button_close and that there is no clue in the key that it's for screen readers. Label could have been "Close modal", but probably just "Close" is enough for people being familiar with a screen reader.
> 
> I agree with that. So maybe we should take the opportunity, correct the key and change the text as well. Then it would have to be re-translated anyway.

I'm not sure of what you've agreed with. Use the generic `js.button_close` or change text to be "Close modal"? I'll assume the latter and change it accordingly.

Also unrelated: there is this "focus anchor" for the modal. I do not clearly understand what it does, but when voice over is activated, it can't be focused while the modal is open (tried on Firefox and Chrome), and once the modal is closed, it happily says "This is a focus anchor for modals. Press shift+tab to go back to the modal trigger element.". Is it the intended behavior? Why is the focus not given back to the select list drop-down button?

**Comment by HDinger** [comment]
> I'm not sure of what you've agreed with. Use the generic js.button_close or change text to be "Close modal"? I'll assume the latter and change it accordingly.

Yes, I meant the latter 👍 

> Also unrelated: there is this "focus anchor" for the modal. I do not clearly understand what it does, but when voice over is activated, it can't be focused while the modal is open (tried on Firefox and Chrome), and once the modal is closed, it happily says "This is a focus anchor for modals. Press shift+tab to go back to the modal trigger element.". Is it the intended behavior? Why is the focus not given back to the select list drop-down button? 

I don't know for sure 🤷‍♀️ I assume that we wanted a clear (and easily findable) point to go back to in case the modal is doing some stuff that looses the original focus order (e.g. a reload or something), but that is only a guess..

**Pull request merged**
