### PR TITLE
Add support for BIM edition selection in packages

### PR DESCRIPTION
**Pull request by crohr**
This adds support for the BIM edition for the following distributions:

* RHEL/CentOS 8
* Ubuntu 20.04
* Debian 10

Test packages can be found on https://packager.io/gh/opf/openproject/refs/packaging

### CODE REVIEW

**Comment by oliverguenther** [comment]
If I understand the added addon correctly, this will result in everyone getting a new wizard question, even existing installations that likely have nothing to do with BIM (and possibly don't know what to select here).

Could we update the wizard step so that if the package already has been configured, it's skipping this step? Users switching to the BIM edition can then simply run `reconfigure` ?

**Comment by crohr** [comment]
@oliverguenther good point. I think I could check whether `server/autoinstall` has already been answered, in which case the wizard doesn't show up. I'll fix the addon and comment here once it's ready.

**Comment by crohr** [comment]
@oliverguenther added the check here: https://github.com/opf/addon-openproject-edition/commit/c45cdedf64a8e0e8e563a67632d81bfee23d004e

So I think this is good to merge.

**Comment by crohr** [comment]
@wielinde is there anything blocking for a review of the packages? Let me know if I can help :)

**Comment by wielinde** [comment]
@crohr Sorry Cyril, at the moment I simply didn't find the time. I'll start testing today.

**Review by wielinde — APPROVED** [review]
Hey @crohr, I generally approve this PR. However, there is a problem with https://github.com/opf/addon-openproject-edition/blob/3e33edf4fc730f5449c6b88569fbfe2e2bfe9705/bin/preinstall#L49. The current master of `xeokit-gltf-to-xkt` seems to be broken. We need some version pinning here first before we can release this, I believe. Therefore I provided this PR https://github.com/opf/addon-openproject-edition/pull/1

**Pull request merged**
