### PR TITLE
[21264] Show file upload widget only when "show all" is enabled

### PR DESCRIPTION
**Pull request by floriank**
This will enable showing the of the file upload widget during the creation and the showing of Work Packages in the details pane.

https://community.openproject.org/work_packages/21264

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://floriank-feature-hide-files-in-wp-standard-form.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://floriank-feature-hide-files-in-wp-standard-form.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Hm @floriank, it does hide/show the attachment section as desired when clicking on the button. But it also hides it even when there are attachments already present. To be consistent it should IMO:
- hide the section if no files are attached and if the button is not pressed
- show the section if files are attached regardless of whether the button is pressed
- show the section regardless of whether files are attached if the button is pressed

Does that make sense to you?

**Comment by ulferts** [comment]
https://community.openproject.org/work_packages/21264

**Comment by floriank** [comment]
Okay, I'll do the changes, the ticket is contrary to a discussion I had about this.

I'll update the functionality to include showing when there are files attached already.

**Comment by floriank** [comment]
Okay, the existance of files should now be checked first for existing work packages

**Comment by ulferts** [comment]
Works good and I will not ask for tests. 

The `console.log` statement should be removed however.

Will wait for travis...

**Comment by floriank** [comment]
I took the liberty and corrected a mistake in the protractor suite which [was introduced by a certain someone](https://github.com/floriank/openproject/commit/305910ba7a4b2cd1018ac8bf412d470f32a1ae32).

The test suite should run in full again.

**Comment by floriank** [comment]
Incidentally, this also covers https://community.openproject.org/work_packages/21263

**Comment by oliverguenther** [comment]
Can you merge or rebase on dev to include the changes made by https://github.com/opf/openproject/pull/3397, fixing the broken protractor example ?

**Comment by floriank** [comment]
done.

**Comment by oliverguenther** [comment]
Briefly confirmed that the rebase did not break anything in the frontend. Looks good.

**Pull request merged**
