### PR TITLE
Feature: timelog for others

### PR DESCRIPTION
**Pull request by rlogiacco**
I had the need to allow project manager to log time on behalf of other users, so I developed this feature which adds the necessary field and logs accordingly.

If you are interested in merging this I need help in developing the necessary tests as I'm very new to ruby: this was my very first attempt at coding anything in ruby or rails.

### CODE REVIEW

**Comment by ulferts** [comment]
Hi @rlogiacco and thanks for the PR.

From a feature perspective: given that there is a [ticket in OpenProject requesting the feature](https://community.openproject.com/projects/openproject/work_packages/21754/activity) the feature change seems to be valid, so I can see the benefit of implementing the feature. As it enables making changes in the name of somebody else, we should definitely guard that power with a separate permission.

From a technical perspective: Skimming over the code, I'd argue that a bunch of additional changes have to be made before this can be merged. E.g. the PR currently focuses on the rails based view and disregards the API v3 completely. There is already a PR on the way (#7954) that will introduce an angular based front end for creating and editing time entries. It relies on the API V3 completely as its backend interface. Once the PR #7954 is merged, we will probably replace the rails based time logging views throughout the application rather sooner than later. What I am getting at is that it might make sense to wait with this change until #7954 is done to avoid working on parts that we will remove later on. I can give you a ping once the #7954 is merged.

In case, you cannot be stopped, I'd advise you too focus on the API for the time being and take a look into:
* the contracts (responsible for checking whether a change to a time entry is valid): https://github.com/opf/openproject/blob/dev/app/contracts/time_entries/base_contract.rb, https://github.com/opf/openproject/blob/dev/app/contracts/time_entries/create_contract.rb, https://github.com/opf/openproject/blob/dev/app/contracts/time_entries/update_contract.rb and their associated specs   
* the permissions (registering the new permission): https://github.com/opf/openproject/blob/dev/config/initializers/permissions.rb
* the time entry schema (which is used to signal valid values when e.g. creating or editing a time entry) to include the users (basically, `schema :user` has to changed to `schema_with_allowed_link :user`: https://github.com/opf/openproject/blob/dev/lib/api/v3/time_entries/schemas/time_entry_schema_representer.rb 
* the time entry request specs (which are tests that act as if some client calls the API):
https://github.com/opf/openproject/blob/dev/spec/requests/api/v3/time_entry_resource_spec.rb
* The api documentation: https://github.com/opf/openproject/blob/dev/docs/api/apiv3/endpoints/time_entries.apib

Once the API (and by that the backend) has been adapted, the front end changes should be easy. 

Please let me know how you want to proceed.

**Comment by rlogiacco** [comment]
Hi @ulferts and thanks for the feedback. I can definitely wait for #7954 and then have a look at the code to see if I'll be able to apply the modification, but I'll still need help with the tests :-)

Right now I'm running my own modified version which can fulfil my needs for a few months.

**Comment by ulferts** [comment]
@rlogiacco, in the shortly to be released OpenProject 10.6 all time logging will happen via the API and Angular. So now everything should be prepared to add the functionality of logging time for other users. Please let me know if you need any help.

**Comment by rlogiacco** [comment]
I will pull the `release/10.6` branch and see what I can do: once I get it working I will submit another pull request.

Until then, thanks a million

**Pull request closed without merging**
