### PR TITLE
Deleted query new/edit forms and corresponding partials/helper methods.

### PR DESCRIPTION
**Pull request by manwithtwowatches**
Removed the majority of the old queries controller/view code.

### CODE REVIEW

**Comment by myabc** [comment]
I love seeing deleted code.

**Comment by manwithtwowatches** [comment]
@myabc @tilt  What do yous think about QueryMenuItem? Is that relevant anymore?

**Comment by tilt** [comment]
yes it is

**Comment by myabc** [comment]
@manwithtwowatches we'll have to figure out a way to build that functionality back in.

**Comment by tilt** [comment]
I think there will be something in the action menu for "highlighting" a saved query

**Pull request merged**
