### PR TITLE
[34358] Unclear warning message displayed when filtered value for assignee board does not match any member

### PR DESCRIPTION
**Pull request by bsatarnejad**
correct the warning message in the assignee board when there isn't any matched member with filter values.

https://community.openproject.com/projects/openproject/work_packages/34358/activity

### CODE REVIEW

**Comment by oliverguenther** [comment]
If you have no members in your project, this message will also appear without entering any search value. I think in this case, it is rather confusing.

I'd prefer we check whether the user has typed anything. I think the check in frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts is simply incorrect, as it checks for `!== undefined`. I would show it if `this.requests.lastRequestedValue !== ''`. What do you think?

**Comment by bsatarnejad** [comment]
Thanks @oliverguenther, as I tested, I understood when there isn't any member defined in a project, there is a choice for the user to choose the assignee named '(none)' .Therefore, I think no time the message will be shown when there isn't any member defined.

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/0c08b58e68772ab93c4d7299310018ae8258cf3e/frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts#L46">frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts#L46</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oliverguenther** [comment]
> Thanks @oliverguenther, as I tested, I understood when there isn't any member defined in a project, there is a choice for the user to choose the assignee named '(none)' .Therefore, I think no time the message will be shown when there isn't any member defined.

You're right of course. LGTM :+1:

**Comment by oliverguenther** [comment]
Backported to 11.0

**Pull request merged**
