### PR TITLE
[#13974] add sqlite to .travis.yml

### PR DESCRIPTION
**Pull request by marutosi**
https://www.openproject.org/work_packages/13974
https://community.openproject.org/work_packages/13974

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://marutosi-finn-sqlite3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://marutosi-finn-sqlite3.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
Please adhere to the hound warnings, it would be great if the codebase would remain in a rather uniform style (I know that this is not yet the case everywhere, but at least basic things like post 1.9 hash syntax and single quotes are obeyed quite consequently)

I am not yet sure if there is a stance regarding SQLite support (@ulferts do you know more here?) I assume that nobody wants to run a PM tool out of an sqlite database, but that does not mean we should actively prohibit it. I am still unsure if I like even more DBMS backends in the test matrix, especially thinking about build times.

@ulferts @floriank Any general thoughts on inclusion of sqlite capabilities?

**Comment by floriank** [comment]
I personally have no opinion on SQLite3 support at the moment. As an Opensource project we could strive to support it (could be nice for the dev docker image for example).

I do not assume that someone would use it in production though.

**Comment by floriank** [comment]
Quote from @ulferts from 11 months ago:

> Please note that SQLite is currently not officially supported. It might work but we do not test for it. So even if the migrations pass, I can not vouch for the application to work.

**Pull request closed without merging**
