### PR TITLE
Fix/ma query controller

### PR DESCRIPTION
**Pull request by tessi**
see: https://www.openproject.org/work_packages/3336

### CODE REVIEW

**Comment by tessi** [comment]
seems to make code climate a little happier: https://codeclimate.com/repos/528f351813d637200e02ef84/compare/fix%2Fma_query_controller

**Comment by hschink** [comment]
@tessi can you please check the following location (I guess permitted params is missing there):
- [x] [app/helpers/queries_helper.rb#retrieve_query (line 89 to 110)](https://github.com/opf/openproject/blob/dev/app/helpers/queries_helper.rb#L89)

**Comment by hschink** [comment]
Ok, I see that [app/helpers/queries_helper.rb#retrieve_query](https://github.com/opf/openproject/blob/dev/app/helpers/queries_helper.rb) is not directly related, although, regarding code duplication, I would expect the use of `permitted params` here too.

**Comment by hschink** [comment]
@tessi There is a bug in this branch: One cannot save a query with filter `subproject` set.

**Comment by tessi** [comment]
@hschink may you have a look at this PR again? I pushed a fix for the issue you found

**Pull request merged**
