### PR TITLE
[38648] Loading indicator when loading "all" notifications (content loader component)

### PR DESCRIPTION
**Pull request by bsatarnejad**
Create a content loader component and add it to the notifications center to hide the delay of notifications loading.

https://community.openproject.org/projects/openproject/work_packages/38648/activity

### CODE REVIEW

**Review by HDinger — COMMENTED** [review]
Hi @bsatarnejad 

is there a reason you added the code of the content-loader instead of simply including the library? Because this is of course a huge drawback of this solution compared to "CSS only" in #9622 .
Other than that, it also looks smooth. I think the bars could a bit larger when comparing them to the specification.

Side note: The issue I mentioned [here](https://github.com/opf/openproject/pull/9622#pullrequestreview-744891670) with the "No results box" does not occur with this solution.

**Comment by oliverguenther** [comment]
I pushed a commit that uses the content-loader component directly and exports it in a separate module. You can continue with the styling of the svgs. There are two places where content is loaded:

1. In the center before we know how many rows are being rendered
2. In the individual rows until the work packages are loaded

Right now, two content-loaders are shown. For me that's okay for the course of this PR, but would be good to check with @opf/frontend and possibly the designers.

Peek 2021-09-07 16-06

**Review by HDinger — CHANGES_REQUESTED** [review]
Depending on the screen size, the lines are too big or to small for the notification row. For example mobile (too small)
Bildschirmfoto 2021-09-09 um 14 16 07

Or a very large screen
Bildschirmfoto 2021-09-09 um 14 16 57

**Comment by bsatarnejad** [comment]
> Hi @bsatarnejad
> 
> is there a reason you added the code of the content-loader instead of simply including the library? Because this is of course a huge drawback of this solution compared to "CSS only" in #9622 .
> Other than that, it also looks smooth. I think the bars could a bit larger when comparing them to the specification.
> 
> Side note: The issue I mentioned [here](https://github.com/opf/openproject/pull/9622#pullrequestreview-744891670) with the "No results box" does not occur with this solution.

Hi @HDinger I thought it is lighter to implement a component itself instead of adding its library, because it doesn't have a big functionality.

**Review by HDinger — APPROVED** [review]
Please fix the eslint issues. Once it is green, it can be merged 👍

**Pull request merged**
