### PR TITLE
Fixed email options hash map keys

### PR DESCRIPTION
**Pull request by MichaelHierweck**
There was some mixup between symbols and strings that were used
as hash map indexes inside the mail handler. As a result at least
the argument or environment variable "project" was ignored.

This was cleaned up by using symbols all the way.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://michaelhierweck-fix-mail-handler-keywords.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by mfrister** [comment]
Thanks for removing the debug code from the commit. Did you think about writing a test?

**Comment by hschink** [comment]
@MichaelHierweck can you provide a spec for your fix? This would help us to prevent this bug for the future.

**Comment by MichaelHierweck** [comment]
Sorry, as I'm not a rails developer I don't know how this should be
tested. I would appreciate if someone familiar with rails testing could
provide a test.

**Comment by hschink** [comment]
Hi @MichaelHierweck, thanks a lot for your response! Could you instead provide reproduction steps for the error you found? That would help us a lot writing a test.

**Comment by MichaelHierweck** [comment]
Send an email without metadata (such as project) to the rake handler and
specify the project identifier on the command line instead.

Example:

cat mail.txt |rake redmine:email:read project=my-project

The email won't be accepted and an error is logged in production.log:

"MailHandler: missing information from <USER>:
Unable to determine target project"

**Comment by kgalli** [comment]
@MichaelHierweck can you please edit this PR so it will be merged into release/3.0. By doing so we will merge this change into stable when we are releasing the next stable (3.0.X) version. I do not think we should merge this fix directly into stable. Especially if specs are missing. Thank you very much!

**Comment by MichaelHierweck** [comment]
Which branch should I choose? How can pull requests be the changed?

**Comment by kgalli** [comment]
@MichaelHierweck If you do not propose a hotfix which should be merged immediately into stable (e.g. security issue) you should create a branch starting from release/3.0. On this branch you do your changes and when you are finished you create a PR against this release/3.0 branch. All changes of this branch will end up in the stable branch at the time we are releasing a new version of 3.0. This procedure is the same if you have changes for other versions say 4.0. Version 4.0 is not released yet but will be soon and then stable will be 4.0 (and 3.0 will be backport). Hopefully this answers your question. 

To change the branch I see two options. You may have the chance to just edit the branches to compare. See image below.

Change branch

Or if this does not work you have to create a new branch starting from release/3.0 and do your changes again on this newly created branch. Then you propose a new PR (this might be the safest path).

Thanks!

**Comment by MichaelHierweck** [comment]
Proceeding with PR #2095 against release/4.0.

**Pull request closed without merging**
