### PR TITLE
fix #24941 Warn before leaving page with unsaved data not working

### PR DESCRIPTION
**Pull request by wielinde**
Remove all code that relies on `onbeforeunload` but keep Angulor's state change detection

### CODE REVIEW

**Comment by oliverguenther** [comment]
Some tests are failing that were testing the alerts previously. Please also adjust the setting under 'My Account'  that this functionality only exists in the work packages view.

**Review by oliverguenther — CHANGES_REQUESTED** [review]
Some tests are failing that were testing the alerts previously. Please also adjust the setting under 'My Account'  that this functionality only exists in the work packages view.

**Comment by wielinde** [comment]
@oliverguenther Thank you for the review. I hope I fixed the specs (let's see which of the many truths Travis will tell us). I tried to maintain the structure of the specs in case we find a solution in the future how to intercept all the 'page leave' events.

Further I adopted the naming of the user setting to reflect the fact that it only applies to editing work packages.

**Review by oliverguenther — APPROVED** [review]

**Comment by oliverguenther** [comment]
LGTM 👍

**Pull request merged**
