### PR TITLE
link to attachment#show to restore old functionality

### PR DESCRIPTION
**Pull request by machisuji**
WP [22206#](https://community.openproject.org/work_packages/22206/activity)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://machisuji-fix-attachment-link.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://machisuji-fix-attachment-link.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by oliverguenther** [comment]
This was introduced not that long ago in a fix to download actions by hotlinking them from the frontend. https://github.com/opf/openproject/commit/db3681661daee4e2051fe606c47acaa3298a230a

**Comment by machisuji** [comment]
@oliverguenther I don't quite get the motivation. Care to elaborate? The very real problem is that through this S3 attachments are served through OpenProject, blocking a whole process for the download for potentially many seconds (depending on how big the file is).

**Comment by oliverguenther** [comment]
The previous behavior caused the actual download link to show a rails view rather than requesting the file itself, thus it was impossible to generate embedded attachment URLs from the frontend. You can still reference attachments, but why do you want to change the download path?

**Comment by machisuji** [comment]
Closed in favour of #3952.

**Pull request closed without merging**
