### PR TITLE
[21911] Restyle projects toplevel menu

### PR DESCRIPTION
**Pull request by mk84**
https://community.openproject.org/work_packages/21911/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://mk84-21911-top-level-menu-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://mk84-21911-top-level-menu-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by basiszwo** [comment]
@lindenthal as discussed we take it as is for now. I create a new WP for the remaining tasks.

**Comment by oliverguenther** [comment]
The subproject indent seems to be broken. (asdf11 is a subproject and should be indented)

asdf11_-_settings_-_openproject

**Comment by mk84** [comment]
@oliverguenther hmm... I tested this again but I cannot reproduce your issue.
This is how it looks on my machine. Btw: the indents are hardcoded nonbreaking white spaces and not nested lists with paddings.

submenu

**Comment by oliverguenther** [comment]
@mk84 Sorry to bother you. I could not reproduce it locally. I blame teatro ;)

LGTM

**Pull request merged**
