### PR TITLE
Removed useless :lang option.

### PR DESCRIPTION
**Pull request by marutosi**
https://github.com/opf/openproject/commit/4f9b6d81f4c2108ca48cf07909f50628507ee453

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-tabular-form-builde.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by marutosi** [comment]
#1873

**Comment by linki** [comment]
why useless?

**Comment by marutosi** [comment]
Why useful?

**Comment by linki** [comment]
cause someone put it there. what was the purpose of setting `:lang` at that point?

**Comment by marutosi** [comment]
> cause someone put it there.

https://github.com/chiliproject/chiliproject/blame/master/app/helpers/application_helper.rb#L849

**Comment by marutosi** [comment]
http://apidock.com/rails/ActionView/Helpers/FormHelper/form_for

**Comment by myabc** [comment]
@marutosi perhaps you can ask @jplang? thanks!

**Comment by linki** [comment]
:disappointed:

please improve your PR descriptions: https://github.com/opf/openproject/commit/4f9b6d81f4c2108ca48cf07909f50628507ee453 removes the `proc` argument. what on earth has that got to do with the `:lang` option?

maybe you're right, but **without explanation this won't be merged**, sorry.

**again**, please don't waste **your and our** time with **obscure** and **undocumented** pull requests!

**Comment by marutosi** [comment]
http://www.redmine.org/projects/redmine/repository/revisions/67/entry/trunk/app/helpers/application_helper.rb#L134

**Comment by marutosi** [comment]
> @marutosi perhaps you can ask @jplang? thanks!

There are answers in commit logs.

**Comment by marutosi** [comment]
Are you kidding?
https://github.com/opf/openproject/commit/f5bb0067f0340b915dc6e75eabac29a587f26869

**Comment by marutosi** [comment]
#2492

**Pull request closed without merging**
