### PR TITLE
[23140] Change wording of cg-busy and create title

### PR DESCRIPTION
**Pull request by oliverguenther**
`cg-busy` allows to set a default value for `message:` in the module initialization, but that isn't properly switched according to the locale.

https://community.openproject.com/work_packages/23140/activity

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://oliverguenther-fix-23140-wording.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://oliverguenther-fix-23140-wording.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
It might make more sense to override the default value for the message:
https://github.com/cgross/angular-busy/blob/master/README.md#overriding-defaults

**Comment by oliverguenther** [comment]
@ulferts I've tried that first (see my PR comment). It doesn't update the message when changing the locale - even though I did a hard reload on the table, so I believe it's cached somewhere. I didn't want to put any more time into this, so I didn't research into the reasons why it didn't change appropriately.

**Comment by ulferts** [comment]
😞

**Pull request merged**
