### PR TITLE
[22831] fix for pagination display error

### PR DESCRIPTION
**Pull request by manuschiller**
related to [https://community.openproject.org/work_packages/22831/](https://community.openproject.org/work_packages/22831/)

a mismatched default pagination value led to a wrong calculation of pages.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://manuschiller-22831.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/' target='_blank'>Open stage</a> or <a href='http://manuschiller-22831.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com//teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
Matching the default values will only fix it for as long as the user does not decide to switch the available pagination options in the backend.

I therefore fear, that this is not a viable solution.

**Comment by manuschiller** [comment]
@ulferts thanks, the pagination options are now based on the main configuration

**Comment by oliverguenther** [comment]
@manuschiller Could you rebase this on release/5.0 since the target is 5.0.17, not 5.1 ? I assume the rebase will fix the npm tests - if not, please fix them to allow merging today.

**Pull request closed without merging**
