### PR TITLE
fix save button display conditions

### PR DESCRIPTION
**Pull request by 0xF013**
[`* `#17263 ` fix save button display conditions`](http://community.openproject.org/work_packages/17263)

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://0xf013-feature-17263-save-button-conditions-fix.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by myabc** [comment]
@0xF013 without having applied any queries, I'm seeing _Save_ greyed out, but it is still clickable (and still triggers the Save modal).
seeded_project_-_work_packages_-_openproject

**Comment by 0xF013** [comment]
@myabc I think I fixed that.

**Comment by myabc** [comment]
:+1: works for me.

**Comment by ulferts** [comment]
@myabc this seems to have broken instantiating a query from an url (e.g. http://localhost:3000/work_packages?query_props=%7B%22f%22:%5B%7B%22v%22:%22me%22,%22n%22:%22author_id%22,%22o%22:%22%3D%22%7D,%7B%22n%22:%22status_id%22,%22o%22:%22*%22%7D%5D,%22t%22:%22updated_at:desc%22%7D)

When reverting the commit, everything works fine.

@myabc can you please check this?

**Pull request merged**
