### PR TITLE
Sort work packages by updated_at by default

### PR DESCRIPTION
**Pull request by b12f**
Before this change, work packages would usually be sorted by ID. This is not just unhelpful behavior, but oftentimes the exact opposite of what people are working on; the latest stuff. This commit changes the finding of work packages to a `DESC` sort of `updated_at` for the following calls:

* Setting relations
* Setting the parent
* Setting children
* Linking work packages in rich text field using the # and ## syntax

Closes https://community.openproject.org/work_packages/44197/activity

### CODE REVIEW

**Comment by b12f** [comment]
This could be counted as a breaking API change. Not sure if this is the way to do it @opf/backend

**Review by wielinde — COMMENTED** [review]
@b12f The changes to the `WorkPackageCollectionFromQueryParamsService` indeed look like breaking changes to the API. Are the changes to the default really necessary? I understand that all changes requested in the WP can be controlled on the client side. Can't we simply leave the back-end untouched in this PR?

**Review by oliverguenther — APPROVED** [review]

**Comment by oliverguenther** [comment]
Changes LGTM, still needs a rebase to `release/12.3` @b12f

**Comment by b12f** [comment]
This is superseded by https://github.com/opf/openproject/pull/11555 because rebasing was a pain

**Pull request closed without merging**
