### PR TITLE
[#14507] Gemfile: awesome_nested_set: use github 2-1-stable branch

### PR DESCRIPTION
**Pull request by marutosi**
https://www.openproject.org/work_packages/14507

There is no answer on #1863.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://marutosi-finn-awesome-nested-set.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by NobodysNightmare** [comment]
> Failed — The Travis CI build failed

**Comment by marutosi** [comment]
> Failed — The Travis CI build failed

Again, All your branches pass Travis CI build?

**Comment by ulferts** [comment]
No, they don't. But we try to make them pass. The PR's removed showed no progress. As unmerged PR's make it harder to organize, we remove those.

Additionally, we usually try to issue a PR only if we have some confidence that the tests will pass. Reopening a PR that already failed does not fit thus.

**Comment by marutosi** [comment]
> No, they don't. But we try to make them pass

Why are there many **stale** branches?
https://github.com/opf/openproject/branches/stale

> As unmerged PR's

Why are there many **stale** branches?
https://github.com/opf/openproject/branches/stale

**Pull request closed without merging**
