### PR TITLE
render ifc default models within angular page

### PR DESCRIPTION
**Pull request by ulferts**
Turns the routes
* projects/:project_identifier/ifc_models/defaults
* projects/:project_identifier/ifc_models/:id

into angular managed routes where the content is rendered (almost) completely by angular.

This PR is not intended to be perfect. It has a couple of caveats:
* The routes are not yet well balanced and namespaced
* The names of the classes are still IFC (not BIM) based
* The error messages (e.g. that an ifc model could not be opened as it is not processed yet) is still rendered by rails and as such will be above the heading.
* There is no behaviour defined for when the screen is too narrow.

### CODE REVIEW

**Comment by openprojectci** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/27e86909e1fa5a9f2ca1fccbcb724ac65e64b561/frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.ts#L44">frontend/src/app/components/modals/wp-destroy-modal/wp-destroy.modal.ts#L44</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/27e86909e1fa5a9f2ca1fccbcb724ac65e64b561/frontend/src/app/modules/ifc_models/ifc-viewer/ifc-viewer.component.ts#L36">frontend/src/app/modules/ifc_models/ifc-viewer/ifc-viewer.component.ts#L36</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by oliverguenther — CHANGES_REQUESTED** [review]
My default model is no longer being shown on visit to `/defaults`:

Otherwise, LGTM :+1: 

Peek 2020-02-19 11-34

**Comment by ulferts** [comment]
Hm, I can't reproduce this on my machine @oliverguenther. Can you please show me in a joined session?

**Comment by HDinger** [comment]
> My default model is no longer being shown on visit to /defaults:

Happens for me too.

**Review by oliverguenther — APPROVED** [review]
Works correctly for me now :+1:

**Comment by ulferts** [comment]
> Works correctly for me now 👍

Weird, I did not make any change that would explain the change towards 'working now'.

**Comment by oliverguenther** [comment]
Probably the merged from dev did it :man_shrugging:

**Comment by ulferts** [comment]
Probably and I am more than happy to roll with it. As a wild guess, I'd say that the dev contains a different XEOKit version you had already running which then caused problems with the "old" version in this branch.

**Pull request merged**
