### PR TITLE
19154 Form checkbox matrix styling

### PR DESCRIPTION
**Pull request by myabc**
:warning: ~~**Includes commits from #2639. Please review, merge first.**~~

https://community.openproject.org/work_packages/19154

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://myabc-feature-form-table-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://myabc-feature-form-table-styling.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by ulferts** [comment]
@myabc this looks good to me. 

I noticed you labeled this as "WIP". Can you please elaborate on what you think is missing?

**Comment by myabc** [comment]
@ulferts rebased.

> I noticed you labeled this as "WIP". Can you please elaborate on what you think is missing?

I wanted to do one further rename + I also need to update openproject-meetings.

**Comment by myabc** [comment]
https://community.openproject.org/work_packages/19154

**Comment by myabc** [comment]
@ulferts this is ready for review

**Pull request merged**
