### PR TITLE
Replace dynamic bootstrapped components with angular elements

### PR DESCRIPTION
**Pull request by oliverguenther**
To pave the way towards turbo, we will need to allow dynamic bootstrapping of angular elements on these visits. As we've made good experiences with Angular Elements in the past, this PR tries to get rid of all dynamically bootstrapped components in favor of angular elements.

There is one case where this is not possible: the col.opHighlight is used for table highlighting of columns, which is an attribute directive an cannot be replaced easily. This PRs replaces it with a stimulus controller instead.

https://community.openproject.org/work_packages/57269

### CODE REVIEW

**Review by HDinger — CHANGES_REQUESTED** [review]
Looks good as far as I can tell. I found some issues with the highlighting stimulus controller:

* On all WorkPackage tables the columsn are not highlighted 

Bildschirmfoto 2024-08-16 um 07 57 36


* With the current approach, we highlight all columns and not only those that we previously marked with the `opHighlightCol` directive. That results in columns with empty header being highlighted as well. However, that might not be such an issue. We could ask product about that.

Bildschirmfoto 2024-08-16 um 07 53 50

* On the project list, there is some weird effect when hovering the hierarchy column as well as the last coumn with the "more" actions. I assume, that this closely related to the point above, as those columns were not meant to be hovered.

Bildschirmfoto 2024-08-16 um 08 01 37

**Comment by oliverguenther** [comment]
@HDinger I knew this would come back to bite me. I now provided a way to disable the highlighting on a per col level and restored all the previous places

**Review by HDinger — APPROVED** [review]
LGTM 👍 

There is one special behavior on the project list, where the last column shows a hover effect although there is no header. However, since that is the only table where I saw that, I am fine with extracting that into a separate ticket.

Bildschirmfoto 2024-08-19 um 14 19 17

**Comment by HDinger** [comment]
> LGTM 👍
> 
> There is one special behavior on the project list, where the last column shows a hover effect although there is no header. However, since that is the only table where I saw that, I am fine with extracting that into a separate ticket.
> Bildschirmfoto 2024-08-19 um 14 19 17

I created a ticket for that: https://community.openproject.org/projects/openproject/work_packages/57329/activity

**Pull request merged**
