### PR TITLE
Refactor/authorization

### PR DESCRIPTION
**Pull request by ulferts**
There are basically three types of authorization checks in OP:
- (Question 1) Does the user have a required permission within a context? The context can either be a specific project or be global, i.e. not project related.
- (Question 2) What users have a required permission within a context? Again, the context can either be a specific project or global.
- (Question 3) What projects does the user have a specific permission in?

The current authorization code is mainly working within the ruby domain at least for questions 1) and 2). Related objects like User, Member, MemberRoles, Project and Roles are fetched from the db and ruby code is executed upon them to determine, whether a user has the necessary permissions to perform an action.

In order to avoid n+1 queries when having to evaluate an authorization check, and such a check is run at least once for almost every request, the current implementation [eager loads the models required for authorization checks together with the current user model](https://github.com/opf/openproject/blob/dev/app/controllers/application_controller.rb#L168)  

While this approach works fine for small installations, performance will drop significantly if the number of memberships increases. The application has to load 
`([Number of memberships in a project] * 2) + [Number of roles in all the projects] + [Number of distinct roles within all projects]` records from the db and instantiate each record as AR objects. If the user is a member in e.g. 1000 projects having 5 roles in each, that behaviour  results in 7005 records to be fetched and instantiated.

If plugins extend the authorization checks, the number of objects to be fetched and instantiated increases accordingly. As the plugins do typically not extend the eager loading of mechanisms, running those plugins results in n+1 queries.

Another problem stems from wanting to check the permissions of multiple users (Question 2). Then, one has to load each user and the objects necessary for permission checks associated to them. While [there is a mechanism to eager load the objects for multiple users](https://github.com/opf/openproject/blob/dev/app/models/user/authorization.rb#L40), a developer has to be aware of that method and has to use it correctly.

Question 3 is [already implemented in the DB](https://github.com/opf/openproject/blob/dev/app/models/project.rb#L350). Unfortunately, the implementation relies on subqueries which again degrade in performance if a lot of records exist in the DB.
### Implementation approach

The PR aims to let the DB do the heavy lifting of authorization checks. The Ruby code generates a DB query based on what the authorization is checked for, issues a single DB query and receives the objects related to the authorization. The queries necessary to answer all the authorization questions are:
- (Query 1) Roles the user has within a certain context (Answers Question 1)
- (Query 2) Users having permission within a certain context (Answers Question 2)
- (Query 3) Projects a user has a certain permission in (Answers Question 3)

The PR is limited to query 1 and 2 where query 2 will only support querying for users having permissions within a project. Querying for users having permission globally is not yet a required use case but might become one when e.g. global roles allow for assigning administrative tasks to non admin users. 

As query 3 is already implemented in the DB the need to improve this part of the code is less urgent, although a subsequent PR will most likely address the mentioned problems.

The subsequent PR can then rely on the structure generated within this PR. The structure consists of: 
- Centralized authorization code 
- Objects able to generate query 1 and query 2
  - The objects need to be extendable via plugins 

Because we are working towards having DB queries and Rails' under the hood implementation for queries is [Arel](https://github.com/rails/arel), the objects will work directly on Arel. This has the advantage of being able to generate complex DB queries without the need to write plain SQL which would be hard to manipulate. Because we want plugins to be able to alter authorization decisions, which manifests in manipulating DB queries, this is an important feature. 

Fortunately, writing Arel results in an AST. The AST is later traversed by a visitor if a different representation, e.g. sql, is desired. We can use the same pattern to manipulate the AST and rely on Arel's visitors for a base class.

As we will be using our visitor to transform the query when altering a query from a plugin, we can use the same mechanism in the core as well. This will result in highly modular code which again increases the modifiability by plugins. 

Due to performance, it is not advisable to do everything in the DB. A couple of permission checks are typically performed per request. Thus issuing a db query per permission check would be costly. Additionally, formulating a question as part of the db query to which we already have the answer in objects we have in the ruby code is inefficient although it would be clearer code wise. An example for this is checking whether the project allows the action when wanting to answer question 1. If one wanted to have the question formulated inside the query, it would require 2 additional joins.
### Alternatives
- Trying to limit the objects and their attributes eager loaded to the absolute minimum. Unfortunately, it will be hard to know which objects will be needed.
- Not relying directly on Arel and build a more specific class hierarchy for parts of the db query in order to avoid having to know Arel. I did try that approach but it was way more effort and resulted in having an AST on top of an AST which was very hard to understand. 
### Out of scope
- Improving Query 3
- Create a mock authorization to be used within tests. This would allow us to have less setup code. One might achieve enabling the developer to only have to write something like

```
Authorization.mock(user, [:view_work_packages], project)
```
### Todo
- [x] Generate queries
  - [x] Query to fetch all the roles a user has in a project
  - [x] Query to fetch all the roles a user has globally
  - [x] Query to fetch all users having a permission in a project
- [x] Create a transformation visitor so that we can modularize the queries and allow plugins to change them 
- [x] remove eager loading memberships on per request current user loading
- [x] Move authorization code into one place
  - _However, I am not sure whether the place is correct. Ideally, it would be moved to a separet gem_
- [x] remove old authorization code and it's usages
- [x] Write unit tests
- [x] Write integrational tests checking if the right models are returned
- [x] Check whether anything broke
  - [x] manually
  - [x] run all tests
- [x] Adapt plugins
- [x] cleanup/structure PR
### OP work package
- https://community.openproject.com/work_packages/22268/activity

### CODE REVIEW

**Comment by ulferts** [comment]
Please note, that I will not fix the last two remaining code climate issues as they are related to the ProjectQuery which basically consists of code I just moved and which will be addressed by a subsequent PR.

**Comment by ulferts** [comment]
The PR will also change the behaviour of acts_as_watchable and the watchers api slightly.

A call to `api/v3/work_package/:id/available_watchers` used to return all members eligible for watching. This included the users that where already watching. On the other hand, it excluded non members although non members might be eligible for watching a work package in a public project if the non member role has the required permission. Non members could use the "Watch/Unwatch" button themselves, but adding them as watchers as not possible for other users.

With the changes in the PR, the call now returns all users eligible for watching including non members for public projects if they have the permission. It now excludes users that are already watching.

**Comment by ulferts** [comment]
Please also merge the PRs on the impermanent_memberships and on the global_roles plugin.

**Comment by oliverguenther** [comment]
👍

**Pull request merged**
