### PR TITLE
enable no_self_notification per default

### PR DESCRIPTION
**Pull request by ulferts**
https://community.openproject.org/work_packages/21192

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://ulferts-feature-no-self-notified-default.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://ulferts-feature-no-self-notified-default.opf-openproject-2af22bf12c7dfdad4ddf.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by NobodysNightmare** [comment]
LGTM, waiting for travis :+1:

**Comment by NobodysNightmare** [comment]
Narf... The changes hit some specs that expected mail delivery and now there is no mail. Apparently because the expected mails were self-deliveries...

**Comment by NobodysNightmare** [comment]
legacy user mailer specs still failing...

**Pull request merged**
